Citadel-Station-13/Citadel-Station-13-RP

code/modules/vore/eating/vorepanel_vr.dm, modular_citadel/code/modules/mob/living/simple_animal/simple_animal_vr.dm, modular_citadel/code/modules/vore/eating/living_vr.dm, vorestation.dme
Title.
This renames the "mob vore" pref to "consumption", and makes it apply to normal players. If you try to shove someone with consumption off into your maw, you'll get a message telling you that the person you're trying to consume is unappetizing.
This also makes it so that hostile mobs will attempt to attack their targets before consumption. Hostile mobs will now only consider consuming their targets if the target is incapacitated. This makes hostile mob encounters a lot more fair for those that wanna keep consumption on.
=> Replaces mob vore pref with devourable pref, makes hostile mobs attempt to incapacitate targets before noms

code/_helpers/global_lists_vr.dm, code/game/gamemodes/gameticker.dm
Did a poll on the RP server channel, if you'd like you can check on them until we can get an end round voting system to have a more controllable scenario for when ERT or crew wishing to stay around a bit longer.
=>  Some users on RP server want to restore original round end timer. 

code/__defines/damage_organs.dm
Title. This decreases the ambient germ cap from 110 to 30, which means the ambient germ cap is no longer sufficient for an object to be capable of causing infections. The germ level cap for moving has been decreased from 200 to 110, meaning it's no longer possible to make items cause instant stage 2 infections later in the shift.
=> Cures the entire station of HIV - makes infections a lot harder to get

modular_citadel/code/game/jobs/job/assistant_cit.dm
Since normal off-duty code is now officially works.
=> Removes off-duty presonnel from alt. title list of Visitor's

modular_citadel/code/datums/supplypacks/misc_vr.dm, vorestation.dme
Title. KHI NIFs are meant to be exclusive to admin events, you shouldn't be able to get them just from 10 minutes worth of mining assuming good RNG. Heads siphoning department funds just to buy themselves KHI NIFs is also pretty bad. The sheer amount of drama that comes out of people losing their KHI NIFs is pretty ridiculous, as well.
The RP server simply can't be trusted with fun shit
=> removes KHI NIFs from cargo

code/modules/organs/organ.dm
At the absolute minimum germ level that started causing damage, the damage ended up being 2.75 toxin loss per process cycle, increasing with each process cycle whenever no antibiotics are present, for a maximum of 7.75(!!!) toxloss per process cycle.
This nerfs it to 0.75 toxin loss per process cycle at the absolute minimum threshold to take damage from infections, with 1.75 toxinloss per process cycle being the max. This should give people a little bit more leeway to rush to medbay if they got a papercut, as infected limbs will no longer kill you in 25 process cycles or less.
=> Nerfs infection damage for living limbs

modular_citadel/code/modules/games/dice.dm, vorestation.dme
Because having to roll them in your hand is lame.
Also, I probably coded it in a lazy way, but this codebase is spaghetti.
Might improve it in future.
=> Actually throwable dice.

code/defines/obj/weapon.dm
[What dose this do?]
50 parts WERE the max but now with the power of sci it can hold a 100 parts!
[Whys?]
*Dies in side well trying to make space for more stock parts well still keeping two other parts*
QoL and ect. Not all that power game-y or creep I think
=> Dubbles rapid part exchange device holding space

code/modules/vore/fluffstuff/guns/bsharpoon.dm
sets harpoon WALLHACK to true by default with a blatant disregard for fuckin...whatever purpose, man.
=> bsharpoon rebuff

maps/tether/tether-03-surface3.dmm
The double glass-airlock in surface 3 next to security had a wall inside it, and the engineering sign was floating on that wall. This fixes both, and adds appropriate detailing on the area around it to match other double-airlocks on the surface.
=> Fixes the wall inside the surface 3 airlock, and adds proper decals

modular_citadel/icons/icon_overrides.dm
Also adds newline at the end of icon_overrides code file.
=> Fixes missing RSF icon

code/modules/multiz/pipes.dm, maps/tether/tether-01-surface1.dmm
Because why the fuck can upwards facing pipes be hidden under a tile????
also, renames a pipe adapter in atmos because it's fucking dumb. More atmos changes will be coming down the pipeline but I needed this.
If the code change for the pipe can be easily modularised let me know, but outside of just like, overriding the entire file I wasn't really sure how to go about that.
=> Makes upwards pointing atmos pipes not hide under tiles.

code/game/objects/items/devices/defib.dm
Only works on organic vox; For now, that can be considered working as intended, as FBPs are harder to actually kill than organics are, beyond electricity and EMP/Ion effects.
=> Vox Defibrillation, with fixed checks

maps/tether/tether-01-surface1.dmm
So, when I did my change to add a mining outpost substation, I used a "downwards from above zlevel" wire, rather than "downwards from adjacent tile" wire. I have a fucking brain disease holy shit this has been plaguing me and Eunice for months
=> Okay so I'm a fucking retard

modular_citadel/code/modules/client/preference_setup/loadout/loadout_accessories.dm, vorestation.dme
gives the fancy expanded webbings (and drop pouches) to the CD, the Pathfinder, explorers, and shaft miners
also changes the webbing vest loadout names from "webbing, [color]" to "webbing vest, [color]", with the white webbing being dubbed "medical-white" because of that dinky ass lil blue cross on the neckline or whatever
=> Loadout Webbing Buff

code/modules/clothing/spacesuits/rig/suits/station.dm
Adds RD and CE rig cameras to be accessed in the command section in security monitoring consoles.
=> command rig cams

modular_citadel/code/game/mecha/equipment/weapons/weapons.dm, vorestation.dme
the Sturmkönig is a machinegun that fires 7.62 (35 brute, +10 compared to the UAC/2's 25 brute) with a 6 round burst.
the Slagger shoots really fast - almost as fast as you can click. still does 40 burn, but it drains more power to assist in cycling the lasers
the Bishop is a marksman's cannon - 2 round burst, but each shell fired is a 14.5mm shell, so...y'know. hit 'em hard, hit 'em fast.
=> whats a fuckign balance - SPICY NEW MECH WEAPONS THAT ARE ADMINSPAWN ONLY

code/modules/research/rdconsole.dm, modular_citadel/code/modules/research/designs.dm, modular_citadel/code/modules/research/designs/medical.dm, vorestation.dme
research default printspeed dropped from 10 ticks to 6 - stock parts, in comparison, have default printspeed 3
metal/glass costs for surgical tools dropped by a bit, because "wow this thing takes like 3 metal sheets for a FUCKING PEN-SIZED THING TO CUT INTO DUMBASS ORGANS"
=> I'M SO MAD RIGHT NOW - unapologetic research buff

code/controllers/master.dm, code/game/gamemodes/gameticker.dm
I added a var to the game ticker, block_start. It starts TRUE and is used to conditionally enter an infinite while-sleep loop predicated on if we're still blocking the game from starting or not. It is later set FALSE in master.dm when initializations complete.
=> Properly-ish prevents an uninitialized game start via ugly sanity test

code/modules/mob/mob_movement.dm
This is a stupid RNG mechanic and it needs to stop existing in general. This is an untested webedit but it literally just comments out the check for the var so it's probably fine.
=> Comments out spaceslipping

code/modules/mob/living/silicon/robot/drone/drone_items.dm
Changes!
Makes organ gripper, and robotics organ gripper hold nifs if needed
Why?
There ment to clearly be able to do robotic/surgery so let them be able to do there jobs at lest to the fullest extent.
=> Makes borgs that should be able to install nifs.

code/modules/power/cable.dm
Fixes vore's light switch frame code. Previously, building light switch would fail because the proc for is_cable_coil() wasn't overridden for the cable coil.
also:
>PR 666
>fixes bringing light to the server
>lucifer is the bringer of light
really makes you think
=> Finally implements is_cable_coil(), fixes light switch construction.

code/__defines/chemistry_vr.dm, code/modules/mob/living/carbon/human/human_powers.dm, code/modules/mob/living/carbon/human/species/station/alraune.dm, code/modules/mob/new_player/sprite_accessories_vr.dm, code/modules/organs/subtypes/alraune.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm, vorestation.dme
Alraune now have regenerate. Regenerate now covers lost organs, but they start off damaged. (Regenerate now regens body markings.)
In preparation for future code, Alraune have an extra language slot, as they will have two languages. Buffs max age to fit lore. 
Their limbs now cascade damage to other limbs when at max damage. (Their limbs do not regenerate damage (unless lost) if they don't have a steady flow of carbon dioxide, and don't if they have any toxin dmg)
Ethanol now hits them extremely hard, making toxin damage almost a certainty. Phosphorus, and all other chemicals that function as nutriment for plants, function as nutriment for Alraune. As does milk and chocolate. Dexalin and plant-b-gone are highly lethal to them. Regular non-pepperspray capsaicin is tasty to them.
=> Unapologetic Alraune Buffs

maps/tether/tether-07-station3.dmm
- Removes two Sec voidsuits.
+ Adds two hazard RIGs, with nonlethal modules in the standard armory. Lethal E-gun modules are available in the Tactical Armory
+/- Increases number of plate carriers to eight, changes plate carriers to CORPSEC variants and replaces armguards with the proper black  variants.
=> Armory Additions

code/modules/random_map/random_map.dm, code/modules/random_map/random_map_verbs.dm
logs verb usage
CHECK_TICKs displaying because BYOND isn't robust enough to handle 65535 list operations.
=> random map fixes

code/controllers/master.dm, code/game/gamemodes/gameticker.dm
This is more often than not causing the issue of needing admins to babysit roundstart. I'd rather have people start pre-init and have to wait a minute than sit around for who knows how long waiting for an admin to be available during off-hours.
=> Revert "Properly-ish prevents an uninitialized game start via ugly sanity test"

code/game/objects/items/weapons/storage/belt.dm
Changling
Makes excavation gear-belt hold Hand Labels
Why?
For quick and easy labeling. Qol
=> Makes excavation gear-belt hold Hand Labels

code/game/objects/items/devices/defib.dm
So literally everyone now gets the "low voltage" warning not just vox 😂 👌
=> Revert "Vox Defibrillation, with fixed checks"

code/modules/mob/living/carbon/carbon.dm
You make a one-line fix and spend thirty minutes trying to get a test server ready to even test it.
Anyhow, since slipping causes weakened, I just added a check to make sure that you aren't already weakened before trying to apply another slip. 
This will prevent the infinislipping exploit, ie using pull+click to move somebody over a bar of soap or banana peel repeatedly in order to keep them stunned indefinitely.
=> Prevents slipping when already weakened.

modular_citadel/code/game/objects/items/trash.dm
Fix?
Makes trash items have icons when being trash
Why?
Dead icons are bad icons. This is a temp fix
=> Icon trash bandaid fix

code/modules/research/designs/medical.dm
Changlings
phasic heath scanner and Advanced health scanner can now be made at insane prices and techs ment for late in the round!
Why?
So people have a reason to bring osmium and other mats to rnd for use!
So medical can have a easier life as they can get fancy heath scanners... To make better malpractice
=> Adds Advanced and phasic medical scanners to Rnd

code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
Changlings
Gives the proper tools and such to sci-doggo for repairing a nifs/synths
Why
Legit engine borg is more useful then a sci-doggo for no reason when it comes to them. Making it a useless model to be after 15 mins in game
=> Makes robotic sci boggo able to repair Synths

code/modules/nifsoft/software/15_misc.dm
a simple line change to make it 3 wear on the nif. It was already absurdly high compared to literally everything else in the nif shop. I brought it down and it will be discussed at the round table. Since it's not meant for combat in the first place, the intense nif wear just felt strange.
=> Reduce Nif wear of Mass Alteration

code/game/objects/items/weapons/storage/firstaid.dm
Changlings
Makes the list "code less verbose, makes it cleaner and prevents future mistakes." - A Ghommie
Makes it so surgery kits take any surgery tool and any health scanner 
Why?
Code improvement and Bone Clamps are a pain to fit into the kit if it can at all!
=> Makes the bone clamps and health scanners fit in surgery kits

code/modules/mob/mob_grab_specials.dm
Because right now, for some reason, if you set your size to 100.001, you can't be grab-pinned by someone with a size of 100.000
This changes it so that grab-pinning someone needs you to be no more than 10 full scaling units smaller than whoever you're trying to mount.
=> Makes pinning not depend on fractional differences.

maps/tether/tether-01-surface1.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-05-station1.dmm
Here's a simple first PR from me.
I couldn't knock together a whole new map within 20 minutes so I've settled for second best and added a few fixes to Tether instead.
The full list of changes are as follows:
- Added air alarms in: Atmospherics second floor, Custodial closet.
- Added emergency shutters in: Atmospherics first floor, Surface 1 staircase/Primary Tool Storage corridor, Station 1 Vacant Restaurant (in line with Station 2 Vacant Restaurant that already had shutters.)
- Fixed atmospheric supply/scrubber pipes actually going into atmospherics.
- Fixed missing green mixing pipe in atmospherics.
Here's an image of all the changes, highlighted:
=> Adds missing air alarms, emergency shutters and air supply

code/modules/research/rdconsole.dm
Changlings
Makes Rnd console maybe display Steel as Steel, Osmium as Osmium, and Plastic as Plastic 
Hos is a Ling?
Do gold/diams/green/sliver/glass being all uppercase and the three up their not being upper case
Rather annoying to me
=> [DNM] Maybe makes the Rnd console use uppercase letters 

code/modules/research/designs/medical.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#774
Yeah uh, I forgot to close these ones but I do NOT think science should get instant injection hyposprays of any kind. End game or no end game.
Port main hyposprays if you really want R&D to have hyposprays, the dual mode ones with delays. The instant one defaults to CMO only for a good reason. Stop powercreeping R&d with these things.
=> Revert "Makes Mark one and two hyposprays printable via RND"

code/modules/mob/living/carbon/human/species/outsider/vox.dm
This is accomplished by giving them the normal unarmed claw and bite attacks instead of the ones that have the 'shredding' property that allows handcuff breaking.
=> Disallows Vox from breaking handcuffs

modular_citadel/code/modules/detectivework/tools/rag.dm
You ever just fail to light a rag? This fixes that, because rag flammability is determined by weldfuel or ethanol-based reagents having 2 or more units in the rag.
=> More Rag Volume + Rags Are Ignitable

code/modules/mob/living/carbon/human/life.dm, maps/submaps/shelters/shelter_2.dmm, maps/tether/tether-01-surface1.dmm, modular_citadel/code/datums/supplypacks/misc.dm
- HUDs from hardsuit visors and optical scanners and everything else work through binocs. Theoretically.
- A pair of binoculars was thrown into Mining again, on top of the cell charger.
- There's a washing machine in the luxury survival pod.
- The holoplant is now tucked in the corner next to the sink.
- Ration crates now have a lower point cost, and have two extra rations.
=> Yet Another Mining Buff From Hatterhat - Binocs and Washing Machines

modular_citadel/code/modules/vore/fluffstuff/custom_items_cit.dm
It's a fucking copypaste operation.
=> Readds life crystal/alert functions because when you "rename an item for lore purposes" you do not remove its functions 

code/datums/supplypacks/munitions.dm, code/game/objects/items/gunbox_vr.dm, code/modules/projectiles/guns/projectile/pistol.dm, code/modules/projectiles/guns/projectile/revolver.dm
Gunboxes. Oh, God, it's Gunboxes.
-
- Instead of reskinnable M1911s in the Security Basic Equipment crate, it's gun boxes now.
- Gun boxes dropped the NT Mk58 in favor of the respriteable M1911. Just right-click the gun that comes out to reskin it if you really want another Mk58.
- Everyone in Security can now rename detective .45 revolvers.
=> Sidearms but Cooler

code/modules/mob/mob.dm
Respawn timer is unreasonably long because Vir devs make me want to scream.  This changes it to fifteen seconds, that way it still can't be spammed with any sort of speed, but it's still convenient enough that anyone who's legitimately checking out a round isn't inconvenienced.  Suggested the change to Kevinz, he asked me to make a pull. 
Edit: Upped the time from fifteen seconds to a minute, a time that isn't quite as quick, but still isn't a speedbump in the slightest for people that are using respawn for legitimate reasons.
=> Makes the respawn timer not make me wanna commit oof()

code/modules/power/smes.dm, code/modules/power/smes_construction.dm, maps/tether/tether-05-station1.dmm, nano/templates/smes.tmpl
The main SMES is now a subtype, rather than a mapmaker var-edited normal one. This also means that it now sends a stationwide alert every 3 minutes when between 30 and 20% to alert the station to set up solars, and when below 20% to alert the station that non-Engineering personnel are now permitted to attempt an engine startup. 
It **shouldn't** output the message when the SMES is actively charging, so it doesn't spam the message when you charge it after a discharge for upgrades. The unfortunate thing is, it will paste the message every 3 minutes during controlled discharges for upgrades but, this is hardly spam.
Also makes the main SMES a SMES subtype, so this can be put on any map at any time just by using the /main SMES subtype. Cool. Engine SMES is also now a subtype, but with no new …
=> Main SMES changes

code/modules/power/smes.dm, nano/templates/smesmain.tmpl
So, I am a retard and changed all SMES units to have the "mute" button, when in reality only the main subtype should. This fixes that. Thank you darksouls.
nword
=> Fixes my idiocy

code/modules/clothing/under/accessories/armor.dm
Literally what it says on the tin. It was a slight icon mishap.
Changed icon_state = "armguards_bullet" & icon_state = "armguards_laser" to icon_state = "armguards_ballistic" & icon_state = "armguards_ablative"
Same story with legs.
=> Fixes Bulletproof and Ablative Plate Carrier Attatchments having no Icon.

code/game/machinery/doorbell_vr.dm, code/game/machinery/exonet_node.dm, code/game/machinery/machinery.dm, code/modules/hydroponics/seed_machines.dm, code/modules/mining/drilling/drill.dm, code/modules/power/batteryrack.dm, code/modules/power/tesla/coil.dm
by adding circuits to most of them, and removing the ability to crowbar deconstruct for the rest.
_also for my boys in xenobotany:_ while i'm at it, xenobotany machines are wrenchable and can be unanchored now.
:cl:
tweak: Xenobotany machines (centrifuge and delivery system) can now be unwrenched and moved.
fix: Machines no longer dismantle() if they have no circuit board by default.
fix: Removed the ability to use a crowbar on certain machines that didn't have a circuit board.
fix: Gave drill braces, grounding rods, and exonet nodes their circuit boards back.
/:cl:
=> Fixes machines that spawned an empty frame and runtimed on dismantle attempts

code/game/jobs/job/engineering.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/z_all_jobs_vr.dm
these should provide a good intermediary between interning and working the full role, while still broadcasting 'i'm learning, teach me!'
todo: potentially better title than 'junior scientist'? just waiting on nicc to ask a friend about it.
update: only 'good' alternative was 'associate scientist', which sounds a bit too ambiguous. junior scientist will do.
:cl:
add: 'Junior' alt titles for Science, Engineering, and Medical; Junior Scientist, Junior Engineer, and Medical Resident.
/:cl:
=> Adds Junior Scientist, Junior Engineer, Medical Resident

code/modules/power/smes.dm
Now checks 3 times in a row, and the third check checks against the first. Only fires the alert when certain conditions are met.
Basic rundown. Every tick, it checks if the power is above, or below the last tick. If it is it marks a yes, and does it a second time, and then a third time. If all 3 of those show a lower power than the last, and the third check is lower than the first, to catch out weird edge cases, the alert fires. On the forth check, it resets it all back to no, and starts over.
Getting false positives is gay.
:cl:
fix: bad drain detection
/:cl:
=> release ready SMES changes

code/__defines/misc_vr.dm, code/datums/outfits/jobs/civilian.dm, code/defines/procs/announce.dm, code/game/jobs/job/assistant.dm, code/game/jobs/job/job_vr.dm, code/game/jobs/job/offduty_vr.dm, code/modules/mob/new_player/new_player.dm
Also removes Assistant as an alt-title for intern, and renames "Off Duty Worker" to "Off Duty Employee." ~~This may come with a config change to disable the PTO tracking, which should make off-duty 100% free of any constraints.~~
Instead, you now require 1 hour in a department to gain PTO, but it never gets spent. So, you can't join off duty medic without actually having played it.
=> Renames the "Visitor" role to "Assistant"

code/modules/xenobio/items/extracts.dm
[Changlogs]
Makes it so that when you inject a slime of blue space with blood it will make a real bluespace rock
[Why?]
For telecoms to work as intented. This can also be used in rnd to get a level in bluespace tho its pointless
=> Makes Blood + blue space slime = a real bluespace rock

code/modules/nifsoft/software/15_misc.dm
VIRGOOOOOOOO
Because now you can cancel the NIF sizechanger when you click it on accident, considering it stuns you for a long-ass time.
:cl:
add: NIF Size changer prompt can now be cancelled
/:cl:
=> Size changer prompt can now be cancelled

code/game/objects/items/crayons.dm
Fixes a bug with crayons allowing you to draw on tiles you're not next to. 
It's a bugfix.
:cl:
Fixes a bug with crayons.
/:cl:
=> Fixes being able to draw on tiles you are not adjacent to.

code/modules/recycling/conveyor2.dm
For one reason or another, conveyors, when constructed by players, have south and north set as their forwards and backwards directions, despite the conveyor's actual direction. I couldn't find a way to just make it fix on spawning, but, I did the next best thing.
This only adds a wrench option on conveyors. If you use a wrench on a conveyor that isn't operating and has its panel open, it runs the direction-setting part again, fixing the forwards and backwards directions.
Simply put, actually being able to create conveyors. I do hope, however, that people don't actually proceed to use this for the old banana peel conveyor circle. I also hope, that it isn't shortly used to crash the server. You people are better than that, aren't you?
:cl:
add: You can now use a wrench on a conveyor with an …
=> Adds an option to fix conveyor movement direction

.gitattributes
the diff having line ending changes here is quite ironic
:cl:
code: The git attributes file now forces all .dm files to (HOPEFULLY!) completely ignore line ending changes
/:cl:
=> [EXPERIMENTAL!] adds *.dm -text to gitattributes to fix the mirror bot having metric fuckloads of line ending changes

code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/game/objects/structures/crates_lockers/closets/secure/security_vr.dm, modular_citadel/code/game/objects/structures/crates_lockers/closets/secure/security.dm
Several crimes have mandatory tracking implants listed as punishment, but security doesn't actually have access to any. This remedies the inconsistency.
=> adds tracking implants to warden and head of security lockers

code/game/jobs/job/captain.dm
Because obviously it's a good thing to add a responsible title to an ERP job BEFORE we add responsible things for them to do like piloting ships :)
=> adds bridge officers to command secretary alt titles

code/modules/mob/living/carbon/human/species/station/protean_vr/protean_powers.dm, code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm
Protean balancing. Current heal does not allow for proteans to heal large toxins without a long wait time (~5 minutes and with multiple times required to absorb steel) 100 units of steel heals 0.1 toxins. So total heal of 10,000 steel is... 10 toxins.
Suggestion, revert the latter change if balance proves to be good for the health regeneration tweak.
:cl:
Tweaked: 	O.damage = max(0,O.damage-0.1) to 	O.damage = max(0,O.damage-1). Allows for proteans to heal 100 toxins without waiting forever and running out of metal. Current rate is 0.1 for 100 steel, new rate will be 1 for 100 steel.
Tweaked:	if(health < maxHealth*0.5) to 	if(health < maxHealth*0.35) to allow for protean to still be somewhat useful in combat (current forces proteans to auto-blob at half health)
The max health change …
=> Protean balance tweaks

code/game/area/areas.dm, code/modules/client/preference_setup/global/setting_datums.dm, code/modules/client/preferences_toggle_procs.dm
This replaces all mentions of ambiance with ambience to make it more consistent to work with
=> replace ambiance with ambience

code/game/objects/structures/trash_pile.dm
Because something that people will only use to be dicks to each other really shouldn't be this easily accessible.
=> Removes voice changers from trash piles.

maps/tether/tether-05-station1.dmm
Replaces library conference room with kitted DnD room. Book binder and fax from conference room moved into librarians area. Also deletes space carp spawn directly below window (who wants a DnD session ruined because of a space carp)
Adds small clown stash beside the excursion shuttle in large empty room.
Replaces broken violin with a piano.
=> Replace Library Conference Room w/ DnD Room

code/modules/mining/satchel_ore_boxdm.dm
Changes the way ore boxes work in two ways.
1. Changes interaction messages from `usr <<` to `to_chat(usr)`
2. Adds a delay to dumping ore.
That's literally it.
This change prevents people from one click dumping over 10,000 items at once.
It'll probably make shit lag less, but no promises.
(Also enforces some extra to_chat usage because to_chat is nice.)
:cl:
tweak: Makes ore boxes unload gradually over time.
/:cl:
=> Nerfs Ore Boxes

code/modules/paperwork/faxmachine.dm
makes fax machines density = 0
a fax machine is not dummy thicc enough to stop people from climbing around it
note: may make spare stealing easier and less easy to spot instantly due to "why is the fax machine on the fucking floor"
:cl:
tweak: fax machines are no longer dense
/:cl:
=> thin fax machine

modular_citadel/code/modules/clothing/under/accessories/accessory_cit.dm, vorestation.dme
Minor addition, that allows all collars to be named without using label machine. While testing, shock collar and holo-collar could be named with one way or another without issues. **Modularised**.
_Suggested by Jaded Cargo Birb/yourdoom9898._
It's good for RPers who like to wear collars ~~for some reason~~ and don't want to use holo/shock collars. Also, label machines doesn't allow you to blank the collar tag if you messed up or changed your mind, while with this addition it will be now possible.
:cl: Anonymous
tweak: All collars can be now tagged with pen.
/:cl:
=> Allows collars to be named/tagged with a pen

code/game/objects/items/contraband_vr.dm
cohiba robusto cases are now present in stolen packages
because sometimes you need something to celebrate your RNG
:cl:
add: Cohiba Robusto cases now exist in stolen packages obtainable through Cargo.
/:cl:
=> cohiba cases in stolen packages

code/modules/power/lighting.dm
Changes the power factor for lights from 20W to 5W.
This change has been carefully tweaked, as previously a single average light tube used about 160W. That same light tube now uses about 40W, which would be in line with a real-world T12 grade florescent tube light.
This change is multifaceted, and is a fairly substantial shake up to the power-grid balance.
This PR has been made on the assumption that the station shouldn't be entirely power-able by the solar array alone. (I dunno if I agree with this, I'm just assuming it's the defacto balance.)
But the current power usage from lighting, on such a large map is absolutely absurd, requiring in some cases more power than a default map-spawn engine set up would provide.
To summarize, this PR is designed (and from my testing achieves) the …
=> Reduces Light Power Consumption to Be More Realistic

code/game/objects/items/robot/robot_parts.dm
Allows roboticists to construct the ED-CLN by adding plastic sheets to a robot frame.
This good cleaning boi was previously impossible to make, since its assembly had no recipe. Now it can be made.
:cl:
add: Adds a way to create the ED-CLN assembly by adding plastic sheets to a robot frame
/:cl:
=> Allows construction of the ED-CLN

maps/tether/tether_defines.dm
A single-line change to the tether_defines that causes gps units and crew monitoring computers to return the contents of their own zlevel if no other data is available. I've done some testing and haven't encountered any major issues.
Partially referenced from [Polaris PR #6247](https://github.com/PolarisSS13/Polaris/pull/6247). We don't seem to use the same modular computers sytem, so the full PR can't be ported, but it seems to function fine without the modular computer change.
Riddle me this; why are the Explorers issued handheld tracker units that can't track each other away from the station, where such devices would _actually be useful_? Normally, the trackers only function on a handful of preset levels. Despite this, handheld trackers can be found in several POIs and in the abductor …
=> GPS self-z functionality

code/modules/client/preference_setup/loadout/loadout_accessories.dm
Title.
Hatter had a PR up doing this shit but the changes weren't applied to code. Weird because as a SaR all the webbings are accessible in game. The holsters are so that Explorers/SaRs/PFs can take an exploration phaser or a backup pistol in lieu of a machete.
=> Changes to allow explorers to use any webbing or holster

code/modules/multiz/movement.dm
This pull request drastically lowers the ammount of nutrition spent with the winged flight ability.
As far as I've seen, not many people really use this ability, as it's something one can only do in the atrium or some very specific z-levels, but it always struck me as odd and rather infuriating how races that were supposed to have flight as a nearly essential part of their lives simply start getting exhausted after thirty seconds of gliding around the atrium, only to pummel to the floor once they get hungry enough ten seconds later.
Pretty sure nutrition can work with decimals, it did work on the server I set up to test it out so if it doesn't then you all have permission to call me dumb and stab me.
:cl:
code: Changed flying nutrition code
/:cl:
=> Making flying not cost your entire lunch and your life

code/modules/organs/blood.dm
Fixes a very weird typo in bloodloss messages, adds a couple of extra descriptors for flavor, and also some minor clarification between minor and moderate bloodloss levels.
'Woosey' isn't a goddamn word and I swear someone mentions it every time bloodloss comes up. Also it makes things a bit clearer where you're at vs minor/moderate/major bloodloss.
:cl:
tweak: added a couple extra words to bloodloss states
spellcheck: fixed a typo
/:cl:
=> fixes some words/phrasing in bloodloss messages

code/modules/mob/living/carbon/human/species/station/station.dm
Title, but to be specific this PR removes the sharpness from their melee attacks, removes their darksight, returns their burn modifier to baseline and does the same with their bleed rate. 
This PR also changes the economic modifier for Unathi and Tajarans to be in line with Human economic modifiers. 
Unathi are wayyyyy too powerful, to create a custom species with THIS PR's UNATHI STATS, would STILL be impossible, it's big stoopid. 
:cl:
balance: Slightly nerfs Unathi.
/:cl:
=> Nerfs Unathi slightly. 

maps/southern_cross/southern_cross_jobs_vr.dm, maps/southern_cross/structures/closets/misc_vr.dm, maps/tether/tether-05-station1.dmm
Gives Pathfinders access to the main R&D lab and the Firing Range, and assigns them their own unique access ID number (44). This means the PF's office & locker aren't keyed to Gateway Access any more.
This doesn't give Pathfinders access to any other parts of science: they still can't get into xenoflora, xenobio, robotics, or the anomaly lab.
1) Explorers and the Pathfinder can already get into the Firing Range by going through maintenance, so there's little reason to keep them out.
2) Exploration team is the most likely to need to acquire additional supplies from R&D, but sometimes no staff are available or even on-shift. This allows the PF to acquire said supplies if nobody is available.
3) Heads with Gateway Access (HoS, RD) can no longer just march into the PF's office like it's no …
=> Pathfinder Access Tweaks

maps/southern_cross/job/outfits.dm
Changes Pilot PDAs to be generic greys with no cart.
Pilots are not in the Cargo Department and should not receive Cargo Department Relay Messages.
:cl:
tweak: changes Pilot's PDA type
/:cl:
=> Pilot PDA Switch

code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
Realized how garbage the recharge rates for engineering hound resources was. Stripped that shit out and made it in line with the base engineering module. Added plasteel synthesizer as well as the sheet loader grasper to make it in line with the base module.
=> Unfucks Engineer Hound Recharge + More

code/datums/autolathe/tools.dm
Adds cable coil to be printed from the autolathe for roughly 64 steel units and 20 glass units and can be printed in 5 cable increments up to 30. Always found it odd it can't be printed, and I've personally run into cases where I wind up using so much cable it becomes inconvenient to scavenge about the station. Only prints out in red because it's either that or a random color each time.
Less faff for getting more cable when needed for projects. Only prints out in red.
:cl:
Add: Cable coils to be printable from the autolathe in a single wire or 5 wire increments up to 30.
/:cl:
=> Adds Cable Coils to Autolathe

code/modules/clothing/spacesuits/rig/rig.dm, code/modules/clothing/spacesuits/rig/rig_pieces.dm, code/modules/clothing/spacesuits/rig/suits/alien.dm, code/modules/clothing/spacesuits/spacesuits.dm, code/modules/clothing/suits/bio.dm
remakes #1334, makes rig pieces phoronguarded
you literally cant wash rig pieces in a washing machine so this is the next best thing
:cl:
tweak: Hardsuit pieces (gauntlets, boots, chestpiece, helmet) now have PHORONGUARD.
code: PHORONGUARD is supposed to be a flag and not an item_flag. Adjustments made. Probably.
/:cl:
=> did you guys know that phoronguard was supposed to be a flag and not an item_flag? i didn't

code/modules/mob/living/carbon/human/emote_vr.dm
Turns out copy pasting code from non human mobs into human code might bork things, who'd've thunk
Allows people to chirp to their heart's content without it stating their name twice.
:cl:
fix: fixed the chirp emote saying a human mob's name twice
/:cl:
=> Fixes the chirp emote for human mobs

code/datums/autolathe/tools.dm, code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
Probably final change to this, but I didn't think of it earlier. BOOP module doesn't get the contents of pipes, and as that's kind of semi important for an engineering borg, added in the base analyzer alongside the BOOP module. If I had knowledge to get BOOP to analyze contents of pipes and canisters, I would.
Getting that module in ship shape.
:cl:
add: Analyzer to engihound
/:cl:
=> Because Boop Doesn't Do This

code/game/mecha/mecha.dm, code/modules/mob/say.dm, code/modules/mob/say_vr.dm, code/modules/mob/typing_indicator.dm
Updates the "Say" and "Whisper" text boxes to have a cancel button and the "Me" and "Subtle" emotes to display in multiline text boxes as opposed to the single line boxes that they used to use.
Allows immediate backing out of speaking IC by hitting cancel instead of being forced to wipe all the text in the box and sending an empty message. The emote changes mean you can proof-read your para posts with greater ease now.
:cl:
tweak: "Say" and "Whisper" now have a cancel button on their pop-up box. "Me" and "Subtle" also have this, in addition to being a multiline text box now instead of the old single line one.
/:cl:
=> QoL Updates to the text boxes for talking & emotes

maps/tether/tether_phoronlock.dm
Port of https://github.com/VOREStation/VOREStation/pull/5470
Makes the Phoron Scubbers work almost twice as fast, while taking slightly more power. They now heat the air while working, preventing atmos alarms from the cold. They now filter down to a lower phoron amount, preventing leftover phoron in the connecting area.
Makes getting into and out of the station easier, faster, and safer. Mainly a QoL change, as waiting for an airlock to cycle is booty.
:cl:
tweak: Makes Phoron Scrubbers work much faster, adds air heating to them as well
/:cl:
=> Makes Phoron scrubbers stronger

code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
Medihounds now get large instead of normal beakers.
Flump/Kered wanted it, not me.
:cl:
add: Medihounds now get a large beaker, instead of a standard beaker.
/:cl:
=> medihounds get beakers but not standard medborgs? hmm

code/modules/materials/material_recipes.dm
Fixes a bug, I guess.
:cl:
fix: Sandstone can now be used for making plant plots.
/:cl:
=> Sandstone Plant Plots

code/modules/clothing/spacesuits/void/void.dm, maps/tether/tether-01-surface1.dmm
The miners now get magnetic boots. This should help if they're pulled into an expedition or if their mining locale of choice suddenly loses all of the atmosphere.
Toggling magboots is good because sometimes you just want to be able to pull a knife out of your boots, even in a voidsuit. Somehow.
Boot knife accessibility, magboots for magboot equality.
:cl:
add: Miners now get magboots. They're not required, but you might as well have them anyway.
tweak: There is now a toggle magboots verb for voidsuits - right-click on your voidsuit or access the objects tab to use it.
/:cl:
=> Miners With Magboots + Toggle Magboots

code/modules/mining/fulton.dm
Closes #1546 by partially reverting #1304. No, I don't know why that code made it so mobs were the only things you could fulton without the beacon getting stuck. Rest assured, I think it's awful too.
Also makes the stun meant to prevent people from running around while being fulton'd is no longer twice the time it takes to actually be fulton'd.
Makes it so you can fulton things that aren't people without it getting stuck in a mob check. Also makes the "oh God why am I stunned for half a minute" now down to "oh God why am I stunned for like ten seconds more".
:cl:
tweak: Fultons should now fulton people and things equally as well, now. Probably.
/:cl:
=> Fulton Fixes - objects and stuntimes

code/game/objects/structures/transit_tubes.dm, code/modules/mining/drilling/scanner.dm, code/modules/mining/satchel_ore_boxdm.dm
Ore scanners can now have their range fiddled with when alt-clicked. Ore boxes no longer get destroyed on explosions.
Ore scanners - More precise usage of scanners, primarily the advanced scanner variant. Only available for handhelds, todo is adding the modifying functionality to the hardsuit module itself.
Ore boxes - I crashed the server once by blowing up an ore box that was stuffed with ores. This is a stopgap measure. (Why doesn't it just have variables or datums or whatever for ores? I don't know, but I hate it. ORMs when, kevinz?)
:cl:
add: Ore scanners can now have their range switched around with an alt-click!
tweak: Ore boxes no longer explode and drop all their contents on ex_act(), meaning that they probably shouldn't crash servers when they get broken. I hope.
/:cl:
=> [READY] Ore Scanner Range Toggle (Altclick) + Ore Boxes No Longer Explode

code/game/objects/items/weapons/tools/weldingtool.dm
You can now hit people with a lit welder to set them on fire if they're flammable (i.e. had weldfuel splashed on them).
Fixes a bug that nobody's really tried to fix. Also lets you set people on fire if they're flammable.
:cl:
fix: You can set people on fire with a welding tool now.
/:cl:
=> Welding Tools Now Set Flammable People On Fire (on non-help intents)

code/modules/mob/living/carbon/human/human_movement.dm
Adds a single line and a tab that makes slowdown only be affected by species' item slowdown modifier when it's positive.
Fixes an issue. Probably introduces powergaming issues. Who knows.
:cl:
tweak: Wearing equipment with negative slowdown values (i.e. alien enhancement vests) will no longer be useless if you've taken an equipment-slowdown-affecting trait such as Major Hardy.
/:cl:
=> Hardy No Longer Suffers With Negative Slowdown

code/game/objects/items/robot/robot_upgrades.dm, code/modules/mob/living/silicon/robot/robot.dm
We already do this for humans, and we have no reason to have people run around as improper nouns (as lowercase automatically makes byond think someone's an improper noun when their name is read in code). we also have no reason to have all lowercase names in the first place.
=> Enforces automatic first letter capitalization of cyborg names

code/modules/admin/holder2.dm
I always wanted to edit fakekey and there's a buncha shit in here that is unnecessarily locked.
Also adds a #define TESTING check, as if that's defined it's assumed you're in a debug environment.
=> Unprotects admin datum from varedit except for rank/permissions variables

code/game/objects/items/weapons/handcuffs.dm, code/game/objects/items/weapons/handcuffs_vr.dm
fuzzycuffs are now 3 seconds to break out of instead of 120
fuzzy legcuffs are now 3 seconds to break out of instead of 30 or whatever
>>>kinkshit taking as long to break out of as standard
:cl:
tweak: Fuzzy handcuffs, like the ones you kinky bastards use, are now 3 seconds to break out of instead of 120. Who thought this through? Clearly, someone didn't.
tweak: Fuzzy legcuffs take 3 seconds to break out of instead of 30. Yikes, bro.
/:cl:
=> why the fuck do fuzzycuffs act as standards

code/game/world.dm
Makes submap generation/map template placement respect GENERATE_MAP in config.txt.
Faster initializations for faster debugging by aspiring coders.
:cl:
code: Disabling the GENERATE_MAP setting in config.txt now prevents submaps from generating. This prevents the use of shuttles, but also makes the whole map initialize really, really fast.
/:cl:
=> Submap Generation Respects Config

code/game/objects/items/devices/tvcamera.dm, code/game/objects/items/weapons/material/foam.dm
This one I'm hesitant on. So foam weapons don't work because they do 0 force/damage. Which means they literally won't attack. Until I can be fucked to make that not the case, this is the temporary. They now do One(1) brute damage, and also sometimes cause bleeds which is annoying but hey it's a minor fix and now you can bash people to death with 100 smacks of a foam weapon. Enjoy.
also closes #1435
=> makes foam weapons work, i guess

code/game/machinery/Sleeper.dm
seriously. There is no code to handle sleepers being destroyed so it just leaves you there, in stasis. This fixes that. Thanks virgo/polaris.
fixes #1411
=> Seriously? Adds code to handle sleepers being destroyed

code/modules/busy_space/air_traffic.dm, code/modules/busy_space/organizations.dm
Does some further work on top of #1470 to fix some issues I overlooked, and lay the groundwork for future additions.
As with the original this has been pretty extensively tested besides just checking if it compiles or not.
Fixes stuff. Unbreaks other stuff. Sets up a couple of things that can be built on later if lore is ever prepared.
Main changes are "Station Space Control" to "System Flight Control" as futureproofing for possible planetside maps, and splitting out the 'law abiding' quality into lawful (now defaults to true) and sysdef. Also adds a couple of new events (SDF ships beginning patrols and scanning regular ships, launches being delayed rather than hard denied) and tweaks existing ones slightly.
Probably one of the biggest changes is a rework of autogenerated destinations; …
=> SpaceTalk Expansion Pack 1

code/game/machinery/pipe/pipe_recipes.dm, code/game/objects/items/weapons/RPD.dm
This PR makes three tiny changes to the RPD that should make it more consistent to the end user.
1: The Wrench Mode button no longer turns grey when it's turned off. (One person reported not seeing it at all.)
2: Pipes that aren't paintable, no longer print pre-painted. While I enjoyed abusing this issue during development, it turns out some pipes disappear entirely if printed pre-painted. Whoopsie.
3: Fast layering has been entirely removed. When I ported the device I wasn't really sure what this feature did, and I think it's fairly clear no one else does either.
Fast layering was a feature that meant you could click a pipe, and the RPD would attempt to automatically attach the next pipe to that one. Obviously, this is confusing, as you might not notice you clicked a pipe, and begin to …
=> Small tweaks/fixes for the RPD.

maps/tether/tether-07-station3.dmm
Fixes the area assigned to a tile in medbay. I could've sworn this was fixed a while back but apparently not?
Once you notice the lighting's weird you'll never **not** notice it. It's driving me up the wall.
:cl:
fix: fixed a tile in the treatment center being assigned to the 'space' area
/:cl:
=> Medbay Area Fix

code/modules/admin/DB ban/functions.dm
Admins aren't stupid enough to flood bans for nonexistant users, and if they really did want to do that because they were malicious there's far worse things to do, all this does is annoy the shit out of us when we try to preemptively ban/mirror a ban a problematic person.
=> Removes the "has this user been here before" check from bans

code/datums/supplypacks/robotics.dm, code/modules/vehicles/bike.dm
Increases the speed of space bikes on land, and reduces cargo cost.
They have a dumbly high power usage and the batteries last about 10 minutes, they are also slow. Instead of changing the power usage I made them significantly faster
Cargo cost has also been reduced because I feel it is a bit much, while doing this I noticed that for some gay reason ATV TRAILERS(Not the ATV itself) were priced at some dumb shit and reduced it.
:cl:
tweak: Reduces ATV trailer cost from 250 to 50
tweak: Reduces bike cost from cargo from 350 to 200
balance:  Increase bike speed
/:cl:
=> Spacebike buff

nano/css/shared.css
Changes the display color of toxins damage on the crew monitoring displays from html green to html lime.
Doesn't touch health analyzers.
Makes toxin damage easier to read, especially if you're tired, have a dark display, or _etc._
:cl:
tweak: changed color of toxins damage on all crew monitors
/:cl:
=> Brighter tox damage on Crew Monitor

code/game/area/Space Station 13 areas.dm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm, maps/tether/tether-04-transit.dmm, maps/tether/tether-05-station1.dmm, maps/tether/tether-06-station2.dmm
Fixes numerous issues with recent map changes.
Adds missing wires, to connect the surface library to the power grid. 
Adds disposal segments to connect library to disposals network
Fixes broken disposals in tether midpoint
Fixed misplaced light and Guest Pass Terminal near surface library
Adds APC and telecomms relay to tether midpoint
Shifts the Asteroid 1 lounge north 1 tile, making the hallway 2 wide.
Redefines the areas for the kitchen and freezer on asteroid 1, making them distinct from surface 3 kitchen (an air alarm in one would trigger both)
Redefines the area in tether midpoint maint, so it's no longer listed as "substation" on power alarms
Slightly adjusts areas in surface bar game room, so the door and windows are powered.
Adds holopads and cameras to Asteroid 1, so the AI can …
=> Numerous fixes to new areas

code/modules/events/event_container_vr.dm, code/modules/events/supply_demand.dm
Adds the cargo bounties back into rotation, removes PDA spam from rotation
The bounties give a otherwise bored cargo something to do, and PDA spam is just obnoxious and spawns _every_ shift
:cl:
tweak: Changed event rotations
/:cl:
=> Adds a few events into rotation, takes PDA spam out

maps/tether/tether-01-surface1.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm, maps/tether/tether-05-station1.dmm, maps/tether/tether-06-station2.dmm
For some reason, the pink cables going to the chapel weren't taking power from the ones next to them, causing the chapel to never be powered despite being wired correctly. This remedies that.
Removes duplicate security cam from surface 2
Fixes Library maint so there's no longer a door blocking egress 
Adds steel walls to tram station maint, and changes the area to better reflect the location
Changes asteroid lounge external walls to be reinforced, as they're touching space
=> More Misc map fixes

maps/tether/tether-03-surface3.dmm
Closes #1642 
Changes doors in the firing range to have reqaccess(47), which is the same as the research front desk.
=> Changes Firing range doors to have same access as research door

maps/tether/tether-03-surface3.dmm, maps/tether/tether_shuttles.dm
Addon to #1601: fixes the lack of a docking controller for the excursion shuttle on the surface 3 pad.
Mostly just fixing things I forgot to do before. The shuttle can now actually be ordered to dock when landed.
:cl:
fix: fixed lack of docking controller for s3 landing pad
/:cl:
=> Fixes missing docking controller

code/__HELPERS/global_lists_vr.dm, code/modules/events/grubinfestation_vr.dm, code/modules/mob/living/simple_animal/vore/solargrub.dm, code/modules/mob/living/simple_animal/vore/solargrub_larva.dm
Ports https://github.com/VOREStation/VOREStation/pull/6442
:cl:
add: The facility PA will now chime in after a period of time, if not all solar grubs have been killed.
/:cl:
=> Ports Grub Announcement fix

maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm, maps/tether/tether_areas.dm
They say if you want something done, do it yourself. So I did. This PR replaces the useless-ass fire/phoron shelter with a slightly-expanded hydroponics bay. The old hydroponics area is now the 'vacant shop' area.
The surrounding area has been reworked a little too;
I consider this 'ready to merge' in its current state, but am open to feedback or suggestions, especially from players with more hydro experience.
Also adds a strip of a new 'bar maintenance catwalk' area and an APC to the exterior of surface 3 just outside the bar, so the lights outside the bar will be powered.
The phoron/fire shelter was pretty much never used at all ever by anyone? I mean I guess you could go fuck there but really, who would choose it over a dorm room?
Hydroponics is now bigger so there's lots more room to …
=> Shelter-B-GON, Hydroponics Moved

code/game/area/Space Station 13 areas.dm, code/game/objects/items/weapons/storage/belt.dm, maps/southern_cross/structures/closets/misc_vr.dm, maps/tether/tether-05-station1.dmm, maps/tether/tether-06-station2.dmm, maps/tether/tether_areas2.dm
An extensive rework of the exploration hangar area. Behold!
A little outdated, but it gets the main points across.
To summarize;
* As a whole, the exploration area is less 'barebones'. This overhaul isn't as complex as Virgo's current setup, but I'm not trying to integrate the currently nonfunctional gateway.
* Prep room significantly expanded, and more voidsuits are provided to match the number of lockers (and job slots), along with seperate medical suits and a medical cycler. The pilot suits and cycler have been moved into the prep room. It also has a basic drill, a shovel, an anomaly detector, and a cyborg analyzer.
* The pathfinder's office is larger, better lit, has its own fax machine, and includes its own recorder and omnitranslator. The PF's locker contains a new belt that holds a …
=> Exploration Hangar Rework

code/modules/vore/fluffstuff/custom_clothes_vr.dm
Re-adds a proc to this item, that stops it from losing it's custom name/description when the name is set
=> Readds a removed proc from my fluff item

maps/tether/tether-01-surface1.dmm, maps/tether/tether-03-surface3.dmm
Makes it so the intercoms in atmos and the public garden aren't broadcasting at round start
=> Turns off the two randomly broadcasting intercomms

maps/tether/tether-01-surface1.dmm, maps/tether/tether-03-surface3.dmm
Adds more Vents and Scrubbers to Shuttle Pad. Removes extra air alarm that was causing problems. Adds fire alarm to room.
Moves dome of the air alarms so they're not inside firelocks when an atmos alert happens.
Fixes wrong type of lights on surface 3 walkway. Fixes double-spawning table.
Fixes issue where some intercoms were reversed in direction.
Moves fire extinguishers out from inside windows. 
Moves barsign so it's only visible from the outside of the bar. This lets the guest pass terminal underneath the sign be usable.
=> Misc Fixes to Station 1 and 3

code/game/objects/structures/crates_lockers/closets/secure/engineering.dm, maps/submaps/engine_submaps/engine_sme.dmm, maps/submaps/engine_submaps/engine_tesla.dmm, maps/tether/tether-01-surface1.dmm, maps/tether/tether-03-surface3.dmm, maps/tether/tether-05-station1.dmm, maps/tether/tether-06-station2.dmm, maps/tether/tether-07-station3.dmm
Adds Shield diffusers around most paths outside the station that normally had to be bashed through. Also adds handheld diffusers to engineering lockers
Diffusers have been in the game and code since pre-polaris baycode, and really should have been mapped into the tether initially.
:cl:
add: Shield Diffusers are now mapped in, meaning shields won't form on certain access paths.
add: Engineers now get handheld diffusers in their lockers, to instantly break shields (No more crowbar bashing)
/:cl:
=> Adds Shield Diffusers around most EVA exits

code/game/machinery/alarm.dm, code/game/machinery/doors/windowdoor.dm, code/modules/food/kitchen/cooking_machines/container.dm, code/modules/food/kitchen/cooking_machines/grill.dm, code/modules/mob/living/simple_animal/vore/solargrub_larva.dm
This PR addresses various various unexpected behaviors encountered while playing the last couple days, and in itemized list form:
- Makes kitchen grill no longer break after a single cooking cycle
- Makes the oven tray empty contents verb usable while holding it
- Addresses a runtime that results in some windoors not breaking #1667 
- Addresses solar grub infestation effects persisting after ejection #1512 
- Allows fire alarms to be deconstructed (again?)
This is nothing but bugfixes and addressing erroneous behavior.
:cl:
fix: Kitchen grills no longer break after a single cooking job
tweak: The oven tray emptying verb can now be accessed while holding it
fix: Fixes certain windoors dropping materials without breaking.
fix: Hopefully prevents solargrub infestation glow from showing up …
=> Miscellaneous fixes, resolves issues #1512, #1667

code/game/jobs/job_controller.dm, code/modules/mob/inventory.dm
Fixes inexplicably janky behavior I would've sworn was fixed before Polaris forked off, let alone Vore
See #1693, also changelog
Before:
After:
:cl:
fix: Loadout now respects capacity and size rules when spawning into backpack; will not nest duffelbags.
/:cl:
=> Implements sanity checks for loadout spawning, resolves #1693

code/modules/mob/living/carbon/human/emote.dm
Some species have a specific scream sound defined in their code but the actual element of the scream emote that plays the sound was disabled some time in the past due to the people at the time having poor scream emotes. I re-enabled it. If a species lacks the scream sound, then no sound plays.
Let my people scream
:cl:
code: Uncommented the 'playsound' portion of the scream emote code so sound can be played
/:cl:
=> Re-Enables Playsound for the Scream Emote

code/game/machinery/jukebox.dm, config/jukebox.json, config/jukebox.txt
This update brings an abundance of music to the jukebox, so that
we can finally listen to something other than the same four songs on
repeat like we have been for who knows how long now. Additionally, this
update lays some better foundation for adding songs to the jukebox in
the future, by adding new genres of music to the selection choice.
All genres of music now have at the *least* five songs in them, so that
we no longer look like we've just left the jukebox as an afterthought.
(alt title: DJ Drof's Mixtape Volume 1, with Crew Input)
This update brings an abundance of music to the jukebox, so that
we can finally listen to something other than the same four songs on
repeat like we have been for who knows how long now. Additionally, this
update lays some better foundation for adding …
=> Adds Songs to the Jukebox

maps/tether/tether-05-station1.dmm, maps/tether/tether-07-station3.dmm, maps/tether/tether-09-solars.dmm
:cl:
fix: Cargo Mailing Room will no longer overpressurize
fix: Solar Shed will no longer throw an alarm if solars aren't wired
fix: Shield Diffusers at Engine EVA will now actually work
/:cl:
=> Misc Map Fixes

maps/tether/tether-07-station3.dmm
Adds a chemfridge to the chemistry public facing wall.
Helps ensure that people don't need to break in to get medical supplies if medical is MIA, while keeping the original medbay chemfridge for the more complex supplies to prevent people from mis-use of meds
:cl:
add: Added chemfridge to western wall
/:cl:
=> Medbay Changes/Upgrades : The word of the day is, chemfridge.

code/modules/media/media_machinery.dm
See title. Fixes #1735 
I've heard people worry that the bug, if left unresolved, could be a possible avenue to use to try and bring the server to a crashing fire. So we should probably fix that.
:cl:
fix: Fixed the "Phantom Jukebox" issue, wherein jukeboxes that once were in an area but since have been moved still played whatever new song the jukebox is playing, regardless of whether or not a jukebox is currently in said area.
/:cl:
=> Fixes Phantom Jukebox Problem, Resolves #1735

code/datums/supplypacks/misc_vr.dm, code/datums/supplypacks/recreation.dm, code/datums/supplypacks/science.dm
Finally, people can get a jukebox of their own.
Adds one crate to the "Recreation" category, the Jukebox crate, and another to the "Science" category, the Jukebox Circuit Board crate. 
Edit: Now also bumps the price up of liquidfood ration crates as requested, to prevent an exploit having to do with infinite cargo points... I think.
Now people can create their own cozy dens and enjoy music with friends in them. Additionally, it gives players more autonomy in the case of player-driven events, and circumvents the need to beg an admin for a jukebox for whatever plans they may have.
:cl:
add: Added two new crates to Cargo's consoles, one under Recreation, the Jukebox crate, and the other under Science, the Jukebox Circuit Board crate.
/:cl:
=> Adds two new crates, the Jukebox crate, and Jukebox Circuit Board crate.

code/game/jobs/job_controller.dm, code/game/objects/items/weapons/implants/implant.dm, code/modules/client/preference_setup/loadout/loadout.dm, code/modules/client/preference_setup/loadout/loadout_utility.dm, code/modules/mob/mob.dm
Fixes the issue with implants starting not inside the player, but in their hands and/or bag.
Just another good QOL change that lets their loadout properly load.
:cl:
add: Mind backup implant is now a loadout item for cost 2
fix: tracking implant now actually tracks
fix: implants now start INSIDE the person
code: adjusted the way implants get handled roundstart to properly load in and work.
/:cl:
=> Roundstart implants now work. Also known as: wow tracking implants ACTUALLY track you? Cool!

code/modules/clothing/masks/breath.dm
=> Breath mask toggles no longer require canmove (which buckling blocks) and instead checks the standard incapacitation/restraints

maps/tether/tether-03-surface3.dmm
These changes are coming in after the voting from the RP poll channel had an overwhelming support for both of these changes. The Kitchen will have a nice, darker tile, as well as tables and supplies moved about to make it easier for the chefs to do their work. The Bar and Kitchen are now connected too for them to easily work between when both departments are open. Furthermore, the bartender will have quick access to the jukebox instead of needing to hop over the table, or run all the way to the original glass door at the top. The bar will also now have wood flooring, and a wooden walkway connecting from the main entrance to the bar.
Kitchen: https://cdn.discordapp.com/attachments/686476138901667895/694056259305078784/Kitchen_Changes.png
Bar: …
=> Bar & Kitchen Changes (Map Layout) Otherwise known as: Uhh.. Bar and Kitchen.. changes..

code/game/jobs/access.dm
fixes id consoles linking stuff to the same list reference.
thsi is a shit system refactor soon tm :^)
=> bandaids around the shitty id system with .Copy()s to prevent stuff from touching the global cache lists

maps/tether/tether-03-surface3.dmm, maps/tether/tether-04-transit.dmm, maps/tether/tether-06-station2.dmm
Changing up the layout of robotics but giving them a jukebox, putting a service window for crew to easily ask for help for them like they can for general R&D. Adds an AI holopad, and intercoms to the mid-point tether. Finally, replaces the excess air alarms in the confession booth, adds more lighting AND also replaces the stools with benches.
QOL love, and suggestions from the community.
Sci Change - https://cdn.discordapp.com/attachments/686476138901667895/696228083639910480/RoboticsChanges.png
Chapel Change - https://cdn.discordapp.com/attachments/686476138901667895/696228086743826533/ChapelChanges.png
:cl:
add: Added holopad and intercomms in parts of the station as stated above
tweak: Service desk added to Robotics original side entrance.
/:cl:
=> Map Changes to Science, Midpoint and Chapel: Also known as, LOL why were air-alarms in the confession booth. 

code/datums/supplypacks/medical_vr.dm, code/modules/virus2/effect.dm, maps/tether/tether-06-station2.dmm
Virology has been a quiet/empty spot for the server since before I got here that's for sure, and even if it was accessible it had almost no benefit for players except antags. This is set to be a series of changes to bring Virology into a spot that is fitting for the server and community, and provide exploration and others some bonuses in their rounds.
(Re-did this since the previous one failed and needed Nicc to re-review this)
Bringing in more things for medical to do in their shifts, and provide some possibly fun RP situations. Eventually we will have a less RNG heavy method of virology, and a much larger swath of positive, and neutral, symptoms for the medical team to find.
:cl:
add: Virology crate now comes stocked with 4 random virus samples
add: new possible symptoms to get. …
=> Virology crates now stocked, plus new BENEFICIAL symptoms. Otherwise known as, "lol lynch viro anyways."

maps/tether/tether-03-surface3.dmm
Non major map changes. Fixing rotation of bar shutters, and adding atmos firedoors on the newly added glass windows for robotics.
QOL and improving safety of station.
:cl:
add: emergency atmos shutters for robotics glass windows
fix: adjusted rotation of some bar shutters
/:cl:
=> Minor map fixing on Surface-3

maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm
More minor fixing to level 2 and 3 of surface maps (Deep water, ensured alarms and other room critical supplies are for sure in, and a robotics anesthesia locker)
QOL love
:cl:
add: Spawn locations for Science Team
tweak: minor map tile fixing
/:cl:
=> More Minor Map Fixing, Also Round-Start Spawn Locations for Science Team

code/game/jobs/jobs.dm
someone asked me to and I think this is pretty sensical.
Exploration is meant to work as a unit, but on station, they're still part of their host departments, even if they can be pulled at times to do exploring.
:cl:
tweak: exploration roles now appear in their host department too, meaning sars/fms are also in med, explorers/pathfinders sci, and pilots civ
/:cl:
=> field medics are infact part of medical (all exploration roles now appear in their respective 'master' departments on manifest as well)

code/game/objects/items/stacks/nanopaste.dm
Hardsync made nanopaste not able to repair severely damaged robotic limbs. Fixes this.
you can't splint robolimbs, so having a surgery-free way to repair them is an option. This option was removed in the hardsync. Brings it back.
:cl:
add: Nanopaste no longer is unable to repair really broken robolimbs.
/:cl:
=> Brings nanopaste functionality back to pre-hardsync.

code/modules/projectiles/projectile/magnetic.dm
The FRC right now is more of a paper tiger than anything. It's big, threatening, takes all your TC to buy (as antag) but is not that practical as an offensive weapon without SM rods which are admin only.
hard to get unwieldly gun should be better
:cl:
balance: Fuel rod gun can now three-hit KO. Good luck getting the three hits off, though.
/:cl:
=> Buffs the Fuel Rod Cannon

code/__DEFINES/dcs/signals.dm, code/game/atoms_movable.dm, code/game/atoms_movable_movement.dm, code/modules/mob/mob.dm, code/modules/recycling/conveyor2.dm
Made conveyors and pulling things update their glide size to the host's glide size.
Conveyors now glide things at a size of 8.
Makes conveyors prettier since they're fast now.
=> Glide size tweaks

code/modules/vore/fluffstuff/custom_items_vr.dm
I don't particularly like translocators (hinting to that they'll die someday by my hands :^)) but until we rip off the bandaid this is convenient.
=> fixes translocators not teleporting to mining

code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm
Being canonically unable to die in-game is a bit too handwavey for my taste.
If they get blasted and die, then let them actually die.
Webedit PR man good.
=> Let Shadekin die.

code/game/machinery/vending.dm, code/modules/food/drinkingglass/metaglass.dm, code/modules/food/drinkingglass/shaker.dm, code/modules/food/food/snacks.dm, code/modules/food/food/snacks_vr.dm, code/modules/food/recipes_microwave.dm, code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm, code/modules/security levels/security levels.dm
Fixing up missing items in the drinks list, and sweatmax vendor. Did minor food tweaking and re-buffed liquidfood to 30 instead of 20. Removed the water from the shakers and lowers their volume to 50 from 100
QOL
:cl:
tweak: Shakers no longer have water. Drink up
tweak: Sushi now takes fish instead of steak meat LUL
tweak: Minor food value changes
fix: Re-added LiquidProtein to SweatMAX
fix: fixed missing sprites for a few drinks
/:cl:
=> Food & Drink Balance Pt 3: Otherwise known as, LOL sushi took steak meat and not fish meat

code/modules/client/preference_setup/loadout/loadout_uniform.dm, code/modules/clothing/under/solgov.dm, code/modules/clothing/under/solgov_cit.dm, code/modules/clothing/under/solgov_vr.dm, vorestation.dme
- crew uniforms are now named crew uniforms and not explorer's uniforms (subtypes)
- security crew uniforms have armor consistent with the standard variants (10 melee thats about it)
- thats probably it
nitpicking
:cl:
tweak: Crew uniform stuff. You probably won't notice too much.
/:cl:
=> a nitpicking pr about uniforms

code/modules/clothing/glasses/glasses.dm
Made the graviton goggles also airtight just like we did with material scanners and just like mesons are. Also made night vision goggles airtight too.
Consistency between item types.
:cl:
tweak: Graviton and Night Vision goggles now airtight
/:cl:
=> Graviton Goggles now Airtight

code/modules/shieldgen/shield_gen_external.dm
Adds sky to the list of blocked turf to hull shield gen so that if a shield passes through the midpoint layer it generates a hull shield. Mostly cosmetic as nothing actually causes danger to the midpoint.
Minor tweak so things look consistent
=> Sky Triggers Shield

code/game/machinery/doors/airlock.dm, code/game/machinery/doors/airlock_control.dm, code/game/machinery/doors/airlock_electronics.dm
Currently if you rebuild or build an airlock with a circuit that requires certain access and then finish the airlock the access requirements aren't added to the door. Copying (and modifying so that it compiles) airlock.dm, airlock_control.dm, and airlock_electronics.dm from Virgo seems to have fixed the issue.
Airlocks should have the accesses you give them during construction.
=> Fixes Airlock Electronic Access Settings not Applying

code/game/machinery/computer/supply.dm
Removed If/Else logic that caused the supply ordering terminal to allow approving, denying, and sending the shuttle instead of just being limited to the control terminal. Control terminal requires cargo access to open again.
Locking the control terminal via an if/else does very little good if you can just approve orders on the non control terminal anyway.
=> Prevents Cargo Ordering Terminal Shenanigans

code/game/machinery/_machinery.dm
Newly made machines respect the area power instead of just being made.
Newly made machines default to stat = 0 which means they have power which is fine in most cases but if made in an area with no power (no APC) or an area where the machine power is disabled on the APC, they pull power anyway. Now they detect power properly.
=> No More Magic Power

maps/tether/tether-06-station2.dmm, maps/tether/tether-07-station3.dmm
More of a warm fix by this point. Repairs oversights and mapping errors in the recent Psych Ward update:
-Links buttons to Riot Control/Yard Access to the appropriate blast doors.
-Adds a computer to Area that should stop players entering cryo from alerting Admins. (Unsure. Testing linkage.)
-Replaces all chloral hydrate bottles with more appropriate medications and sedatives.
-Adds in missing pipes and power lines.
-Rearranges external turfs to align correctly between z-levels.
=> Psych Ward Hotfix

code/modules/hydroponics/spreading/spreading.dm, code/modules/hydroponics/spreading/spreading_growth.dm, code/modules/hydroponics/spreading/spreading_response.dm
Space Vines were a pretty low threat event to take place on the station. Yeah, nah that isn't the case anymore. Vines will now do damage if you run across them, and will also lash out at players instead of grabbing and doing nothing. However, they will STILL grab and do extra damage on top. Damage types are ONLY Brute & Toxin for now to ensure crew doesn't just 100% die trying to contain angry plants.
Space Vines still won't go through airlocks (for now), and they can not travel up or down a z-level.
QOL change and gives more of a challenge for crew to deal with a major threat.
:cl:
balance: Space Vines are now dangerous, and an actual threat to the station.
/:cl:
=> Un-Hugboxes Space Vines. Makes them an actual Level 7 threat now!

maps/tether/tether-03-surface3.dmm, maps/tether/tether-06-station2.dmm, maps/tether/tether-07-station3.dmm
Station 2 airlock and holding chamber was exposed to space round start. This is the part that stick out from cargo on Station 3. Also fixed up vents in science to prevent a breach from being turbo gay.
QOL and map fixing
:cl:
add: Proper roof to airlock on station-2
fix: Vent & Scrubber set-up on Station-2 and Science Surface-3
/:cl:
=> Station-2 Airlock roof fix, and atmospheric vent fixing

code/game/objects/items/weapons/tanks/tanks.dm
for whatever reason equipped is not always called
"but kev why are you fixing the symptom and not the problem??"
because the bigger issue here is I don't see why tanks need to start processing when a mob PICKS I UP which can lead to edge cases if we ever have a case where tanks are modified in contents before a mob picks it up. see, premade ttvs, etc etc. 380 process() calls isn't worth this.
=> fixes tanks

code/modules/reagents/dispenser/_defines.dm, code/modules/reagents/dispenser/dispenser2_energy.dm
Doubles the storage of the reagent containers while we're in transition of updating the chem dispensers to run from a battery similar to TG.
QOL
:cl:
tweak: Buffed the container capacity of the reagent containers.
balance: reduced power cost to recharge
/:cl:
=> Buff Chem Machines before re-work

code/modules/hydroponics/grown.dm, code/modules/hydroponics/seed_datums.dm
How can you make the accursed pineapple pizza if pineapple slices are unobtainable?
PR fixes a typo in the Spineapple fruit preventing it from generating chems, as well as makes Spineapple sliceable into pineapple slices.
=> Fixes Spineapple and pineapple slices

code/modules/food/food/snacks/meat.dm, code/modules/mob/living/simple_mob/subtypes/animal/farm animals/chicken.dm
Chickens were using the wrong meat subtype.
=> Fixes chicken meat

code/game/machinery/recharger.dm
I thought it was incredibly unwieldy and an absolute pain to have to pull out the cell mag from your gun, then pull out the cells, then charge each one individually, then stick them back in the mag, then reload.
So I made it so you can just shove the whole magazine or the gun with the magazine into the charger to charge.
=> Cell loaded magazines and their respective gun can now be stuck in chargers.

code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Adds an industrial inducer to the electrical closet contents. Only three on station so it shouldn't be that huge of an issue and allows for quick recharging of cells in emergencies.
Makes it so they might actually see the light of day
:cl:
add: Added inducer to the secure electrical closet.
/:cl:
=> Adds Inducer to Electrical Closet

code/modules/mob/living/carbon/human/emote.dm
I got tired of people thinking I was sneezing or coughing on them when I wanted to use other shriek sounds. So I made emotes for them. shriekloud is the sneeze sound, shriekshort is the cough sound.
Also updated the list of emotes when using *help.
Updated list of emotes as well as not spreading germs when trying to be noisy.
:cl:
add: Added *shriekshort (vox cough sound) and *shriekloud (vox sneeze sound). Both are restricted to Vox.
add: Added emotes that have been added over time to the list of emotes displayed with *help
/:cl:
=> Vox Screams

code/modules/mob/dead/observer/observer.dm
this was needed because examine didn't work for ghosts now it does so uh let's not because this actually lets ghosts see each other on right click
=> removes ghost orbits removing mouse opacity

code/game/objects/structures/trash_pile.dm, code/modules/power/cell.dm, code/modules/power/cells/device_cells.dm, code/modules/power/cells/power_cells.dm, code/modules/research/designs.dm, code/modules/research/designs/power_cells.dm
Tin
So people don't think their cell is full when printing a new one.
:cl:
fix: Cells appear empty when fabricated with no energy
/:cl:
=> Make Cells Appear to be Empty on Fabrication

code/modules/events/solar_storm.dm
Fixes "refain" to "refrain" in the solar storm comms announcement thingy. Extensive, I know.
grammer
:cl:
spellcheck: fixed typo in solar storm announcement
:cl:
=> Fixes typo in solar storm announcement

code/modules/mob/transform_procs.dm
We had changed borg cells to start with 15,000 charge rating pre-hard sync. but it was reverted. This restores that.
Edit: It was actually 15,000.
Bit of QoL for borgs.
=> Restores 15,000 Rated Borg  Starting Cell

code/modules/atmospherics/components/unary/vent_scrubber.dm
Makes it so setting scrubbers to filter NO2 actually filters NO2 and doesn't set it to scrub fuel.
We want to be able to scrub NO2.
=> Setting to Scrub NO2 Should Scrub NO2, not Fuel

_maps/map_files/Tether/tether-07-station3.dmm
In light of being unable to get a floor diffusor so that the cargo shuttle is blocked, I've added a handheld one. Especially now that they can be recharged as well.
Prevents cargo from being blocked from their own shuttle.
:cl:
add: Handheld diffusor added to a table on cargo
/:cl:
=> Adds Portable Shield Diffusor to Cargo

_maps/map_files/Tether/tether-01-surface1.dmm
Adds a mining weapons locker for station locked Phaser weapons. This will work the same as exploration weapons.
QOL and needed mining buff
:cl:
add: Weapons Cab for Mining
/:cl:
=> Mining Love, otherwise known as "Hey you get guns now"

code/modules/shieldgen/shield_capacitor.dm, code/modules/shieldgen/shield_gen.dm
I noticed there was code and interaction for using an ID on the shield generator and its capacitors but it would always give the lacking access response. I fixed it.
Re-enables a broken feature.
:cl:
fix: Shield generators and capacitors can be locked
/:cl:
=> Fixes Shield Gen/Shield Capacitor ID Locking

code/modules/admin/chat_commands.dm
why did i make it endnotify instead of notify this is just annoying to have to memorize both
=> changes endnotify to notify for consistency with main

_maps/map_files/Tether/tether-05-station1.dmm
This is an update to the SNR gear to compensate regarding the access adjustment to ensure they can still provide assistance to their away teams & on-site when no parameds are around.
Quality of Life and quick fix for access and & gear. Cleaned up the Triage center in the exploration bay.
:cl:
tweak: tweaked SNR lockers to ensure access is not messed up. (for reals this time oh god)
balance: Added needed chemistry gear for SNR due to chem access being revoked 
/:cl:
=> Search & Rescue Access Fix Pt 2 & Gear

code/modules/mob/living/carbon/human/human_movement.dm
@kevinz000 decided to be a powergaming catgirl again and merge OP things
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/1929
This PR made hyperzine last for a meme amount of time.
It's too good right now.
So this PR removes Hyperzine's speed buff, and instead makes it remove any pain slowdown and item related slowdown without increasing your speed.
PS. Y'know I just realised this removes the speed up from changeling epiniphrene, nuka cola and the electric spider toxin since those relied on the chem speedboost.
I'm gonna call that intended since [meme speed] infuriates me in regards to balancing anything.
=> Hyperzine nerf/buff

_maps/map_files/Tether/tether-01-surface1.dmm
Runtime happened because there was no more stacker for the console to connect to. This removes the stacker console on the map. I also changed the tech floor the stacker originally was on to plating to match the rest of the conveyor path.
=> Fixes Stacker Console Runtime

code/modules/clothing/spacesuits/rig/rig_wiring.dm
If RIGs get emp_acted on or if the control wire is pulsed they gain some 'malfunctioning' and malfunction_delay numbers which are just two timers that count down before you can do anything with the suit again. The problem is these numbers only count down if the rig is initialized and equipped as that's the only time where the rig is seeming to be processed.
This means if someone pulses the control wire or if the rig happens to get emped when not equipped, it becomes a paperweight. There's already a more or less unused wire (well, that is if you want to add malfunction OR zap yourself) I hooked into to be used as a method of resetting both these vars. The max emp_act seems to add 30 of each as well as drain charge, meaning the rig is normally out of commission for a minute at most, unless …
=> Adds way of Unbricking RIGs

code/modules/holodeck/HolodeckObjects.dm
The Esword sprite got shuffled about some time during hard sync and this restores it to the right visibility. However another problem is introduced wherein the color overlay for the onmob sprite doesn't work, but that's already an issue with the normal eswords. Maybe I'll figure that out some day.
Fixes missing sprite
=> 'Fixes' Thunderdome Esword Sprite

code/modules/power/tesla/energy_ball.dm
Tesla Reactor now doesn't drain in 30 seconds when released, and also you MUST keep the Particle Accelerator running at all times to keep the reactor fueled. This will ALSO allow for engineers to easily turn off and upgrade the reactor with more parts later in the shift. 
QOL
:cl:
tweak: Tesla Reactor now can lose power when contained similar to TG, tesloose is now more deadly
/:cl:
=> Un-hugboxes Tesla Reactor

code/game/gamemodes/meteor/meteors.dm, code/modules/events/electrical_storm.dm, code/modules/events/event_container_vr.dm, code/modules/events/meteors.dm
This PR focuses on adjusting the weights of the Electrical storm, and Meteor Wave events. The Electrical storm is now a shorter running event, and has less chance to proc. The Meteor wave weight is reduced, and the damage the meteors can do is severely reduced to not cause a station-ending event on the round, but will give Engineering more work to do later in the round.
QOL and balance fixing.
:cl:
tweak: Reduced weight and duration of Electrical Storm events
tweak: Reduced danger of Meteor Wave events
balance: Damage and weight adjustments of the above events.
/:cl:
=> Event Weight Lowering Adjustments & Patching

_maps/map_files/Tether/tether-01-surface1.dmm, _maps/map_files/Tether/tether-02-surface2.dmm, _maps/map_files/Tether/tether-05-station1.dmm
1. _Fixes Exploration blood bag locker._
**Why:** SAR can't unlock their locker full of blood. Vampires most affected.
2. _SAR now receive Exploration weapon permits in their locker._
**Why:** It's odd that they didn't have them before. Fixed.
3. _Removed Clotting Kit from Paramedic Staging Area._
**Why:** Apparently clotting kits aren't just used to treat brute damage. Hopefully this will stop all of the break-ins. Replaces the kit with two cryobags, which are more in line with the kind of triage gear I want Paramedics to utilize in recovery attempts.
=> The "Pardon Our Dust" Update

code/modules/turbolift/turbolift.dm
zzz race conditions make my blood boil and this didn't make sense anyways
:cl: silicons
balance: turbolifts no longer gib people while moving up
/:cl:
=> prevents turbolifts from gibbing people while moving up. makes turbolift gib actions async.

_maps/map_files/Tether/tether-01-surface1.dmm, _maps/map_files/Tether/tether-06-station2.dmm, maps/tether/submaps/tether_underdark.dmm
1. _Adds Department Vendors for Exploration and Mining to the Underdark._
**Why:** Simple quality of life addition. Adds an Exploration and Mining vendor to the UD so that crew with points on their cards can replenish supplies/purchase better gear without having to walk two z-levels back without reason.
2. _Adds ceiling tiles to all external charging bays/air ports._
**Why:** I realized recently that snow covers these areas. I've added ceilings in to prevent snow from covering the ports/pads. Purely aesthetic.
3. _Removes a light fixture in Station Paramedic Staging._
**Why:** This was left over from when the area was remapped, apparently. Only just now located. This deletes the errant fixture and adjusts the lighting to maintain an even coverage.
4. _Repositions Mining Processing …
=> General Map Fixes/QOL

code/game/gamemodes/meteor/meteors.dm, code/modules/events/meteors.dm
God I don't know why I hate myself this much BUUUTTT. Buffs the meteor wave threat to throw more rocks and a SMALL chance of throwing a mega death rock. The damage numbers for the meteors have NOT been adjusted, including the Tunguska (which is VERY likely going to get SOMETHING adjusted or re-disabled if its unfun)
Because people love chaos a lot more than you'd think on this server. 
:cl:
tweak: Re-enabled the meteor type Tunguska (Will spawn NO more than one)
balance: Adjusted spawn chance and count of current meteors
/:cl:
=> Meteor Wave Buffs. Also Re-enables TUNGUSKA OH GOD

_maps/map_files/Tether/tether-07-station3.dmm, maps/tether/submaps/tether_misc.dmm, maps/tether/tether_areas2.dm, maps/tether/tether_things.dm
_When we here at CMF took this contract, our team of skilled Engineers and Technicians worried that we might have bitten off more than we could chew. A surgical room? Well, that's easy! We can build those in our sleep! A surgical room for a specific species? Just as easy! A fully equipped surgical theater capable of rapidly catering to a virtually endless list of species? Well, we'd have to get pretty creative to pull off something like that!
Fortunately for NanoTrasen and its diverse assortment of crew, the team here at Cyan Modular Fabrications is proud to announce the unveiling of our latest Modular design: The **CMF Exotic Surgery Suite**! Decked out in the latest hard light and nanotechnology, our proprietary system allows for the rapid cycling of fully equipped surgical theaters …
=> CMF: Exotic Surgery Suite

_maps/map_files/Tether/tether-01-surface1.dmm, _maps/map_files/Tether/tether-02-surface2.dmm, _maps/map_files/Tether/tether-03-surface3.dmm, _maps/map_files/Tether/tether-05-station1.dmm, _maps/map_files/Tether/tether-07-station3.dmm, code/modules/clothing/spacesuits/rig/rig.dm, maps/tether/submaps/tether_misc.dmm
1. _Removes Paramedic machetes._
**Why:** Initially, Paramedics were granted machetes in the interests of mitigating risk during hazardous retrieval operations. Extended study has implied that more often than not, these machetes are not needed. Paramedics will retain their survival knives, but barring major incident, will not be granted machetes on the Tether.
2. _Adds Department Mail rooms to: Paramedic Bay, Atmospherics, Mining, Science, Engineering, Security, and Medbay._
**Why:** Attempted to mail crates back to Cargo earlier and was unable. Discovered the mail system on the Tether has been severely handicapped, either unintentionally or for some arcane reason. This adds a mail room to each major department.
3. _Adds fancy SOP and CorpReg bookcases to relevant areas (IA, Sec break …
=> Tether Map Tweaks 08-23

code/modules/mob/living/simple_mob/subtypes/animal/space/mouse_army.dm, code/modules/projectiles/guns/projectile.dm, code/modules/projectiles/guns/projectile/pistol.dm, code/modules/projectiles/guns/projectile/shotgun.dm, code/modules/reagents/Chemistry-Recipes.dm
1. _Removes Recoil from Ballistics. (Boy, these **shake** weapons sure aren't **shudder** viable for some reason **spin**.)_
**Why:** Making an entire class of weapons irredeemably terrible for some reason is simply not fun. Now recoil exists as a variable the way it should: Sawn off shotguns, zip guns, and heavy caliber weaponry have boosted recoil stats due to poor ergonomics.
2. _Fixes the Outlaw drink._
**Why:** Tequila isn't a recognized reagent. Replaces tequila with vodka.
3. _Hopefully fixes the Pyro Mouse death proc._
**Why:** The Pyro mouse is meant to vent plasma and sparks, like its fuel tank has ruptured. Hopefully this code will finally allow that to happen. I really hope it will. I love the Mouse Army, but boy do I want a break from this .dm already.
=> General Tweaks: Recoil Edition

code/modules/mob/living/carbon/human/species/station/traits_vr/positive.dm
Adds a sizeshift trait that costs 4 points, but allows the player to shift between 25%/200% sizes at a whim. 
Not having to rely on NIFsofts/science/maint runs for sizeguns is nice. At a 4 point cost, this shouldn't fuck with balance.
:cl:
add: Added Sizeshift trait for custom species.
/:cl:
=> Adds "Sizeshift" trait for custom-species.

code/modules/mob/living/simple_mob/subtypes/animal/space/carp.dm, code/modules/mob/living/simple_mob/subtypes/vore/zz_vore_overrides.dm
This would fix the missing icon states for the holographic carp as per spawned by the holodeck as well as the large and huge carp from turning invisible once they eat some unfortunate victim as the vore64x64.dmi sprite set is no longer in use.
=> Fixes broken icon states for carp

maps/nsv_triumph/triumph_things.dm, maps/tether/tether_things.dm
Quality of life because people are accidentally tramming out
:cl:
tweak: tram station now requires drag-drop to leave instead of bump. behavior for other people shoving you in is unchanged.
/:cl:
=> you now have to dragdrop yourself into tram doors to leave instead of bumping into it and literally falling out of the world

code/modules/admin/admin.dm
:cl:
admin: toggle-respawn renamed to toggle-return-to-menu
/:cl:
=> >rename respawn to return-to-menu >leave the toggle verb alone so anyone with 6 years of muscle memory presses it by accident twice a day

code/game/jobs/job/captain.dm
Adds helmsman alt title to command secretary and also bumps total positions to 3 so one of each can be had.
People seem to like driving the ship but not wanting to do anything else.
:cl:
add: Adds the helmsman alt title
tweak: Tweaks the amount of command secs that can be had
delete: Deletes herobrine
/:cl:
=> Adds Deanman's helmswoman thingie idk

code/modules/food/food/snacks.dm
What it says on the tin. Resolves the override failing to include the base type's attackby behavior when not being attacked by the specified object. "Properly" for the dough, and quick and dirty for the bun. Both should be fine, tho.
Makes the foodbag more useful
:cl:
fix: Makes buns and dough enter foodbags normally
/:cl:
=> Fixes dough and bun foodbag behavior, resolves issue #2277

code/modules/mob/language/station_vr.dm
Fixes Sagaru by porting the T language key from Virgo. I tried a few times to do a bigger refactor of saycode to bring it up to date but holy shit I'm not ready lmao.
I didn't merge the VR files because it might make it more painful to refactor/update saycode later. I don't have enough understanding of the system and all files involved yet to overhaul properly
`say ",T Gold Ring for life."`
If only there was a PR mirror bot :( could've just dismissed the unwanted PRs
:cl:
fix: You can now speak Sagaru with ,T. Why there wasn't a language key at all before is a mystery.
/:cl:
=> Cures the Silence of Sergals

code/game/objects/structures/dancepole.dm, code/modules/materials/material_recipes.dm, maps/nsv_triumph/triumph_things.dm, maps/tether/tether_things.dm, vorestation.dme
Implements deconstructing and constructing dance poles, also adds a get_description_interaction() based instructions blurb after the desc.
Not being able to destroy and build /obj/structures with steel is just wrong and unamerican.
:cl:
add: Steel sheet recipe to make dance poles (1 sheet)
add: Added construction/deconstruction functionality to dance poles
tweak: Fancy bluetext instructions for moving/removing dance poles
/:cl:
=> Dance pole improvements, resolves #2368

code/game/objects/buckling.dm
Beds, chairs, etc. did not check if the mob was already buckled to any other chairs before forcemoving the mob onto the destination tile, letting mobs be moved between chairs without unbuckling them from the first. This is a simple three line change to implement the overlooked check.
Bugfix.
:cl:
fix: can no longer slide between beds/chairs with clickdrag while buckled
/:cl:
=> Unfucks buckling, adds check if a mob is already buckled to a different before forcemoving

code/game/mecha/equipment/tools/medical_tools_vr.dm
All this does is ensures that the BL-3 P is no longer invisible as there was no sprite properly tied to the item at the time. Not much else to really say about it. 
Most I really did is take a working item layout and did this. Fully aware of the upcoming changes so I will touch up on this when that happens. 
closes #2380
closes #2153
:cl:
fix: BL3 Phoenix sprite now visible.
/:cl:
=> BL3 P Sprite fix

code/modules/projectiles/guns/energy/special.dm
Makes it so that Xenobotanists  can use it for Xenobotany without having to go to Sec or asking their RD for a pin.
Adds one line of code to ensure that the floral somatoray is usable on station for Xenobotany.
Allows Xenobotanists to actually use their equipment rather than having to take over the firing range for their projects. 
:cl:
adds: Removes the floral somatoray's pin requirement to be usable on station. 
/:cl:
=> Removes floral somatoray pin requirement

code/modules/projectiles/guns/energy/phase.dm, code/modules/projectiles/guns/energy/temperature.dm
This PR does the following:
Removes the pin requirement from phase weapons. Allowing crew and Science to still have phase weapons available if there are situations that Security are absent.
As well removes the requirement for pins on temperature guns as they're generally used to kill slimes. 
This PR is a follow up to the in
Enables crew to defend themselves with more than just improvised weapons, screwdrivers and what ever other oddities they may find, in the case of a random event occurring that causes hostile mobs to spawn and there are no Security on to handle the situation. As Phase weapons do barely any damage to carbon mobs.
:cl:
tweak: Removes pin requirement from Phase weapons.
tweak: Removes pin requirement from Temperature guns.
/:cl:
=> Removes firing pin requirement from: Temperature gun and Phase weapons. 

code/modules/client/preference_setup/loadout/loadout_eyes.dm
Something something ampersands were a mistake
fix: Optical Meson Scanner aviators can now be chosen again in the loadout
/:cl:
Closes #2396
=> Fixes Optical Meson Aviators in the Loadout

code/game/objects/items/weapons/autopsy.dm, code/modules/surgery/external_repair.dm
Vorecode in its infinite wisdom had the autopsy scanner used for external repair surgery. Moreover, it broke using the autopsy scanner on help intent. The autopsy scanner is now strictly an autopsy tool, as intended by God.
For external repair surgery, the health scanner is now the ideal tool to use, but hey if a doctor wants to use an atmospheric analyser to inspect a wound I guess they can still try that too idk
Standard fucking behavior, jesus christ vorecode pls
:cl:
fix: autopsy scanner now works on help intent
tweak: autopsy scanner no longer used for external repair surgery
tweak: health analyzer now the right tool for external repair surgery
/:cl:
=> Unfucks autopsy scanners, external surgery tweak

code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm, code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm, code/modules/reagents/reagent_containers/borghydro.dm
Because having dogborgs be better than regular borgs is a bad meme. Also removes a redundancy in that the /crisis hypo variant is not needed with the /lost variant
tweak: Gives borg hypos the same chems as the sleepers.
/:cl:
=> Gives borg and dogborg hypos the same chems as dogborg sleepers

code/modules/client/preference_setup/general/03_body.dm, code/modules/client/preference_setup/global/01_ui.dm, code/modules/client/preference_setup/preference_setup.dm, code/modules/mob/new_player/preferences_setup.dm
Ports https://github.com/PolarisSS13/Polaris/pull/7215 from Polaris.
Refactors preference colour previews to use colour square from Paradise.
Adds buttons to navigate forward or backward in the list of hair & facial hair styles
Adds a button to put a marking in a specific order.
Ports https://github.com/PolarisSS13/Polaris/pull/7215 from Polaris.
Refactors preference colour previews to use colour square from Paradise.
Adds buttons to navigate forward or backward in the list of hair & facial hair styles
Adds a button to put a marking in a specific order.
Significantly improves the experience of customizing a character's hair, facial hair and markings while cleaning up code.
:cl:
add: Added buttons to go forward or backward hair & facial hair styles.
add: Added a button to move a marking to …
=> Refactors Preference Colour Previews, Improves Marking & Hair Customization

code/controllers/subsystems/jobs.dm, code/modules/mob/new_player/preferences_setup.dm
Ported from https://github.com/Aurorastation/Aurora.3/pull/10205, credit to fernerr
Now you can see all the accessories (within standard equipping logic) you've selected in the character preview.
Additionally, these accessories will now all be equipped when you spawn instead of filling your backpack unless it's actually necessary.
Fixes a long-standing issue where only one accessory is shown in character preview or equipped at spawn.
:cl:
fix: Character preview will now show all loadout accessories (within usual logic) in the order you selected them.
fix: All loadout accessories will be equipped to your character when you spawn (within usual logic) in the order you selected them.
/:cl:
_Example from Virgo character preview.
Order of Accessories: Brown webbing vest, drop straps, metal …
=> Fixes Only One Accessory Equipped at Spawn & in Character Preview

code/modules/client/preference_setup/loadout/loadout_donator.dm, code/modules/client/preference_setup/loadout/loadout_event_rewards.dm, vorestation.dme
See title.
**Donator Items:** If someone went out of their way to PAY for a custom item, given our no-gameplay-advantage-granting-items rule, it's only right that they aren't penalized and need to re-adjust their loadout to compensate for their new item's cost.
**Event Rewards:** Grants a reward for participating in events that people can show off. This encourages people to participate in events to have a chance at earning one (when applicable), grants something permanent to veterans of the community who remain around long enough to have earned something shiny to show off, and adds extra flavor to the game.
:cl:
add: Added an "Event Rewards" category to the loadout. 
tweak: Donator Items now cost 0 loadout points.
/:cl:
=> Adds an "Event Rewards" section to the loadout. Changes Donator Items to cost 0 loadout points.

code/modules/mob/living/carbon/human/species/station/station.dm
For some reason, Xenohybrids - literal Xenomorphs with either a genetic or technological separation from the hivemind - don't have basic Xeno traits. I've given them _some_.
1. _Adjusts Xenohybrid racial traits: Xenohybrids are now fully spaceproof, but still require Oxygen. They now take double fire damage, and half brute damage._
**Why:** Hybrids have been brought more in line with standard Xenomorph biology with this update, with small adjustments for balance.
=> Xenohybrid Racial Adjustments

code/controllers/subsystems/supply.dm
_Corporate recently looked over last quarter's expenses, and noticed a distressing amount of waste in Central Command's logistical budget. On an entirely unrelated note, corporate has announced their brand new Recycling Incentivization Program! Every crew in the local sector will soon receive a Supply credit per individual item that meets the "trash" classification. If you are interested in participating in the NanoTrasen R.I.P. initiative, get in touch with your local Service or Cargo department today!_
1. _Gives all /trash/ family items an Export value of (0.1) via Cargo._
**Why:** Exporting trash is mostly a thematic touch, as well as an excuse to get the Janitors to want to actually collect garbage from bins. The current exchange rate is 0.1 per item. In initial tests it was 0.01, but …
=> NanoTrasen Recycling Incentivization Program

code/modules/power/fission/computer.dm, code/modules/power/fission/engine.dm, code/modules/power/fission/modular_computer.dm, nano/templates/fission_monitor_prog.tmpl, vorestation.dme
Simple PR to add a modular computer program to check on the fission engine.
Varies from the standard fission monitor computer in two key ways:
• Does not require a multitool to link it.
• Operates in a read only mode.
This is to ensure that sabotaging the fission engine requires more effort than "Buy or own any modular computer/tablet."
(Achieving modular computer compatibility required a fair bit of a change on the engine's back end, however.)
This allows engineers to check on the engine temperature and reaction rate while busy with other tasks.
:cl:
add: Added modular fission monitor program.
/:cl:
=> Adds fission monitoring program to modular computers.

code/game/objects/items/weapons/traps.dm
adds an activate() proc to beartraps so you don't have to manually set them with a mob
adds an adminspawn only "disruptor trap" that EMPs whoever it latches onto
buffs hunting trap to 45 force instead of 30 because it's science shit and it requires quirky materials
beartraps are criminally underutilized
:cl:
tweak: Bear traps now have an activation proc, instead of relying on manual placement.
/:cl:
=> beartraps upgraded

code/modules/reagents/Chemistry-Machinery.dm
This is a sanity check that runs is_open_container() before allowing the beaker to be inserted. With this addition, you will no longer be able to insert a closed beaker into any chem dispensers, and potentially lose contents.
=> Closes #2463

code/datums/outfits/jobs/command.dm
Switches the hand the clipboard spawns in so that it does not overwrite the tank Vox require to survive.
=> Closes #2413

code/modules/nifsoft/nif.dm
Adds soulcatchers to all NIFs by default. This means that, whenever a fresh NIF is installed in someone, they will get a soulcatcher automatically, much like commlinks.
People barely use soulcatchers and this'll hopefully encourage their usage a bit more.
:cl:
add: Adds soulcatchers to NIFs by default.
/:cl:
=> Adds soulcatchers to NIFs by default

_maps/map_files/triumph/triumph-04-deck4.dmm
This PR affects the Civilian Shuttle, and makes it more player-friendly.
1. _Fixes the Civilian Arm Airlock issue._
**Why:** The actual airlock that's supposed to allow for entry into the shuttle has been busted for a while. Fixed.
2. _Moves the telecomms relay to the exterior of the ship._
**Why:** Wouldn't fit anywhere else. It blocked access to the engine console.
3. _Removes the ID lock on the Jump Console._
**Why:** This was meant to be twinned with a prior ID lock reversal on the helm console itself. Now anyone can pilot the shuttle. Mind your SOP, gents.
=> Fixes the Civilian Shuttle

code/modules/mob/living/silicon/robot/robot_modules/station/drone.dm
Humans use soap, not silicons.
Silicons are able to use mops, however.
Therefore, the soap that is given to drones (and only drones, no doubt an ancient unfixed strand of spaghetti) must be replaced by a mop to restore their ability to clean floors.
They must wet the mop in a sink, as any other synthetic or humanoid, then use it as normal.
=> Closes #2342

code/modules/mob/living/carbon/brain/brain.dm
Yes it removes the entire block. It made **zero sense.** If you wanted to prevent brains from hearing outside of MMIs it should just apply in general, not to only silicons. I'm not sure what this is for but I'm 99% sure it isn't needed so correct me if I'm wrong. Silicons aren't exactly a special scrambled voice that you can't understand unless you're human.
:cl:
fix: brainmobs can understand AIs without a snowflake MMI check.
/:cl:
=> Fixes soulcatcher mobs not being able to understand AIs 

code/controllers/subsystems/input.dm
this isn't a fix as much of a bandaid but it works and i can't really be assed to rewrite input again atm
=> fixes clientside keybinds minus T/O/M because those are the usual hardbinds for communication macros

code/game/objects/items/weapons/id cards/sprite_stacks_cit.dm
Un-triggers pathfinder players.
Returns the pathfinder's ID to what it was before whatever update broke it.
Pretty ID.
:cl:
fix: The path for the pathfinder sprite stacks is fixed to allow the icon to actually show up.
/:cl:
=> Pathfinders need normal-looking IDs.

code/__DEFINES/mobs.dm, code/game/mecha/equipment/tools/tools.dm, code/game/objects/items/weapons/storage/bags.dm, code/modules/mining/drilling/scanner.dm, code/modules/mining/mine_items.dm, code/modules/mining/mine_turfs.dm, code/modules/mining/satchel_ore_boxdm.dm
removes feedback messages from ore satchels and ore boxes, along with mining and digging, except you'll still get notified if you hit a rock with an anomaly in it (which you should still take as a cue to maybe not hit the rock with the anomaly in it)
also lets the digspeed of mining tools affect digging because nobody likes standing still for 10 seconds to get 3 sand
also increases sand yield per tile to 5 sand per, because i like having glass
buffs exosuit drills (30 to 13 for standard, 10 to 3 for diamond)
man i sure love half of my chatlog being pushed out of the way by "You empty the satchel into the box" or "You start drilling"
:cl:
tweak: A fair bit of feedback messages from your ore satchel or hitting rocks has been removed. Except the bit that pops up when you hit an …
=> the "Use Your Eyes" update for mining: sand digging speed and yields, feedback messages mostly removed, ripley drill faster

code/game/objects/items/weapons/nullrod.dm, code/modules/mob/living/simple_mob/subtypes/humanoid/cultist.dm
Finally remembered to update the Null Rod's SA Vulnerability flags. It'll now do bonus damage to Cult mobs and Aberrations.
1. _Adds the SA flags to the Null Rod._
**Why:** The anti-magic/anti-cult weapon should probably have the appropriate buff.
2. _Makes Cult mobs count under the appropriate Mob Class._
**Why:** The SA isn't triggering on mobs that are meant to be vulnerable.
=> Null Rod Tweaks/Buff

code/modules/mob/living/carbon/human/human_movement.dm
disregard the commit name i tested it
item slowdowns only get affected by item slowdown modifiers if they're greater than 0, otherwise just applies them (negative slowdown items make you run fast as fuck btw)
basically a remake of pr #1560
being slow is unbased but being unable to benefit from negative slowdown items is also unbased
:cl:
balance: Items with negative slowdown now work nicely for people of any hardiness. This is a re-implementation of something lost in the hardsync.
/:cl:
=> something about slowdowns and item_slowdown_modifiers

code/game/machinery/biogenerator.dm, code/modules/clothing/chameleon.dm, code/modules/reagents/reagent_containers/borghydro.dm
for @drofoljaelisglis who bullied me into this
_I said I wasn't interested in rewriting the chameleon code but..._
If the item has no icon, or it cannot be resolved, it will not be shown to the user. This obliterates obsolete/junk items from being an issue for any chameleon items.
Anyway, @silicons  is an amazing human being that did 90% of the work. I only made sure that missing item properties were copied over from the original item > 'fake' chameleon item, which without this was resulting in some _working_ icons showing a 'missing icon' error where there actually did exist icons for the item.
:cl: realbuffalowing
fix: fixes chameleon items
fix: fixes service borg bags
fix: fixes service borg booze dispenser
/:cl:
=> Multiple issue fixes

code/game/jobs/job/assistant.dm, code/game/jobs/job/civilian.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/exploration.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm
Interns are no longer a class of Assistant. Instead, Intern titles are now sub-titles of the related base department job. You can still RP being an Intern/Trainee, but now you don't have to deal with guest passes and janky shit.
1. _Removes the Intern subset of Assistant, and redistributes its titles._
**Why:** QOL for "Intern" RPers.
=> Intern Reassignment Initiative

code/game/objects/items/weapons/barrier_tape.dm
yeeclaw
ghosts will no longer be spammed about crossing engineering tape, since they are not a type of mob/living
:cl:
fix: fixes engineering tape
/:cl:
=> fixes engineering tape

code/modules/mob/living/carbon/human/species/station/teshari.dm
i missed item slowdown mod in the original pr and now they move like a snail in a hardsuit which is too hard of a nerf
plus 1.1x mod with 75 health is already really weak, we can tune it back again if it turns out this is bad
:cl:
balance: teshari have been given a bit less damage vulnerability and item slowdown mod.
/:cl:
=> buffs teshari brute/burn damage resistaances to 10% vuln instead of 35%, and item slowdown mod to 1.25 from 2

code/modules/mob/_modifiers/modifiers_misc.dm
apparently some simplemobs have this and just decimate people
:cl:
balance: berserk modifier used by saviks reduces slowdown by 0.75 instead of 1
/:cl:
=> nerfs berserk from -1 slowdown to -0.75 giving avg 8 tiles runspeed instead of 10

code/modules/clothing/suits/hooded.dm
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA …
=> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
qol
why is mobvore defaulting to on again
=> fixes protean vore settings because if i get hardstunned by a carp again i'm going to go ape and punch a hole through the code 

code/game/objects/items/toys.dm, code/game/objects/structures/curtains.dm, code/modules/mob/living/carbon/human/emote.dm
:cl:
fix: fixes curtains so they dont vanish underneath the window
fix: fixes plushie code typo
/:cl:
=> fixes curtains, typo in toy code

code/modules/mob/living/say.dm
See title.
Ported from polaris again, makes speech bubbles appear above containers if you're inside of one.
=> Speech bubbles appear above objects you're inside of.

code/modules/reagents/reagent_containers/patch.dm
Chemical Patches made at the ChemMaster3000 are currently pretty useless, given there are only a few chemicals that function on touch, most are harmfull. So I went and basicly copied some elements from bruise packs to allow the patches to seal wounds as the name and icon suggests.
In addition to that I added a check to avoid applying patches onto open surgery sites, as is present in bruise pack code.
During testing I discovered a bug that would trigger the check for Robolimbs while on harm intent, even though there was clearly no robotic limb targeted or affected. Not sure where that comes from, my fix would be to have a harm-intend check before hand and kill the function before giving the wrong information to the user.
The Original bruis Pack code I copied was supplied by Kevinz000, just …
=> Make chemical patches more usefull

code/__DEFINES/species_languages.dm, code/game/objects/items/devices/defib.dm, code/modules/mob/living/carbon/human/species/outsider/skeleton.dm, code/modules/mob/living/carbon/human/species/station/station_special.dm, code/modules/organs/organ.dm
This PR removes the slightly unfun defib timer, and instead replaces it with brain damage (i.e. mandatory surgery) that increases the longer the subject was dead.
Also adds a species flag, NO_DEFIB, since using NO_SCAN to check if someone could be defibbed is stupid.
So now your Vox/Alraune/Shadekin/etc. can all be defibbed, but not resleeved. Except Xenochi, since they have a unique revive mechanic.
=> Removes defib timer. Replaces with brain damage over time. Alien species can now be defibbed.

_maps/map_files/triumph/triumph-01-deck1.dmm, _maps/map_files/triumph/triumph-02-deck2.dmm, code/game/objects/items/weapons/grenades/chem_grenade.dm
Just some small tweaks and fixes.
1. _Repairs missing air pipe segment on Level 1._
**Why:** Due to this missing pipe, areas of Level 1, like Telecomms, cannot currently be refilled with air automatically.
2. _Removes the Mining shuttle Relays._
**Why:** Apparently these just don't work. I would remove the Civilian Shuttle's too, but I know that file's about to be edited.
3. _Fixes Holy grenades._
**Why:** Foaming/cleaning agent wasn't working like it's supposed to. This should fix it.
4. _Adds a valve to the Engine loop so people don't accidentally vent the entire gas line into space._
**Why:** I did this last night, and it almost made the engine completely useless. So let's just add in a bit of user interaction to confirm before we let the entire loop fly out into space.
=> Map Tweaks: Engineering Atmos and Mining Shuttle Relays

_maps/map_files/triumph/triumph-04-deck4.dmm
1. _Unlocks Exploration shuttle Jump Console._
**Why:** I hate that I'm still having to find and fix this stuff. Yeah I get that Pilots and the Pathfinder should be the ones with primary access to the shuttle controls, but news flash: Sometimes they aren't available, or they're _dead or incapacitated_. We're all adults here. If someone takes the shuttle that isn't supposed to, we can punish them. Not everyone preemptively.
=> Unlocks Exploration Jump Console

code/game/machinery/rechargestation.dm
makes charger code less goddamn awful by a tiny bit
chargers now only drain the power needed to recharge missing rather than full at all times
as funny as this is i don't need to keep having to ask people to stop afking in the chargers every round so the engines don't die mid-flight
:cl:
add: now introducing nanotrasen SMART CHARGE - no longer will expedition ships be shut down by 50 powergamers rolling protean and erping in the rechargers.
tweak: cyborg chargers now waste less power while idle
/:cl:
=> local expedition team found crashing through meteors at 60 Gm/h after proteans fall asleep in cyborg recharger, more at 10

code/modules/ventcrawl/ventcrawl_atmospherics.dm
Prevents Diagonal movement while ventcrawling, because it caused ejection from the pipes, and you cant move diagonal in pipes, thats sort of the point of pipes.
Issue related to this:
resolves https://github.com/Citadel-Station-13/Citadel-Station-13-RP/issues/2112
It fixes a bug and makes sense.
:cl:
fix: Fixes ventcrawl-ejection on dieagonal movement
/:cl:
=> Prevents any Diagonal Movement while ventcrawling

code/modules/clothing/spacesuits/rig/suits/alien.dm
no more internal unremovable cells that selfcharge
no more snowflake emp protection
no more ai override because IT DOESNT EVEN WORK
their gloves are insulated but the rest of them only halves conductivity
radiation is now 90% instead of 100%
if you want an unremovable cell that links to their nutrition, do it right instead of something that makes the powersink useless
also unironically powercreeped to shit while not even working right
:cl:
balance: protean rigs are slightly less godawful
/:cl:
=> removes some of the goddawful shitcode from protean rigs, removes their complete radiation and taser immunity

code/game/machinery/doors/airlock.dm
We had this bug for over a year and deleting this line was all it took to fix.
Left over oversight from an old PR ages back that optimised airlocks by not generating access lists unless needed, which was runtiming airlock construction.
=> Fixes airlocks not having wires after being constructed

code/modules/client/preference_setup/loadout/loadout_xeno.dm
This PR simply fixes the CMO being listed twice and the quartermaster not at all.
Every other role has a Teshari cloak, but the Quartermaster's was not working. 
:cl:
add: Teshari Quartermaster cloak is set properly in xeno loadout file. 
/:cl:
=> Fixes / Adds Teshari Quartermaster Cloak Loadout

code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
As protean blobs are rad immune and their humanoid forms aren't, I though it made little sense for a species with 2 forms to have differing resistances, so here I am, making them more similar.
The entire PR is me editing two lines of code, with the express purpose to make proteans more OP.
Also, a personal gripe, there're too many protean apps right now and I will spare a lot of effort due to my laziness to reduce the amount and freely given acceptance of them.
-Ashet
<3
=> Protean rad immunity, because it makes sense

code/game/objects/items/weapons/nullrod.dm, code/modules/projectiles/guns/energy.dm, code/modules/projectiles/guns/energy/special.dm, code/modules/projectiles/projectile/bullets.dm
Recent playtesting has revealed that anti-Cult weapons and ammunition aren't doing sufficient damage to cult mobs. This rolls out some buffs and tweaks to special weapons which may become relevant in events relatively soon.
=> Buffs/Adjustments to Anti-Cult Weaponry

code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/living.dm
So after a while of trying to understand why and how things do. I've opted to just compare the port of Polaris' indicators to that of Chomps, and added in the differences. This in high hopes, fixes the floating sleep icon after surgery. If not, I uh - I'll keep looking into it.
Fixes the stuck status of Sleeping when coming out of surgery.[Hopefully]
:cl:
fix: Fixes the 'stuck' Sleeping indicator after surgery.
/:cl:
So while doing this I have discovered, and more harrowing - there is no way to toggle off the indicators. I however am just a simple caveman who doesn't understand how Byond is coded and how it works in general. I would encourage someone with better knowledge and skill to look into this. If not well, get cozy with the icons. ^^'
Sadly no pictures, as it's a fix.
=> Fix: Sleep Indicator being stuck after Surgery

code/game/gamemodes/events/power_failure.dm, code/modules/power/smes.dm
now it stores if it used powerout holders and is only restored to the values if it's, y'know, actually SET.
=> i'm not sure why the "power all apcs" button also drains the SMES but i'm annoyed enough to fix it

code/modules/projectiles/guns/magnetic/bore.dm, code/modules/reagents/reagent_containers/patch.dm, html/changelog.html
The standard Phoron bore starts with a capacitor and manipulator.
The standard Phoron bore can only be aquired via the mining and the exploration vendor and is only used if science isnt around, or exploration forgot and/or lost other equipment on the go. Meaning in both use cases the people wanting to use it dont have access to proper parts, which is stupid.
:cl:
fix: Vendor Phoron Bores only need phoron and a powercell.
/:cl:
=> Phoron Bores start with a capacitor and a manipulator

code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm, code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm, code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
This is my attempt at making Proteans able to survive, along with other miscellaneous fixes and tweaks
Note, this does make the Protean power creep advance, but such is the way of balance.
Less instant death, hooray.
:cl:
add: Added Protean unarmed verbs
add: Added Protean blob resistances/weaknesses
tweak: Made Proteans not need to blob to reform single limbs
balance: Made Proteans not die instantly to ions, and not blob instantly to lasers
tweak: Other tweaks, that in my mind make sense for the hyper-advanced nanoblobs
/:cl:
=> Mild Protean un-fucky wucky-ing

code/modules/modular_computers/hardware/battery_module.dm
Ready to (Test)Merge
Now properly, fixes an override that shouldnt have existed
Things now work as intended(hopefully) only tested it with loadout tablets, but unless someone did a lazy on the vandor tablets it should be fine.
:cl:
fix: Tablets now spawn with their proper Battery modules.
/:cl:
=> [RTM] Battery_Modules no longer override their battery on charge_to_full()

code/modules/detectivework/tools/swabs.dm
Swab kits are a little munted, though mostly in weird fiddly ways that could really do with a general overhaul.
Either way, this fixes something that could end up really bad in the 'this vox/plasmaman needs to take off his mask or else i can't check his palms for gunshot residue' kind of way
I've also slightly adjusted the text for a mouth swab being blocked by a mask since that also includes cigarettes and other items, and changed the sample_type of palm swabs from 'GSR' to 'residue' which implied there was gunshot residue to be found even if there wasn't.
It's worth reworking them somewhere down the line: currently full-face helmets don't block swab kits, you can swab a synth's mouth and get a DNA string (though synths bleed and have fingerprints so ???), and you need a target to be on …
=> masks no longer block your ability to use swabkits on hands

code/modules/food/food/drinks.dm
Fixes #2738
One-line check to make sure the standard_pour_into() target isn't loc. Since this is only ever called by reagent containers, there shouldn't be any side-effects.
:cl:
fix: Drink glasses no longer fill chem/condimasters when being put into them.
/:cl:
=> quick fix for drinks filling chem/condimasters when being put into them

code/__DEFINES/lighting.dm
E.
Changes the hex value of station lighting tubes from 
#E0EFFF
to
#B3D7FF
which is about 11% more blue, making the lighting slightly less straining on the eyes.
I would have gone with orange which is technically better, but would also make the station look like piss.
why is this station so fucking bright
:cl:
tweak: tweaks the lighting color for tubes
/:cl:
=> Station lighting tubes are now very slightly less white.

code/modules/client/preference_setup/loadout/loadout_head.dm
🆑
tweak: returns previously removed berets to loadout selection
/:cl:
'sol' berets 💯
=> re-adds berets that vorestation removed

_maps/map_files/triumph/triumph-03-deck3.dmm
Now in the proper format, re-upload of #2787 
Bug bad. tgm good.
🆑FreeStylaLT
fix:Fixed virology power issues and other misc. map bugs on Deck 3 of Triumph.
/🆑
=> Fixes Virology areas and removes loose disposal items from Triumph (Now in tgm)

code/game/turfs/flooring/flooring.dm, code/game/turfs/flooring/flooring_decals.dm
From my **limited** understanding, the `LateInitialize()` of the decals was simply never called, swapping them back to `Initialize()` fixed it with no apparent issues, but I did not do a full code dive into the initialization subsystem.
This should **definitely** be looked at by someone who understands the current decal system / mapload order / atom initialization system better, as every decal is now initialized regularly, not late.
Fixes a rather fun tool for those who enjoy customization:
fix:Fixed the floor painter
/:cl:
=> [Review Needed]Moves floor decals from LateInitialize() to Initialize(), fixing floorpainter

code/modules/client/preference_setup/loadout/loadout_uniform.dm
see title
underused but cool looking suit might see more use
:cl:
tweak: requirements for command bodysuit
/:cl:
=> Allows Command Secretaries to spawn with the Command Bodysuit in loadout.

code/modules/mob/inventory.dm
uncomments out ???? the part where whatever vore goober modified this code that we acquired during the vorecode 2019 update :pepemods:
:cl:
fix: items in the character setup preview no longer remain across different slot previews
/:cl:
=> let's actually delete the inventory when we call delete_inventory()

code/modules/mob/living/carbon/human/life.dm
Previously everything was stuck behind a check for bodytemperature >= 361, which meant you'd only see the max temperature icon, and it'd never go away.
You'll start to see the temperature icons for being cold again, too. 
sqosh bugs
:cl:
fix: Fixed hud thermometer sticking at maximum
/:cl:
=> moved synth cooling check so it won't interfere with heat status icon

_maps/map_files/triumph/triumph-01-deck1.dmm, _maps/map_files/triumph/triumph-02-deck2.dmm, _maps/map_files/triumph/triumph-03-deck3.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm
This PR does four things:
- Trims all the abundant lights.
- Re-distributes some lights for better coverage.
- Replaces maintenance / toilet / shower area lights with small fixture lights.
- Also fixes a minor Virology cable bug causing it to be depowered.
This is purely aesthetic, but reduces map clutter and makes Shadekins less prone to breaking down in tears (though some consider that a good thing)
This is also a difficult PR to showcase in images, just, uh, trust me. There are way fewer lights everywhere now.
del: Abundant lights on Triumph
/:cl:
=> Reduces the ungodly amount of lights on Triumph across all four decks

code/game/objects/items/weapons/material/knives.dm, code/modules/clothing/under/accessories/accessory.dm, code/modules/clothing/under/accessories/holster.dm
machetes can now be click holstered and unholstered like regular holstered weapons, and will no longer be stuck in backpacks permanently
:cl:
fix: machetes are now as functional as any other holsterable weapon
/:cl:
WIP
=> let's make machetes less busted

code/modules/telesci/hyper_pad.dm
Mechs are anchored.
The leap pad doesn't teleport anchored objects.
So I just wrote an exception for mechs, because they should teleport.
=> Fixes quantum leap pad not teleporting mechs.

nano/templates/partslathe.tmpl
makes parts lathe not terrible to use.
Parts lathe UI gets a little CSS change and layout reordering to be less jumpy. 
Parts lathe moves the buttons around every time you click one currently, and has too much wasted space, enough that you have to scroll multiple times to make parts. We don't have TGUI for this machine yet, so this makes it less painful to use until then. 
:cl:
tweak: Parts Lathe GUI is improved slightly. 
/:cl:
=> Parts Lathe GUI update.

maps/citadel_minitest/citadel_minitest_defines.dm, maps/nsv_triumph/triumph_defines.dm
this stops using triumph lobby screens in minitest. there will now be minitest specific lobby screens to prevent ANY confusion for a dev as to where they're at.
see: devmins hitting 'start now' on live
🆑
tweak: minitest has minitest specific lobby images now
add: 1 new rp lobby image
/:cl:
=> adds some lobby screens

code/modules/mob/living/silicon/robot/robot_modules/station/cargo.dm
see title
funny knife heho :)
(knife with moderate effectiveness for jabbing shit, but **50** force against animals and aberrations, intended purpose "stabbing whatever's hiding out in the belt")
:cl:
add: Mining-module equipped stationbound synthetics now get a disruptor blade when given a scrambled module. What's a disruptor blade? Who knows.
/:cl:
=> disruptor blade in mining borg emag modules (read: scrambled equips)

_maps/map_files/triumph/triumph-02-deck2.dmm, _maps/map_files/triumph/triumph-03-deck3.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm, code/game/area/Space Station 13 areas.dm
This purges all(?) varedited instances of areas from Triumph .dmms. Hopefully. @silicons be sure to double-check with linter in case I missed any.
In *general* this is bad practice, because there are area-specific events (radiation storm, brig virus, any potential new ones) that can inadvertently affect an area you never intended it to, simply because you were a lazy mapper and instanced instead of adding 2-3 lines of new code.
fix:Area errors. You won't know where, trust me.
/:cl:
=> removes instanced areas from Triumph

code/modules/nifsoft/nif.dm
just using [human] here will make it return blank space, so we force it to use human.real_name to pull the real_name var from the mob/living/carbon/human
closes #2701
=> fixes #2701

code/game/objects/structures/crates_lockers/closets/secure/security.dm, code/modules/clothing/suits/armor.dm
Repaths Captain's Carapace to be under /storage/vests
HoS and previous Captain's vest have pockets so the carapace deserves pockets too >:(
:cl:
tweak: Repathed capcarapace
/:cl:
=> Captains have pockets too

_maps/map_files/triumph/triumph-04-deck4.dmm
I have no concrete clue how this was removed in the sec remap, but it was entirely unintentional.
Command should probably be able to make emergency engine calls from bridge. In case of, you know, an _imminent explosion._
:cl: FreeStylaLT
fix: Missing core ejection button from Bridge
/:cl:
=> Returns the missing core eject button to Bridge

code/__DEFINES/logging.dm, code/modules/admin/admin_investigate.dm, code/modules/atmospherics/components/unary/outlet_injector.dm, vorestation.dme
adds ui to air injectors. you can now modify on/off and pump rate without a console to control it
why in the name of all that is holy do you have it so you can only control pre-mapped injectors
what happens if you lose the console??
even this isn't preferable but it's slightly less awful than not being able to do it at all.
:cl:
add: air injectors are now OP.
/:cl:
=> "the codebase never ceases to amaze me with its amazing ideas and piss-poor implementation": air injectors.

code/modules/power/singularity/collector.dm, code/modules/shieldgen/shield_gen.dm
This needs some real round testing.
This PR removes the actual gas content from the math related to how much power a collector produces. Granted, this will take a  lot of tweaking to make ideal but- the general goal is to make it impossible for a set of collectors to 10x your power generation. They should be helpful to boost your power, but not to the absolutely ludicrous degree they are now.
It ALSO makes shields a lot more power-heavy. A fully charged, 10 RW hull shield now draws 1.6 MWs, while also increasing the max charge rate from 0.5/s to 0.9/s to allow it to more easily be set at lower levels, and boosted in times of higher risk. This will also likely need further tweaking after live tests.
Engineers who powergame the fuck out of the engine and shields at the start of every round …
=> How to piss off engineers in one simple step

code/modules/fishing/fishing.dm
Reduces max fishing time from 99s to 70s
Removes chances of any fish which use sif meat which to my knowledge do not work in any recipes
Increases chances of getting actual fish over junk
Fish isn't used often enough and that's because fishing takes fucking ages and is more likely to give you shitty items than actual useful fish, and when it does there's a solid chance you get useless fish you can't even cook with.
:cl:
del: removes several sif fish types
tweak: tweaks time on fishing
tweak: tweaks droprates for fish
/:cl:
=> Makes fishing less fucking dogshit

code/modules/games/dice.dm
it is what it says on the tin
you can play the dice game from KCD now if you want need i say more that's right i needn't
:cl:
tweak: dice cups hold 6 dice now
/:cl:
=> makes dice cups able to hold 6 dice instead of 5

code/modules/mob/living/carbon/human/species/station/traits/negative.dm
title
consistency and accuracy = poggers
:cl:
tweak: made the minor rad trait mechanically accurate to its description
/:cl:
=> makes minor rad weakness actually cause 25% more rads like it says instead of 35% more

code/modules/client/preference_setup/vore/02_size.dm, code/modules/clothing/under/miscellaneous_vr.dm, code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm, code/modules/nifsoft/software/15_misc.dm, code/modules/resleeving/designer.dm, code/modules/vore/resizing/resize_vr.dm
max mob size reduced to 150% from 200%
mobs shouldn't be 3 tiles long or tall considering for headgear and different turf layers. dog borgs (and normal player mobs) at 200% can take up an entire hallway and no longer interact with things predictably; they enter doors above their sprite, couches can cover parts of them, etc
tweak: max mob size reduced to 150% from 200%
=> max mob size reduced to 150% from 200%

code/modules/projectiles/pins.dm
title
using this on lavaland/beltmining is based, if i wanted to commit homicide i'd use a kinetic accelerator anyways 
:cl:
balance: explorer pins now work on lavaland/anywhere off station
/:cl:
=> makes explorer pins work anywhere off station, not just on explorer levels sue me

_maps/map_files/triumph/triumph-02-deck2.dmm, _maps/map_files/triumph/triumph-03-deck3.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm
Lots of minor fixes, but major-ish ones include:
- Flattening out the layout of D4's maint, also removes blood and skulls
- Redoes Warden's office
- Reshuffles some equipment around the armories
- Standardizes department stripes
- Fixes cameras under lights (as many as I could locate)
- Fills up certain coffee / drink dispensers
Warden's office:
Essentially just addressing various complaints / concerns and establishing (or following) standards.
tweak: Minor changes to Security and armories.
/:cl:
=> Various aesthetic fixes and tweaks to Triumph, especially Security and D4.

code/game/jobs/job/security.dm
Removes the listed titles for the following reasons.
Gaoler and Constable are old english that likely wouldn't see use in Galcomm
Constable was doubly removed because a Constable is a law enforcement term, and station sec aren't law enforcement.
E
:cl:
del: Constable Alt Titles
tweak: Gaoler > Jailer
/:cl:
=> Replaces "Gaoler" with "Jailer" and removes the Senior Constable and Constable titles.

code/modules/mob/living/silicon/robot/robot_modules/station/science.dm
One new module available for the sciencehound, the wirecutters.
This is another case where the base non-dogborg option has certain equipment while the dogborg does not.  Wirecutters are necessary for mech construction and borg repair, the lack of them alone restricting the sciencehound's uses.
:cl:
Adds some wirecutters to scihound
/:cl:
=> Adds wirecutters to sciencehound

_maps/map_files/triumph/triumph-04-deck4.dmm
Nanotrasen's Human Resources division was left disturbed by an incident where an employee was found drowned inside a pool. Preliminary investigation found it to likely have been an accident.
Due to this, appropriate measures have been taken:
- The exterior of the railing has been covered by a hazard line, indicating potential danger
- A falling hazard sign has been added, to signify potential dangers of falling inside the pool
- A pair of swimming fins were added to aid in rescue.
With these added measures Nanotrasen hopes the crew can feel safe and their morale reinvigorated, knowing that the corporation is willing to take every precaution necessary to avoid any further tragedies. We Care:tm:
add: Safety features around the pool
/:cl:
=> Following an unfortunate incident where an employee was found drowned in a pool, NT has added appropriate safety measures.

_maps/templates/engines/triumph/triumph_engine_burnchamber.dmm, code/modules/power/powernet.dm, maps/submaps/engine_submaps/engine.dm
This PR adds a burn chamber engine for the NSV Triumph, creating heat by burning off gasses for the thermoelectric generators. 
A lot of this engine is subject to change based on feedback. As of the initial PR, it is a usable engine that is very fast to start for a basic setup.
This submap will require a config change to enable, adding in "ENGINE_SUBMAP EngineSubmap_Burn <weight>" to game_options.txt
It's an easy engine to set with a large amount of in-round optimization for players to do. It's also a decent atmospherics playground. More engine variety is also good. 
:cl:
add: Burn chamber engine submap. 
/:cl:
=> Adds a burn chamber engine submap

code/__HELPERS/atmospherics.dm, code/game/machinery/atmoalter/canister.dm, code/modules/atmospherics/pipes/pipe_base.dm, nano/templates/canister.tmpl
You get to see moles in your pipenets and cannisters, as opposed to just relative KPA. Ghosts can also analyze pipes now!
KPA leaves out a lot of information and is relative to area. Moles is an absolute measurement of how much gas is available before other factors. Main shows this information (to ghosts too), and it's immensely helpful there, so I think we should too. 
:cl:
add: Moles measurement to pipes and cannisters
add: Ghosts can inspect pipes
/:cl:
=> Adds moles to gas analyzer & allows ghosts to analyze pipes

code/modules/food/kitchen/cooking_machines/_appliance.dm, code/modules/food/kitchen/cooking_machines/_cooker.dm
Fixes #3032
Speeds up the cooking machines significantly, and makes them not lose half their heat just by opening them. 
Feels, to me, realistic in speed and behaviour now. 
It's well known how agonizing the oven is to use, this fixes a few of these issues. 
:cl:
tweak: Oven heat momentum sped up almost 8x. They don't lose their heat when opened, too. 
fix: Machines no longer say they're off upon inspect when they're on. 
/:cl:
=> Speeds warming up of cooking machines & fixes "it is switched off." always appearing bug

code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
sdql2 can't access contents natively and still print while retaining assoclist printing functionality due to byond being byond.
=> adds _contents() wrapper for SELECT SDQL2 statements

code/__DEFINES/chemistry.dm, code/__DEFINES/mobs.dm, code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/new_player/sprite_accessories.dm, code/modules/organs/subtypes/shadekin.dm, code/modules/vore/appearance/sprite_accessories_taur_vr.dm, code/modules/vore/appearance/sprite_accessories_vr.dm
this is a port of virgo PRs https://github.com/VOREStation/VOREStation/pull/6241 and partially https://github.com/VOREStation/VOREStation/pull/9578, allowing the selection of nerfed shadekins (if headmins decide to allow using them that is)
at the moment, black-eyed shadekins:
-lose all shadekin powers (phase shift, corpsemending, flashdark)
-have less health than their non-powerless counterparts, with a higher brute modifier
-are completely immune to shocks (subject to change)
-have the best darksight modifier around (equal to normal shadekin)
-are slower than humans on baseline as well as get weighed down more by heavy objects
-are immune to vaccuum (they do not breathe and are immune to cold and low pressure)
-are immune to high pressures
-are resistant to high temperatures
-cannot be …
=> Ports black-eyed shadekins from Virgo (WHITELIST ONLY)

code/_onclick/hud/ghost.dm, code/controllers/configuration_old/configuration.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/verbs/panicbunker.dm, code/modules/client/client procs_vr.dm, code/modules/client/client_defines.dm, code/modules/client/client_procs.dm, code/modules/mob/mob.dm, vorestation.dme
Ports IP reputation from Vorestation
making it harder to grief
:cl:
add: IP reputation checking
tweak: return to menu is now respawn. 
config: new things to config: IP rep
admin: IP rep admin verb
/:cl:
=> IP Reputation port from Vorestation & Return to menu >> Respawn

code/game/objects/items/devices/text_to_speech.dm
As the title says. QOL Stuff.
We can use other devices from pockets and chairs, why not TTS?
:cl:
fix: TTS Devices are now usable in while sitting in chairs and from pockets.
/:cl:
=> TTS Devices can now be used in chairs, and by alt clicking from pockets.

code/game/objects/items/devices/scanners.dm, code/game/objects/items/storage/belt.dm, code/modules/research/designs/engineering.dm
adds a long range analyzer to the game, available from RnD
This adds a long-range analyzer to the game, printable by RnD. Balance may be needed for the tech levels and materials. 
It's another engineer upgrade, like the better t-rays and tools. Useful when building rooms or fixing destroyed areas. 
:cl:
add: long-range analyzer to RnD for engineering.
/:cl:
=> Adds a long rang analyzer to the game. 

maps/~map_system/maps.dm
oh so this two line fix was why triumph had a snowflake get map zlevels proc are you kidding me how did we not have this fix if you're good enough to port overmaps you should be good enough to not snowflake this
=> stupid fix for get_map_levels() 

code/__DEFINES/dcs/flags.dm, code/__DEFINES/dcs/signals.dm, code/datums/elements/conflict_checking.dm, code/datums/looping_sounds/_looping_sound.dm, code/modules/mining/kinetic_crusher.dm, vorestation.dme
stacking them on someone will now cause recharge conflicts.
slightly nerfs damage, you now need to backstab to do the full 75 damage. otherwise damage on detonation is now 40 instead of 50.
haha funny backup weapon
:cl:
balance: Kinetic daggers have been slightly nerfed.
/:cl:
=> nerfs kinetic daggers 

code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm
Yeah, I forgot to add the line of code that makes adding the ointment module actually happen.  I quickly realized this when trying to do surgery on a burn victim
I'm dumb and forgot to do this before
:cl:
adds burn kit to medical cyborg module
/:cl:
=> makes it so mediborgs actually have burn kits (god i'm really dumb)

_maps/map_files/triumph/triumph-04-deck4.dmm
Security showers had a really unusually placed frosted window that prevented you from entering without breaking it.  This just removes that.
Decreased risk of hand exposure to sharp glass, as well as it just makes more sense.
:cl:
Frosted window removal
/:cl:
=> Removes random frosted window in security showers

code/game/jobs/job/captain.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/job.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/offduty.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm, code/game/machinery/computer/timeclock_vr.dm
Adds the off-duty commander role, to allow people to reduce their command PTO, they can only join again as command secretary.
Off-duty command
:cl:
add: Off-Duty Command
code: Allow_jobhup is no longer double negated
/:cl:
=> [RFM]Off-duty command

_maps/map_files/triumph/triumph-04-deck4.dmm
Tin
The stunsword is a donator item not meant to be used by the general public.
:cl:
del: no more stunsword in sec armory
/:cl:
=> Removes stunswords from the sec armory

code/__DEFINES/chemistry.dm, code/modules/food/food/snacks.dm, code/modules/mob/living/carbon/human/examine.dm
Long story short, brings down all of the "max nutrition" levels above the default normal of ~400.
This reduces the max nutriment possible from SIX THOUSAND, to 1250. For reference, a liquidfood ration is 30.
This also reduces the standard hunger drain from 0.05 to 0.03 to help counter the reduction in max capacity for certain races like Xenochimera that heavily rely on food to not go nuts.
A system like this will need a long testing period because it's impossible to balance nutriment without shittons of testing based on how much shit uses it. So we'll see how she goes.
This ALSO, possibly contentiously, removes the examine text based on nutriment. The WEIGHT YOU SET IN CHARACTER CREATION still works, however, vampires who eat one person will not longer be seen as fat.
1- Nutriment drains …
=> Changes to nutrition and fetish code

code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/human/species/station/station.dm
Currently Black-Eyed Shadekin are afflicted by phoron toxins when they equip contaminated clothing (the ones with hazard symbol on it after being in phoron rich atmosphere).
Since they don't really "breath", aka - don't get affliction from phoron in atmospherics, it's a bit odd to be afflicted by clothing.
It makes sense for Black-Eyed Shadekin to be unafflicted by phoron, since both clothing and atmospherics don't damage regular shadekins and their biology doesn't differ much after the "Ritual". 
It will prevent a weird situation where a Black-Eyed Shadekin needs to undress fully to go out into the phoron fields. They aren't required to wear clothing on station, but if they do - they will get in this situation without the fix.
:cl: …
=> Removes contamination from Black-Eyed Shadekin

code/modules/mob/living/carbon/human/emote.dm
Multiple people have been raging about this.
Multiple people have been raging about this.
:cl:
fix: *chuckle no longer plays the laugh emote
/:cl:
=> Makes '*chuckle' to 'chuckles.' instead of laugh

code/modules/multiz/movement.dm
stolen from Silicons
Prevents people from falling through catwalks while moving diagonally
no teleporting downstairs out of no where.
:cl:
fix: You shouldnt drop through catwalks anymore
/:cl:
=> Prevents falling through catwalks and lattice,

_maps/map_levels/140x140/talon/talon1.dmm, _maps/map_levels/140x140/talon/talon2.dmm, code/modules/maps/talon/talon.dm, code/modules/maps/talon/talon_areas.dm
I probably should have split this up since it contains fixes to oversights *and* my own additions, but PRing twice for map changes on the same DMM is painful in my experience and I already had it all finished before thinking about it.
-I fixed up the weapon and suit storage rooms. Added two mining voidsuits and a suit cycler with the appropriate access so that abnormal crew (teshari and such) have temperature resistant suits that they can wear.
-Added a vault that has a bit of mostly random loot that can be traded with the colony and its crew for things the Talon needs/wants. The vault shouldn't be looted without the captain's permission. I'd make special access for the captain only, but I'm hoping that it would be unnecessary.
-Everyone in the Talon should have access to voidsuits. …
=> Talon Changes and Additions

code/modules/client/preference_setup/general/03_body.dm
see title
i don't want to have to switch to a different species before hitting the reset slot button every time i want to look at a different bodypart
:cl:Kraseo
fix: Synthetics no longer carry over every single character save.
/:cl:
=> fixes synth bodyparts persisting between charslots (again)

code/modules/mob/mob.dm
>bandaiding shit code practices with setting things to harddel_now
lmfao no.
=> mobs are no longer HARDDEL_NOW for performance reasons because the occasional bugged player is a small price to pay for server speedups.

code/game/objects/items/devices/scanners.dm
fixes issue #3227 
the gas analyzer can analyze a great many things including turfs and containers, and as such, needed this check a long time ago. see: ancient vorecode where this bug remains likely to this day
by adding the check, we eliminate the duplicate output without refactoring analyzer code. there is a separate proc that handles checking a tank's contents, so this stops the first proc from being called at the same time as the second.
closes #3227 
:cl:
fix: fixes gas analyzers duplicating output
/:cl:
=> fixes issue #3227

code/modules/food/recipes_microwave.dm
it _should_, anyway.
closes #3213 on fullmerge automatically if it does
also there was a /obj/item/reagent_containers/food/snacks/carpmeat/fish in a list() twice, don't know what that was about. if this breaks something, reply and i'll amend further
:cl:
fix: fixes sushi being ruined when using sif meat
/:cl:
=> this should fix issue #3213

code/modules/mob/new_player/new_player.dm, code/modules/resleeving/mirror.dm, code/modules/surgery/implant.dm
I never expected people to actually try to remove mirrors with surgery instead of the convenient tool, so I never made mirrors null out when removed through surgery which basically bricked them and made it impossible to implant a new one without var editing. Now it's fixed for when people do it wrong/accidentally do it wrong because they tried to remove shrapnel.
(Because I also forgot how dogshit surgery is for shrapnel removal)
ALSO.
Synthetics don't spawn with mirrors. This is now fixed.
You also are now incapable of installing mirrors into mobs that have no client attached. Use the resleeving console. An error message has been added to facilitate this.
obvious tbh
:cl:
fix: synthetics now spawn with mirrors as intended
tweak: Mirrors can now properly be removed through surgery without …
=> Fixes a few issues with mirrors

_maps/map_files/tether/tether-05-station1.dmm, _maps/templates/engines/tether/engine_rust.dmm, _maps/templates/engines/tether/engine_singulo.dmm, _maps/templates/engines/tether/engine_sme.dmm, _maps/templates/engines/tether/engine_tesla.dmm, code/modules/power/smes.dm, code/modules/power/smes_construction.dm
This PR returns the engine SMES subtype to it's original, unmodified form (250kw in/out) and then shifts the SMES units onto the submaps. The RUST submap has it's own SMES variant that has 750 kw in/out, while the rest return to the standard 250 version.
We modified the core engine SMES unit to have more coils for the RUST, but the buff was heavy handed and also didn't work on Tether since it didn't use that subtype, rather a var edited version of the primary one. The RUST SMES NEEDED more power, and the others didn't need it- but they can still be upgraded. Moving the SMES units to their related submaps makes future edits of them a bit easier, and allows for modularity between the submaps as demonstrated with the RUST now having an upgraded one, without the rest also having them.
:cl: …
=> Changes to engine submap SMES units.

code/modules/research/rdconsole.dm
Hard access locks are godawful on rounds with no one to fill a department.
This still makes locking the console viable, as they cannot unlock it without an ID, and if they forcefully unscrew it,  they now need to redo the levels manually.
This however intentionally gives intruders a way around this, by using tech backup disks to store the tech before unscrewing it if they are doing levels themselves.
:cl:
balance: R&D console is no longer hard access locked other than for the lock toggle itself and syncing.
/:cl:
=> Removes R&D console access lock other than for locking and syncing

code/game/machinery/rechargestation.dm
staring at a 1x1 room to recharge is pretty unfun
plus this makes it marginally worth it to use these instead of hyper expensive APC connectors goddamn
:cl:
balance: cyborg chargers charge synths/FBPs 2x fast (cyborgs unchanged)
/:cl:
=> cyborg rechargers now charge 20 nutrition per tick instead of 10

code/game/objects/items/devices/radio/headset.dm
Literally just a var. This gives anyone who dares ruin their fashion mild flashbang immunity.
This change is most pertinent to Sec and Exploration, as right now the only items that actually provide ear damage resistance are:
- Earmuffs / Headphones
- A hardhat
- A helmet
Which is a very strange, barren list. Also, fun fact, ERT, besides helmets, had no flashbang immunity.
**POTENTIAL CONCERN:** This also gives minor flashbang immunity to every Head and every department (barring service) if they choose to wear the bowmen.
:cl:
add:Ear protection to Command, ERT, CC and Sec bowmen headsets.
/:cl:
=> Adds ear protection to every bowman headset

code/modules/overmap/ships/computers/sensors.dm
The paper that came out of the sensor console was blank every time.
Let people actually see the sensor descriptions???
:cl:
fix: sensor console no longer prints out blank paper
/:cl:
=> Fix shuttle sensor console printing out blank paper

code/modules/mining/drilling/drill.dm
Drills no longer vanish your ores into limbo. This is untested, by the way.
Bugggggs.
:cl:
fix: mining drills unload into boxes properly now
/:cl:
=> make drills unload properly

_maps/map_levels/140x140/talon/talon1.dmm, _maps/map_levels/140x140/talon/talon2.dmm
-Deck 1
Moved the inducer to make space.
Replaced a crew voidsuit with a mining voidsuit for species like Teshari, where there isn't a cyclable Talon crew variant.
Changed jetpack layers.
Added the correct flaregun ammunition instead of standard flares.
Replaced the shotgun and it's buckshot with the burst laser that was there at the virgo port.
Moved the holdout pistols, replaced their pins and fixed their descriptions to fit with the existing phasers.
Readded holsters.
Moved the netgun, and readded the egun that was there at the virgo port.
Added spare weapon cells to brig.
-Deck 2
Moved packages into the locker, and added more
Removed sec restriction from egun spawner to add variety where previously only the egun, and laser rifle were spawning.
Having cyclable suits is important for …
=> Talon Restored/Tradified 

code/controllers/subsystems/planets.dm, code/modules/multiz/turf.dm, maps/tether/tether.dm, maps/tether/tether_virgo3b.dm, maps/tether/tether_virgo4.dm, vorestation.dme
Planets were always night time and never had any weather! This fixes that. Also changes 3B's day/night cycle duration to 6 hours because the way this system works likes even numbers way more and also Virgo did this on their server anyway.
These systems should actually work.
:cl:
fix: day/night cycle and weather effects now work again
tweak: virgo 3b's day/night cycle now takes 6 hours instead of 3 hours
tweak: open turfs are now affected by lighting
/:cl:
=> Fixes to the plantery day/night cycles and weather effects

code/modules/shieldgen/shield_gen.dm
back to the values prenerf when they were nerfed on triumph
unlike the triumph, the tether isn't powercreeped to every way imaginable
having shields be more than 2x as shitty as they should be is pretty awful when the map was designed around the values upstream uses
infact upstream shields are different now but until we port those, this is the next best thing.
=> reverts shield power usage nerfs

_maps/map_files/tether/tether-09-solars.dmm
As it turns out the way Virgo Generate caves in UD and in solars/mining is different in that it will generate rocks on top of mineral turfs in solars/mining but not in UD. Not realizing this I accidentally gave the entrance to the UD in solars the ability to generate caves. This has been fixed with the use of 'ignore cavegen' mineral turfs which should make certain that the cave entrance to UD generates unblocked every time and miners don't have to deal with Z-levels transitioning them into a rock wall. I admit I probably should have caught this sooner however it appears Cavegen can coincidentally decide to keep the open mineral turfs so during some tests the cave appeared as it should have.
:cl:
fix: UD Secondary entrance, in solars region.
/:cl:
=> Fixes Solar-Side UD Entrance

code/modules/projectiles/guns/projectile/boltaction.dm
Which was quite embarassing considering I added them. However since I was not aware they were broke, until someone mentioned them being broke over radio, I was not able to fix to add the four "." to make them work.
:cl:
fix: lever actions now accept proper ".357" and ".44" rather then nonexistent "357" and "44"
/:cl:
=> Fixes Lever Action Rifles

_maps/map_files/tether/tether-06-station2.dmm, code/game/turfs/simulated/floor_types_eris.dm
This PR is about modifying the Exploration shuttle, its hangar and the Pilot's office on station level 2 (Z6).
- The Exploration shuttle has been given a new layout to help maximize its space and arrangement. Main additions to the shuttle have been a proper Cargo storage section and a Micro-Medbay that houses a Sleeper and basic medical tools. Seatings for the exploration crew have been expanded to allow both big and small teams to have spaces tailored to them. The Shuttle's cockpit was relocated to be in the very middle of the shuttle, giving it protection from direct impacts while its windows allow a clear view of the entire ship. All of the atmospherics, power and fuel systems have been moved backwards to be all in close proximity. All this, in a maximized hull that takes all the space …
=> Improving the Exploration Shuttle, the Exploration Hangar and the Pilot's Lounge

code/game/jobs/access_datum.dm, code/game/jobs/job/assistant.dm, code/game/jobs/job/captain.dm, code/game/jobs/job/cargo.dm, code/game/jobs/job/civilian.dm, code/game/jobs/job/civilian_chaplain.dm, code/game/jobs/job/department.dm, code/game/jobs/job/department_vr.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/exploration.dm, code/game/jobs/job/job.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm, code/game/jobs/job/silicon.dm, code/game/jobs/job/special.dm
Read the title
+ Ports VOREStation/VOREStation/pull/8419
Xenobotany is on the other side of the station from Xenobiology, they're not going to be working together normally anymore.
ALSO MORE NICE ALT_TITLES
:cl:
add: Xenobotanist Job
add: Lots of other Job Names
del: Xenobotanist alt_title for Xenobio
fix: Moreso readding values we SHOULD'VE had but were missed in someone's port or something
/:cl:
=> Readded some lost alt_titles, added some new ones, and ported the Xenobotanist job

code/__DEFINES/mobs.dm, code/modules/mob/living/carbon/human/species/station/station.dm
and give them the resistances and weaknesses like suggested in lore
Xenomorph Hybrids are actually Neomorphs, this PR rectifies that.
Brings the game data uptodate on lore things
:cl:
fix: Neomorphs get the resistances and weaknesses lore suggests
refactor: Xenomorph Hybrids are now correctly named Neomorphs
/:cl:
=> Xenomorphs to Neomorphs

_maps/map_files/tether/tether-05-station1.dmm
As a follow-up of my previous changes to the exploration department - The Hangar, Exploration Shuttle and Pilot's office - This PR is about improving the Exploration Department of the asteroid deck 1. It involves a full redesign of both layout and aesthetic for the department, which allows the department to have more life. First of all, trees and plants have been added around the department, helping make the place feel much more alive. The layout has also been improved to make each room feel connected in some way. Even the hallway, previously an utilitarian two-tile wide, has been given life with chairs and grass spots. The crew area has been given a full remake, making it truly feel like somewhere the crew would be working at instead of a grey metal hell. Same goes for the Pathfinder …
=> Improvement of the Exploration Department

code/modules/food/kitchen/smartfridge.dm, code/modules/xenobio/machinery/processor.dm
- Processor can now be set to auto intake mode with alt click
- Fridges and processors are unwrenchable
- You no longer need the thing you'rei nserting to be adjacent, just either it, or yourself
the most obnoxious part of xenobio is the wild amount of movement.
you still have to do that a lot, it's just quite easier now.
:cl:
add: xenobio qol: alt click processor to auto intake, unwrenchable, etc.
/:cl:
=> ""small"" xenobio QoL update

code/modules/events/infestation.dm
These vermin are so disgusting that people may actually try to eliminate them. Besides its probably good we get some amount of use out of the Eris Roaches, and they provide much needed variety to the vermin infestation space events. The fact that the event will only spawn roachlings should mean that even if the not dealt with its no big issue.
=> Vermin Infestation Now Can Spawn Roaches

code/modules/vore/eating/belly_obj_vr.dm
Was discussing this with someone about how this is one of the only qdel deaths I can find that doesn't make the mirror drop, so figured it should. Also kind of humourous to me to imagine how this works with digesting someone and then pulling the mirror out to revive them.
Idk. Maybe not permadying from this if they didn't get their mirror taken out is good?
:cl:
tweak: dying from digestion now drops your mirror
/:cl:
=> make it so digestion drops their mirror

_maps/map_files/tether/tether-02-surface2.dmm
I did two things in this PR:
1: Moved two of the xenobiology wall chargers up where the sink used to be, and moved the sink over (Yes, I know the watertank is in front of the sink by default now, no, I don't care)
2: Moved all the cell chute exits to their opposite corner, so they're not being free cover for slimes from weaponry
These are both just minor "Man, I wish I had these" from my time playing xenobio recently
:cl:
tweak: tweaked xenobio layout
/:cl:
=> Minor Xenobiology changes

code/datums/autolathe/devices.dm, code/datums/outfits/jobs/science.dm, code/game/objects/items/devices/geiger.dm
I'm tired of having to take off a labcoat I'll never wear when I join as a Roboticist.
QOL
:cl:
tweak: Adjusts labcoat dispersion.
/:cl:
=> Removes the Labcoat from Roboticists at Spawn, Repaths RD to Spawn with RD Labcoat, Repaths Scientist to Spawn with Science Labcoat.

code/game/objects/structures/window.dm
It makes windows of all kinds melt similarly to walls. Rather simple, but it will probably annoy engi players.
Basic windows will break at 500 C, R-windows will break at 1000 C.
For engineering and toxins reasons, borosilicate will not melt.
Enjoy your hellburns.
This is only if they're next to a fire, same as the walls.
Consistency. Why can walls melt, but windows not?
:cl:
fix: Windows can now melt.
/:cl:
=> Window melting fix

_maps/map_levels/140x140/debrisfield.dmm
1. _As it says. Repositions the Debris Field shuttle landmark._
1. The shuttle should probably fit in its landing zone. Thank you Buffy for alerting me to this one.
:cl:
tweak: Adjusts shuttle landmark @ Debris Field.
/:cl:
=> Rearranges Shuttle Landmark to Account for Explo Shuttle.

_maps/map_files/tether/tether-03-surface3.dmm, code/datums/outfits/jobs/civilian.dm, code/game/jobs/job/civilian.dm, code/game/objects/items/weapons/melee/misc.dm, code/modules/clothing/spacesuits/void/station.dm, code/modules/clothing/under/jobs/civilian.dm, code/modules/vehicles/skateboard.dm, code/modules/vore/appearance/sprite_accessories_vr.dm
1. _Fixes the bug where a dropped skateboard reverts to its basic state._
2. _Working on fixing backpack issue._
3. _Adds coloration to a tail that's meant to have it._
4. _Adds Keycard scanners to HoP and Captain's Offices._
5. _Fixes typos in Construction and Flight suits._
6. _Adds reporter gear to the Reporter alt title._
1. Aggravating issue.
2. Duping issue.
3. Blatant fault.
4. These were just missing.
5. Standard quality control.
6. I added this stuff a long time ago and just totally forgot to implement it.
:cl:
add: Keycard scanners to HoP/Cap's room.
add: Reporter gear to Librarian Alt.
fix: Skateboard faults/duping.
fix: Lizard tail coloration.
fix: Typo correction in flight suit and construction void.
/:cl:
=> Skateboard Duping Fix and Assorted Bugfixes

maps/tether/tether_defines.dm
1. _Removes V.O.R.E./Virgo branded lobby screens from our code.
1. I'm over advertising for an upstream I'm trying to shift away from every round. There's no reason for us to be using these. If someone likes them, commission replacements that aren't tied to their server instead of ours.
:cl:
del: Removes all Virgo screens.
/:cl:
=> Removes V.O.R.E. Lobby Screens From Our Rotation

code/modules/mining/machine_processing.dm
this is flat out awful to deal with on lowpop
if you can't secure one room or atleast detect when people break in you probably don't have enough crew to justify a hard id lock on a currently perma extended server
=> removes id lock from mining point claiming 

_maps/map_files/tether/tether-02-surface2.dmm
Adds fancy NT hats for your armored hats! pewpews have been added!
Adds four hats covers to the armory. Added two phase rifles.
Phase Rifles could be fun to use. Had to wiggle some things around to pack EVEN MORE GUNS in the armory.
Sec wants fancy hats!
This will shut them up!
:cl:
add: Adds four hats to the armory.
add: Adds two phase rifles to the armory.
/:cl:
=> Tears of The Armory

_maps/map_files/tether/tether-02-surface2.dmm, code/datums/supplypacks/security.dm
1. _Remaps the Armory so it isn't so terrible._
2. _Replaces Special Armor sets with specialized Plate Carrier sets._
1. I'm mad at the old Armory and I'm here to fix it.
2. After an extensive series of debates, I'm testing this compromise now so everyone can feel very special and pretty during emergencies without obliterating every minor threat they come across.
:cl:
add: New Armory layout for QOL.
balance: Swaps specialized armor sets out for plate carrier patterns of equivalent design.
/:cl:
=> Remaps the Armory - Replaces Specialized Armor Sets with Specialized Plate Carrier Sets

code/modules/client/preference_setup/loadout/loadout_role_restricted.dm
Edit made by Anodyne, PR made for them upon request.
changes:
* lets talon crew take holsters in loadout
* lets talon crew take departmental duffelbags (engineering, medical, security)
* adds security dispatch uniform because it doesn't exist anywhere else in the game
* adds HoS turtleneck to the loadout
Simple fix
:cl:
tweak: Talon crew can now take holsters and department dufflebags in their loadout. HoS can now select the turtleneck option for their loadout.
/:cl:
=> Loadout Changes for Anodyne

code/__DEFINES/chemistry.dm, code/modules/reagents/machinery/chem_master.dm, tgui/packages/tgui/interfaces/ChemMaster.js, tgui/packages/tgui/interfaces/ChemPress.js
1. _Autoinjectors can now be crafted at Chemistry._
1. Production, yay. I wish I knew what TGUI icons we had available, because the UI is just a stack of squares now.
:cl:
add: Autoinjectors can be produced at chem now.
/:cl:
=> Autoinjectors Can Now be Crafted at Chemistry (Redux)

code/modules/projectiles/guns/projectile/pistol.dm
Added the practice magazine as a valid magazine for the .45 pistol available to security. Previously would not accept the practice magazines that spawn in the firing range.
Needing to unload an entire practice magazine and rubber magazine, then reload all of the practice bullets into the rubber magazine is a bit silly.
:cl:
fix: .45 Pistol from sec now accepts practice magazines
/:cl:
=> Adds practice magazine as valid magazine for .45 sec pistol

code/modules/mob/living/simple_mob/subtypes/animal/roach/roach.dm
It turns out that spiderlings have a bunch of snowflake code when it comes to processing their deaths in order to make it so they don't leave a corpse. However, this caused a issue in which when the code was...borrowed without intent to return...from the spiderlings, it would cause any roach that had to chance to grow up to _always_ grow up unless the roach was killed and gibbed.
I'd rather not have roachlings starting any religions about coming back from the dead, and it makes no sense for a dead creature to suddenly come back to life new and improved.
:cl:
fix: Roaches no longer come back from the dead by becoming swole
/:cl:
=> Fixes Roaches becoming Jesus

_maps/submaps/mountains/Cliff1.dmm, _maps/submaps/mountains/Geyser1.dmm, _maps/submaps/mountains/Geyser2.dmm, _maps/submaps/mountains/Geyser3.dmm, _maps/submaps/mountains/crashed_ufo.dmm, _maps/submaps/mountains/crashed_ufo_frigate.dmm, _maps/submaps/mountains/lava_trench.dmm, _maps/submaps/mountains/vault6.dmm, code/modules/maps/generic/submaps/mountains/mountains_areas.dm
Aight now this SHOULD work, cleaned up bad variables and added proper zones to POI's that were missing them. This should stop these POI's from overlapping with others while the map is being seeded (The four main culprits being the three gysers and the cliffs but a few others were missing zones on placed turfs as well)
Makes POI's seed as intended, *not* on top of eachother
:cl:
/:cl:
=> Mountain (V4 Caves) POI Fixes. This time with less bad ayylien ship variables

maps/tether/tether_turfs.dm
1. _Adds Wood and Sifwood turfs configured for V3b's atmos._
1. The Southern Plains POIs all look terrible because they're spawning interior air mixes and clashing with V3b's phoron atmosphere. This is possibly also contributing to our perpetual active edge concerns.
:cl:
add: Adds V3b Wood and Sifwood variants.
/:cl:
=> Creates Virgo3b Atmos Subsets for Wood and Sifwood Turfs for POI Mapping.

_maps/map_files/tether/tether-05-station1.dmm, _maps/map_files/tether/tether-06-station2.dmm, maps/tether/tether_defines.dm, maps/tether/tether_shuttle_defs.dm
A large shop area, the docking arm, a visitor room. Most importantly, all somewhat secure. It's now possible for security to watch a single chokepoint that people coming to the docking arm can access without hacking. There's still a side-door to encourage sneaking gameplay if traders wish to break in without taking out a wall, but overall, more secure. At the very least, customs is now more between the docking arm and the rest of the station, instead of on the far side of the docking arm. Note: old customs is still in place, as it has a shuttle attached I don't feel like needs to be moved. Old laundry is gone, but haven't decided what to do with old visit office.
Once I get this done, i'll be using the old docking arms for my planned Hardspace Shipbreaker content, to give engineering …
=> Moves docking arm to D2 below cargo+ useful customs and shop

_maps/map_files/tether/tether-05-station1.dmm
Fixes 'all'tm issues from the previous hasty removal of the A1 visitor facilities. I had a really nice Command dorms built there, but was later talked out of it by five diffrent people. For now, it'll become a construction area.
Once the map clears up for A2 however, I'll be turning the existing construction area that's shared in A1 and A2 into a, hopefully, very nice two-floor garden.
Fixes things I was far too hasty with in my rush to clear up mapping conflicts. Having a big construction area isn't specifically better, but it's somthing in the spot, since I'll be removing the other one soon.
=> Turns the hastily maintified area into a large construction zone

code/modules/overmap/ships/engines/gas_thruster.dm
only applies to mass
not pressure
mass is less cheesable than pressure. slightly.
dear god why do thrusters not use proper impulse equations yet.
:cl:
tweak: gas thruster efficiency +
/:cl:
=> decreases sqrt() penalty for gas impulse thrusters

code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/_giant_spider.dm, code/modules/mob/living/simple_mob/subtypes/animal/space/alien.dm, code/modules/mob/living/simple_mob/subtypes/horror/horror .dm, code/modules/mob/living/simple_mob/subtypes/humanoid/humanoid.dm, code/modules/mob/living/simple_mob/subtypes/occult/creature.dm, code/modules/mob/living/simple_mob/subtypes/occult/faithless.dm, code/modules/mob/living/simple_mob/subtypes/vore/corrupt_hounds.dm
Apparently some months ago, changes from Virgo were ported that meant that the Taser_Kill var was be default enabled. This meant that tasers became incredibly effective at killing a ton of different mobs that they probably shouldn't be. This PR makes sure Taser Kill is disabled for mobs it should have never been enabled with to begin with, since it frankly stupid that a taser more effective than lethal weapons uinder certain circumstances.
:cl:
tweak: Tasers no longer damage the following mobs: 
1. All Humanoids including Mercs, Pirates, and Cultists.
2. Corrupt Hounds because they are Machines
3. Giant Spiders: since they seem like it wouldn't effect them
4. Xenomorph Simple Mobs: Because its a Xenomorph
5. Horror Mobs: Flesh Monstrosities Should not be Tased to Death
6. Horror Adjacent …
=> Tasers Should Not be More Effective Than Guns at Killing

code/modules/mob/living/carbon/human/human_powers.dm, code/modules/mob/living/carbon/human/species/station/station_special.dm
Changes:
- Each morph ability (except for the one that changes your accent) can now be used on yourself OR a target.
- Breath morph removes poison gasses
- Temperature morph adds significantly higher (lower) high / low temp tolerances for cold / hot blooded
- Choosing to add one to someone else has a pretty high chance of giving them a random virus. They ARE a virus themselves, after all. Maybe don't let them shove themselves literally inside of your bloodstream.
- (Unrelated to PR, non-issue to revert) adds 5 languages to Xenochimeras. Seriously, the adaptive multi-species chimeroid only having two?  This makes them, I believe, on-par with Proteans in known language capacity.
- (Unrelated to PR, non-issue to revert) Changes their max age to 200. No lore iteration we have or do use has a …
=> Fixes and improves Xenochimera morph abilities, makes them have 5 alt languages, additional minor tweaks

code/game/objects/items/storage/secure.dm, code/game/objects/structures/crates_lockers/crates.dm, code/modules/client/preference_setup/loadout/loadout_utility.dm
- Adds wrench interactions to the large bin, Triumph people rejoice.
- Adds a portable secure briefcase to loadout. It fits into satchels now! Very specific number of people who were bothered by this rejoice! (It's just me.)
- You can move the bins that are everywhere on a certain map.
- You can have a keycode-secure personal container in your loadout that fits into your satchel.
:cl:
fix: Large bins can now be wrenched
add: a portable version of the secure briefcase, replacing the current one in loadout.
/:cl:
=> Makes the trash bin wrenchable, adds a portable secure briefcase to loadout, 

code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/species/species.dm
that's it, after this PR you can now give Tajarans Jaunt or some shit, or make your own / convert other abilities to spells.
WAY WAY WAY better technical and mechanical foundation for any species ability that you'd like to be active / cooldown based
:cl:
tweak:species spells can now be a thing
/:cl:
=> adds species specific spell compatibility

_maps/map_levels/140x140/lavaland.dmm
Miners always have to burry jerry if they dont safe him the moment the round begins, this prevents that.
:cl:
add: Added a curtain to the lavaland base bar, to protect jerry.
/:cl:
=> Adds a closed curtain to the lavaland bar to save jerry

code/modules/clothing/chameleon.dm
fix
:cl:
fix: masquarade clothing now works with chameleon kits.
/:cl:
=> chameleon clothing now works properly for default_worn_icon

code/_onclick/hud/screen_objects.dm, code/game/dna/dna2.dm, code/game/dna/dna2_helpers.dm, code/modules/mob/living/carbon/human/human_powers.dm, code/modules/mob/living/carbon/human/species/outsider/replicant.dm, code/modules/mob/living/carbon/human/species/species_shapeshift.dm, code/modules/mob/living/carbon/human/species/station/prometheans.dm, code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm, code/modules/mob/living/carbon/human/species/station/station_special.dm, code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm
A biit of a blender here. If requested, I can remove, or split, any parts.
- Makes commune a bit less concerning, though the delay may be too harsh if genetics comes back (depends on distance, up to 90 seconds if they're off somewhere, 30 if they're far away on-station. Make that message count, I suppose)
- Standardizes xenochimeras, however I couldn't add 'change body shape', it kept needing forced icon updates.
- The species that goes schizo from damage now heals passively faster. I think that's a natural expectation.
- Proteans got their languages back, as you'd expect them to.
:cl:
tweak: Xenochimeras now heal passively
add: 2 more extra languages to Proteans
/:cl:
=> Moves Xenochimera to /shapeshifter/, gives them passive regen akin to prommies, reworks commune verb, gives proteans 2 more languages

code/modules/catalogue/cataloguer.dm
makes explo not suffer from splitting up as much (they already do enough)
makes it so you don't magically get points from scans on other zlevels too
:cl:
tweak: cataloguers now consider everyone on their zlevels for sharing
/:cl:
=> cataloguers now have unlimited sharing range if someone is on the same zlevel as sharers

code/game/objects/structures/crates_lockers/closets.dm
fixes being able to start welding, open a locker, to have it welded such that closing it immediately welds whoever's on the tile inside.
=> fixes locker welding race condition

code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
Allows dogborgs to boop mobs/people and to sniff contents of tanks.
Some people in the past claimed that the Boop module was bugged because it could not check pipes or tanks. This partially restores the Boop module's abilities by making it able to check tanks, but not making it able to check pipes as to not just make it a better analyzer, leaving the ability to check pipes to the Engiborg.
In addition, Borgs can now use their Boop module to, shockingly, boop people. Along with a cute sound.
:cl:
add: Boop module can now scan tanks
add: Boop module can now boop people and simplemobs
/:cl:
Boop module used on a human. Small text message (not in red, not an attack) and a little sound is played.
Boop module used on a bottle with a chemical. No changes to prior function.
Boop module used on a …
=> Dogborg boop enabled

code/modules/mob/living/silicon/robot/drone/drone_items.dm, code/modules/surgery/implant.dm
Allows Mediborgs (both dogborg and non-dogborg) to install NIFs and other implants.
Mediborgs already had the option to pick up NIFs, but were never able to install them. This lead to situations where Mediborgs, who were able to do other surgery just fine, were not able to install implants like the NIF, and lead to awkward moments. These days are now days of the past.
:cl:
add: Enables Borgs to install NIFs and Implants
add: Enables Borgs to pick up Implants with the Medical Gripper
/:cl:
=> Mediborg NIF install

code/modules/mob/living/silicon/robot/emote.dm
Adds *flip, *dwoop, and *scary to the emotes for cyborgs/robots/drones, with focusing (like *glare-name).
Has all been tested on a local server, no issues.
The borgs get the new synth noises, and dogs can now roll over.
:cl:
add: *flip emote
add: *dwoop emote
add: *flip emote
add: A random space in the dm that literally does nothing.
/:cl:
=> Dogborg, tell me the weather.

code/modules/mob/living/carbon/human/species/outsider/celestials.dm
stops annoying thing 
that was annoying wasn't it
:cl:
tweak:Auril / Dremachir no longer have their species languages set as default
/:cl:
=> Changes Dremachir and Auril default languages to galcom

code/modules/atmospherics/pipes/pipe_base.dm
tl;dr
101 occludes from range() and view()
sane codebases like /tg/ use 100 because there's no reason to occlude from range() and view().
if someone doesn't check for hidden pipes in range(), that's their issue. not the goddamn pipes.
don't wanton throw invisibility 101 on things.
=> [testmerge first] pipes hiding now use 100 invisibility instead of 101

code/modules/projectiles/gun.dm
1. _Enables the illegal extraction of firing pins._
1. Currently, firing pins can only be overwritten by other pins. There is no way to extract extant pins with bootleg modification. Although I can see this being rife with abuse potential, I also believe it frees up a lot of choice and experimentation potential for the players. I'm willing to revisit this to tweak the RNG weights on failure and success chances, after further testing.
:cl:
add: Adds the ability to extract firing pins from guns.
/:cl:
=> Allows The Illegal Removal of Firing Pins From Guns Without Destroying Them (Not Clickbait)

code/modules/mob/hear_say.dm
tl;dr
you can now do
`thing++` without the regex triggering
useful if you're shitposting code huh
=> [testmerge first] adjusts say emphasis regex .*? --> .+?

code/datums/outfits/jobs/cargo.dm, code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Literally what it says on the tin (also adds one to the QM locker in case)
This is honestly a QOL thing for QM, since the mining radio has shortwave, and is the only way to communicate on mining zones such as the belt or the Magmatic Rift. Since the QM prior could just steal one of these radios out of the lockers, it's not really even a balance change.
:cl:
add: Mining headset to QM locker
tweak: Replaced QM cargo headset with a mining headset
/:cl:
=> Gives QM a mining radio

code/__HELPERS/text.dm
the sanatize proc checks how many linebreaks were used and does not replace them as long as its less than 7
Allows to make emotes more readable, especially if you are text walling each other.
:cl:
add: Adds up to 6 linebreaks per emote, works both for subtle and me.
code: sanatize() proc now allows up to 6 linebreaks per message before removeing them all.
/:cl:
=> Linebreak your emotes up to 6 times now

code/modules/vore/eating/living_vr.dm, code/modules/vore/eating/vore_vr.dm, code/modules/vore/eating/vorepanel_vr.dm, code/modules/vore/fluffstuff/guns/nsfw.dm
1. **Makes the Stripper Gun a Pref Toggle.**
2. **Changes Size Gun and Stripper Gun Toggles to Off by Default.**
1. _Players are being made uncomfortable by the function and presence of stripper guns. There are further meta implications for this kind of tech being readily available. I am making Stripper beams a pref, just like size beams have become._
2. _I am making both of these functions Off by default due to the revelation that the majority of the playerbase does not know the Vore panel held options to toggle these. The players that want these functions are more likely to toggle them on, and enabling it is trivial to do._
:cl:
tweak: Stripper beams are now a pref.
tweak: Stripper and Size Mechanics are now toggled to off by default.
/:cl:
=> Makes the Stripper Gun a Pref, a la Size Guns - Defaults Both to Off

code/game/jobs/job/science.dm, code/game/objects/items/weapons/id cards/station_ids.dm
Yes, they keep the spiffy gear
Also removes hydroponics access from them.
We don't nearly have the playercount or map design (I hate triumph) to justify separating two subdepartments of science into subroles.
They're literally the same thing because god knows we're too much of cowards to turn on minimal access.
Furthermore the alt title bloat is insane, why do we need 3 alt titles each of the two subdepartment roles?? Bruh.
Science max pop bumped to 7 to compensate, with 5 spawn positions. 
:cl:
del: Xenobotanist and Xenobiologist have been demoted to Scientist alt titles.
/:cl:
=> Demotes xenobotanist/xenobiologist to alt titles of scientist

code/game/gamemodes/game_mode.dm
:cl:
fix: The endcard now shows how many people left the station.
/:cl:
=> Fixes the endcard and removes unwanted sleeps

code/modules/atmospherics/components/binary_devices/passive_gate.dm, code/modules/atmospherics/components/binary_devices/pump.dm
:cl:
tweak: Allows for pumps and pressure regs to be renamed with a pen.
/:cl:
=> Makes pumps and pressure regs renamable with a pen

code/modules/organs/robolimbs.dm
Just makes them be a subtype and share the same spriteset. You can make the spooky eyes using markings, anyway. Black-faced sprites aren't colorable /at all/, which is kinda lame, given Skrells aren't supposed to be tar-black, thus why would the vey-med version of them be?
Just some sprite cleanup. That's all.
:cl:
tweak: Skrell Vey-med prosthetics are now colorable
/:cl:
=> Cleans up vey-med skrell prosthetics

code/game/objects/structures/crates_lockers/closets/secure/cargo.dm, maps/nsv_triumph/lavaland.dm
1. *Increases the time between storms on Lava Land.*
2. *Gives each mining locker one free survival capsule.*
1. _The increase in storm lengths requires a touch of balancing._
2. _There should be one per miner, as was the old way._
:cl:
tweak: Adjusts clear sky time on Lavaland and gives miners a survival capsule by default.
/:cl:
=> Buffs Clear Sky Time on Surt

code/game/machinery/suit_storage/suit_storage_prepared.dm
:cl:
fix: Fixed solar space suits not being able to be refitted
/:cl:
=> loads the ugly voidsuits into suit storage insteadof space suits

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Makes drinks, which previously didn't have names and descriptions, defaulting to "Ethanol" their proper names and descriptions when put into a metamorphic glass.
I went through all of /drinks/ and /ethanol/ subtypes, but might've missed something nonetheless
Removes a giant annoyance.
:cl:
fix: Fixes some drinks defaulting to Ethanol when put into metamorphic glasses
/:cl:
=> Gives default-named glasses names and descriptions

_maps/map_files/triumph/triumph-01-deck1.dmm, _maps/map_files/triumph/triumph-02-deck2.dmm, _maps/map_files/triumph/triumph-03-deck3.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm
1. *Removes the corrupt drones from maint and returns some mimics.*
2. *Adds a Community Theater where the Vacant Store is.*
1. _This was a ridiculous substitution. I'm reversing it._
2. _This store is never used for what it's supposed to be used for. I've made it a small theater now._
:cl:
add: Adds mimics.
del: Removes all corrupt maint drone spawns.
add: Adds a Community Theater.
/:cl:
=> Anti-Drone Map Edit, Also Adds Community Theater

code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm, code/modules/vore/eating/bellymodes_vr.dm
With synths being objectively worse in terms of nutrition gain, I gave them the same vore nutrition max, as well as allowing people with succubus drain to drain synths
Solarmoffs enjoy!
Powercreeps the synths. Literally.
:cl:
add: Gave solarmoffs the ability to drain synths
/:cl:
=> Solarmoff draining and synth nutrition

code/modules/client/preference_setup/loadout/loadout_donator.dm, code/modules/clothing/ears/ears.dm, code/modules/clothing/ears/speakrock.dm, vorestation.dme
Speak 'n' Rock headsets are headphones and Radio Headsets in one. Currently, they're not accessable via loadout. I have re-made my donator item as a subtype of this, to powercreep it a little later. That code is a lot more difficult then this is.
Speaking of difficult coding, Sillycons accidentally didn't adjust a thing, and all of the single-eared musical note headphones he craved to have on without sacrificing the radio earpiece where giving top-tier flashbang protection. this makes it so that they give none, as a stop-gap until further in-depth discussion can happen on the subject. ((Earmuffs are unaffected, and still give good flashbang protection))
Better code, and a small bugfix in the affected areas while I'm at it. Technically some new content, but I haven't added it to the …
=> Creates new item type, cleans up code, fixes unintentional buff

code/modules/research/rdconsole.dm
Does what it says on the tin.
This allows us to place research machines further apart, while still being short enough to not interfere with robotics or elsewhere.
:cl:
tweak: RD console sync range 3 --> 5
/:cl:
=> Changes RD console sync range from 3 to 5 tiles

code/modules/mob/living/silicon/robot/drone/drone.dm, code/modules/mob/living/silicon/robot/drone/drone_vr.dm, vorestation.dme
You feel kinda silly talking to a drone that turns out to have ghosted even before you found it.
:cl:
fix: Fixed Maintdrones not indicating that they have been abandond when the player inside ghosts.
/:cl:
=> Maint drones now die if you ghost from them, no more pseudo alive drones!

code/modules/research/designs/HUDs.dm
1. *Removes Gravitons from R&D Protolathe list.*
1. _Gravitons are just kinda ridiculous. They disrupt events. They disrupt Overmap flight. They're essentially wallhack goggles that trivialize encounters and daily functions. Their primary justification - ore detection, will be refactored shortly._
:cl:
del: Removes graviton goggles from R&D printer.
/:cl:
=> Removes Gravitons from R&D Protolathe

code/controllers/subsystems/mapping/_mapping.dm, code/game/gamemodes/game_mode.dm
to allow people to see what engine loaded instead of having to observe and go back to the lobby because its again one of the usuall 4, smh why cant we have cool engines
:cl:
Add: Adds engine type info to round info
/:cl:
=> The gamemode announcement at round start now tells what engine is used, additional to the gamemode

code/game/turfs/simulated/water.dm, code/modules/mob/living/carbon/human/species/station/diona.dm, code/modules/mob/living/carbon/human/species/station/station.dm, code/modules/mob/living/carbon/human/species/station/teshari.dm
1. *Fixes Water Breathing not returning correctly.*
2. *Gives Akula Water Movement Value.*
3. *Removes Links to Vore Wiki from Multiple Races. (Soft WIP)*
1. _Water Breathing was generating a unique air mix, but wasn't returning it on proc._
2. _Skrell have a Water Movement of -3. For some reason Akula had none. I've given them -4._
3. _These are vestigial, and provide new players with incorrect data. They have been replaced where appropriate. I have undoubtedly missed some, so this is a soft WIP, but the integrity of the PR is not contingent upon its completion._
:cl:
add: Adds Water Movement to Akula.
del: Removes vestigial Vore Wiki links.
fix: Fixes Water Breathing.
/:cl:
=> Fixes Water Breathing Trait, Gives Akula Water Movement, and Removes Vore Wiki Links from Race Blurbs

code/modules/clothing/suits/aliens/teshari.dm
Fixes an oversight with the Teshari Hooded Cloak
It was rather obviously an oversight that the Hood part of the Hooded Cloak was not given cold protection. This PR fixes that.
:cl:
tweak: Added Cold Protection to the Teshari Hooded Cloak's Hood
/:cl:
=> Teshari Wintercloak Update

code/modules/mob/living/carbon/human/species/station/traits/neutral.dm, code/modules/mob/living/carbon/human/species/station/traits/positive.dm
Reduces the trait cost for sizeshift to 2.
Since using size mechanics for combat and such is against the rules anyway, I don't think this trait should cost the equivalent of haste. I wanted to reduce it down to 1 point, but 2 seems much more agreeable.
:cl:
balance: reduced sizeshift trait cost to 2
/:cl:
=> Reduces sizeshift trait cost to 2

code/controllers/configuration/entries/game_options.dm, code/controllers/configuration_old/configuration.dm, code/modules/security levels/security levels.dm, config/entries/game_options.txt
The alert descriptions displayed whenever the alert level changes have been moved to `game_options.txt` instead of being hardcoded, allowing them to be modified much more easily.
_The current settings/defaults are the descriptions as-is, however, there are some discrepancies from the wiki so it'd probably be a good idea to change that before adding them in._
Easier administration.
:cl:
server: Alert descriptions have been moved to game_options.txt.
/:cl:
=> Change alert descriptions to be config options

code/modules/client/verbs/ooc.dm, code/modules/mob/new_player/login.dm
Adds the ship's current alert status to the MOTD, shown either when someone logs in or if they use the MOTD verb. Since there is no pending emergency for code green and its description is a "down to" text, there is no description shown for it. All others use the "up to" text for the relevant alert level.
Pictures of each alert level as shown:
Provides a useful glance of the current alert level. Since it is shown on the hub and (as I am told) on the join screen I don't think it provides any ick ock or anything of that sort.
:cl:
add: The alert status is now shown when logging in and when displaying the MOTD.
/:cl:
=> Add alert status to MOTD

code/game/turfs/simulated/wall_attacks.dm
Wall actions are now based on intent. If you click a wall on help intent, nothing happens. On disarm and grab intents, you will push it. On harm intent you will punch it (which will hurt yourself if the wall isn't weakened).
Some people like yours truly like to rotate our character by clicking in the direction that we want to face. If we end up clicking on an adjacent wall we push it for no reason which just looks silly. This fixes that.
:cl:
tweak: You will no longer push a wall on help intent.
tweak: On harm intent, you will punch a wall instead of pushing it.
/:cl:
=> Wall actions are based on intent

code/game/objects/structures/crates_lockers/closets/secure/security.dm
1. *Removes the Energy Gun from the HoP Locker.*
1. _It was brought to my attention that the HoP locker has two guns, thanks to a VORE edit that was presumably not implemented properly. I've removed the baseline e-gun, and left the holdout in place, as that seems more suitable for the role._
:cl:
del: Removes the egun in the HoP locker.
/:cl:
=> Nerfs the HoP

code/modules/projectiles/guns/projectile/shotgun.dm
The warden's shotgun fits on the back slot now, because the sprite for it has a sling and so you should be able to wear it without having a vest on.
Makes sense to be able to carry a long gun with a sling on your back without needing an unrelated vest/jacket.
:cl:
tweak: The warden's shotgun can now be stored on your back.
/:cl:
=> Warden's shotgun can go on the back slot

code/modules/mob/living/carbon/human/species/station/xenomorph_hybrids/hybrid_resin.dm
:cl:
fix: Fixes xenohybrids being unable to buckle anyone into their nests
/:cl:
=> fixes resin nests being not buckleable

code/game/objects/items.dm, code/game/objects/items/weapons/material/twohanded.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/energy/modular/gunframes.dm, code/modules/projectiles/guns/energy/nuclear.dm, code/modules/projectiles/guns/energy/particle.dm, code/modules/projectiles/guns/energy/phase.dm, code/modules/projectiles/guns/energy/pulse.dm, code/modules/projectiles/guns/energy/special.dm, code/modules/projectiles/guns/launcher/grenade_launcher.dm, code/modules/projectiles/guns/launcher/pneumatic.dm, code/modules/projectiles/guns/magnetic/magnetic_railgun.dm, code/modules/projectiles/guns/modular_guns.dm, code/modules/projectiles/guns/projectile/automatic.dm, code/modules/projectiles/guns/projectile/boltaction.dm, code/modules/projectiles/guns/projectile/contender.dm, code/modules/projectiles/guns/projectile/rocket.dm, code/modules/projectiles/guns/projectile/semiauto.dm, code/modules/projectiles/guns/projectile/shotgun.dm, code/modules/projectiles/guns/projectile/sniper.dm, code/modules/projectiles/guns/vox.dm
Teshari are now able to use some two-handed, large-sized weapons despite being small. Since their entire species is built around being small it isn't that fair to exclude them from wielding most non-pistol weapons, so they have an exception built in to the usual "if small and gun large can't two-hand it".
**This PR is for a code bounty from @VailTheWolf.**
<details>
<summary>A full list of BLACKLISTED melee weapons</summary>
Anything not in this list is two-handable by teshari.
- Sledgehammer
- Fire axe
</details>
<details>
<summary>A full list of BLACKLISTED ranged weapons</summary>
Anything not in this list is two-handable by teshari. Categorized (mostly) by file.
- Modular cannon
- Modular energy cannon
- Advanced modular energy gun
- Dark matter gun
- Sound cannon
- Laser rifle
- …
=> [BOUNTY] Teshari can now use some two-handed weapons

code/modules/client/preference_setup/vore/04_autohiss.dm, code/modules/mob/living/autohiss.dm, code/modules/mob/living/carbon/human/species/station/station_special.dm
Refactors the autohiss file, now the maps are stored in their own datums and not on the species. This is done because now the species you're playing as and the species you autohiss as might not be the same anymore!
You can once again change your autohiss type with the new "Toggle Autohiss" verb in the OOC tab, but you can now use "Toggle Autohiss Type" to change what species you autohiss ass. Playing as a custom lizard but want to autohiss as an unathi? There you go. Catgirl human that wants to speak like a tajaran? Bam.
This also comes with its own preferences selection. **Just like with the old autohiss, changes made mid-round will not be saved for future rounds.**
Custom species ahoy, and it can't hurt to be able to change your autohissing midround if something happens.
:cl:
add: …
=> Add back autohiss verbs, add type discrimination

code/__DEFINES/mobs.dm, code/modules/clothing/clothing.dm, code/modules/mob/living/carbon/human/species/station/human_subspecies.dm
:cl:
fix: fixed human subspecies not being able to wear human voidsuits
/:cl:
=> Allows grav and space adapted humans to wear standard human voidsuits

code/game/atoms.dm
Previously, visible messages would always show to everyone in the viewport (and they still do). But now there's an argument that you can specify if you want that range to be shorter/longer.
Obviously, this needs implementation in places that need it which is outside the scope of this PR.
Self-explanatory
N/A
=> Adds range as an argument to visible message

code/game/jobs/job/exploration.dm
Reverts 'Containment Specialist' as an exploration job title
This is a good first test PR, but also 'containment specialist' is a weird-as-hell exploration title that no one uses, everyone and their mother finds weird, and several headmins wanted to revert but forgot to.
:cl:
del: Containment Specialist Exploration alt job title
/:cl:
=> Removes 'Containment Specialist' as an exploration job title

code/modules/mob/living/carbon/human/life.dm
There is a bug where despite spawning with normal nutrition amounts, you'll get the HUD icon for being overfed anyway. I think it was due to a problem with the max_nutrition value so the value was hardcoded instead. (It's the same 450 but when I tested it it didn't break the hud anymore.)
bugfix
:cl:
fix: Potentially fixed an error where you would spawn with the "overfed" nutrition icon despite having normal nutrition amounts.
/:cl:
=> Fix nutrition I think

code/game/objects/items/weapons/grenades/explosive.dm
1. *Nerfs Tyrmalin Mining Charge and Large Tyrmalin Mining Charge explosion sizes from 16 and 20 to 1 and 2, respectively.*
1. _It turns out when I made these I misread portions of the math, resulting in explosions that surpass the maxcap._
:cl:
fix: Fixes explosion values.
/:cl:
=> Fixes Bad Math in Tyrmalin Mining Code

_maps/map_files/triumph/triumph-01-deck1.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm, code/game/objects/items/weapons/manuals.dm
This brings up engine setup guides up to date with the wiki. It also ensures that the engineering bay (and library) have the guides needed to function.
Gives the library some fun new books on SPESS LAW. Not coleslaw.
The R-UST guide literally ended up with a delam.
:cl:
balance: Nerfs the R-UST Operating Manual. It no longer causes an EMP blast strong enough to murder any robot on-site.
fix: Brought the other two manuals up-to-date with the wiki. They should be clearer and easier to follow now.
fix: Adds CorpReg, SOP, and Chain of Command books to the proper bookshelf. They are presently empty 😩 
/:cl:
=> I am the Globglogabgalab (Engineering Buff 2.0)

code/modules/mob/living/carbon/human/species/station/traits/neutral.dm, code/modules/reagents/reagent_containers/blood_pack_vr.dm
Introduces the all-new Vampire/Vetalan trait. This is a merger of... Bloodsucker, major darksight, numbing bites, antiseptic saliva, major burn weakness, and photosensitivity.
Patches bloodpacks to not allow literally anyone with hands to apply it to their face to gain nutrients. Ex3-378 does not have a mouth and runs on electricity. Ex3-378 would've been able to bite the bloodpack and drain its blood to gain electricity.
New trait is stage one in reworking the Vetalan species.
That bloodpack was one hell of a drug.
:cl:
add: Introduces the all-new Vampire/Vetalan trait. This is a merger of bloodsucker, major darksight, numbing bites, antiseptic saliva, major burn weakness, and photosensitivity.
fix: Patches bloodpacks to not allow literally anyone with hands to apply it to their face to …
=> new vampire trait + why could literally anyone with hands drain IV packs and get nutrients from it

code/modules/mob/living/silicon/robot/robot_vr.dm
Makes sci-hounds have a visible overlay when they have a xeno-tazer equipped, maybe also regular sci borgs, but I do not believe they have proper overlays set up.
now Hawke can know when he's about to get shot to shit.
:cl:
fix: added borg xeno-tazer to the borg overlay system
/:cl:
=> Adds a gun overlay for Science-Hounds (and maybe science borgs?)

code/_globalvars/lists/misc.dm, code/controllers/configuration/entries/general.dm, code/game/world.dm, config/config.txt, config/entries/hub.txt, config/strings/server_taglines.txt
This PR is largely a mirror of Citadel-Station-13/Citadel-Station-13#15610 , though this PR also brings RP's hub description up to parity with that of Main.
The popcap display and change to only display active players are both missing from this port, though, as RP lacks equivalent procs and config options. However, this does make some changes that're new for RP. Notably, the map's shortname is now displayed in the footer like map names are on Main, the security level's displayed there, and the display of the active gamemode has been axed.
All other changes are more or less the same as the above PR. The station name is now hidden if it's the same as the default, the community name and link can now be modified via the config, there's now an 18+ tag at all times, the tagline can be …
=> Hub refresh 2022 - Cleans up hub desc code, adds some more config options, and more!

_maps/map_files/triumph/triumph-04-deck4.dmm
1. *Reduces Armory ion rifles from 2 to 1.*
2. *Reduces Armory laser rifles from 4 to 2.*
3. *Adds two lethal gunboxes to Red Armory.*
4. *Removes Red Armory cell charger and adds a new wall charger.*
1. _Tentative rebalancing. May not keep this weight._
2. _As the above._
3. _These were meant to be mapped in, but never were._
4. _Just QOL/space rearranging._
:cl:
tweak: Tweaks weapon allotment in the Red Armory.
/:cl:
=> Tweaks Red Armory Weaponry

code/defines/obj/weapon.dm, code/modules/clothing/under/accessories/holster.dm
Lets you put the spraybottle, soap, bikehorn and cardboard tube in the machete holster like you can with the regular holster.
:cl:
tweak: The machete scabbard now fits the cardboard tube, soap, spray bottle and bikehorn like the regular holster
/:cl:
=> Holster lifehacks

code/_rendering/parallax/parallax_holder.dm, code/modules/client/preference_setup/global/setting_datums.dm
turns out parallax is really FPS-damaging for people with bad laptops
they can now disable it.
=> adds a parallax disable option

code/modules/integrated_electronics/core/assemblies.dm, code/modules/integrated_electronics/subtypes/memory.dm
Fixes 3 long standing bugs. Memory circuits failed due to two separate bugs, both simple mistakes. Power cells had no way of being removed from assemblies. The proposed change is to use crowbars to keep it in line with removing cells from other devices and move opening and closing assemblies to a screwdriver action.
Cohesion. No more unga opening.
:cl:
tweak: Screwdrivers required for opening.
fix: Memory circuits and cell removal
/:cl:
=> Bugfix: IC memory circuits & power cells

code/game/atoms.dm
turns out float precision isn't a thing here
=> fixes relative layering for mobs

.github/workflows/ci_suite.yml
Title. This allows the CI to run on the dev-atlas branch, for both pushes and PRs
=> adds dev-atlas to ci branches

code/modules/mob/living/bot/medibot.dm
this is annoying because it doesn't fix being unable to make it while inside a closet without having it pop out but not until storage refactor i guess
=> fixes medibot construction not using get_turf

code/modules/organs/robolimbs.dm
title
don't ask but makes the veymed skrell usable
why not have regular veymed available to all species instead?
uhh idk don't ask omg look over there is that ICON LAYER CODE? YOU BETTER LOOK OVER THERE.
:cl:
tweak:veymed skrell prosthetics usable again
/:cl:
=> makes veymed skrell prosthetics use the same spriteset as regular veymed

code/datums/perspective.dm, code/modules/client/client_procs.dm, code/modules/mob/perspective.dm, code/modules/overmap/ships/computers/ship.dm
changing perspective is expensive and people reset_perspective() for no reason all the time
so i fixed it by optimizing it to update_perspective()
problem:
update_perspective() calls reset_perspective() if it detects something's wrong, and in this case, there was **another** bug that's going on that triggers this.
this stops that.
=> (probably) fixes an infinite loop from an """optimization""" in my perspectives code and fixes some ""edge cases""

code/game/objects/items/devices/defib.dm
whoever made perfect triggered-twohanding from /tg/code into automatic wielding should not be allowed to touch code ever again
words cannot describe how utterly deranged it is to make twohanding automatic when we all know how well our inventory code works
=> monkey patches defibs to work again until we can refactor twohanding 

code/__DEFINES/text.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/human/examine.dm
Helper added for inserting 'lookitem' hrefs, updated examine code.
Get to see those sweet, sweet custom item descs without having to strip first. Also will probably cause no end of issues with UI stuff.
add: on examine items are href'd with lookitem.
/:cl:
=> 'lookitem' href to examine text.

code/modules/power/singularity/collector.dm
since mappers INSIST on building reactors like it's a game of [forts](https://store.steampowered.com/app/410900/Forts/), let's just make collectors non-dense while turned off
=> streamlines the SECOND most obnoxious part of engine setup

code/modules/maps/rift/levels/_lythios43c.dm, maps/rift/rift_lythios-43c.dm
why this is good for the game:
makes the map nicely lethal without needing literal spacesuits.
if we want to run any kind of gameplay we can't have the tether issue of one breach ruining the atmos for an hour.
=> raises map temp to -50 to -20C instead of -170C

code/__HELPERS/vfx/shake_camera.dm, code/game/objects/items/devices/communicator/messaging.dm, code/modules/cargo/supplypacks/materials.dm, code/modules/client/preference_setup/vore/02_size.dm, tgui/packages/tgui/interfaces/SeedStorage.js
1. shake_camera() : Beginning of loop skipped, causing animation to crash out.
2. IPv2 circuits : In messages circuit.name is always displayed as sender.
3. Wood crates : Overwritten by hardwood.
4. Persistent weight : Value returns to default when at either extreme at round end.
5. Seed storage : Accidental disposal of seeds.
1. Trigger value set to 1 in line with initial loop value.
2. circuit.displayed_name is used, allowing for custom sender names.
3. Hardwood crates have correct path.
4. Refactor sanitize_integer into the proc to avoid double processing in the default var.
5. Button changed to Button.Confrim.
fix: Camera shaking, IPv2 circuits, wood supply crates, persistent weight and seed storage emergency disposal.
/:cl:
=> Five misc fixes

maps/rift/rift_defines.dm
1. *Changes the name of the station from Raytheon to Demeter.*
1. _Naming the overhead station after an extant military contractor stoked some discontent among the staff team. Although I have no horse in that particular race, it is worthwhile to change the name of the vessel. This is the structural equivalent of my prior issues with Sergal naming conventions, and I am correcting it for that reason. The current staff pick for a rename is Demeter. This may change._
:cl:
tweak: Changes name of CentCom Station.
/:cl:
=> Renames CentCom's Orbital Station

code/modules/mob/hear_say.dm
:cl:
fix: you can tilde again
/:cl:
=> changes regex to ~~ instead of ~ because tildeposters somehow still need rights

code/game/objects/effects/traps.dm
Gives chat and inspection feedback to pop-up traps once they are broken. Adds a name and a description to some traps.
This gives any dungeon dwelling people feedback about the state of hidden traps if they are already trying to disarm them. This also removes the annoying "Contact admins" debug message on inspection of properly mapped traps.
:cl:
tweak: pop-up trap feedback
/:cl:
=> Clarifies Pop-Up Traps

code/__HELPERS/atom_movables.dm, code/modules/mob/mob.dm
tin
this makes zero sense
if you wanna be toxic and spam-click examine on the toxin bar when someone you don't like you should do it before we merge this
for the latter, well, it'd really suck if you could spot people examining their own backpack gear and know what name it is on a "stealth gameplay" basis.
:cl:
fix: visible examines showing for atoms not in the world
fix: visible examines showing for atoms within oneself
/:cl:
=> you can no longer see people examining UI buttons + things inside themselves/carried by them

_maps/map_files/rift/rift-04-surface1.dmm
Renovates the maintenance bar into a sort of jazz lounge
I didn't particularly like the old maint bar, and at the very least I wanted to remove the floor mimic that made it borderline unusable unless you could bribe Sec to clear it
:cl:
tweak: Renovated the Maint bar
/:cl:
=> Renovates Maint Bar

code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
Gives Xeno-Hybrids the sonar ability
Xeno-Hybrids are an eyeless race, they see through vibrations picked up by their dorsal spines on their back. Sonar for them just makes sense.
:cl:
tweak: Xeno-Hybrids not having Sonar
/:cl:
=> Gives Xeno-Hybrids Sonar

code/modules/mob/living/carbon/human/human.dm, code/modules/species/station/xenomorph_hybrids/hybrid_abilities.dm, code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
:cl:
tweak: Tweaked Xenohybrids lose the healing verb, because its passive now
/:cl:
=> make xenohybrid heal passive instead of active(effect stays same)

code/modules/clothing/clothing_accessories.dm
might result in unspecified behavior but we'll see, worst case we throw a "direct" flag onto get_equipped_items
=> accessories are now included in inventory enumeration

code/modules/mob/inventory/items.dm
people keep doing this historically and it will result in issues.
=> adds a warning about assuming location-change precedence on dropped()

code/game/objects/effects/effect_system.dm
bad practice to do the latter, the former isn't much better but it's cheap when the last fix pr to fix the null state is done.
=> just nulls out fading ion trails instead of setting them to an invalid state

code/modules/paperwork/paper.dm
:cl:
fix: fixed burned paper spawning ash in the wrong spot
/:cl:
=> Paper drops ash on the floor when burned

code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/life.dm
:cl:
fix: fixed radiation glow on creatures
/:cl:
=> Fixes Prometheans glow

code/controllers/subsystem/fail2topic.dm
No changelog due to no player-facing changes. This disables the ability for admins to call the procs that handle firewall blacklisting in fail2topic, patching a vulnerability in the process.
=> [S] Fixes a small vulnerability in fail2topic

code/controllers/subsystem/ai.dm
:cl:
fix: fixed people in mechs not loading the z they are on
/:cl:
=> Fixes people in mechs not loading the z they're on

code/modules/jobs/outfit.dm
if we don't spawn an ID for some reason we should probably not runtime
=> sanity check for job equip id proc

code/game/machinery/vending.dm
Adds phase pistols to SecTech vendors.
Security officers will have easy access to a basic gun to deal with spiders infesting arrivals without needing a boss around to open the armory.
:cl:
add: Added phase pistols to SecTech
/:cl:
=> Adds phase pistols to the security vendor

code/modules/cargo/supplypacks/contraband.dm
Fuck you
Renamed Surlplus military weapons into Misplaced Rifle Crate, and gives the crate an access lock
It's propably not, but none of the Maintainers told me not to do it, so here's a PR. Kiss kiss.
:cl:
Please review my PR
:cl:
=> Cargonia, but with less weapons

_maps/map_files/rift/rift-06-surface3.dmm
No More Phoron spewing vents
Fixes the pipes on the Civ shuttle so they don't spew phoron in your face.
:cl:
fix: Vents on the civ shuttle cycle air rather than phoron. 
/:cl:
=> Fixes Civ Shuttle

code/__HELPERS/global_lists.dm
1. *Swaps RIG and Duffle Bag names in interface.*
1. _This was so easy to do, there's no excuse for the bug taking months to fix. All you had to do was look in-game, see the words "Duffle Bag" and "RIG" were swapped. Then you just had to search for the phrase "Duffle Bag". It's literally right at the bottom of the results. You can see where the two words are swapped in the load order. Then you just swap the two words. That's it. That's how easy it was to fix the bug you've all been pinging about for months. Unacceptable._
:cl:
fix: Fixes bad naming on RIG and Duffle Bag selections.
/:cl:
=> fixes rig/dufflebag spawning issues

code/modules/mob/living/butchering.dm, code/modules/mob/living/organs.dm, code/modules/mob/living/simple_mob/simple_mob.dm
Apparently simple mobs still dropped organs after being gibbed or butchered for whatever reason, of which has been used for hilarious but detrimental effect when people get insta-deaded by a pile of mouse livers and lungs rocketing at them
Should also help claw back a little bit of processing as it's no longer keeping track of fifty mob organs all in varying levels of decay as time passes.
add: Added a var for mobs to have organs drop on gibbing, humans have this on by default but simple mobs do not. (many monkeys died to test this out.)
fix: Fixed simple mobs dropping organs that they weren't supposed to have in the first place upon being butchered or gibbed. (Apparently it'd spawn them an entirely fresh new set of organs upon being gibbed for whatever reason, even holodeck carp)
/:cl:
=> Hopefully fixes simple mobs dropping organs

code/game/objects/structures/crates_lockers/closets/secure/explorer.dm, code/modules/mining/ore_redemption_machine/survey_vendor.dm
1. *Removes AR-V Goggles from Pathfinder Locker and Survey Vendor.*
1. _Yay Explo powercreep. We're gonna just get rid of these._
:cl:
del: Removes AR-V vectors for Explo.
/:cl:
=> Removes AR-V Goggles From Pathfinder Locker and Survey Vendor

_maps/map_files/rift/rift-06-surface3.dmm
the stupid unecessary atmos hole in bar maint is gone :crabdance:
Also fixes access on the surface 3 bunkers.
Because Engineering suffers enough, they don't need a sinle uncessary open space venting a whole floor to the outside to make their jobs even more thankless.
:cl:
tweak: Removed Open space in Bar Maint
fix: Access on Surface 3 Bunkers
/:cl:
=> Salvation for Engineering

_maps/map_files/rift/rift-03-underground1.dmm
1. **Removes an Unsimulated Turf in Engineering.**
1. _It's messing with some stuff and needs to go._
:cl:
fix: Fixes an Unsimulated turf's erroneous placement.
/:cl:
=> Removes Unsimulated Turf from Engineering

code/modules/mob/living/carbon/human/emote.dm
Changes the synthetic check to also factor in synthetic voiceboxes for the purpose of synth emotes.
Allows more emote flexibility for those logically able to use synthetic emotes.
:cl:
tweak: Allows anyone with a synthetic voicebox to use synthetic emotes.
/:cl:
=> Allows people with synthetic voiceboxes to use synthetic emotes

_maps/map_levels/192x192/lavaland.dmm
1. **Removes the Shades from Surt.**
1. _These guys were thrown in before we got the cyberhorror storyline set up. Now that the horror aura works, it's a little less fun to keep them around._
:cl:
del: Removes cult mobs from Surt.
/:cl:
=> Removes Cult Mobs from Surt

code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm, code/modules/cargo/supplypacks/supply.dm
1. **Changes Tyrmalin Heavy Charges to craftables.**
1. _Four Tyrmalin charges and eight pieces of duct tape = one heavy charge. Supply packs currently only provide two charges, so you can't just print one out straight out of the gate._
:cl:
balance: Tweaks Tyrmalin heavy charge distribution.
/:cl:
=> Tyrmalin Heavy Charges Now Have to be Crafted

code/controllers/subsystem/xenoarch.dm, code/modules/xenoarcheaology/tools/tools.dm
For some reason the anomaly scanner deletes the subsystem list (all of it). I instead move the list pruning to where it should be -- when artifacts are actually generated. 
the code is hot shit and this fix is hot shit
but it works roughly as intended now
you can find artifacts now
:cl:
fix:xenoarch bug
/:cl:
=> "Fixes" a xenoarcheology bug that prevented artifacts from being found ever

code/game/objects/effects/traps.dm
1. **Adds a pitfall trap that drops you down a Z level.**
2. **Gives Launchers a Faction.**
1. _Heheheh. Chutes and ladders._
2. _I don't know why this is necessary, but checks are runtiming when the launchers fire without having one._
:cl:
add: Adds an open space turf.
add: Adds a faction to launchers.
/:cl:
=> Adds an Open Space Pitfall Trap

_maps/submaps/level_specific/lavaland/ashlandercamp.dmm, code/modules/hydroponics/trays/tray_tools.dm
1. **Fixes color change inheritance on plantcutters.**
1. _As it says._
:cl:
fix: Corrects inheritance of color changing var.
/:cl:
=> Fixes Bone Plantcutter Icon Issue

code/modules/mob/living/simple_mob/subtypes/horror/Eddy.dm, code/modules/mob/living/simple_mob/subtypes/horror/Master.dm, code/modules/mob/living/simple_mob/subtypes/horror/Rickey.dm, code/modules/mob/living/simple_mob/subtypes/horror/Smiley.dm, code/modules/mob/living/simple_mob/subtypes/horror/Steve.dm, code/modules/mob/living/simple_mob/subtypes/horror/Willy.dm, code/modules/mob/living/simple_mob/subtypes/horror/bradley.dm, code/modules/mob/living/simple_mob/subtypes/horror/horror .dm, code/modules/mob/living/simple_mob/subtypes/horror/sally.dm, code/modules/mob/living/simple_mob/subtypes/horror/shittytim.dm, code/modules/mob/living/simple_mob/subtypes/horror/timling.dm, code/modules/mob/living/simple_mob/subtypes/occult/constructs/_construct.dm, code/modules/mob/living/simple_mob/subtypes/occult/constructs/artificer.dm, code/modules/mob/living/simple_mob/subtypes/occult/constructs/harvester.dm, code/modules/mob/living/simple_mob/subtypes/occult/constructs/juggernaut.dm, code/modules/mob/living/simple_mob/subtypes/occult/constructs/proteon.dm, code/modules/mob/living/simple_mob/subtypes/occult/constructs/shade.dm, code/modules/mob/living/simple_mob/subtypes/occult/constructs/wraith.dm
1. **Assigns the Horror Aura to Individual Mob Types.**
1. _Originally the aura was applied to every type of a mob, which has led to some unexpected issues. I've added the aura directly to each mobtype to prevent issues like this in the future. This has also allowed for more fine tuning of the aura strength per mob._
:cl:
tweak: Tweaks how the horror aura is assigned to mobs.
/:cl:
=> Adjusts Horror Aura Subtyping

_maps/map_files/rift/rift-07-west_base.dmm, _maps/map_files/rift/rift-08-west_deep.dmm, _maps/map_files/rift/rift-09-west_caves.dmm, _maps/map_files/rift/rift-10-west_plains.dmm, maps/Generic/turbolifts.dm, maps/rift/rift_areas.dm, maps/rift/rift_defines.dm, maps/rift/rift_shuttle_defs.dm, maps/rift/submaps/_rift_submaps.dm
As the title suggest adds an elevator, belter shuttle pad, and a few things like a small substation to the west mining base
Need some help getting the belter stuff to work, currently the console keeps saying the shuttle location is not 
A step towards a feature that people have been wanting back plus just general expansions to the west side structures.
:cl:
/:cl:
=> Adds elevator, belter shuttle, and more to west side

code/game/turfs/simulated/floor_types_eris.dm, code/game/turfs/simulated/floors/dirt.dm, code/game/turfs/simulated/floors/grass.dm, code/game/turfs/simulated/floors/lava.dm, code/game/turfs/simulated/floors/outdoors.dm, code/game/turfs/simulated/floors/snow.dm, code/game/turfs/simulated/floors/water.dm, maps/nsv_triumph/submaps/lavaland/_lavaland.dm
1. **Adjusts the Edge Blending Priorities for Turfs.**
1. _These numbers are open to change. I'm just doing quick math and adjustments off the top of my head with limited testing here._
:cl:
fix: Fixes turf edge blending.
/:cl:
=> Fixes Turf Edge Blending (Because otherwise you'll all just deal with pink triangles and do nothing for a year.)

tgui/packages/tgui/interfaces/Canister.js
Removes the redundant shielding and cell UI elements from the Canister UI
:cl:
del: Removed redundant shielding and cell UI elements from the atmospheric canister UI
/:cl:
=> Removes redundant UI elements from canisters

code/game/objects/items/weapons/stunbaton.dm
Stunprods were unable to be constructed as they would go invisible upon adding wirecutters due to the icon being set to stunprod_nocell_nocell. Stunprods also couldn't have a cell loaded.
:cl:
fix: Stunprods and teleprods can once more be constructed
/:cl:
=> Stunprods are now constructable and function correctly

code/modules/reagents/Chemistry-Machinery.dm
Fixed borgs being unable to interact with the grinder without sending the beaker to the nether realm
:cl:
fix: Borgs can now remove beakers from the grinder correctly
/:cl:
=> Fixes borg interactions with grinders

code/_onclick/cyborg.dm
Stops a double-call of the altclick() action for borgs which broke some interactions such as ovens
:cl:
fix: Fixes alt-clicking for borgs to not double-call AltClick() thereby breaking some interactions
/:cl:
=> Removes an un-necessary double-call on borg alt-clicking

code/game/objects/items/weapons/grenades/chem_grenade.dm
1. **Adjusts Chem Grenade Activation.**
1. _So Chem Grenades had their det_time set to Null. The issue is that there was supposed to be some accounting in the procs for the timers on the constructed grenades. For whatever reason though, this value just doesn't exist, or isn't being processed properly. So I've given the chem grenades a hard-set timer for now that can't be changed while I investigate the issue further._
:cl:
fix: 'Fixes' Chem Grenade timer.
/:cl:
=> Band-Aids Chem Grenade Activation

citadel.dme, code/game/objects/random/mapping.dm, code/game/objects/structures/flora/rocks.dm, code/modules/random_map/automata/map_specific/rift_automata.dm, maps/rift/rift_defines.dm, maps/rift/rift_turfs.dm
This adds oregen to the station z levels (without cave generation) as well as impliments a simple system to generate rocks, plants, various snowman, and ice crystals on the snow around the station and west planes. 
A follow up PR will be needed to change the mineral turfs on the upper levels to only generate low value ores but for now they are generating standard ore distribution (will require touching all the rocks again and changing them to a different variant in a map editor). 
Oregen is something that was missing from the station z levels and anything that helps the west plains be something other than GM_Flatgrass with snow is good. To note any mineral floor turfs mapped into the station z levels will need to be a ignore_cavegen variant otherwise oregen will turn them into a rock wall …
=> Oregen to Station Z levels, Rocks and fauna generation to snow turfs
