Citadel-Station-13/Citadel-Station-13-RP

code/game/gamemodes/gameticker.dm
3 minutes felt a bit too long.
=> Changes round end restart timer to 2 minutes

code/world.dm
=> Makes the hub entry match main's hub entry.

modular_citadel/code/datums/outfits/jobs/centcom.dm, vorestation.dme
This PR adds the Central Command Officer job's equipment to the "Select Equipment" verb for admins. It also adds in a snowflake one for myself.
=> Equipment selection update

code/game/objects/structures/trash_pile.dm
"I'm the trashman, I eat garbage"
changelogs in the commits
=> Trash Pile Loot Table Edits

code/modules/client/preference_setup/loadout/loadout.dm, modular_citadel/code/modules/client/preference_setup/loadout.dm, modular_citadel/code/modules/client/preference_setup/loadout_donator.dm, vorestation.dme
Donator items can now be added in, rejoice!
=> Donator Loadout Item Framework

code/modules/mob/new_player/new_player.dm
Title. Will send to Polaris when i'm not on the verge of passing out. Contains cit edit comments in case of weirdity
=> [S] patches an exploit that allows skids to spawn as any species

code/game/objects/items/weapons/grenades/flashbang.dm, code/modules/mob/living/carbon/human/human_helpers.dm, modular_citadel/code/game/objects/items/devices/radio/headset.dm, vorestation.dme
Exactly as it says on the tin.
=> Security and Command bowmans now provide protection from flashbangs

maps/tether/tether-05-station1.dmm, modular_citadel/code/modules/vore/fluffstuff/custom_items_vr.dm, vorestation.dme
Corp Regs and the item description were in conflict, so I fixed it to be 100% more reasonable
=> Translocator corpreg conundrum corrected

code/world.dm
=> Fixes Travis.

maps/submaps/surface_submaps/mountains/mountains.dm, maps/submaps/surface_submaps/mountains/mountains_areas.dm
=> C I T A D E L C H A N G E

code/modules/research/designs/stock_parts.dm
[What dose it do!] 
Speeds up part printing to the 5th hit form the 20 hits before hand speeding up mass part upgrade printings!
[Why]
*ZZZ*
To help stop lazy sci form not upgrading the other departments do to the long wait time for parts
[Did it compile and did you test it?]
Yep counted the hits it took to completes a bin compared to a speedy manipulator 
https://cdn.discordapp.com/attachments/499347891161137172/504840962770599949/unknown.png
=> [Ready] Makes parts print at the 5 animation's hit

code/controllers/autotransfer.dm
Alternative to https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/438
=> 3+1+1 Round length

code/modules/clothing/spacesuits/rig/suits/station_vr.dm
vests was big shit maybe this will be less big shit
=> Allows bags to fit on EVA hardsuits.

modular_citadel/code/datums/supplypacks/contraband_cit.dm, modular_citadel/code/datums/supplypacks/costumes_cit.dm
=> Makes medieval crates to be cheaper

code/modules/admin/verbs/debug_vr.dm, modular_citadel/code/modules/admin/verbs/debug_vr.dm, vorestation.dme
Basically adds a prompt that lets you choose the NIF type to implant in the target.
=> Improved Quick NIF again, now modularized

code/datums/supplypacks/hospitality_vr.dm, code/datums/supplypacks/munitions.dm, code/datums/supplypacks/security.dm
yeet em and skeet em boys we're uncommenting Them Shits (tm)
(uncomments a bunch of shit like -
crates of food
crates of LWAPs
crates of burst somethings
a box of "Security Basic Equipment")
=> Uncomments supply packs of varying fun

code/modules/clothing/suits/aliens/seromi.dm, code/modules/clothing/under/xenos/seromi.dm, code/modules/planet/sif.dm, code/modules/reagents/reagent_containers/syringes.dm, code/modules/vore/eating/vorepanel_vr.dm
Original change by @deathride58 
Also removes some unnecessary intendation stuff, i hope nobody will mind. ~~Except for travis, probably.~~
=> Reverts vorepanel_vr.dm to our changes, fixes some missing icons

modular_citadel/code/modules/client/preference_setup/loadout_donator.dm
Donator Item for RisingStarSlash
=> Adds Donator Item - Ultra Rare Hat

modular_citadel/code/game/objects/items/devices/radio/spy_bug.dm, vorestation.dme
Re-making the PR because the previous one got way too fucked for me to bother to fix. #441
=> Adds radio stuff to spy bugs and spy bug monitors.

code/datums/supplypacks/robotics_vr.dm, code/modules/organs/robolimbs_vr.dm
Because trying to justify anything is like repeatedly smashing your head against a brick wall
=> Re-adds a singular type of fluff robolimb

code/modules/mob/living/carbon/human/descriptors/_descriptors.dm
this system is about to be commented out upstream according to Virgo devs, so I'm not gonna take the time to go crazy to modularise two lines that may soon get removed anyway. Will hold a vote regarding the system if virgo goes through with plans to remove the system.
=> fixes custom species tag with height/build system

modular_citadel/code/modules/clothing/masks/gasmask_cit.dm, vorestation.dme
Because what the hell there's sprite for it, so why not use it?
=> Allows facemask to be adjusted

code/modules/vore/fluffstuff/guns/bsharpoon.dm
cd buffed 30 --> 20
range buffed 7 --> 8
wallhack removed
=> bsharpoon tweaks

code/modules/admin/verbs/randomverbs.dm
Which antifun motherfucker did this?
=> Unsanitizes admin narrates/subtles

code/modules/admin/verbs/adminsay.dm, code/modules/admin/verbs/pray.dm
why wasn't this done years ago this is literally a 5 character change
=> allows moderators/Player reps to see asay.

code/modules/admin/verbs/adminsay.dm, code/modules/admin/verbs/pray.dm
=> maybe fixes mods seeing asay

code/datums/supplypacks/contraband.dm, modular_citadel/code/datums/supplypacks/security.dm
adds plate carrier crates to cargo, cant fucking remake #428 because its THE SAME FUCKING INDENT FUCKING ERROR FUCKING SHIT FUCK
=> [ready] Plate Carrier Integration

modular_citadel/code/datums/supplypacks/security.dm
changes names so empty plate carriers appear first up,
some dumb name changing shit,
merc kit now has a helmet because its a cool helmet
=> Plate Carrier Integration Tweaks

modular_citadel/code/datums/supplypacks/security.dm
i want to git commit -m "die" - tweaks some names for plate carriers to satisfy my caveman brain
=> you ever just get lazy and forget to tweak some names?

code/modules/clothing/spacesuits/rig/suits/station_vr.dm
takes it from:
armor = list(melee = 50, bullet = 10, laser = 20, energy = 15, bomb = 30, bio = 100, rad = 50)
to:
armor = list(melee = 60, bullet = 50, laser = 30,energy = 15, bomb = 30, bio = 100, rad = 50)
=> HOT TAKE - comments out the virgo industrial hardsuit nerf

modular_citadel/code/datums/supplypacks/security.dm
=> makes pouch crates actually have a decent amount of pouches for their janky ass cost

modular_citadel/code/modules/donatorreskins/items.dm
Does this matter on the server when it made no difference in local testing? Let's find out.
Why yes, this is a webedit done on mobile. Thank you for noticing.
=> Donator items suck

modular_citadel/code/game/jobs/job/z_all_jobs_cit.dm, modular_citadel/code/modules/clothing/shoes/miscellaneous_cit.dm, vorestation.dme
Modularized, also adds specific modular code file for further changes, if somebody wants it.
=> Adds "Viscera Cleaner" as alternative job title for the janitor + tweaks slowdown for semi-galoshes

code/game/objects/structures/crates_lockers/closets/secure/security_vr.dm
this took me an ungodly amount of time im so sorry if it sucks
=> fixes dme this time i swear, removes hydra, adds x01 to hos locker

code/modules/resleeving/machines.dm
Changes the message upon resleeving.
=> Why is this needed?

code/game/objects/items/devices/translator.dm, code/modules/research/designs/misc.dm, modular_citadel/code/game/objects/items/devices/translator.dm, modular_citadel/code/modules/research/designs/misc.dm, vorestation.dme
fuck you, adds translators that understand E V E R Y T H I N G
actually tested, actually works
despacito
=> Omni-Translators!

code/controllers/subsystems/vote.dm, vorestation.dme
Changes the crew transfer vote prompt to an IC version. This gives an IC reason as to why you go to work having no idea when you actually get to leave, and thus start on projects not knowing if you can finish them.
This is probably going to be a testmerge for a bit to see if it causes IC salting and whining.
=>  Changes crew transfer message in line with player vote.

code/game/objects/effects/spiders.dm
This triggered the HECK out of me when I saw it in a screenshot
https://cdn.discordapp.com/attachments/342070163417333761/530662970506608640/unknown.png
=> Fixes bad grammar.

modular_citadel/code/datums/supplypacks/misc.dm, modular_citadel/code/datums/supplypacks/security.dm, vorestation.dme
a crate with liquidfood rations, adding some shit to the holster crate, lowering plate carrier stuff prices across the board (except for the heavy kit but we don't talk about the heavy kit), blood type patches, some decorative NT/PCRC/"police" patches for plate carriers and helmet covers to go with the patches
also comments out tactical plates because nobody bought them and they were just medium plates with better laser/energy resist anyway tbh
=> jesus, what the fuck am i doing - CARGO STUFF

code/modules/mob/living/carbon/human/species/station/prometheans.dm, code/modules/mob/living/carbon/human/species/station/prometheans_vr.dm
i despise git, i despise kev. KEV. KEV. FUCK YOU. YOURE THE WORST MENTOR. i did this in the fucking webeditor cos fuck git REE
=> prommiebuff but working i hope

code/modules/clothing/under/miscellaneous.dm
i changed the name and description of the "schoolgirl" uniform to be less schoolgirl. fuck.
=> less schoolgirl since people were slightly concerned

code/modules/mob/living/carbon/human/species/station/alraune.dm
kevinz promised he wouldn't give me the belt for this one and i'm impatient for the rebase meme so here we go
=> unwhitelists alraunes

maps/tether/tether-01-surface1.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm
Fixes absolutely everything, all future issues are now invalid. 
Changes shitty object based storage into room based storage.
Reworks some of the pipes in atmos.
Adds an APC to the intake.
Adds engineering camera monitors.
Reduces number of random maint spawns in atmos.
=> Atmos fixes.

code/modules/vore/fluffstuff/custom_clothes_vr.dm, modular_citadel/code/modules/vore/fluffstuff/custom_clothes_vr.dm
=> something something sweaters?

modular_citadel/code/modules/research/designs.dm
=> research buff pt. 2: i actually make things print faster this time

code/game/objects/items/weapons/handcuffs.dm, code/modules/resleeving/machines.dm
Why can cables work better as restraints than handcuffs? Cus someone is dumb, that's why. Live on, almighty rig suit.
Closes #623
=> Removes stupid decision.

maps/submaps/surface_submaps/mountains/mountains.dm
Changes costs of V4 structures by 1/5 (edit: with the exception of some) of their original value, consistently spawns ~15 templates with decent spacing, but not so much as to have 10 minutes of digging just to find a pod, as it used to be.
The actual budget seems hardcoded, otherwise I'd have tried that first.
(Ignore the title of my branch I'm actually brain dead it seems, this edits V4 its late ok, don't hate me?)
=> V4 high activity

maps/tether/tether-01-surface1.dmm
Heck.
Adds missing gas sensors to tanks, adds some junk to the surrounding area.
=> Adds missing crap to Atmos.

maps/tether/tether_areas2.dm
This is just a lame, mini-PR that fixes a typo that triggered me mid-game.
=> Fixes spelling for solars, public garden maint

maps/submaps/surface_submaps/mountains/mountains.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#646
slime time
=> v4 high activity revert

maps/tether/submaps/aerostat/submaps/virgo2.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#649
mekhi is a sub pass it on
=> Revert "V2 high activity"

modular_citadel/code/modules/client/preference_setup/loadout_donator.dm
The file doesn't like when you use the wrong casing.
=> Fixed Mewchild donator spawn

code/game/objects/structures/crates_lockers/closets/utility_closets.dm
What do this do?!?
Adds one stack of /obj/item/stack/medical/ointment to each fire locker
Why did ya do dis?!?!
Its a fire locker and in the case of massive fire or hear people get burned. Kinda like how some O2 lockers have O2 kits
=> Adds ointment to fire lockers

code/modules/xenoarcheaology/misc.dm
Adds in things to the xeno archaeology locker
Adds 3 rolls of film for cams
Adds 2 boxes of plastic bags
Adds a suitcase with a lock 
Adds a cam for photos
Adds a paper bin
For people to better log and report there finings
=> Adds more cataloging tools and such to Xeno Archaeology 

code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm
It works, I'll PR it to virgo but given the sync, this can also be merged here and now.
=> Fixes protean languages for real this time.

code/modules/mob/mob_movement.dm
=> actually comments out spaceslipping

code/controllers/Processes/alarm.dm, code/game/objects/items/weapons/grenades/chem_grenade.dm, code/game/objects/structures/crates_lockers/closets/secure/freezer.dm, code/modules/food/food/snacks.dm, code/modules/food/food/snacks_vr.dm, code/modules/food/recipe.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/nano/modules/crew_monitor.dm, code/modules/reagents/reagent_dispenser.dm, code/modules/research/circuitprinter.dm, code/modules/research/protolathe.dm, code/modules/vore/eating/vore_vr.dm, modular_citadel/code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
Actually tested the cooking fixes. All reagent containers and things that create reagents upon being created should use the `initialize()` proc to do so now, fixing runtimes. ALSO CHEM DISPENSERS WORK. Buns now have flavors instead of "something indescribable". NO MORE SAUSAGE SPAM.
=> Cooking fixes + attempts to fix a few miscellaneous runtimes.

code/game/jobs/job/science.dm
=> Adds explorer access to the RD

maps/southern_cross/structures/closets/misc.dm
kevinz is a coward and a fiend
=> Adds machetes to Search and Rescue/Field Medic

code/game/objects/structures/trash_pile.dm
Adds
pill bottle citalopram, - happer pills
pill bottle iron, - Grind metal to get same thing
pill bottle bicaridine, - Basic medical easy to make if you know what to grind
pill_bottle antitox, - Basic medical easy to make if you know what to grind
pill bottle kelotane, - Basic medical easy to make if you know what to grind
brown vest, - Better webbing
black vest, - Better webbing
white vest - Better webbing
Note Vests are just better webbing
Removes
Spare black shoe role of the dice - Fudges the numbers
=> [Ready] Adds a lot more things to trash piles and removes some things

code/controllers/autotransfer.dm
>2 of the 3 are configs
>the third isn't a config
>whoever did this changed the wrong value
>I got memed on
=> fixes 3+1+1 rounds

code/modules/mob/living/silicon/robot/robot_modules/station.dm
What dose this do?
Hopefully gives all borgs signaler
Why?
Usefull for things like pinging eacher in stages of a plan, or to be used with a human well doing a time project, or for remove singuling buttes
=> Gives borgs singulars as well as basic drone

code/modules/mob/living/carbon/human/species/station/station_vr.dm
THEY KNOW SKRELLIAN NOW, GET GOT
cake is crying
=> WRINKLED MINDS: THE SHORKS KNOW SKRELL

.travis.yml
Yeah okay if indentation is bad DM will catch it as a compile error, and I'm hoping no one's dumb enough to try to space-indent. Regardless this "test" is the source of endless annoyances so goodbye it goes, I'm done.
=> Gets rid of the indentation travis test

code/modules/nifsoft/software/15_misc.dm
raises the cost of the size changer, ups the 'sigNIFicant wear', and makes it disorient people
why:
pretty much removes the combat capabilities of the software, and makes it less of a 'free size gun that i can use without roleplaying'
=> size changer NRF

code/modules/reagents/dispenser/dispenser2.dm
=> fixes chemical dispensers

code/game/objects/structures/trash_pile.dm, code/modules/paperwork/handlabeler.dm
Changes
Makes hand label a small item
Doubles the roll of labels
Why
Makes it kinda worth having or useing
=> Makes Hand Labels small items and double the roll 

code/game/objects/structures/trash_pile.dm
=> bad faith prs

code/modules/food/recipes_oven.dm
I'm lazy. The proper solution would be "add blueberries" but this still works.
=> Replaces requirement for blueberries with berries.

code/game/objects/items/devices/taperecorder.dm
Changling
Makes tape last 3x longer
Why
God their still so useless
=> Buffs the shit out of tape

code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
Changlings
Lowers time you need to be ghost maybe to 5 mins before you can be a drone.
Why
Requested by Vail Seria/BV-852i 'Gnut', so people can play the game or such to grater fun
=> Lowers time you need to be ghost maybe to 5 mins before you can be a drone.

code/modules/client/preference_setup/loadout/loadout_head.dm
Changling 
Adds maid to loadouts
Whys?
Its a nothing item that looks good, prefect for loadouts
=> Adds maid handband to loadouts

code/modules/food/food/condiment.dm
=> Fixes space spice not having a sprite sometimes.

code/game/jobs/job/assistant.dm
=> Adds "Assistant" alt-title for interns

code/modules/mob/living/simple_animal/simple_animal.dm
=> does this compile? no. does it make phase guns viable? no.

code/modules/mob/living/carbon/human/emote_vr.dm
Changling
No one plays a nymph so I made their chip be usable for all
Hos is Ling
Nymph never seen or really played people like the sound let people have Fun-TM
=> Makes the chirp emote useable by all!

code/game/jobs/job/medical.dm
Changlings
Therapist for a alt tile from Psychiatrist same outfit and shuch maybe
Hos is a ling
I asked and it seems logical
=> Makes a therapist alt tile for Psychiatrist

code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/modules/research/designs/medical.dm
Tweaks material costs a bit for advanced/phasic health analyzers. Makes advanced roller beds slightly better (85%, up from 75% base odds) at field surgery.
=> R&D Medical Tweaks (WEBEDIT)

code/modules/mob/living/carbon/human/emote.dm
Adds a very low functionality *fingerguns emote.
=> These are the Guns of the Patriots!

code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
Truns out if you have ***Everthing*** it stays as ten mins and not five
~~~Math is hard~~~
=> Maybe makes drones be a thing ever time MKII

code/modules/mining/mine_turfs.dm
Changling
Makes digging sand, you know SAND faster
Hos is a ling
Man spending 40 ticks digging sand sure is boring... Even with the best tools no different in dig time kinda sucks. Likely will be fixed in time
=> Make digging sand half as slow

code/modules/clothing/spacesuits/rig/suits/station.dm, maps/tether/tether-05-station1.dmm
whats different?
- renault no longer lurks in the front
- the lockdown doors have a fuckin button
- office doors have a button too
- fixed some missing carpet
- deleted some leftover pipes
- put in a light tube
it went from "this light" to everything else im sorry
=> some more map fuckery + bonus RIG changes

code/defines/obj/weapon.dm, code/game/gamemodes/cult/cult_items.dm, code/game/gamemodes/cult/ritual.dm, code/game/gamemodes/cult/talisman.dm, code/modules/clothing/head/misc_special.dm, code/modules/clothing/shoes/miscellaneous.dm, code/modules/mob/living/simple_animal/constructs/soulstone.dm, code/modules/research/designs/misc.dm, code/modules/xenoarcheaology/tools/tools.dm
Changling
Arcane tech is now used for xenoarchy multy tool but you get the needed level by getting the normal scanner like allways
All cult items now give some cult tech do to cult being arcane
Hos is a ling
Lets use code we have that makes logical 100% good idea scene
=> Makes all cult and arcane items have arcane tech

code/modules/research/rdconsole.dm
=> Revert "[DNM] Maybe makes the Rnd console use uppercase letters "

code/modules/xenoarcheaology/finds/find_spawning.dm
=> xenoarch talkative machine 🅱️roke

code/modules/research/designs/medical.dm
Mark one and two hyposprays are now printable via Rnd 
These are COSTLY upgrades for medical and at end game.
=> Makes Mark one and two hyposprays printable via RND

code/modules/vore/fluffstuff/custom_items_vr.dm
did nobody notice this shit until now? i swear to god
=> unfucks the two "weapons" in the rec restraints crate

code/modules/mob/living/carbon/human/human_attackhand.dm, code/modules/mob/living/carbon/human/human_defense.dm
=> Dislocations are now admin logged

code/modules/food/food/snacks.dm, code/modules/food/kitchen/cooking_machines/_appliance.dm, code/modules/food/kitchen/cooking_machines/grill.dm, code/modules/xenoarcheaology/tools/coolant_tank.dm
Changes some flavors to make more sense, fixes a few typos, makes cereals, candy, and grills actually function. Whoops.
Chips also work! Yay.
=> Fixes misc. cooking bugs.

code/modules/mob/living/carbon/human/species/station/alraune.dm
=> alraune pick fruit abilities tab

code/modules/reagents/reagent_containers/syringes.dm
>hardcoded suit checks for injection ports
😩
=> [UNTESTED] Plate Carrier Injection Ports

code/modules/mob/living/carbon/human/emote_vr.dm, code/modules/virus2/effect_vr.dm
=> git rm -r "sound emotes" git commit -m "oof()" git push

code/modules/research/designs_vr.dm, modular_citadel/code/modules/projectiles/guns/energy/netgun_vr.dm, modular_citadel/code/modules/vore/fluffstuff/guns/protector.dm
the myrmidon's name fuckery bothered me and now we're here
=> Lore Revision Revision - The Revisioning

code/datums/autolathe/devices.dm, code/game/machinery/cell_charger.dm
Ever been fucking tired of having to ransack planetside for cell chargers? Go fuck yourself, these cell charger deployment kits exist in the autolathe now.
=> Cell Charger Kits

code/controllers/autotransfer.dm
=> if this doesnt work let's blame nik

code/game/objects/random/misc.dm
=> removes grenadine from random booze spawner

code/modules/materials/material_recipes.dm
=> weed racks buildable

code/datums/supplypacks/recreation_vr.dm, code/datums/supplypacks/science_vr.dm
Cars for driving in the dangerous hallways and outside world. Expensive so they're not bought every round or at bulk, but cheap enough that a good mining shift could get them.
=> Re-add Humvee and Science Rover

code/modules/reagents/Chemistry-Recipes.dm
=> Roy Rogers/Screaming Viking Recipe Tweaks

code/modules/mob/living/carbon/human/human_attackhand.dm
A basic flavor change so that when you target someones legs and push them, you'll instead do a leg sweep. Purely flavor and nothing more.
=> Add Leg Sweeps

code/modules/client/preference_setup/loadout/loadout_utility.dm, code/modules/paperwork/pen.dm
little clicky pens ok if people spam it i'll uhhhh remove the sound and add a cooldown if i can figure it out
=> Click pens (oh my god)

code/modules/events/communications_blackout.dm, code/modules/events/event_container.dm, code/modules/events/event_container_vr.dm, code/modules/events/event_dynamic.dm, code/modules/gamemaster/actions/comms_blackout.dm
Good God, why did this have SUCH A HIGH WEIGHT and why did it only have a THIRTY PERCENT CHANCE OF ALERTING CREW? FUCK ME.
This might make worse, and more annoying events more common, so it's gonna get testmerged for a while.
=> Nerfs comms blackout into the ground.

code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
Changlings
Maybe fucken adds wires to Sci borgs correctly?
Hos is a ling
I am shit with this code base, Like what didnt it just add the var by itself?
=> Fixes wires for Sci borgs

code/modules/power/smes.dm, nano/templates/smes.tmpl
=> Doubles the mute function timer to 20 minutes

code/modules/power/smes_construction.dm
=> Fixes some issues with Engine SMES subtype

modular_citadel/code/modules/mob/living/silicon/robot/robot_modules/station_cit.dm
Changlogs
Gives Serv hounds the riding mod that all other doggos have
Why?
Clearly it was ment to be added or was forgotten do to reasons. Fixed!
=> Gives Serv hounds riding mounts

code/modules/power/smes.dm
"no nicc this wont work you have to do *this*"
yeah well hey f worders it worked ok
=> im a genius

.github/PULL_REQUEST_TEMPLATE.md
=> Copies TG's pull request template.

maps/tether/tether-01-surface1.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-06-station2.dmm
Fixed some issues with xenobiology access, engineering workshop access, and made it so that a wire to Telecomms from the substation doesn't go through a wall (there's an with the proper access requirements airlock there now).
=> Fixes various access issues.

code/modules/power/smes.dm
Fixes a really weird edge case where the engine would fire the wrong alert entirely, because it stored old values from the wrong alert.
spam gay
:cl:
fix: fixes weird edge case that eluded me in testing.
/:cl:
=> Fixes a weird edge-case with the warning system.

code/modules/power/smes.dm
https://www.youtube.com/watch?v=VKhpE-oNoGY
=> please kill me

code/modules/power/smes.dm
=> Fixes typo in code

code/modules/admin/callproc/callproc.dm
hotfix while hardsync gets finished
=> proccall arguments now support files/sound

code/datums/supplypacks/misc_vr.dm
im contractually obligated because of #872 
:cl:
add: crabs
/:cl:
=> Look sir, free crabs!

code/modules/mob/living/simple_animal/vore/otie.dm
This should make them significantly less dangerous to have around.
=> Security oties no longer chase crew set to arrest

code/modules/research/rdconsole.dm
local man only just now realizes he put in the wrong variable to draw from
fixes a bug i put in
:cl:
fix: protolathes actually show THEIR mat costs instead of the circuit imprinter's
/:cl:
=> protolathes now actually show appropriate costs

code/game/objects/items/weapons/storage/backpack.dm
hEY DID YOU KNOW YOU CAN COMPLETELY FUCKING DELETE A BOH BY CLICKING ON ANOTHER BOH WITH IT? NO? YOU DO NOW. FUCK.
maybe instantly deleting your bag is a retarded idea
:cl:
tweak: you can't delete bags of holding by misclicking anymore
/:cl:
=> ided pr - "why the fuck can i qdel() my entire bag with a misclick"

code/__defines/misc.dm, code/_global_vars/lists/mapping.dm, code/game/jobs/access.dm, code/game/machinery/computer/ai_core.dm, code/game/machinery/computer/prisoner.dm, code/game/machinery/computer3/computers/prisoner.dm, code/game/machinery/door_control.dm, code/game/machinery/doors/brigdoors.dm, code/game/machinery/portable_turret.dm, code/game/machinery/syndicatebeacon.dm, code/game/machinery/teleporter.dm, code/game/objects/items/devices/PDA/cart.dm, code/game/objects/items/devices/communicator/helper.dm, code/game/objects/items/weapons/teleportation.dm, code/game/objects/structures/morgue.dm, code/modules/admin/verbs/mapping.dm, code/modules/hydroponics/seed_controller.dm, code/modules/mining/drilling/drill.dm, code/modules/mining/mine_turfs.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/silicon/pai/recruit.dm, code/modules/power/supermatter/setup_supermatter.dm, code/modules/xenoarcheaology/tools/tools.dm
Reduces memory usage by moving `ore_types` from individual turfs (an associative list of 10 string keys and 10 typepath values, per turf) to one single global list.
Also makes it so that `req_access` and `req_one_access` is null unless it's actually needed.
=> In Memoriam

code/datums/autolathe/arms.dm, code/modules/projectiles/guns/projectile/boltaction.dm
Readds "hunter" cartridges which do bonus damage against animal simplemobs.
Ballistics? On Exploration? In my CitRP round?
:cl:
add: hunting cartridges are back in the autolathe
/:cl:
=> hrnngh colonel i really like hunting bullets

code/ZAS/Phoron.dm, code/__defines/nifsoft.dm, code/_onclick/hud/human.dm, code/game/objects/items/devices/translator.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/mob_defines.dm, code/modules/nifsoft/software/15_misc.dm, html/changelogs/buffalowing.yml
lots of reworks for synthetics to make them less reliant on the human/carbon base stats, and more accurately reflect the robots that they are
=> synthetic changes

code/modules/admin/verbs/adminhelp.dm
=> sanitizes ahelps

code/modules/surgery/organs_internal.dm
"Your hand slips, getting mess and tearing the inside of [target]'s [affected.name] with \the [tool]!"
to
"Your hand slips, tearing the inside of [target]'s [affected.name] with \the [tool]!"
etc
=> Grammar fix for surgery

code/modules/paperwork/paper.dm
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/8229/files
=> This allegedly fixes a thing thanks bhijn

code/modules/mob/new_player/new_player.dm
=> Fixes the observer prompt to actually match the respawn timer.

code/modules/mob/living/silicon/robot/emote.dm
Doggos can't bark. This injustice cannot stand.
=> Lets dogborgs use *bark

code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
improves delay code
Oh the nerf worked but this is better
:cl:
balance: Wheelchair speed halved
/:cl:
=> wheelchair slow code better

code/game/machinery/vending.dm
Changlogs
Gives medical pill bottles in their venders
why
For people to place pills in when they carry like 21 of them for medical aid
=> Gives medical pill bottles in their vender

code/datums/supplypacks/contraband.dm, code/datums/supplypacks/contraband_vr.dm, code/game/objects/items/contraband_vr.dm, code/modules/clothing/gloves/miscellaneous.dm
Adds curated stolen packages (tentatively available from bulk stolen supply crates), advanced combat gloves (combat gloves with added punchforce), and bulk stolen supply crates, which have a chance of having curated stolen packages.
It's not. I just wanted to have knuckle duster combat gloves.
:cl:
add: Advanced combat gloves! Like combat gloves, but knuckle-dusters.
add: Extra stolen crates! Expensive, but with more stolen packages.
/:cl:
=> YAHCB - curated stolen packages, adv glubbs, extra stolens

code/game/jobs/access.dm
=> Fixes access on master

code/game/machinery/vending_vr.dm, code/modules/projectiles/ammunition/magazines.dm, code/modules/projectiles/ammunition/rounds.dm, code/modules/projectiles/projectile/bullets.dm
Adds pepperballs. Because flashrounds are pretty retarded.
These work exactly like pepperspray but in bullet format, with some minor muckery.
=> Adds pepperballs. 

code/modules/clothing/spacesuits/miscellaneous.dm, code/modules/clothing/suits/armor.dm, code/modules/clothing/suits/hooded.dm, code/modules/clothing/suits/jobs.dm, code/modules/clothing/suits/miscellaneous.dm, code/modules/clothing/suits/utility.dm, code/modules/food/food/snacks.dm, code/modules/food/recipes_microwave.dm, code/modules/mob/living/simple_animal/animals/lizard.dm, code/modules/mob/living/simple_animal/animals/lizard_vr.dm, code/modules/mob/living/simple_animal/vore/solargrub_larva.dm, html/changelogs/buffalowing.yml, vorestation.dme
they make excellent pets, but also excellent snacks
=> Lizard fixes

code/modules/mining/fulton.dm
slaps you in a crate and also stops the animation from bugging out by updating the icon
resolves #1167
=> Fixes Fulton Beacons

code/modules/mob/living/simple_animal/aliens/alien.dm, code/modules/multiz/open_space_controller.dm, code/modules/multiz/turf.dm, html/changelogs/buffalowing.yml
they seem to fire like mercenaries; very high quality bay code from years ago no doubt. buffy fix.
=> Fixes Aliens burst firing

code/game/objects/items/weapons/storage/bags.dm, html/changelogs/chaoko99 - pullbox.yml
it's a fixed port PR
https://streamable.com/7acm4
miner QoL (and not Hatterhat's powercreep this time! Wow!)
:cl:
add: Thanks to chaoko99 over on Polaris, ore satchels now auto-pickup ore off the ground and dump them into boxes.
/:cl:
=> ore bag autopickup - CitRP#1286 fixed - Polaris#6106 port

code/modules/client/preference_setup/loadout/loadout_eyes_vr.dm
Because there isn't much reason this shouldn't be possible IMO
=> Give Head of Personnel AR-B glasses as a loadout option

code/game/objects/items/contraband_vr.dm
Well, it's in the title, innit?
Flexing on those "premium" cigar cowards.
:cl:
fix: Havana cigar cases now actually have Havana (Cohiba Robusto) cigars.
/:cl:
=> cohiba robusto/havana cigar cases now actually have cohiba robusto/havana cigars

code/game/objects/items/trash.dm
Makes SkrellSnax trash have a icon
=> Banaid fix to a broken sprite

code/modules/client/client procs.dm
the issue is player_age is 0 until the next day after they connect.
WARNING: THIS IS NOT TESTED. I DO NOT HAVE THE MEANS TO SET UP A TESTING DATABASE ~~or I'm just too lazy to~~ so uh, testmerge.
=> Fixes the panic bunker

code/__defines/misc.dm, code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm
Fucking russians, man. To be speedmerged immediately. If you're seeing this and your server of choice hasn't yet mirrored this PR or a variant of it, gently DM their coders with a link to this PR.
The diff got fucked due to line endings, so be sure to view the diff with a ?w=1
:cl: deathride58
fix: Fixed a fairly huge server crash exploit
/:cl:
=> [S] Fixes a fairly huge vector for server crashes

code/modules/resleeving/designer.dm, code/modules/vore/persist/persist_vr.dm, config/names/first_female.txt, config/names/first_male.txt, config/names/last.txt
fixes nif saving in theory
fuck nifs
:cl:
fix: nif saving may or may not be fixed
/:cl:
=> half_life_scientist_screaming (alt. title - i'm going to thoroughly shit myself)

code/game/world.dm
Normie compatibility not guaranteed lmao.
:cl:
config: edited the server's hub description
/:cl:
=> edits the hub description to something more friendly

code/__defines/misc_vr.dm, code/datums/outfits/jobs/civilian.dm, code/defines/procs/announce.dm, code/game/jobs/job/assistant.dm, code/game/jobs/job/job_vr.dm, code/game/jobs/job/offduty_vr.dm, code/modules/mob/new_player/new_player.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#849
uhhhh not sure if i should touch the PTO values or not
=> reverts goonchem

code/game/objects/objs.dm
Pretty sure this'll make it so little thing like a damn candy wrapper won't leave a bruise and eventually crit someone if you were to be smacked by one 100 times.
I also have no clue what I'm doing or what any other potential consequences this'll have because I'm pretty sure Kev told me to change a different file that didn't even have a throwforce variable from what I could tell, but when I tried to test this, it seemed to successfully make it so a protein bar wrapper no longer hurt you when thrown.
=> Update objs.dm throwforce from 1 to 0

code/modules/nifsoft/nif.dm
30 minutes is a longass time man. I fixed that. Also, I say hopefully because I am _not_ gonna waste my time trying to figure out how to test this, and then test it. Maybe testmerge i dunno.
People don't sit in medbay for half an hour AFK and never come back to realise its finished.
:cl:
tweak: half the time, epic style.
tweak: different messages, new messages, more clarity that it TAKES A WHILE to install
/:cl:
=> Halves NIF install time (hopefully), adds a couple other messages and shit

code/modules/clothing/under/accessories/lockets.dm
lockets dont have an open iconstate and i am Not fucking with that
locket man broken. this may or may not fix.
no
=> makes lockets "sliding a picture inside" feature work

code/modules/nifsoft/software/15_misc.dm
Well for one they now log.
Compliance disks have been changed to only be effective as a scene tool, rather than a general gameplay-capable mechanic.
tell me if the wording is shit or something i typed this up while half conscious
=> Changes up compliance disk OOC mechanics

code/modules/mob/language/station_vr.dm
Surprisingly not even close to the most snowflaky language we have.
More languages, just don't be stupid with it and claim you're an epic syndicate. The language can hint at a poor upbringing or life event, remember that your character is working for a megacorp.
:cl:
tweak: Removed the Gutter language whitelist
/:cl:
=> Removes the gutter whitelist

code/datums/mind.dm, code/modules/mob/mob.dm
concatenator circuit 2.0
requesting immediate speedmerge since this is pretty major
=> [s] fixes major server crash vector involving notes

vorestation.dme
Original PR https://github.com/VOREStation/VOREStation/pull/4635 never had the .dme addition for this thing. Newbie mistake from me, rectifying now.
This is a follow up to https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/897 which got merged, but like stated previously, a small issue was completely overlooked.
:cl:
bugfix: Fix inability to print holocollars in the autolathe.
/:cl:
=> Holocollar Printing Fix

code/game/objects/items/weapons/storage/firstaid.dm, code/modules/games/dice.dm
I didn't realize pill bottles had children, so my last PR messed with them. This fixes the issue.
Bug fixing grmbl
:cl:
fix: Dice bags are visible again
/:cl:
=> Makes dice bags visible again

code/modules/mob/mob_movement.dm
Direct port of this https://github.com/VOREStation/VOREStation/pull/5087
Fixes wheelchairs so they aren't stupid fast and we have to keep bwoinking people over it instead of just fixing the problem.
=> Fixes wheelchair movement.

code/modules/mob/mob.dm
=> [s] patches an exploit

code/controllers/Processes/supply.dm
Make's Cargo able to sell gold, silver, and uranium
Cargo tends to end up with excesses of these materials half the time, and the phoron + plat meta was getting stale
:cl:
add: Added the ability for cargo to sell gold, silver, and uranium
/:cl:
=> Made gold, silver, and uranium worth cargo points

code/datums/supplypacks/misc_vr.dm, code/game/objects/structures/crates_lockers/largecrate_vr.dm
Fixes the free crab crate by making a crab crate to order instead of trying to populate a crate with the crabs
Look sir, free crabs!
:cl:
add: Added crab crate, containing 3 crabs
fix: Fixed the Free Crab supply crate
/:cl:
=> Added crab crate, fixed the crab crate supply pack (also technically buffed the Free Crab crate)

code/datums/repositories/radiation.dm, code/modules/materials/materials.dm
fixes wall radiation calc
3.6 roetgen
rwalls now actually block radiation better than a moist paper towel
:cl:
tweak: rwalls actually calculate radiation properly
tweak: plasteel has a radiation resistance
/:cl:
=> rwall rad fixes

code/_helpers/atmospherics.dm, code/game/objects/items/weapons/flamethrower.dm, code/game/objects/items/weapons/tanks/tank_types.dm
Flamers now work.
They use welding fuel.
One tile of flame - 5 units of welding fuel.
They light people in the path on fire, damage simple mobs, and kill vines.
BURN BABY, BURN
:cl:
refactor: flamers refactored
/:cl:
=> Flamethrower Overhaul

code/modules/mob/living/simple_animal/vore/shadekin/shadekin.dm, modular_citadel/code/modules/shadekin/shadekin.dm
title
lol diffs
see branch name
:cl:
fuck shadekin with a flammenwerfer
/:cl:
=> removes pawbs

code/modules/flufftext/Dreaming.dm
No more vore dreams
No more vore dreams
:cl: Cebutris
del: No more vore dreams
/:cl:
=> Steals the dreams of the crewmembers

code/modules/clothing/spacesuits/rig/modules/utility.dm, code/modules/mining/drilling/scanner.dm, code/modules/research/designs_vr.dm
fixes the adv scanner not picking up platinum, makes the ore scanner small, adds a hardsuit module
the adv ore scanner was intended to be small this whole time and the platinum i forgot was just osmium. also consistency.
a changelog might be helpful but do we really do those anymore i mean damn
=> adv ore scanner fixes but also not fixes

code/datums/autolathe/tools.dm
So I did a dumb and in trying to make it so that you could print a set amount of cables I made things worse. This fixes it.
Basically, bugfixing.
:cl:
Fix: Made it so that there's only one option to print cables because the other options were buggy.
/:cl:
=> Fixes Cables in Lathe

code/modules/research/designs_vr.dm
you'd think nik could make the fix himself instead of making a revert pr
=> holy shit what a difficult pr to make to fix travis

code/modules/mining/satchel_ore_boxdm.dm
why doesn't ore collecting just push that shit into a fucking datum i mean god damn
arm and sigh
=> that one thing about the ore boxes and not exploding

code/modules/mining/satchel_ore_boxdm.dm
Turns out this doesn't actually do anything
=> Revert "that one thing about the ore boxes and not exploding"

code/game/world.dm
Makes it so stuff like the is-it-down checkers/playercount checkers work.
=> Readds world/Topic() ping response

code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
=> discordwizard is afk so i'm going to just change xenochimera revival cooldown to a less-crappy timer system

code/game/world.dm
=> [SPEEDMERGE] Revert "Submap Generation Respects Config"

code/modules/xenoarcheaology/finds/finds.dm
=> stupid fucking thing that might fix strange rocks but i dunno this code sucks

html/create_object.html
https://github.com/VOREStation/VOREStation/pull/5684
=> Makes the Create Object menu not freeze the client for an eternity

code/modules/admin/chat_commands.dm
something something convenience not having to stay logged in
=> Adds admin IRC bunker whitelisting to RP server

code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
Closes #1578 
thanks now dogs can tase people faster
=> adds tasercoolers for k9

code/modules/food/food/snacks.dm
replaces the momo sprite with tajaran soup because momo sprites don't exist thanks darksouls
closes #1556
=> lol what the fuck is momo

code/game/objects/items/devices/tvcamera.dm
=> Fixes a camera name

code/modules/research/designs/illegal.dm
slashes out binary keys
this ruins rogue ai and its also horribly balanced and gay
:cl:
balance: you cant build binary keys whenever you want
/:cl:
=> [Antag balance] Removes Binary keys from R&D

code/modules/client/client_procs.dm
=> fixes first day joins being unable to join any jobs

code/game/machinery/cell_charger.dm, code/game/machinery/frame.dm, code/game/machinery/recharger.dm, code/game/objects/items/bodybag.dm, code/game/objects/items/weapons/circuitboards/frame.dm, code/game/objects/items/weapons/stunbaton.dm, code/game/objects/items/weapons/tanks/tank_types.dm, code/game/objects/items/weapons/tanks/tanks.dm, code/game/objects/structures/crates_lockers/closets.dm, code/modules/xenobio/items/weapons.dm
bodybags are now slightly less fucky i guess also stasis bags dont kill you from low pressure
cell chargers and rechargers are now upgradable
bodybags/stasis bags less fucky
cell chargers/rechargers less shitty to use
:cl:
fix: stasis bags dont kill you and bodybags are less shitty to use
tweak: cell chargers and rechargers can now be upgraded
add: cell chargers can now be constructed but cell charger kits still exist so *shrug
/:cl:
=> bodybags - density + pressure, cell chargers suck a lil less dick

code/modules/client/client_procs.dm
=> how did i forget an if block that resulted in everyone being considered new players

code/modules/flufftext/Dreaming.dm
Adds in more dreamtext!
Currently there's not much, but I'm very open to suggestions!
I killed virgo's dreams. Now I must add more, to restore the balance.
:cl: The Community
add: Diversified dreaming!
/:cl:
=> [WIP][SUGGESTIONS WANTED!] Adds new dreamtext

code/game/area/Space Station 13 areas.dm, maps/tether/tether-05-station1.dmm
This adds a new pretty lounge to the first level of the station. This means there's now a proper eatery on the upper section, meaning you don't have to elevator down to the rather bare bar. It's a little more comfy, including some private tables and a nice stage for... performances. It's had some minor testing but all bugs should be reported here or to me on discord nicc#3604 thanks
[https://i.imgur.com/qrHwi49.png](url)
No more going to the surface to get food that isn't from a vending machine.
:cl:
add: Added a new lounge and areas to go with it
/:cl:
=> adds a new lounge to station level 1

maps/tether/tether-04-transit.dmm, maps/tether/tether_things.dm
Fixes falling from the midpoint
also fixes a dark spot
because now you can fall and admins won't get 1k lines a second of errors when someone tries
:cl:
fix: fixed gravity
/:cl:
=> Fixes falling from the midpoint

code/game/objects/items/weapons/storage/_storage.dm, code/game/objects/items/weapons/storage/bags.dm
fixes #1401 (the chat spam portion) as for the functionality of simply having an ore bag on you somewhere and it collecting i don't find that particularly game breaking nor am i going to remove the feature without maint approval
=> mining satchel fix. fixes the spam in issue #1401

maps/tether/tether-03-surface3.dmm, maps/tether/tether-05-station1.dmm
=> ports library changes

code/modules/organs/subtypes/standard.dm
This reverts commit 50db8230c8f763fb91fa446afccd72b6288a6915.
:cl:
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> Revert "changes the icon for l_arm"

maps/tether/tether-01-surface1.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm, maps/tether/tether-04-transit.dmm, maps/tether/tether-05-station1.dmm
Reverts Citadel-Station-13/Citadel-Station-13-RP#1652
=> Revert "More Misc Map fixes."

maps/tether/tether-01-surface1.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm, maps/tether/tether-04-transit.dmm, maps/tether/tether-05-station1.dmm
Remakes my previous fixes PR, as it somehow managed to break the entirety of Master due do a dict conflict.
Reassigns several areas, so fix gaps/incorrect placements
Moves Telecomms relay from the midpoint down into telecomms
Closes #1651, Again
Fixes an area of incorrect decals
Adds an air buffer to the telecomms airlock
=> Remakes #1652

code/game/turfs/unsimulated/sky_vr.dm
=> Fixes falling phased kin from tether mid-point

code/game/world.dm, code/global.dm, code/modules/mob/new_player/login.dm
code improvement debugging/vv purposes until it's moved into a config.
=> MOTD is now a global variable

code/controllers/configuration_vr.dm, code/game/jobs/job/job_vr.dm, code/game/machinery/computer/timeclock_vr.dm, config/example/config.txt, nano/templates/timeclock_vr.tmpl
This is a port of the timeclock system from vorestation, that allows players to go on and off duty via the timeclock. Full details can be read here https://github.com/VOREStation/VOREStation/pull/5101
This will need to be testmerged to make sure it works. There was no way for me to verify that PTO was being built, on a local server, as I don't have a SQL database set up.
=> Ports fully realized timeclock system

maps/tether/tether-03-surface3.dmm
:cl:
tweak: Reworked some of the wiring/piping in hydroponics, so they're not going under walls
tweak: Added a second pair of Pumps/Vents to Hydro, to better suit the size of the room
tweak: Added a couple holopads to the bar
/:cl:
=> Numerous Tweaks to Bar and Hydroponics

maps/tether/tether-01-surface1.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm
Angery. Remakes #1668, which itself remakes #1662
=> Remakes Atrium PR. Again. For the last time.

code/modules/vore/eating/vore_vr.dm
if i knew how to rust i'd combine the file write procedure with tg's to make one that works with this but i don't and this isnt' too laggy
=> fixes vore preferences god why 

maps/tether/tether-07-station3.dmm
:cl:
fix: Fixes overwritten section of cargo mailing room. oops
/:cl:
=> Unfucks mailing room

code/modules/mob/living/carbon/human/species/station/alraune.dm, code/modules/mob/living/carbon/human/species/station/blank_vr.dm, code/modules/mob/living/carbon/human/species/station/station_special_vr.dm, code/modules/mob/living/carbon/human/species/station/station_vr.dm, code/modules/mob/new_player/sprite_accessories.dm
:cl:
tweak: Allows all species to tie their hair up/let it down via the "Tie Hair" verb, previously restricted to humans.
/:cl:
=> Allows all species to tie their hair

code/modules/events/grubinfestation_vr.dm
Fixes typo in the followup grub alert.
We don't like no tpos here.
:cl:
fix: Fixed a typo in the second alert for grub infestation.
/:cl:
=> Fixes Typo in Grub Alert

code/game/objects/items/stacks/stack.dm, code/modules/mob/inventory.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/inventory.dm
title
qol
:cl:
add: stack splitting can be done via alt click and stacks automatically merge when they cross another stack.
/:cl:
=> stack crossover automerge and alt click splitting because clicking on 50 sheets of metal is not something that is okay  

code/modules/mob/living/carbon/human/emote.dm
:cl:
Add: a new emote for people to use. A rodent squeak
code: added *squeak as a usable sound emote.
/:cl:
=> Added rodent squeak emote

maps/tether/tether-01-surface1.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm, maps/tether/tether-09-solars.dmm
:cl:
fix: Solar SMES units will no longer drain master when they're wired.
fix: Shifts some areas in maint to no longer be misaligned
fix: The doors from the tram station into maint now have normal access
fix: Duplicate pipes under the old botany maint door have been removed
/:cl:
=> More tiny map fixes

code/game/turfs/flooring/flooring_premade.dm, maps/tether/tether-03-surface3.dmm, maps/tether/tether-05-station1.dmm
:cl:
add: Added a vat of cooking oil to the kitchen
add: Added a sink to the bar
tweak: Fixed up some of the air pipes and wires near the bar
tweak: Moved the meat coolers into the freezer
tweak: Sets the air alarm in the kitchen freezers to 4C/39F (Within food safe temperatures). They'll spawn this cold, due to a change to the tiles.
/:cl:
=> Adjustements to Bar/Kitchen area

code/modules/projectiles/effects.dm
bad, stop making me knife laser impacts.
=> projectile effects no longer blocks clicks

code/game/machinery/vending.dm, code/modules/food/drinkingglass/shaker.dm, code/modules/food/food/snacks.dm
This will be handling the first big re-balance of food changes for the server. We're hoping to have this set in a way that chefs are no longer overshadowed by one singular food item they couldn't even make.
This is only a singular part of this adjustment. I want to eventually do at least three more waves of balancing as players report differences in their play experience, and if chefs need further buffs or a bit of dialing back to ensure the flow of the round is not affected in a negative manner.
QOL adjustments, that will also help add extra balance for players that were forced to rely on one single food item to not die.
:cl:
tweak: Lots o' number crunching and adjustment.
balance: Balanced Shaker to contain 30 protein and 10 nutriment vs 35/30. The protein value it to not immediately …
=> Revamped food changes part 1, also known as: Burgers only contained 4 useful food units while shakers had 65 omegalul.

code/modules/vehicles/rover_vr.dm
fixes invisibility exploit/bug
=> bluespace traffic accidents are bad, m'kay?

code/modules/mining/machine_stacking.dm
Fixes them not taking into account stack amount when inputting and some other pet peeves about code quality.
=> fixes stackers being horrendous shitcode

code/game/machinery/computer/supply.dm
Fixes issue #1739 that was letting anyone order from a supply console.
Fixes a glaring bug, and now cargo isn't doomed if someone breaks in and spends all their points.
:cl:
fix: Bug with Supply consoles
/:cl:
=> Cargo Supply Consoles NOW check for ID

maps/tether/tether-04-transit.dmm
A bit of extra beautification to the tether-mid point, as well as removing the magical extra chairs that sneaked in from the original PR.
QOL changes as the usual.
:cl:
add: more changes to tether midpoint.
add: Camera added so security and AI can see all of midpoint now with no issue.
/:cl:
=> Minor adjustments to Tether Midpoint

code/datums/supplypacks/engineering.dm
Tin
No
:cl:
fix: Fixed missing access to collector crate
/:cl:
=> Adds access to collector crate

code/game/machinery/vending.dm, code/game/objects/items/trash.dm, code/modules/food/drinkingglass/metaglass.dm
Quick adjustments to add a missing sprite or two, with very minor adjustments to a couple food items. Mainly was to get the price added to liquid protein, as well as its sprite.
QOL goodness.
:cl:
balance: Quick tiny adjustments to food.
fix: added missing price, and added sprite to used liquidprotein.
/:cl:
=> Food & Drink part 3: Known as, I forgot to set a price to liquidprotein, lul.

maps/tether/tether-03-surface3.dmm, maps/tether/tether-06-station2.dmm
Fixes immediate round-start issues with surface-3 and adjusted a fire extinguisher up on asteroid-2.
Fixes immediate issue that causes Kitchen to have no power after a while.
:cl:
fix: added proper cable connection to kitchen so it doesn't run outta power.
fix: moved fire extinguisher onto an actual wall tile.
/:cl:
=> Quick Map Fixes

code/modules/mob/living/simple_animal/humanoids/head.dm
=> Removes forbidden word - Speedmerge Maybe

code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm
=> hardsync protean bug fix

code/game/objects/items/devices/radio/headset_vr.dm
Hey let's do a define that breaks the defines in another spot. Makes it so Vox headsets are displayed properly again.
Fix
=> Fixes Vox Headset Regression

code/modules/recycling/conveyor2.dm
=> UMM DID I ACCIDENTALLY MAKE CONVEYORS TAKE 10X THE POWER YES I DID 

code/modules/mob/living/carbon/human/species/station/protean_vr/protean_blob.dm, code/modules/mob/living/carbon/human/species/station/protean_vr/protean_powers.dm
=> protean fixes

code/modules/clothing/under/color.dm
=> Fixes Prison Uniform

code/modules/clothing/glasses/glasses.dm
Science goggles didn't actually cover the eyes so their airtight flag does nothing. Which means that you get the ole phoron burn on the eyes.
Bugfixings
=> Zhe Goggles! Zhey Do Something!

code/game/objects/items/weapons/dna_injector.dm, code/modules/materials/material_recipes.dm, code/modules/mob/living/simple_mob/subtypes/vore/solargrub_larva.dm, code/modules/power/cable.dm
solargrub overlays
power cables no longer require examining at close up 
unnecessary =null in dna injectors (they're still broken for some inexplicable reason though probabyl due to the fucking New() override I hate vorecode holy shit lmao)
drying racks are in
=> Fixes some various things

code/modules/power/cell.dm
fixes rechargers and power cells.
=> "you are giving me more power than i need, instead of using what i need i will refuse to take it" said no sane code ever

code/modules/mob/living/silicon/robot/robot.dm
Y'know I don't really see any reason why an AI shell has to be limited to only Service, standard and clerical.
=> Removes the AI shell restriction

code/modules/food/food/snacks.dm
E
E
:cl:
tweak: Using the right sprite now omfg.
/:cl:
=> Fixing LiquidProtein Sprite cause whoopsy daisy.

maps/tether/tether-02-surface2.dmm
Fixing an immediate issue with the new garden. (wrong water tile). Also added stuff for AI to actually look in and see
QOL LOVE
:cl:
add: cameras, and holopads for AI players and sec
tweak: fixed water and last bit of lighting.
/:cl:
=> Minor Map Adjustments, honk.

code/modules/clothing/suits/hooded.dm
=> Winter Coat Flavourtext

code/modules/mining/machine_processing.dm
2 seconds --> 0.2 seconds tick
=> Speeds up ore processor

code/modules/mining/machine_unloading.dm
=> Speeds up mineral unloader

code/modules/mining/drilling/scanner.dm
instead of scanning the ground and outputting to the user it's scanning the user and outputting to the ground?
=> fixes mining scanners

code/modules/admin/verbs/smite.dm
=> ok but what if you can smite non-players

code/game/objects/items/devices/t_scanner.dm
=> fixes t-rays invis

code/__DEFINES/nifs.dm, code/modules/client/preference_setup/vore/08_nif.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/nifsoft/nif.dm, code/modules/vore/persist/persist_vr.dm, vorestation.dme
need to test this locally brb
moral of the story: don't use typepaths in savefiles because you can't migrate those.
=> migrates nif saving to an id based system

maps/southern_cross/southern_cross_jobs_vr.dm
Ehh can't hurt, people said they liked this.
=> SEARCH AND RESCUE IS BACK but it's an alt title sorry :(

code/game/objects/buckling.dm
I'm probably removing thi sagain if it becomes an issue but eh, fun's fun I guess.
=> Okay fine, we will readd being able to shove yourself into a chair even if it is already full

code/game/verbs/ooc.dm
why the hell not
if someone spams or something ban them lol, i trust our players to be reasonable and don't want everyone to be shut up for 60 seconds over a vote.
:cl:
tweak: ooc is now allowed during voting
/:cl:
=> OOC is infact allowed while voting

code/datums/looping_sounds/weather_sounds.dm
this is really loud, i like ambiance but it shouldn't be this loud.
:cl:
tweak: weather is quieter
/:cl:
=> turns down weather sounds

code/game/machinery/vending.dm
Re-adding the guns in here, but not as many as before.
Haha spess man go horizontal
:cl:
tweak: Re-added two guns and six mags of rubbershot.
/:cl:
=> SecTech Change (minor adjustment)

maps/tether/tether-02-surface2.dmm
E
A
:cl:
del: Removed birds from garden, lol.
/:cl:
=> Removing birds from garden to stop eating the fish, weh.

code/__DEFINES/atmos.dm, code/game/machinery/doors/checkForMultipleDoors.dm, code/game/objects/items/weapons/flamethrower.dm, code/game/objects/structures/janicart.dm, code/modules/mining/mine_turfs.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/simple_animal/humanoids/head.dm, code/modules/power/supermatter/supermatter.dm, code/modules/virus2/helpers.dm, code/modules/xgm/xgm_gas_mixture.dm, maps/RandomZLevels/listeningpost.dm, maps/tether/submaps/gateway/listeningpost.dm
But you all clicked on it anyway
=> Nothing to see here

config/legacy/config.txt
???? WHO THE HELL USES 0.6???? LIKE WHAT WHO USES 16.6666666667 FPS INSTEAD OF 20?
=> Makes default config use 0.5 ticklag instead of 0.6

code/modules/mob/living/carbon/human/emote.dm
AKA kevin fucking forgot ANYTHING at the end of the cat emote, making the game unplayable, so i fixed that by adding a !
=> i'm on my period

code/modules/admin/verbs/SDQL2/SDQL_2.dm
=> Fixes SDQL2 global proccalling

code/modules/mob/mob.dm
=> moves turf alt click examine to before the admin tabs in statpanel

code/modules/client/preference_setup/general/06_flavor.dm
=> Bumping flavortext max length per section to 8192 on request.

code/game/objects/items/weapons/storage/boxes.dm, code/game/objects/items/weapons/storage/boxes_vr.dm, code/modules/food/food/snacks.dm, maps/tether/tether-02-surface2.dmm
Fixes up some needed food values still after more testing (will do more soon). Adds nutriment to worms, and also tries to add a proper sprite for them for now.
QOL and balance
:cl:
add: worm box
tweak: food values
/:cl:
=> Fishing & Food tweaks pt 3: Otherwise known as, :agony:

maps/southern_cross/structures/closets/misc_vr.dm
unga dunga why not i forgot to not do this on the sync
:cl:
add: sars have machetes again
/:cl:
=> readds machetes to sar lockers

code/datums/supplypacks/engineering.dm
Changes the circuit board for the gyrotron crate
I was asked to do this
:cl:
tweak: Changed gyrotron circuit to gyrotron control circuit in gyrotron crate
/:cl:
=> Changes gyrotron circuitboard to gyrotron control board

code/game/objects/items/weapons/tools/crowbar.dm, code/game/objects/items/weapons/tools/screwdriver.dm, code/game/objects/items/weapons/tools/weldingtool.dm, code/game/objects/items/weapons/tools/wirecutters.dm, code/game/objects/items/weapons/tools/wrench.dm
holy shit who thought gating these tools behind precursor research and then making them basically useless was a good idea
=> hybrid tools no longer irradiate

code/modules/tables/interactions.dm, code/modules/tables/rack.dm, code/modules/tables/tables.dm
unintended, why are racks subtypes of tables.
=> racks no longer pixel place

code/modules/materials/materials.dm
morphium is now good at research and is pretty durable, but it's less good at weapons now
rarity = power which is why bohs are diamondgated
:cl:
balance: morphium is strong now
/:cl:
=> Buffs Morphium in line with its rarity

code/datums/supplypacks/hospitality_vr.dm, code/game/objects/structures/crates_lockers/closets/coffin.dm, code/modules/reagents/reagent_containers/blood_pack_vr.dm
Adds a new supply pack, the Vampire Care Package, which gets you a extra comfy coffin, a black suit, and 3 packs of O+ for 50 points
I asked if anyone wanted me to add supplypacks, and this was suggested, and I thought it was funny
:cl:
add: Comfy coffin
add: Vampire Care Package supply pack
/:cl:
=> New Supply Pack - Vampire Care Package

code/modules/power/apc.dm
pretty sure init is a byond builtin. maybe.
=> might fix apcs

code/controllers/configuration/entries/lobby.dm
=> config entry fix for gamemode vote

code/game/world.dm
We live in a world where server descriptions are still hard coded.
=> Adds Discord to desc for easier access

config/legacy/config.txt, html/changelog.html, html/templates/header.html
Adds wiki to button on top ( config/legacy/config.txt )
Adds wiki to wiki verb ( config/legacy/config.txt )
Changes wiki link in changelog to our wiki ( html/templates/header.html, html/changelog.html )
It allows our new wiki to be the primary source of information instead of one intended for another server. It may also prompt users to fill in information if something is missing.
:cl:
fix: Changed wiki link on the Changelog page to ours.
add: Wiki searching with the "wiki" verb works now.
add: Wiki searching from the button on the top of the screen works now.
/:cl:
=> Wiki links replacement

code/modules/mob/living/carbon/human/life.dm
see title
well it was a thing before the sync and it was probably a bad idea but it still got merged
=> rig visors and mesons work through binocs again

code/modules/research/designs/mining_toys.dm, code/modules/research/designs/misc.dm, code/modules/research/designs/weapons.dm, code/modules/research/designs/weapons_vr.dm, code/modules/research/designs/xenoarch_toys.dm, code/modules/research/mechfab_designs.dm, code/modules/vore/fluffstuff/guns/pummeler.dm, code/modules/vore/fluffstuff/guns/sickshot.dm, modular_citadel/code/modules/research/designs/misc.dm
holy shit i hate this pr with a passion
- SOME SHIT IS NO LONGER SCATTERED AROUND THE ENTIRE PRINT MENU
- illegal tech now marked as Nonstandard designs in print menu
- stunshell design consistent with cost in autolathe(?), may be cheaper(?), whatever
- sickshot renamed Discombobulator
consistency with names and tool placements in the print menu, less stupid name for the sickshot, whatever else i forgot to point out
:cl:
tweak: R&D console has been slightly sorted out. It's still awful, but just...less.
/:cl:
=> digging through bad designs and stuff? maybe? it's just name changes really

code/modules/modular_computers/file_system/programs/engineering/supermatter_monitor.dm, code/modules/power/supermatter/supermatter.dm
Read about it in PolarisSS13/Polaris/pull/7009
Fix
=> Ports SM Mod Comp EPR Fix PolarisSS13/Polaris/pull/7009

code/game/objects/structures/fireaxe.dm, maps/tether/tether-07-station3.dmm
Added cork board to medical and sec, and hopefully (????) fixed fireaxes.
QOL and community suggestion and bug fixing.
:cl:
fix: fireaxe should be in case now
add: corkboards in sec and medical
/:cl:
=> Fireaxe and map adjustment

code/game/objects/items/weapons/melee/energy.dm
title
consistency balance sort of deal
:cl:
fix: Charge blades from R&D properly use their cell now.
/:cl:
=> chargeblade uses cell like it was supposed to

code/modules/client/preference_setup/loadout/loadout_xeno.dm, code/modules/clothing/under/xenos/vox.dm
Basic job pressure suits will come soon. This is also a test to see if I got the merging down right.
=> Adds new pressure suits for Vox in the service industry.

maps/tether/tether-01-surface1.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-03-surface3.dmm, maps/tether/tether-04-transit.dmm, maps/tether/tether-05-station1.dmm, maps/tether/tether-06-station2.dmm
Adding timeclocks on each floor to make it easier for crew to go off-duty and back on-duty as needed.
QOL love
:cl:
add: timeclocks on every floor
/:cl:
=> Adding timeclock to every floor, and oh god I hope this doesn't break

code/modules/research/designs/medical.dm
holy shit why are they so far down
cool analyzers deserve to be used
:cl:
tweak: Advanced and phasic health analyzers are now where they should be; with the rest of the health analyzer designs.
/:cl:
=> health analyzers are now all together again in the protolathe menu

code/__DEFINES/species_languages.dm, code/modules/mob/language/generic.dm
New fun language for crew to use that wanna squeak away at other rodents.
QOL and if we make an official rodent language we got one now in place.
:cl:
add: new language (Squeakish)
/:cl:
=> Adds an Official Language for Rodents. Squeak!

code/game/machinery/airconditioner_vr.dm
Thermal Regulators use New when they're called to be made which was no longer being called for mapped in Thermal Regulators which also meant they spawned with no component parts. This fixes that by swapping New with Initialize.
Parts are important
:cl:
fix: Thermal Regulators get their parts should they exist through inits.
/:cl:
=> Parts Are Important

code/modules/client/preference_setup/loadout/loadout_accessories.dm, code/modules/clothing/under/accessories/accessory.dm
"wyci". the words echo through your head. you are compelled to code the features you want.
=> custom desc/name necklace

code/game/machinery/bomb_tester_vr.dm
Does the same fix as the one for the Thermal Regulator
No bugs please
=> Bomb Tester Needs Parts Too

code/modules/mob/living/carbon/human/species/station/protean_vr/protean_blob.dm
lets blobs speak parent carbon's languages. incase blob is adminspawn, they get EAL and Galcom.
=> protean language fix

code/modules/reagents/Chemistry-Machinery.dm
=> Exploit begone

code/modules/client/client_click.dm
technically you do but the refocus is fast enough that it won't do much unless your'e typing and clickmashing at the same time
=> Non hotkey users now no longer defocus on clicks

code/modules/events/event_container_vr.dm, code/modules/events/hostile_migration.dm, code/modules/events/hostile_migration_vr.dm, code/modules/events/meteor_strike_vr.dm, vorestation.dme
Adds a new official Moderate level migration event that can take place. The event will spawn a set random number of hostile rats that flood into a department of the station, or in the surface tether area in general. Dorms will be protected from hostile actions (If rats show up PLEASE send an immediate ahelp for us to update/remove/bugfix). Also added a proper alarm sound to play when a meteoroid is about to strike the surface.
More events for sec and medical to enjoy during the round, and there is a small timer before the rodents actually enter the station giving time for crew to weld up areas and get lucky on stopping the migration.
:cl:
add: new hostile rodent migration event
add: sound effect trigger for major event meteoroid strike.
/:cl:
=> New Rat Migration event & Update to Random Events Part 1

code/modules/mob/language/station_vr.dm
:agony: This damn language had an un-needed directory tag
QOL fix and people won't be spewing around like crazy, as much.
:cl:
fix: fixed Pan-Slavic language
/:cl:
=> Fixes Pan-Slav no longer being Gibberish

code/_onclick/hud/human.dm
Copies PolarisSS13/Polaris/pull/6999
=> Display Internals Setting Properly after Reconnecting/De-AdminGhosting

code/game/objects/items/devices/flashlight.dm, code/game/objects/items/devices/geiger.dm, code/game/objects/items/devices/suit_cooling.dm, code/game/objects/items/weapons/tanks/jetpack.dm, code/game/objects/items/weapons/tanks/tank_types.dm, code/game/objects/items/weapons/tanks/tanks.dm
Copies optimizations from:
VOREStation/VOREStation/pull/7828
VOREStation/VOREStation/pull/7829
VOREStation/VOREStation/pull/7830
VOREStation/VOREStation/pull/7833
=> Optimization Lump

code/modules/clothing/under/accessories/accessory.dm
=> so it turns out i underestimated how short 200 characters was

maps/tether/tether-03-surface3.dmm, maps/tether/tether-05-station1.dmm
Adds a morgue to Tether for robotics, as well as a hallway connecting the shuttle dock to science to prevent artifacts going out into general space. Medical wing for exploration received some adjustments to better reflect what field medics usually do to prepare for shift. Adds a couple first-aid kits with a chemmaster, and medical RIGs in the prep room.
QOL love and helps exploration out on prep work.
Exploration: https://cdn.discordapp.com/attachments/697679518630019133/710648351615615018/Update-3.png
Robotics: https://cdn.discordapp.com/attachments/697679518630019133/710648356132618300/Update-1.png (Image is before electro windows and fire protection doors were added)
:cl:
add: Morgue and robotics hallway to shuttle
add: Medical updates to exploration
/:cl:
=> Robotics Morgue & Hallway + Exploration Medical QOL

code/modules/events/electrical_storm.dm, code/modules/events/event_container_vr.dm, code/modules/events/hostile_migration_vr.dm, code/modules/events/meteor_strike_vr.dm, code/modules/events/spacevine.dm
Updating some of our existing events, and fixed Electrical storms to now target multiples areas instead of just science (This is mainly a port from VORE which is a port from Baystations' back in March)
QOL love and slowly trying to bring updates to the server
:cl:
tweak: added electrical storm to all event weights and types
balance: Events manager weight adjustment, first pass
/:cl:
=> Fixing up events

code/modules/mob/living/carbon/human/species/station/protean_vr/protean_blob.dm, code/modules/mob/living/simple_mob/defense.dm
why do they take burn from halloss when a blob but not a human??
=> brings protoblobs in line with their carbon form

code/game/machinery/computer/camera.dm, maps/tether/tether-03-surface3.dmm, maps/tether/tether-06-station2.dmm
Changes the layout of the medical break room, and adds decals per BMs request :agony:
QOL and niceness
:cl:
tweak: Fixed up break room for medical, and decals to science.
/:cl:
=> IDK why this didn't show up earlier.

code/modules/events/event_container_vr.dm
Weight tweaking to newer events
Reducing the spam that these events spawn every single round.
:cl:
tweak: Weight number adjustment
/:cl:
=> Adjusted Weights

code/modules/client/preference_setup/loadout/loadout_eyes.dm, code/modules/clothing/glasses/glasses.dm
See title.
As it was requested, so it shall be. (Someone asked for this, I saw no reason not to.)
:cl:
tweak: Changed the way the White Blindfold uses blindness, so now you should be able to have a *small* amount of vision around your character.
/:cl:
=> Updates the White Blindfold to use the more modern form of blindness.

code/controllers/configuration_old/configuration_vr.dm, code/modules/paperwork/faxmachine_vr.dm
the tgs4 client crashed from this who thought this was a good idea?
=> can we stop logging every fax in the history of time to a single folder 

code/modules/mob/new_player/sprite_accessories_vr.dm
=> fixes inkling hair

maps/tether/tether-03-surface3.dmm
Adjusted minor decals
Posters and decals adjusted
:cl:
add: a few more posters to level 3
tweak: decal and poster locations
/:cl:
=> Adjusted Level-3 surface decals and posters

README.md
=> makes readme not boring

code/modules/keybindings/keybind/movement.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_movement.dm, code/modules/mob/mob.dm, code/modules/mob/mob_defines.dm, code/modules/mob/mob_movement.dm
Ctrl Shift Direction to pixel shift 
non erotic roleplay
:cl:
add: pixel shifting is now possible via ctrl  + shift + direction.
/:cl:
=> adds voluntary pixel shifting 

code/modules/mob/animations.dm
=> mildly important thing

code/__DEFINES/tgs.dm, code/modules/tgs/LICENSE, code/modules/tgs/README.md, code/modules/tgs/core/README.md, code/modules/tgs/core/core.dm, code/modules/tgs/core/datum.dm, code/modules/tgs/includes.dm, code/modules/tgs/v3210/README.md, code/modules/tgs/v3210/api.dm, code/modules/tgs/v3210/commands.dm, code/modules/tgs/v4/README.md, code/modules/tgs/v4/api.dm, code/modules/tgs/v4/commands.dm, code/modules/tgs/v5/_defines.dm, code/modules/tgs/v5/api.dm, code/modules/tgs/v5/commands.dm, code/modules/tgs/v5/undef.dm
basically the same as Citadel-Station-13/Citadel-Station-13#12364
no changelog because no playerfacing changes etc etc etc
=> updates dmapi from 5.2.0 to 5.2.1 

code/game/objects/items/devices/lightreplacer.dm
Updates the examine text for the light replacer to tell the player that it also takes broken bulbs as well as working.
=> Light Replacer Clarification

code/modules/mining/drilling/drill.dm, code/modules/power/apc.dm
Enables the Inducer to recharge APCs and big mining drills.
=> Allows APC and Drill Inducer Interfacing

maps/tether/tether-01-surface1.dmm, maps/tether/tether-02-surface2.dmm, maps/tether/tether-05-station1.dmm, maps/tether/tether-06-station2.dmm
add: Added PAI Cards to the following areas: Surface Locker Room, Surface Bar stairs, Middle floor Public Garden, Asteroid 1 abandoned library, asteroid 1 atrium, asteroid 2 public meeting room.
/:cl:
=> Adds PAI Cards to a few public places

code/game/objects/items/weapons/RCD.dm
=> how the hell did this compile

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Who at Polaris thought it was ok to make a reagent call itself in an infinite loop.
=> What the fuck

code/game/objects/items/weapons/tools/holotool.dm
fixes switchtools
why didn't you tell me earlier cunt
=> notsuchai is a bitch

code/modules/research/designs/medical.dm, code/modules/vore/fluffstuff/guns/cell_loaded/ml3m_cells.dm
Current Medigun cells are REALLY weak for what they costed and what you got from them. This buffs the core cells to be a lot more useful.
QOL and makes combat situations in the future easier for crew to overcome.
:cl:
balance: reduced cost of cells by 10% over all materials
balance: buffed core medigun cells by 2x
/:cl:
=> Buffing Medigun and reducing costs

code/modules/mining/abandonedcrates.dm
=> Fixes Abandoned Crate Rig Spawn to be Actual Rig

code/game/objects/items/weapons/storage/bags.dm
just testmerge this too busy to refactor rn
=> maybe fixes mining satchels

code/game/objects/items/weapons/inducer.dm
There was no check to keep someone from hopping onto a camera with an inducer in hand and remotely recharging things. That's a bit... yeah no. This fixes that.
It also fixes inducers locking up if you try to recharge a gun with its 'recharge_weapons' var set to 0.
Prevents... interesting scenarios with cameras and inducers.
=> Removes Long Distance Transmission from Inducers

code/modules/mob/living/carbon/human/species/species.dm
well whatddya know being lazy is a bad idea
=> fixes people not spawning with oxygen tanks

code/game/objects/items/weapons/tanks/tank_types.dm
=> fixes large air internal tanks spawning with bad gas ids

code/modules/mining/mine_turfs.dm
=> potentially fixes ore box dragging by silicons

code/modules/mob/language/generic.dm
Shells should know this language.
QOL
:cl:
fix: Un-ironically changed a 1 to a 0
/:cl:
=> Adjusting Language Understanding for Shells

code/modules/mob/living/silicon/robot/robot_modules/station/engineering.dm
Something that was lost in the hard sync being fixed. Also removes a duplicate of the RPD from the pupdozer inventory.
Consistency across modules, as well as not having duplicate module items.
=> Enables Pupdozer Plasteel Generator Again

_maps/map_files/Tether/tether-01-surface1.dmm, _maps/map_files/Tether/tether-03-surface3.dmm, _maps/map_files/Tether/tether-05-station1.dmm, _maps/map_files/Tether/tether-06-station2.dmm, _maps/map_files/Tether/tether-07-station3.dmm, _maps/map_files/Tether/tether-10-colony.dmm, code/modules/power/cell.dm
=> Fixes Cells Spawning with No Charge

code/modules/clothing/spacesuits/rig/rig.dm
=> Inducer can charge Rigs Now

code/modules/security levels/security levels.dm, config/legacy/config.txt
:cl:
tweak: Sounds more in-line with alert upgrades and downgrades
server: updated delta alert and downgrade to red alert to provide more use for it.
/:cl:
=> Update to Config Text for Alert Levels

code/modules/shuttles/escape_pods.dm, code/modules/shuttles/shuttle.dm, code/modules/shuttles/shuttle_specops.dm, code/modules/shuttles/shuttles_multi.dm
Its is the possessive form of it, meaning 'of it'. ... Its, without an apostrophe, is a possessive form, where an apostrophe is usually required. It is similar to words like his and hers, neither of which needs an apostrophe.
Its is the possessive form of it, meaning 'of it'. ... Its, without an apostrophe, is a possessive form, where an apostrophe is usually required. It is similar to words like his and hers, neither of which needs an apostrophe.
=> It's Its, not It's

code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm
proteans get all the fluff verbs xenochim do for the same reason xenochim do
=> proteans get all the fluff verb

code/__DEFINES/atmospherics/gas_strings.dm
Tin
We don't need two N2 tanks.
=> Actually put N2O in the N2O Tank

code/modules/materials/material_recipes.dm
Re-adds the ability to make airtight plastic flaps from the plastic sheet menu.
=> Re-allows Airtight Plastic Flap Production

code/modules/admin/chat_commands.dm
Ooga Booga I change one line!
Ooga Booga I get pinged about round end if I want to know!
:cl:
code: admin_only changed from TRUE -> FALSE on /datum/tgs_chat_command/endnotify
/:cl:
=> !tgs endnotify is finally not admin only

code/modules/events/hostile_migration_vr.dm, code/modules/events/spider_infestation.dm, code/modules/hydroponics/spreading/spreading.dm, code/modules/hydroponics/spreading/spreading_growth.dm, code/modules/hydroponics/spreading/spreading_response.dm
Fixing the numbers on current infestation style events to spawn more, and speed up the vines just a little bit.
QOL and keeping events a challenge for crew
:cl:
balance: Adjusted numbers on spawns and speed.
/:cl:
=> Random Events Buffs (Take two) FFS TravisCL

code/modules/atmospherics/atmosphere/_atmosphere.dm
sorry for the bad title im multitasking
=> uhhh maybe fixes the planet not being cold or something idk (check for gases existing to prevent runtime on atmosphere init)

code/modules/client/preference_setup/vore/07_traits.dm
Custom species now are able to set their blood properly
No more cumblood
=> No More White Blood (Unless you Really Want it)

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Fixes a small issue with the tea reagent
glass of cup of tea
no
=> Fixes small grammar issue with tea

code/modules/power/fusion/core/core_field.dm
Someone didn't indent their returns properly and made it so an if statement was just completely skipped over.
I dunno, why do you think.
=> Fixes the Warning on Compile

code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Why does custodial get light replacers but not engineering.
Let me see
:cl:
add: Light replacer to electrical closets
/:cl:
=> Let there be Light

code/modules/events/hostile_migration_vr.dm
Haha, why ya had to have a while loop that didn't terminate correctly? :agony:
Fixes an OOM crash with rodent migration.
:cl:
fix: Rat migration no longer eats the server.
/:cl:
=> Rat Migration no longer OOMs due to Vermintide.

maps/tether/submaps/tether_misc.dmm
"Runtime in code/modules/maps/tg/reader.dm, line 205: Undefined model key in DMM: tether_misc.dmm, mN"
=> Fixes to Misc failing to load.

code/modules/clothing/spacesuits/rig/rig_pieces_vr.dm
=> Sometimes Just Because it Compiles doesn't Mean it Works, Fixes Vulp Rig Helmets

code/modules/mob/mob.dm
now targets self plane if turf and target plane if not, and float layer
=> fixes pointing going under mobs instead of over

code/__HELPERS/logging_vr.dm, code/modules/mob/say_vr.dm
fine ill do it myself
adds a verb
invisible to ghosts
logged.
=> subtler. anti. ghost.

code/__HELPERS/unsorted.dm, code/game/verbs/advanced_who.dm, code/modules/admin/admin.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/verbs/deadsay.dm, code/modules/client/preference_setup/global/setting_datums.dm, code/modules/client/preferences_toggle_procs.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/mob_helpers.dm, code/modules/mob/new_player/new_player.dm, config/admin_nicknames.txt
ports main stealthmin systems
adds preferences for anonymous ghost chat, showing up on advanced who, ghost/observer joinleave, stealthmin preferences.
=> some stealth/min updates

README.md
=> Updates the readme to be more current to events

html/changelogs/AutoChangeLog-pr-2168.yml
This is literally one character web edited
=> Someone missed the Shift key

code/game/jobs/job/medical.dm
SPEED MERGE PLEASE. PARAMED SHOULD NOT HAVE THIS MUCH ACCESS OMEGALUL
AAAAAAAAAAAAAAAAAAAAAAAAAA
:cl:
tweak: e
balance: removed paramed mining access
/:cl:
=> Why does paramed have mining access like that lmao

nano/templates/jukebox.tmpl
Adds the Artist's name to the Jukebox UI until I can figure out how to make it cleaner but at the moment it's kinda barebones and not good looking but hey that language is pissawful anyways because it doesn't support if statements
First step at making it a touch less shitty
:cl:
add: A song's artist name will now display alongside the song on the jukebox selection menu.
/:cl:
=> Jukebox UI Minor Tweaks

code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm
Gives shadekins the trash-eat and lick-wound verbs.
why didn't they have either of those in the first place is unknown to me
:cl:
add: Gives shadekin trash-eat and lick-wounds
:cl:
=> Gives shadekin trash-eat and lick-wounds

_maps/map_files/Tether/tether-09-solars.dmm
Got a report something wasn't working with Toxins - found out that the burn chamber lacked two pipes. 
Other changes: Slightly smaller toxin disposal room, plants in the middle area have been changed to fit better, (No grass/flowery stuff and more what is normally spawned on the surface.). Added a minor adjustment to the western hall.  As well adds a console screen so people don't need to run back and forth too much.
Hopefully the last but will update and fix as issues come to my knowledge.
=> Sci post adjust/fix

code/modules/client/verbs/ooc.dm, code/modules/keybindings/keybind/mob.dm
tin
We have a OOC bind, so why not?
:cl:
add: LOOC hotkey
add: LOOC hotkey in prefrences
/:cl:
=> Adds hotkey for LOOC and changeable bind

_maps/map_files/Tether/tether-09-solars.dmm
see title
space hole bad
:cl:
fix: The hole in the floor in Toxins that led directly to space has now been patched over. Probably.
/:cl:
=> toxins floor hole fix

code/modules/mob/living/living.dm
=> fixes dogborg pixel shifting not shitcode edition*

code/modules/power/fission/engine.dm
basically #2039 
spite
:cl:
add: The Underdark is very tired of miners melting down fission reactors.
/:cl:
=> Meltdown Creaturepocalypse

code/__HELPERS/logging.dm
how the rp staff tolerates this i will never know
=> logs now also show the user's area because i don't realize how terrible this is until i have to use it

code/__HELPERS/files.dm
QoL what the hell I'm not waiting half a minute to grab logs.
=> drops log access cooldown from !20! seconds to 3.

code/modules/admin/verbs/SDQL2/SDQL_2.dm
=> sdql2 fix see main pr

code/game/jobs/job/civilian.dm, code/game/jobs/job/civilian_chaplain.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/exploration.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/security.dm
1. _Adds a collection of new alternate titles to jobs that specifically did not have at least one alternate before._
**Why:** Wanted to spice up job titles.
***Cargo Tech:** _Logistics Specialist_
***IAA:** _Ethical Compliance Analyst_
***Chaplain:** _Paracausal Scholar, Religious Affairs Liason_
***Chief Engineer:** _Director of Maintenance_
***Atmos Tech:** _Pipe Network Specialist_
***Pathfinder:** _Expedition Manager_
***Pilot:** _Aviator_
***Explorer:** _Field Scout, Pioneer_
***Chief Medical Officer:** _Surgeon General_
***Warden:** _Gaoler_
***Security Officer:** _Patrolman_
=> Job Description Morale Initiative

code/modules/mob/living/carbon/human/species/station/traits_vr/negative.dm
Its appears I didn't check my new traits closely enough. The Radiation Weakness Traits were accidentally named Radiation Resist instead. This fixes that error.
:cl:
fix: Changed the names for Radiation Weakness traits to be correct.
/:cl:
=> A Trait Fix

code/game/objects/items/stacks/stack.dm
=> will this fix splints i don't know testmerge it and find out @blackmajor

code/modules/client/preference_setup/loadout/loadout_xeno.dm, code/modules/clothing/under/xenos/vox.dm
Update to the update: fixing broken shit isn't fun.
more pressure suits baby wahoo
=> Update to the Update: Vox pressure suit update.

code/modules/client/preference_setup/loadout/loadout_gloves.dm, code/modules/clothing/rings/rings.dm, code/modules/clothing/under/accessories/accessory.dm
=> custom name/desc rings. custom necklaces can recolour.

code/modules/mob/mob.dm
=> pointing goes over things but it probably actually works this time because I didn't mistake FLY_LAYER for FLOAT_LAYER

code/game/machinery/fossilrevive.dm, code/game/objects/items/weapons/circuitboards/machinery/research.dm, code/modules/research/designs/circuits/circuits.dm, code/modules/xenoarcheaology/finds/fossils.dm, vorestation.dme
New machine, fossil DNA extractor. Hit it with fossils to process them.
Plant fossils can now be processed into a strange seeds packet (randomized everything.) 
Doesn't delete the fossil, but can't be repeated.
Fossils are no longer totally useless. Xenoarch-Xenoflora interaction.
planned to make animal fossils spawn a random animal or slime later for xenoarch-xenobio interaction.
:cl:
add: NT has rolled out a machine capable of extracting residual genetic data from fossils. Currently, it only processes plant-based fossils, however, the design may be updated in future.
/:cl:
=> Your scientists were so preoccupied with whether they could, they didn't stop to think if they should.

code/datums/autolathe/arms.dm, code/modules/projectiles/ammunition/magazines.dm, code/modules/projectiles/ammunition/rounds.dm, code/modules/projectiles/projectile/bullets.dm
First time coding aka just copy pasting shit and PR'ing it. I hope I didn't break shit. 
Added new 9mm and .45 Hunter rounds. Balanced to not be as powerful as 7.62. 
New map is opening up more possible uses of ballistics and energy weapons both. Security/Expedition crew both using this will prevent FF incidents from turning fatal while against hostile fauna.  
:cl:
add: Added new hunting ammo type for pistols
code: changed bullets.dm
/:cl:
=> [READY] New 9mm and 45. ammo types 

code/modules/power/lighting.dm
honestly why was this ever a thing please fuck off
=> removes the stupid fuckin' chance for lights to just BE BROKEN at roundstart

code/game/objects/items/weapons/inducer.dm
allows you to inducer smeses
untested because i hate testing shit on rpcode
:cl:
fix: inducers can charge SMESes now
/:cl:
=> induceable SMESes

code/game/objects/items/weapons/mop.dm
Buffs the mop to not suck as much!
QOL love for janitors
:cl:
balance: Improved HUD for cleaning & cleaning time
/:cl:
=> Mops don't suck anymore. Prepping for Sweep ability

code/modules/projectiles/ammunition/magazines.dm
Had a critical typo in Magazines.dm. Made everything Hunter ammo. 
Speedmerge please.
=> Magazine Coding Hotfix

code/global_vr.dm, code/modules/clothing/chameleon.dm, code/modules/mob/living/silicon/robot/robot_modules/station/service.dm
This will contain buffy:tm: fixes
Fixes #2079 
Fixes #2042 
Fixes #1745
=> Buffy goes through issues and fixes things

code/controllers/subsystems/lighting.dm
whoever wrote this is just terrible
=> instead of emitting 13000 runtimes, the lighting subsystem will instead try to actually fix itself using only 6 lines of code

code/__HELPERS/global_lists.dm, code/controllers/configuration_old/configuration.dm, code/modules/admin/verbs/randomverbs.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/death.dm, code/modules/mob/living/silicon/ai/latejoin.dm, code/modules/mob/mob.dm, code/modules/mob/new_player/new_player.dm, config/legacy/config.txt
Ports VOREStation/VOREStation#8050 as honestly, "Respawning" isn't really what it's meant for these days
This pleases the nerds of technicalities very much.
:cl:
tweak: tweaked a bunch of comments and removed a handful of //VORE Edits
refactor: ported the refactored code
config: changed some of the outdated config settings
/:cl:
=> Return To Menu - VOREStation/VOREStation#8050 Port

_maps/map_files/Tether/tether-03-surface3.dmm, code/game/jobs/job/science.dm
Stop thinking you're science when you're not aaaaaaaaaaaaa.
E
:cl:
tweak: Adjusted access on the Sci doors to R&D
/:cl:
=> Why the hell do so many people have R&D Access?

code/modules/resleeving/designer.dm
=> Body Designer Fix

code/game/objects/items/weapons/swords_axes_etc.dm
*groan
refactor when
30 pain force on nonlethal that should be good without being op
weaken is a hard no due to it being op.
=> 19 lines of absolute shitcode to make telebatons only harm on harm intent without making them hardstun

code/modules/overmap/ships/computers/ship.dm
bad signal + repeatedly reregistering
=> fixes overmap runtime spam

code/modules/events/cult.dm, code/modules/events/meteors.dm
Fixes sounds of meteors.dm and cult.dm
Stops ruining ears
:cl:
fix: Volume adjustment
/:cl:
=> Fixes sounds for some random events: also known as "OH MY GOD MY EARS ARE GONE"

code/game/jobs/job/security.dm, code/modules/client/preference_setup/loadout/loadout_uniform.dm, code/modules/clothing/under/miscellaneous.dm
**_Med-Sec Uniform_** gonzo. Speed merge please.
Someone else remove it from the .dmi please. 
https://www.youtube.com/watch?v=97du1N7Znb0
=> Removes something that shouldn't have been cleared in any way shape or form

code/game/objects/items/weapons/swords_axes_etc.dm
=> oh man i am in agony - ACTUALLY makes telebatons not ridiculously lethal

code/__DEFINES/_globals.dm, code/controllers/subsystems/emergency_shuttle.dm, code/datums/ai_law_sets.dm, code/game/machinery/computer/communications.dm, code/modules/busy_space/air_traffic.dm, code/modules/busy_space/loremaster.dm, code/modules/busy_space/organizations.dm, code/modules/gamemaster/actions/stowaway.dm, code/modules/gamemaster/actions/swarmboarder.dm, code/modules/lore_codex/lore_data_vr/orgs.dm, code/modules/security levels/security levels.dm
makes this code readable and makes it use managed GLOBs
yes
:cl:
code: cleaned up /busyspace/
/:cl:
=> Optimizes lorecode

code/game/objects/items/weapons/tools/holotool.dm, code/modules/mob/living/carbon/human/species/station/protean_vr/protean_blob.dm, code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm, code/modules/projectiles/guns/energy/modular/modulargun.dm, code/modules/projectiles/guns/energy/modular/modularlenses.dm
fixes an issue with modweapons and switchtools
fixes some things with proteans and headset keys 
proteans get a recharge battery now since they use power
tested
=> misc fixes

code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm
how come i havent fixed this shit yet
=> fixes proteans getting stuck in blobform due to instability

_maps/map_files/NSV_Triumph/triumph-04-deck4.dmm
tweak: Remodels the civilian shuttle
/:cl:
=> Civvie shuttle 2.0

code/modules/clothing/head/pilot_helmet.dm, code/modules/shuttles/shuttle_autodock.dm, code/modules/shuttles/shuttle_console.dm, code/modules/shuttles/shuttles_web.dm
fix: Pilot helmets can once again be linked to shuttle jump consoles.
/:cl:
=> Pilot helmets fixed

_maps/map_files/NSV_Triumph/triumph-01-deck1.dmm
add: Gives the CE his paperwork stamp back
/:cl:
Closes #2398
=> CE can have his stamp back

_maps/map_files/NSV_Triumph/triumph-01-deck1.dmm, _maps/map_files/NSV_Triumph/triumph-02-deck2.dmm, _maps/map_files/NSV_Triumph/triumph-03-deck3.dmm, _maps/map_files/NSV_Triumph/triumph-04-deck4.dmm
Adds proper airlocks to each deck, and a few more adjustments and changes to improve the ship.
QOL
:cl:
add: airlocks & a few other adjustments to map.
/:cl:
=> Minor Adjustments to Triumph Map

_maps/map_files/NSV_Triumph/triumph-04-deck4.dmm, maps/nsv_triumph/triumph_areas2.dm
add: Adds a new area for the Library Private Study
/:cl:
Closes #2397
=> The Library's Private Study is now a separate area

code/modules/admin/verbs/SDQL2/SDQL_2.dm
=> updates sdql2 yet again

code/__HELPERS/unsorted.dm
=> [NOT JUST SDQL2 MASS PROCCALL FODDER FOR ADMIN ABUSE I SWEAR] Shake() 

.github/workflows/update_tgs_dmapi.yml
Runs every UTC midnight, makes a PR if there's an update
Sample: https://github.com/Cyberboss/tgstation/pull/15
=> Adds automatic TGS DMAPI updates

.github/workflows/update_tgs_dmapi.yml
:cl:
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> Haha i'm dumb

.github/workflows/update_tgs_dmapi.yml
Old command won't add new files. git hard.
=> Fix git add in DMAPI update action

code/modules/vore/resizing/sizegun_vr.dm
Makes it so Size Guns don't need firing pins. Truly, a _small_ issue. Ha. See what I did there? This PR is clearly not a..._big deal_. Man, I'm funny.
=> Size Gun Firing Pin

code/modules/projectiles/ammunition/magazines.dm, code/modules/projectiles/ammunition/rounds.dm, code/modules/projectiles/projectile/bullets.dm, code/modules/projectiles/projectile/energy.dm
Prep work for @Captain277 approved changes in preparation to another project in the works. More to come trickling in.  Now without errors, or autolathe fuckery because this ammo isn't supposed to be available yet by normal means.
:cl:
add: Sniper Hunter ammo
fix: Makes Phase energy balls behave against appropriate mob types
/:cl:
=> New 7.62 Ammo & Phase Bolt fix

code/modules/nifsoft/software/13_soulcatcher.dm
QoL
:cl:
fix: soulcatcher emotes now format properly for the person emoting
fix: soulcatcher AR projections now support text formatting
tweak: soulcatchers now use distance rather than view/linetrace check, less cpu usage. range bumped to 7.
tweak: soulcatcher AR projections now use their eyeobj perspective rather than host perspective
/:cl:
=> soulcatchers: text formatting, better range for AR

code/game/objects/structures/crates_lockers/crates.dm
=> you can now toss things over/into garbage bins (and any other subtype of /closet)

code/modules/mob/living/carbon/human/emote.dm
removes the message from flipping
funny vertical spin spamming chat without message stacking because >no goonchat? cringe
why should i put one here
=> comedy is subjective but flipspam is unfunny

code/modules/nifsoft/nif.dm
OK I think it fucking works now
nme and nsay should work now, pog? credit to kfive for helping brainstorm what was wrong with this
:cl:
fix: maybe fixed soulcatchers for starting NIFs
/:cl:
=> Maybe fixes default soulcatchers?

code/game/objects/items/weapons/stunbaton.dm
=> removes disarm harmbatonning 

code/modules/nifsoft/software/13_soulcatcher.dm
=> monkey patches in pixel shifting for soulcatcher projections

code/game/turfs/space/space.dm
=> MAKES SPACE NOT ROOM TEMPERATURE

code/game/machinery/floor_light.dm
Floor lights can now have their color modified via either hex code, or entering the color name. e.g. green
:cl:
fix: fixed floorlights
/:cl:
=> fixes floorlights

code/modules/events/cult.dm, code/modules/security levels/security levels.dm
because buffy is tired of getting her ears blown out instead of her back
:cl:
fix: fixes cult sound volume
/:cl:
=> fixes the cult sound volume

code/modules/mob/living/carbon/human/species/station/teshari.dm
Reduces teshari speed and gives them a boost in health. This will drop their normal speed from 10 to 6.66 which is equivalent to normal tg/bee runspeed. Gave them a health boost so they can adjust.
With the code overhaul of movement speed and the fact that you no longer need less than 200 ping to properly play the game, teshari go a little too fast. This tones down their speed slightly while giving them a health boost to keep their speed more healthy for gameplay.
:cl:
balance: Reduced teshari speed but gave them a health buff to improve gameplay.
/:cl:
=> Adjusts teshari balance

code/game/objects/items/weapons/nullrod.dm
=> this should not have compiled

code/modules/shuttles/shuttle.dm
=> shuttles can no longer crush ghosts ai eyes and other technical mobs

code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
=> stops protean statpanel change on blobform change

code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
=> fixes protean blobform material consumption whitelist

code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
i know it was me because who else protean
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/2350
:cl:
/:cl:
=> how did i overwrite my own fix

code/modules/mob/living/carbon/human/species/species_shapeshift.dm
=> hair shapeshifting no longer balds you on cancel

code/modules/vore/fluffstuff/custom_items.dm
=> translocator malfunctions to unreachable locations now just puts it on recharge for 10 seconds instead of succeeding

code/__HELPERS/files.dm
=> fuck off with the 10 second log access delay

code/modules/xenobio/items/weapons.dm
Title.
Just a gun that shouldn't need a pin.
=> removes pin requirement on xeno taser (missed one, damn)

code/modules/mob/living/carbon/human/emote.dm
=> Unusable emote 'me'. Say *help for a list.

code/modules/mining/machine_processing.dm
see title
ore processor go fast, sometimes you need ore processor go no fast
ported from PolarisSS13/Polaris#7778
:cl:
tweak: The material processor can now be toggled to and from a slower processing speed.
/:cl:
=> ore processor speed toggle

code/game/machinery/rechargestation.dm
i didnt test this LMAOOO
- allows for hardsuit-wearers to step into borg rechargers
- charges their suit cell
- repairs their hardsuit modules
potential future addition:
- repairs suit breaches
suit charging cool
:cl:
add: Hardsuit wearers can step into cyborg chargers to recharge their suit.
/:cl:
=> hardsuit recharging via borg charger

code/modules/mob/living/carbon/human/species/station/station_special.dm
=> adds shapeshifting verbs to xenochimera because why wasn't it here

code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm
=> changes how xenochimera can regenerate because my brain is liquid

code/game/objects/items/stacks/medical.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm, code/modules/vore/eating/living_vr.dm
🆑 
add: adds new functionality to vampirism, including more immersive text feedback for parties involved
add: victims who have been bitten will now appear to have been bitten in their examine until treated
fix: changes the 'fat and bloated' examine text after feeding to be more appropriate
/:cl:
=> let's make vampirism not bad

code/modules/mob/living/carbon/human/species/station/station_special.dm
adds regeneration verb to xenochimera for damaged limbs/organs based off of their current nutrition
=> adds regeneration verb to xenochimera

code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm
:cl:
add: expands vampirism mechanics
/:cl:
*bloodsucker attacks are now logged
*can now feed on non-player mobs such as simple_mobs or anything in mob/living (note: if the mob is dead you can't feed on it)
*adds distinction between attacks on different mob types, such as:
-human v human
-synth v synth
-human v robot
etc
*half of nutrition gained from sucking blood is subtracted from the victim (balance)
*if the victim has 100 or less nutrition, any feeding on them will only harm them (balance)
=> adds more funcitonality to bloodsucker()

code/modules/food/food/snacks.dm
is this even a fix or a feature i don't know but let me poison food please
=> marks food as opencontainer so you can pois- errrr take toxins out of them ^w^

code/modules/clothing/spacesuits/rig/suits/station.dm, code/modules/clothing/spacesuits/void/station.dm
1. _Increases Mining Voidsuit rad resistance to 65._
**Why:** It was originally 20. This should help drop first-run miner lethality.
=> Increases Mining Void Rad Resistance So People Stop Dying, Even If It's Funny When They Do

code/game/objects/items.dm
no need to have separate lists
=> microoptimization for origin tech

code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/crates.dm
🆑 
fix: fixes fulton crates; specifically on closets and crates as they were reported by a user
/🆑
=> fixes fulton extraction packs

code/modules/materials/material_sheets.dm, code/modules/mob/living/silicon/robot/robot_modules/station/service.dm
=> unbelievably shitcode fix for janiborgs not being able to recycle glass which is caused by a bug that was the result of unbelievably shitcode code 

code/modules/reagents/Chemistry-Machinery.dm, code/modules/reagents/dispenser/dispenser2.dm
See title.
Chem master/dispenser will eject a beaker into the users hand, reagent grinders use radials now instead of nanoui.
Some misc chem machine fixes too.
=> Makes chem machines eject beakers into your hand. Add radials to grinder.

code/game/objects/items/weapons/barrier_tape.dm
fixes barrier tape reacting to ghosts
=> ghosts are infact supposed to go past the barrier tape

code/modules/reagents/reagent_containers/glass.dm
Fixes a small bug where pouring beakers into other beakers posts a message to chat about dipping the beaker into the beaker.
First time PR, let me know if there's a better way to do this.
=>  Suppresses beaker dipping for foods, drinks and other beakers.

code/datums/wires/autolathe.dm, code/defines/obj/weapon.dm, code/game/machinery/_machinery.dm, code/game/machinery/autolathe.dm, code/game/objects/items.dm, code/game/objects/items/weapons/storage/_storage.dm, code/modules/research/destructive_analyzer.dm, code/modules/research/rdconsole.dm
see PolarisSS13/Polaris#7784
dec 15 update: also see PolarisSS13/Polaris#7098
- RPEDs drop lowest part tier when used
- clickdrag RPED to destructive analyzer to decon lowest part tier
- destructive analyzer returns materials to lathe properly
- PROTOLATHE AND AUTOLATHE UI THAT DOESN'T MAKE ME WANT TO SCOOTER ANKLE
qol
:cl:
fix: Destructive analyzers now return material to their lathes properly.
tweak: RPEDs now drop lowest part tier when used inhand.
tweak: RPEDs can be clickdragged onto destructive analyzers to recycle lowest part tier.
tweak: Protolathes and autolathes are now less awful to look at.
/:cl:
=> polaris 7784 and 7098 port - RPED QoL, destructive analyzers return material to lathe, R&D UI improved

_maps/map_files/triumph/triumph-01-deck1.dmm, _maps/map_files/triumph/triumph-02-deck2.dmm, _maps/map_files/triumph/triumph-03-deck3.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm
Rework on the engineering/deck 1 while fixing the errored areas; Such as a camera installed on the doorway or wires placed in the wrong areas.
Fixing bugs, while making the engineering hallway straight as possible.
:cl:
/:cl:
=> Engineering rework/Additional error item, airlock and camera location fixes

_maps/map_files/triumph/triumph-01-deck1.dmm, _maps/map_files/triumph/triumph-02-deck2.dmm, _maps/map_files/triumph/triumph-03-deck3.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm
Security major re-work
Changing the security hallways into a straight line, while merging few empty areas into security for the sake of security navigation.
:cl:
/:cl:
=> Security re work

_maps/map_files/triumph/triumph-02-deck2.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm
Cafe re-done after the bug fix
Better cafe location, more snuggy
:cl:
/:cl:
=> Cafe re-comp, re-re-work

_maps/map_files/triumph/triumph-02-deck2.dmm, _maps/map_files/triumph/triumph-03-deck3.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm, code/__DEFINES/damage_organs.dm, code/game/machinery/vending.dm, code/modules/reagents/reagent_containers/syringes.dm, code/modules/reagents/reagent_containers/syringes_vr.dm, code/modules/virus2/biohazard destroyer.dm, vorestation.dme
Medical gear is no longer infinite in terms of CLEAN. You need to start replacing your syringes and gloves and make sure everything is washed and sterile before operating or jamming syringes in people.
Feedback request, and needed change that was removed way long ago.
:cl:
tweak: Re-enabled syringes giving infections if re-used
balance: Adjusted Germ Levels to prep for Virology rework
/:cl:
=> Medical Gear Unhugbox - Infections

code/datums/outfits/misc.dm, code/game/objects/items/weapons/id cards/station_ids.dm
makes it so that admins dont have to varedit merchant IDs to have access to their own ships
=> Fixes merchant IDs

code/game/objects/effects/spiders.dm
Gonna be real with ya cleaning up these things is an unnecessary chore.
=> Reduce spider Cocoon health from 60 to 10

_maps/map_files/triumph/triumph-03-deck3.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm
Makes a few small changes
Idk map fixes are cool
:cl:
fix: fixes name of xenoarcheology door
fix: fixes some misplaced? tiles in the entrance to explorer prep
fix: adds a sign to the robotics rear entrance to make it less of a small weird hole in the wall
hope: hopes this works as a first pr in literal months
/:cl:
=> Minor map fixes

code/_onclick/hud/human.dm, code/game/objects/items/devices/translator.dm, code/modules/atmospherics/zas/Phoron.dm, code/modules/mob/_modifiers/modifiers_misc.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/mob_defines.dm
@silicons hi please merge x
minor add of giving synthetics an cooling feature on a long cooldown. they'll still take damage, but this will enable them to not burn to death as their human counterparts would; machines taking a little longer with this. i plan to add/fix more with synths in the future, this is just a small start
=> re-adds a previously present PR

code/modules/mob/living/carbon/human/life.dm
fixes #2669
fixes #2665
:cl:
fix: fixes FBP/synths temperature values
/:cl:
=> fixes FBP issues some more

code/modules/admin/verbs/randomverbs.dm
as per @Captain277 's request
note: you cant locally narrate if there's no type of mob in view
:cl:
add: adds local narrate verb
/:cl:
=> adds local narration

_maps/map_files/triumph/triumph-01-deck1.dmm, code/game/area/areas.dm, code/game/machinery/embedded_controller/airlock_docking_controller.dm, code/game/machinery/embedded_controller/docking_program.dm, code/game/mecha/space/shuttle.dm, code/modules/modular_computers/hardware/battery_module.dm, code/modules/overmap/ships/landable.dm, code/modules/planet/weather.dm, code/modules/shuttles/shuttle_autodock.dm
see video: https://www.youtube.com/watch/jyCmnvBbm8Q
=> lets fix runtimes

code/game/machinery/jukebox.dm, code/game/machinery/jukebox.json, code/game/machinery/jukebox.txt
Kept you waiting, huh?
After nearly a year of stagnated development and burnout, I finally put out what I'd consider a personally acceptable update to the jukebox tracklist. People have asked, and although it took me damned near a full year - I did finally deliver. Others want to take up the torch of jukebox development that I left behind when I went on break, and I figure before we end up with any conflicting messes I should put out what I've left in limbo for a long while.
Adds over 100 new songs and 3 new genres to the jukebox. 
More music more good.
:cl:
tweak: Changed a small amount of tracks, some are new lobby tracks, others have been retired from the lobby, others have been shifted to the emag-only tracklist on the jukebox (very few). Changed a handful of genres around.
soundadd: …
=> Adds 100+ New Songs To The Jukebox

modular_citadel/code/modules/games/dice.dm
someone asked me to do this
:cl:
fix: dice no longer double rolls on throw
/:cl:
=> buffs dare dice

code/modules/mob/living/carbon/human/unarmed_attack.dm
robots no longer can be negatively affected by being punched in the balls
i should probably make them resist most things in unarmed melee combat but they're already stronger as it is
1. salt pr
2. protean buff
3. immersion
:cl:
balance: you can no longer kick robots in the nuts
/:cl:
=> salt pr: robots no longer have balls

code/modules/nifsoft/nif.dm
it should fix things lemme testmerge this rq
=> changes NIF init order to make the soulcatcher/commlink hopefully AFTER the new character mob is spawned in, instead of before.

code/modules/nifsoft/software/13_soulcatcher.dm
You lose out on the descriptive "please enter something to say into your soulcatcher", but this removes all client-server ping lag associated with pressing the command and the popup.
=> makes soulcatcher verbs clientside

code/game/machinery/painter_vr.dm
=> fixes colormate matrix mode labels 

code/game/machinery/vending.dm
=> adds leotards to vendors

code/modules/mob/living/carbon/human/species/station/traits/negative.dm, code/modules/mob/living/carbon/human/species/station/traits/positive.dm
i'm going to snap and redo the dumpster fire that is trait minmax powergame sooner than i thought at this rate
awful code on the tier of using `:`'s for a garbage unbalanced minmax system.
:cl:
fix: toxin_mod --> toxins_mod
/:cl:
=> fixes toxin weakness/resist traits causing runtimes

code/game/world.dm
*sigh
unneeded with 514 coming, it just crashed the server
=> Disables extools 

code/modules/asset_cache/asset_list_items.dm, code/modules/nano/nanoui.dm
woo yea woo yea 
without this it won't load properly due to things being in different directories.
=> makes nanoui a namespaced asset to work on our web server

code/modules/projectiles/guns/energy.dm
=> fixes energy guns runtiming

code/modules/client/preference_setup/loadout/loadout_head.dm
haha by request haha yeah.
they're nice
:cl:
add: wooden circlets and flower crowns have been added to the loadout
/:cl:
=> adds wooden circlets and all 4 types of flower crowns to the loadout by request

code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
turns out i told the previous coder it was a factor and not additive
so on this episde of I forgot to read the code..
slight buff from baseline shouldn't be too bad but i'm willing to restore it to normal if needed
:cl:
tweak: protean hunger rates fixed
/:cl:
=> fixes proteans hunger rate 600% --> 80% per author request (woops)

code/__HELPERS/text.dm
=> minor autocorrect fix

code/modules/projectiles/guns/energy/kinetic_accelerator.dm
:cl:
tweak: kpas now pressure dependent, 60 kpa
/:cl:
=> kpa changes

code/__DEFINES/flags/preferences.dm, code/modules/admin/admin_verbs.dm, code/modules/client/preference_setup/antagonism/02_candidacy.dm, code/modules/client/preference_setup/vore/06_vantag.dm, code/modules/client/preferences.dm, vorestation.dme
read the defines file it thas the descriptions
**WARNING: THIS IS PER CHARACTER.**
Unga dunga I want to see who wants to be what.
:cl:
add: event prefs
/:cl:
=> replaces vorestation vore-vent preferences with a bitflagged event prefs with descriptions

code/modules/keybindings/setup.dm
copied from what i did on main, forces a full reassert.
=> Adds fix-keybindings verb 

interface/stylesheet.dm
=> note this will not fix emote italics - removes italics span from old stylesheet.dm's emotes

code/modules/reagents/Chemistry-Recipes.dm, code/modules/reagents/distilling/Distilling-Recipes.dm
Old recipe code was only commented out, and one, now broken Recipe still was active, NO MORE
Commented out code is bad practice, but I forgot to remove it before the merge, and I forgot an old recipe in my commenting...
:cl:
code: Removed code that was no longer needed/Breaking stuff
/:cl:
=> [Ready to merge]Removes Remnants of old touch chem recipes

code/modules/overmap/ships/ship.dm
woops, incomplete process() conversion, wish SDMM had a linter enforcement of arg names able to be opted into for a proc.
=> Fixes overmap ships going 10 times slower than they should

code/modules/maps/tg/map_template.dm
there's still a config entry for submap rotation, but i'm also fairly certain changing it here will do the trick
=> lets randomize submap rotation less

code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
just because you tested your code doesn't mean it isn't broken, boys and girls
:cl:
fix: protean blobs climbing up onto people while they're nto adjacent
/:cl:
=> fixes an issue with proteans

code/modules/admin/verbs/SDQL2/SDQL_2.dm, code/modules/admin/verbs/SDQL2/SDQL_2_parser.dm, code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
i don't know who made this mess (probably me) but it's being replaced with a better mess
=> replaces sdql2 with main's sdql2 because that actually works 

code/modules/admin/verbs/randomverbs.dm
=> let's also replace cmd_admin_delete with main's because I just deleted someone on accident. Twice.

code/datums/browser/color_matrix_picker.dm, code/modules/client/preference_setup/loadout/gear_tweaks.dm, code/modules/client/preference_setup/loadout/loadout.dm, vorestation.dme
adds matrix recolor to all loadout options
We already have recolor, this is being applied to everything because unlike regular recolor there's not a single piece of clothing you can't manipulate with matrices with enough effort
Honestly this is probably better off only on clothing but uhh
I'm uh
sure no one will abuse this
.... right?
:cl:
add: matrix recolors are now possible in loadout
/:cl:
=> adds matrix recolor gear tweaks to everything

code/modules/mob/living/carbon/human/life.dm
=> protean temps

code/modules/admin/admin_verbs.dm
=> adds stop-sounds back

code/__DEFINES/spaceman_dmm.dm, code/__HELPERS/lists/associations.dm, code/game/world.dm
=> makes codebase compile on 514 (wow one line)

code/__HELPERS/global_lists.dm
=> fixes a pretty horrific memory leak

code/modules/clothing/glasses/hud.dm
see title
all ar huds are now prescription
Why? because they're advanced glasses that are also important to the job so having dogeyed people not be able to see while using them is dumb
e
:cl:
fix: fixes ar hud glasses to be simultaneously prescription glasses
/:cl:
=> now you dogeyed snowflakes can see with AR huds, congrats.

code/modules/mob/living/silicon/robot/drone/drone_items.dm
lets medical and sci grippers pick up nifs
cus AI good
:cl:
tweak: lets medical and sci grippers pick up nifs
/:cl:
=> AI shell users rejoice

code/modules/power/fission/rods.dm
The Fission reactor has ran into a few issues during the re-factoring and we're looking to handle some critically broken exploits with the reactor while looking to long-term/permanent fixes.
Immediate fix (??) on decay systems.
:cl:
balance: decay slashed.
/:cl:
=> [WIP] Rod Change 

code/game/machinery/newscaster.dm, code/game/objects/items/devices/communicator/UI.dm, code/game/objects/items/devices/communicator/communicator.dm, code/game/objects/items/devices/communicator/helper.dm, nano/templates/communicator.tmpl
Uses the PR from https://github.com/PolarisSS13/Polaris/pull/6713 to fix the newsfeed app on our communicators. Hopefully this does not cause any issues.
Fixes broken things.
:cl:
fix: Fixed communicators not displaying any stories in the newsfeed app. 
/:cl:
=> Fixes The Newsfeed App On Communicators Being Broken

code/modules/food/food/snacks.dm, code/modules/food/recipes_microwave.dm, code/modules/mob/living/simple_mob/subtypes/vore/horse.dm
1. _Adds Three New Sushi Rolls._
**Why:** Because Sushi.
We now have:
-Crab Roll: Two crab meat
-Horse Roll: Two horse meat
-Mystery Roll: Two ??? meat?
2. _Repaths Horse mob meat type._
**Why:** Horses now have their own unique meat.
None of the new rolls have unique sprites, for now.
=> Adds New Types of Sushi

code/modules/mob/new_player/new_player.dm
fixes #2670
see above
:cl:
fix: Cyborgs get announced again
/:cl:
=> Cyborgs rejoice, your presence shall be known

code/game/turfs/flooring/flooring.dm, code/game/turfs/flooring/flooring_decals.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#2797.
This should not have been merged.
=> Revert "[Review Needed]Moves floor decals from LateInitialize() to Initialize(), fixing floorpainter"

code/game/objects/items/storage/secure.dm
:cl:
fix: you can now switch briefcases between hands
/:cl:
=> fixes not being able to switch briefcases between hands

code/modules/organs/pain.dm
=> Fixes pain using SEND_SOUND instead of to_chat

code/modules/mining/mine_turfs.dm
=> fixes mining turfs creating mineral effects while not dense

code/modules/mining/mine_turfs.dm
=> bandaids mining turfs to properly recalculate lights when being dug pending full turf refactoring

code/modules/mob/living/silicon/robot/drone/drone_items.dm
Adds items to some grippers, fuel rods to engineers, beakers to service.
grabbits
:cl:
tweak: tweaks relevant items for borg grabbits
/:cl:
=> adds new items to grippers, doesn't rename them cus captain hates funny

code/modules/client/preference_setup/loadout/loadout_role_restricted.dm
amazin
cus miners getting health hud eyepatches was weird
:cl:
fix: loadout meson eyepatch
/:cl:
=> fixes meson eyepatch in loadout

code/modules/mob/mob.dm
rng's a number locally between 1 and n for you.
=> adds diceroll <n> command on request 

code/game/machinery/bioprinter.dm
hey so it turns out bioprinters not only did not match the rest of machinery code but they were also broken for god knows how long if you wanted to print anything other than limbs and specific organs
things not being broken is (arguably) good
:cl:Kraso
fix: Bioprinters are actually worth upgrading now.
/:cl:
=> fixes bioprinters not printing organs beyond the basic list

code/modules/client/client_procs.dm
=> moves panic bunker drop + db connection logging before most of client/New, maybe fixes no one getting the panic bunker drop message

_maps/map_files/triumph/triumph-01-deck1.dmm, _maps/map_files/triumph/triumph-02-deck2.dmm, _maps/map_files/triumph/triumph-03-deck3.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm, code/modules/events/cult.dm, code/modules/events/event_container_vr.dm, code/modules/events/hostile_migration_vr.dm
Adjusting the rate of mob spawns on the facility, as well as removing the mimics on the ship. A little bit of adjustment to maintenance too, and vents added to a room that needed piping.
QOL
:cl:
add: Surgery Maintenance area
add: Atmos for missing area
del: Mimics removed on all decks.
balance: Hostile mob spawn
/:cl:
=> Adjustments to Ship Events, Spawning & Map

code/game/objects/structures/stool_bed_chair_nest/bed.dm
=> roller bed code continues to be a dumpster fire

code/modules/power/supermatter/supermatter.dm
neat mechanic but kinda funny when you're a race that quite literally cannot fix hallucinations huh.
:cl:
balance: supermatter no longer hallucinates synthetics.
/:cl:
=> supermatter no longer makes synthetics, who cannot process synaptizine for the information, hallucinate.

code/modules/lighting/lighting_source.dm
read the code, it's, uh, complicated.
=> [testmerge only, experimental] makes dynamic lighting overmaps allow sensor usage in dust clouds 

code/modules/mob/living/carbon/human/life.dm
life() continues to be a joke that makes me lose faith in every coder who's ever worked on it
=> synthetic heat sinks now only activate if the user is actually over species.heat_discomfort_level. 

code/modules/power/fusion/core/core_field.dm
also adds cameras and all non mob/obj atoms to the blacklist
=> makes rust slightly less awfully buggy (please stop destabilizing due to the abstract concept of lighting)

code/modules/reagents/Topical-Recipes.dm
fixes hyronalin not mixing with topical agent into cleansalaze because people can't be assed to test their code or use a spellchecker
things not being broken is good
:cl:
fix: Cleansalaze mixes as intended.
/:cl:
=> sometimes life is cock and ball torture without the e

code/__DEFINES/misc.dm
Idk I type too much or something here
Doubles Max_message_len
Roleplaying is good, having to awkwardly cut up messages to make some wall-blocks fit is messy.  This is a minor nitpick, but.  I'm sure someone will like it
:cl:
tweak: Doubled max_message_len from 2048 to 4096
/:cl:
=> Enables Novel Posting.  RP edition!

code/modules/mob/living/carbon/give.dm
only things you can see + use typecache for type processing
=> fixes an oversight in give + microoptimization to its mob scan

code/__DEFINES/admin.dm, code/modules/admin/verbs/smite.dm
Adds a new smiteverb.
Dislocate all limbs.
bone
hurting
juice
:cl:
add: bone machine broke
/:cl:
=> Bone Hurting Juice

code/modules/clothing/spacesuits/miscellaneous.dm
Adds pressure and cold/heat protection variables to the Captain's Armor
The Captain's armor is functionally the same as the voidsuit but is cooler and is supposed to be spaceproof so I did it
:cl:
tweak: Fixes the Captain's armor to be spaceproof
/:cl:
=> Spaceproofs Cap Armor

code/modules/clothing/clothing_accessories.dm
=> what if i didn't keep accidentally stripping myself from moving my mouse one goddamn pixel?

code/modules/client/preferences_toggle_procs.dm, code/modules/organs/pain.dm, code/modules/vore/eating/living_vr.dm
:cl:
add: toggle pain messages
/:cl:
=> toggle pain messages

code/modules/power/port_gen.dm
old coders unironically tick me off to an unhealthy degree with this shit.
=> portable generators no longer explode from emps unless they are actually on. which, y'know, makes more sense. 

code/game/objects/items/robot/robot_upgrades.dm
im not even going to humor the blurb that goes here normally man
=> fixed the borg adv health analyzer module desc that referred to it as a carbon dioxide jetpack

code/modules/admin/admin.dm
=> oh that meme title was too long: removes the "are you certain" check from spawn 

code/_onclick/cyborg.dm, code/_onclick/item_attack.dm, code/game/area/Space Station 13 areas.dm, code/game/area/areas.dm, code/game/atoms.dm, code/game/turfs/turf.dm, code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm, code/modules/multiz/movement.dm
fixes borgs
infinite loops
gravity maybe
etc
=> fixes a bunch of things (borg attacks gravity etc combined pr) 

code/game/objects/items/weapons/manuals.dm
Updates the RUS-T manual to be more accurate to how it is used here.
People don't follow a guide to failure. 
:cl:
fix: RUS-T manual in game now is accurate.
/:cl:
=> Update's RUS-T Guide. 

code/modules/clothing/spacesuits/rig/suits/station.dm
Yes, I'm a snowflake.
Consistency reasons.
=> gives ce hardsuit magboots 0 slowdown just like the regular because you can just wear the regular anyways and the hardsuit one looks less awful 

_maps/map_files/triumph/triumph-02-deck2.dmm
now its in the chef's bar area near the arcade machines and i wish to drown in a concoction of every soft drink ever invented
=> moved the chef's soda machine because no one mentioned the spot was weird while the PR was still testmerged aaaaaa

code/modules/nifsoft/software/13_soulcatcher.dm
=> fixes soulcatcher ar projections and switches AR rendering to appearance cloning (quite literally 3 orders of magnitudes faster)

code/modules/food/kitchen/cooking_machines/_cooker.dm
=> This might make ovens heat up faster but they're a fucking dumpster fire so WHO KNOWS

code/modules/vore/resizing/sizegun_vr.dm
=> makes sizegun standard with other size nerfs

code/game/jobs/job/captain.dm, code/game/jobs/job/medical.dm
Apothecary needs no explanation
First/Executive officer for HOP were a bit confusing and didn't add much other than wonder
=> Removes more nonsensical alt-titles

code/modules/atmospherics/components/unary/heat_exchanger.dm
=> heat exchangersa re no longer dense

code/__DEFINES/controllers/_subsystems.dm, code/controllers/subsystems/events.dm, code/controllers/subsystems/overmap.dm, code/modules/overmap/overmap_object.dm, vorestation.dme
=> removes fun - no more spawning in dust clouds :( and i guess faster/more organized overmaps init 

_maps/map_files/triumph/triumph-04-deck4.dmm
Re-Uploading the new shuttle
Because of later merges, my already merged shuttle got overwritten. Here is the PR to get the shuttle in again.
It was already added, but was overwritten by a mistake.
:cl:
tweak: Added the shuttle again
/:cl:
=> Re-Uploading Exploration Shuttle

code/modules/nifsoft/software/13_soulcatcher.dm
=> soulcatcher appearance cloning now strips out hud overlays

code/modules/mob/living/carbon/human/species/species.dm
Ports over nose booping from vorestation/wherever it was originally created.
Just another bit of flavour that goes beyond hugging/patting heads/shaking hands.  Some may find use in it, others may not.  Another option for those interested, though.
:cl:
Add in nose booping
/:cl:
=> Nose booping because why not?

code/modules/mob/new_player/new_player.dm
this is a little annoying for debugging.
=> localhost no longer tries to ask you for your age (why is this not a config like it is on main again)

code/modules/vore/resizing/sizegun_vr.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#3034
Does the thing
=> Revert "makes sizegun standard with other size nerfs"

code/modules/client/preference_setup/vore/02_size.dm, code/modules/clothing/under/miscellaneous_vr.dm, code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm, code/modules/nifsoft/software/15_misc.dm, code/modules/resleeving/designer.dm, code/modules/vore/resizing/resize_vr.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#2993
Does the thing
=> Revert "max mob size reduced to 150% from 200%"

config_static/jukebox.json
=> Adds an extremely important song to the jukebox

code/game/objects/items/weapons/manuals.dm
By request, a more nerf'd guide is provided.
Less power more safety
:cl:
balance: Guide tells you the safest way to start the engine possible
/:cl:
=> NERF's RUS-T's Manual

code/modules/mining/ore_redemption_machine/equipment_vendor.dm
=> as funny as it is for AI to be able to telepathically steal miner ID's, let's uhhhhhh

code/game/objects/structures/bonfire.dm
=> Doubles the amount of fuel given to bonfires by wood, and halves their consumption.

code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm, code/modules/mob/living/silicon/robot/robot_modules/event_vr.dm, code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm, code/modules/resleeving/computers.dm, code/modules/resleeving/machines.dm, code/modules/resleeving/mirror.dm
Okay uhhh
Added some extra checking to mirrors so that you can't implant more than one, it also tells you if the person you're tryna remove it from doesn't have one
Fixed a bug that would allow you to spawn infinite mirrors
updated the text the resleeving recpient sees
gives dogborgs a mirror tool
bug bad
:cl:
add: Mirror tool for borgs
fix: fixed a bug that would allow infinite mirror production
tweak: tweaks spawn in text when resleeving
add: further sanity checks to the mirror tool for more easy usage
/:cl:
=> Mirror Update #1

_maps/map_files/triumph/triumph-04-deck4.dmm
adds a fucking light on deck 4
and also the HOS has a room that isn't a cave and also has a light switch
=> seriously how has this random stairwell been a black hole of darkness for this long after 14 million deck 4 remaps

_maps/map_files/triumph/triumph-02-deck2.dmm
=> crazy fucking idea i know but maybe ALL The dorms should have light switches instead of just some??

code/modules/assembly/timer.dm
=> don't you think timers should tick down 1 second every second instead of 1 second every 2 seconds?

code/game/machinery/cryopod.dm, code/modules/nifsoft/software/05_health.dm, code/modules/nifsoft/software/13_soulcatcher.dm, code/modules/resleeving/mirror.dm
redoes some of the logic for mirrors and also adds a (working) warning for attempting to remove a mirror from someone who has none
oh yeah also makes cryopods run a transcore save because
A why is that not already a thing
B Allows for round continuity since backup implants r dead
oh and mind backups aren't in the nifsoft shop now
=> slight mirror refactor + additional error reporting

code/modules/xenoarcheaology/tools/tools.dm
man no one notices these things are broken?
=> fixes xenoarcheology tools 

code/datums/world_topic.dm
=> exploration and command now renders properly in manifest checks

code/modules/admin/admin.dm, code/modules/mob/mob.dm
=> finishes renaming return to menu back to respawn, adds return to menu as an alias to respawn

code/modules/nifsoft/software/14_commlink.dm
have you ever kept forgetting to turn yours on
:cl:
tweak: nif commlinks automatically turn on
/:cl:
=> commlinks automatically activate

code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
Just fixes the hypospray.
I already fixed it in my previous PR but I think updating to master may have reverted those changes, so here she be.
:cl:
fix hypospray
/:cl:
=> Fixes medihound hypospray double bicaridine

code/modules/nifsoft/software/14_commlink.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#3125
testmerge this please i think i broke something
=> Revert "commlinks automatically activate"

code/modules/integrated_electronics/subtypes/output.dm
fixes
also buffs max range to 8 from 6 as compensation.
=> >light power should never be above 1 >circuit lights can go up to 6

code/modules/mob/living/carbon/human/death.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm, code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm, code/modules/mob/mob.dm, code/modules/organs/subtypes/machine.dm
*maybe* fixes protean death.
for real.
maybe.
=> despite making up only 3% of the population, nanite fetish blobs make up 75% of known bugs about speciescode 

code/modules/mob/living/carbon/human/human.dm
=> I'm at the point where I look at harmless code used for roleplaying flavor and see exploits everywhere :)

code/modules/mining/machine_unloading.dm, code/modules/mining/satchel_ore_boxdm.dm
makes O(N^2) --> !!!300,000!!! calls per tile to O(1) --> 10 calls per tile.
=> de-lags mining by about 5 orders of magnitude 

_maps/templates/engines/triumph/triumph_engine_burnchamber.dmm
Fixes a bunch of issues with the burn chamber submap.
More easy, less buggy, more aesthetic, less janky
:cl:
tweak: burn chamber re-layout
/:cl:
=> Updates triumph_engine_burnchamber.dmm

code/modules/recycling/conveyor2.dm
=> speeds up conveyors to 50 items/tick from 10

code/modules/catalogue/cataloguer.dm
=> requested by sillycowns

code/modules/events/event_container.dm
I'd be willing to place money down on a grand total of 5 people or less bother to interact with this event, or even know how to fix it, and it's otherwise a uninteresting inconvenience for everyone involved
"Gee Bill, I do love running across the station so I can click two buttons to keep my bones from being broken by cans
:cl:
del: Commented out the brand intelligence event
/:cl:
=> Comments out the Brand Intelligence event

code/game/objects/structures/crates_lockers/closets/coffin.dm
I might as well end my pedantic bitching on a high note, right?
🆑 
fixed: typo
🆑
=> Fixes the world's most pedantic typo

_maps/map_files/triumph/triumph-01-deck1.dmm
Title says it all.
Less lines of code makes Admemes happy. 
:cl:
/:cl:
=> Replaces wood, steel, and glass with 2x50spawners 

code/modules/events/event_container_vr.dm
IHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILESIHATEVRFILES
I already did this
:cl:
del: Comments out Brand Intelligence. Again.
/:cl:
=> Comments out Brand Intelligence part 2

code/modules/busy_space/air_traffic.dm
=> JESUS CHRIST GRAMMAR CHECK YOUR CODE

nano/css/icons.css, nano/css/layout_default.css, nano/css/shared.css, nano/css/shared_vr.css, nano/js/nano_base_callbacks.js, nano/js/nano_base_helpers.js, nano/js/nano_state.js
Baystation12 has responsive buttons, in testing locally, this gave our base them too.
less laggy buttons until tgui is fully in
:cl:
code: nanoui sync
/:cl:
=> Updates nanoui assets to baystation12's version

config_static/jukebox.json
music man good
adds three ULTRAKILL songs so Harold can be a little pogchamp
also two songs from Vektor, one from Daft Punk, and funny old song from Soft Cell
was also a decent excuse to get myself back into github/minor code stuff
haha more music variety
:cl:
add: new songs
/:cl:
=> adds music to jukebox

code/__HELPERS/areas.dm, code/game/area/areas.dm
teleportlocs need to be redone every time.
=> fix greater slime crystals and disposable teleporters 

code/modules/admin/view_variables/mark_datum.dm
=> mark datum is now global

config_static/jukebox.json
This was a hard to find song that was requested months ago that I finally found, told you I'd find it eventually :0)
Adds a song (that was a bitch to find)
Song is : Versti
Artist is: Peter Lasdauskas
More music is always a good thing
=> Adds a requested song

code/modules/catalogue/cataloguer.dm
exploration shouldn't be punished for being smart and splitting into teams.
:cl:
tweak: cataloguers have no range limit for point sharing anymore.
/:cl:
=> cataloguers now have infinite point sharing range 

_maps/map_files/tether/tether-03-surface3.dmm, _maps/map_files/tether/tether-05-station1.dmm, _maps/map_files/tether/tether-06-station2.dmm, _maps/map_files/tether/tether-07-station3.dmm, _maps/map_files/tether/tether_misc.dmm
tether
tether
:cl:
fix: tether builds
/:cl:
=> Tether: Compliable and Loading

modular_citadel/code/modules/vore/eating/living_vr.dm, vorestation.dme
:) i can't believe i'm doing this
=> fixes vore not working unless you have mobvore on

config_static/jukebox.json
yea yea i forgot to add them to the previous PR before it was merged sorry >:(
adds Astrix on Mushrooms by Infected Mushroom
adds Takyon (Death Yon) by Death Grips
adds Takyon (Death Yon) by Death Grips remixed by /k/ for added violence and warcrimes (emag only)
fixes Tin Tin on the Moon (Remixed) to be hearable
fixes A Shattered Illusion by Heaven Pierce Her to not end suddenly before the song actually ends by a few seconds
=> adds 3 more songs to the jukebox (i'm not being held hostage)

code/modules/client/preferences_toggle_procs.dm
=> updates instrument toggle string to be more consistent with others

code/game/machinery/biogenerator.dm
Hydroponics can now create eggs in the biogenerator
There is no otehr way to reliable obtain eggs once the kitchen supply is depleted
:cl:
add: Adds eggs to the Bio-Generator.
/:cl:
=> [RFTM]Adds a way to obtain eggs so I can keep smashing Tys

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm, code/modules/reagents/Drink-Recipes.dm
Added a new drink, Orange Ale. Planning on documenting it shortly. 
fixed peanut butter milkshake mixing, shirley temple tastes, a few typos... that's pretty much it.
proof of concept.
also testing an OC and it isn't turning out well 3:
adding a variety of drinks is always good, and with a little wiki documentation I can add orange ale to the list!
:cl:
add: Added orange ale. A slightly cursed but overwhelmingly fizzy combination of orange juice and ginger ale.
spellcheck: A local service cyborg blasted some typos from existence.
fix: you can now make peanut butter milkshakes again.
fix: you now correctly taste shirley temples.
/:cl:
=> Mitz's Culinary Adventures Vol. 1: M i l k and J u i c e

code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
Read our lore, Diona arent plants so why should they take damage from plant-b-gone?
Read our lore
:cl:
fix: Diona are no longer killed by plant-b-gone
/:cl:
=> Dionea arent plants, they shouldnt suffer like one

_maps/map_files/tether/tether-06-station2.dmm
Changes stuff in exploration
:cl:
tweak: Replaced exploration's oxygen tanks and co2 jetpacks with 02 jetpacks.
tweak: Gave the pathfinder restricted access to their office+locker.
tweak: Replaced precious foliage with a medical suit cycler for S&R
/:cl:
=> Exploration Edits

code/modules/mob/new_player/sprite_accessories.dm, code/modules/vore/appearance/sprite_accessories_vr.dm
A player requested this item be moved to ears, instead of hair, and that it be renamed.
This seems to largely be a cosmetic thing, but I suppose it helps with customization?
:cl:
tweak: Moved mature inkling hair to Ears and renamed it.
/:cl:
=> Moves Mature Inkling Hair from Hair to Ears and Renames It

code/game/objects/items/weapons/material/twohanded.dm, code/game/turfs/simulated/floor.dm, code/modules/mapping/shuttle.dm, code/modules/mapping/submap.dm, code/modules/maps/admin/ert.dm, code/modules/maps/admin/mercship.dm, code/modules/maps/generic/submaps/plains/plains.dm, code/modules/maps/tether/levels/underdark_things.dm, code/modules/maps/tether/shuttles/geckos.dm, code/modules/maps/tether/shuttles/mackerels.dm, code/modules/maps/tether/shuttles/salamander.dm, code/modules/maps/tether/submaps/debrisfield_vr.dm, code/modules/power/fusion/fuel_assembly/fuel_assembly.dm
=> fixes master

code/__DEFINES/math.dm, code/modules/mob/mob_movement.dm
diagonal moves were penalized too strongly
:cl:
balance: diagonal moves now take sqrt(2) instead of x2 time to do
/:cl:
=> diagonal moves are now euclidean 

code/game/machinery/doors/door.dm
tin
BUZZ
BUZZ
BUZZ
BUZZ
:cl:
tweak: Simplemobs don't make annoying buzz noises bumping doors
/:cl:
=> Players rejoice, non-client simplemobs no longer buzz doors they bump.

code/modules/fishing/fishing.dm
I just spent like half an hour fishing and getting nothing, figured I couldn't possibly be that unlucky. Turns out, defines. Weird first PR here I know.
:cl:
fix: fishing indoors should work again
/:cl:
=> make indoor fishing work??

_maps/map_files/tether/tether-02-surface2.dmm
The prosthetics fabricator in maint on surface 2 was an exosuit fabricator instead of a prosthetics fab. The machine has been replaced
:cl:
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
=> Maint Pros Fab Replacement/fix

config_static/jukebox.json
=> removes a really weird song from the jukebox

code/modules/clothing/suits/hooded.dm
=> wintercoats and epxlorer suits now have PHORONGUARD again 

code/modules/vore/eating/living_vr.dm, code/modules/vore/eating/vore_vr.dm, code/modules/vore/eating/vorepanel_vr.dm
Ever wanted to actually smell like flowers or butterscotch? Well now you can, or don't, you do you.
Some extra slice of life verbs
:cl:
add: Smell System from upstream
fix: Some of the formatting of the VORE Panel has been adjusted for consistency 
/:cl:
=> Smell System

code/__HELPERS/view.dm, code/modules/client/preferences.dm, code/modules/client/verbs/ooc.dm
Ports the Fit-Viewport Verb from CitMain
It's Fit-Viewport! We can now forgo the days of manual fitting
:cl:
add: Fit-Viewport
add: Other View stuff for future projects
code: Changed some code... Obviously.
/:cl:
=> QOL - What if we hold hands behind the Fit-Viewport verb 😳

code/game/objects/items/stacks/stack.dm
hilariously bandaid atm but it should work
=> fixes stack deletion bug (for the third time)

code/modules/food/recipes_microwave.dm
=> man i just wanted to make sushi instead i ended up figuring out how sushi works for 45 minutes 

code/modules/power/supermatter/supermatter.dm
why are hardsuits shitcode lol
too bad, my shitcode is stronger.
=> hardsuit mesons now blocks supermatter hallucinations (while active)

code/game/objects/effects/portals.dm
i personally hate this feature but, let's fix it anyways.
=> fixes hand teles not randomly jaunting you on fail

code/_onclick/click.dm, code/game/objects/items/storage/_storage.dm, code/modules/vehicles/bike.dm, code/modules/vehicles/cargo_train.dm
VOREStation/VOREStation/pull/7712
VOREStation/VOREStation/pull/11042
Lets have features that are just standard.
:cl:
add: Alt-Click support for Storage
add: Alt-Click and Ctrl-Click to some vehicles
/:cl:
=> Alt-Click Storage and Alt/Ctrl-Click Vehicles

code/modules/mob/living/carbon/human/species/station/station_special.dm
Cancelling makes it cancel
Kinda just annoying really
:cl:
fix: Xenochimera bioadapts now cancel properly
/:cl:
=> Fixes Xenochimera adapting abilities firing even if you cancel

code/game/objects/items/devices/defib.dm
bandaid
real fix is proper organ decay after baymed.
=> defibs no longer instantly kill people on the first defib

_maps/map_files/tether/tether-05-station1.dmm, _maps/map_files/tether/tether-06-station2.dmm
Splitting this up into four parts, because i'm super skittish about touching the shuttle points, and this is a good break spot anyways- This moves the QM and PF's offices, adds a 'secret' escape route, fills in the old space with some nice things, and as a bonus, fixes three other map issues on A1 while I was at it. ((A wall/door that lead to nothing, a timeclock terminal, and a stray pipe.))
Unlike the later PRs, which is why I'm doing the split here, this keeps the departments as closed up as they where before, and thus, I don't imagine there'll be any fuss over the changes. Maybe this'll also get me a maintainer actuially asking what the fuck I'm planning, so I can point them to the dozens of times I asked them specifically if what I'm planning was gonna fly or not. We'll see!
It gives …
=> Part 1/4 of my update to explo/cargo

code/__DEFINES/is_helpers.dm
closes #3355
vore changed the mouse path to what it is and forgot to update the ismouse()
=> very complex fix for mouse traps

code/game/machinery/cryopod.dm
this doesn't even fix the actual bug but atleast it makes it actually call the proc right
=> fixes runtime on cryoing out (goddamnit mirrors why)

code/modules/nano/nanoui.dm
file never had anything important and it's runtiming
=> removes shared_vr.css

code/modules/clothing/spacesuits/spacesuits.dm
they're unarmored and useless
why?
=> normal eva suits have 1 slowdown instead of 3

maps/~map_system/maps.dm
not being able to rescue people who are clearly alive and able to communicate really does suck, don't you think
this doesn't make it easy
this just makes it slightly more accessible.
=> makes empty space levels accessible by players

code/game/objects/items/devices/radio/headset.dm
:cl:
Short Version:
>Removes Pathfinder Bowman Ear Protection
>Refuses to elaborate further
>Leaves
/:cl:
=> Removes Pathfinder bowman headset ear protection

code/game/area/Space Station 13 areas.dm, code/game/area/ss13_deprecated_areas.dm, code/modules/maps/tether/shuttles/itglight.dm, code/modules/maps/tether/shuttles/shelter_6.dm, maps/nsv_triumph/triumph_telecomms.dm, maps/tether/tether_areas.dm, maps/tether/tether_telecomms.dm
there's no reason for this to be on most of the station
scenes do not prioritize over gameplay
=> removes telescience shielding from everything but the armory  and vault

code/game/objects/items/stacks/tiles/tile_types.dm, code/game/objects/structures/flora.dm
Finally got it working.
Anyways
Adds flora deconstruction via shovel, construction via grass tiles, and proper, more descriptive names
Decor, woot woot
:cl:
add: Added flora construction, deconstruction and names
/:cl:
=> Plant names, decon and construction

_maps/map_files/tether/tether-05-station1.dmm, code/modules/power/gravitygenerator.dm
1. _Adds the classic gravity generator machine._
1. Our gravity mechanics are janky and need a physical agent.
:cl:
tweak: Replaces the old knock-off gravity gen with the proper unit.
/:cl:
=> Updates our Gravity Generator to the Proper Sprite/Machine WIP

code/modules/client/preference_setup/loadout/loadout_utility.dm
1. _Reduces the cost of the Neural Interface Web and all "Dud" Implants in the loadout to zero points._
1. On RP these items serve no purpose beyond general roleplay flavor.  There shouldn't be a cost for character building functions this obscure. Also the NIW will literally kill you if you handle your damage mitigation poorly, so, balance.
:cl:
balance: Rebalances loadout costs for implants.
/:cl:
=> Loadout Implant Cost Reductions

code/modules/events/infestation.dm, code/modules/gamemaster/actions/infestation.dm, code/modules/mob/living/simple_mob/subtypes/animal/roach/roach.dm, vorestation.dme
1. _Adapts Hostile Migration code to repair unknown damage to vermin infestation event. Event now spawns mobs properly._
2. _Spiderlings spawned by Infestation will now mature, as will Roachlings._
1. For some unknown reason, after hardsync this particular event completely failed to activate and spawn mobs. Hostile Migration was confirmed to work, so Infestation has been recoded to match.
2. Spiderlings are a non-issue in the current variant. In the interests of giving Security more to do, and encouraging more proactive responses to vermin spawns, spiderlings and roaches can now mature.
:cl:
tweak: (Event) spiderlings and (all) roachlings mature.
fix: Vermin Infestation now functions.
/:cl:
=> Fixes and Buffs Vermin Infestation

_maps/map_levels/140x140/virgo4_beach.dmm
See Ursa/Pandora for any questions or details
=> Doing the Github part of a map update

code/__HELPERS/mobs.dm, code/__HELPERS/text.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/modular_computers/file_system/programs/command/card.dm, code/modules/surgery/robotics.dm
No longer will we be oppressed by stupid naming restriction by the shipbound creatures
Our Headmin would rather administrate stupid nameing trends than enforce them by code.
:cl:
admin: All names can now contain numbers and a few other specieal characters.
/:cl:
=> Numbers and certain specieal characters are now allowed in Character Names

_maps/map_files/tether/tether-05-station1.dmm, _maps/map_files/tether/tether-06-station2.dmm
Re-greebles cargo, adds missing sec-cams and intercoms, and moves one light. more to come.
Planned additions will finish the shop area south of cargo, build the docking port without functionality, and possibly adjust cargo hall, depending on how much people still bitch about it.
People like the floorpaint to look good. It'll probably take a few people looking at it to catch everything, but hey.
And since i'm having a PR open on this floor, might as well finish the other non-major changes that don't need to be itemized.
:cl:
add: greebles
add: intercoms
add: camera.
/:cl:
=> Cargo maintinance and docking port prep

_maps/map_levels/140x140/talon/talon1.dmm, _maps/map_levels/140x140/talon/talon2.dmm
Makes some alterations to the Talon. Mostly small, but one major.
Makes some minor touchups to the Talon, primarily focused on fixing the shield generator so that it isn't completely vulnerable to environmental hazards.
The Talon won't be a sitting duck and will actually use the Shield Generator/Comms room a bit more.
:cl:
tweak:Swaps the shield generator to Hull
add:Add a capacitor to the Shield Generator so that it will work
tweak:Makes the Shield Generator room slightly larger
add:Adds a Live Capture crate to the hangar
add:Adds a freezer to the medbay backroom
tweak:Rearranges the Workroom
tweak:Picks the Medkits off of the floor in the medbay backroom
add:Adds donk-pockets to the Bar area
/:cl:
=> Touches up the Talon

code/game/mecha/micro/mechfab_designs_vr.dm, code/game/objects/items/devices/communicator/communicator.dm
Removes MAT_Copper from the research designes
We cant aquire MAT_Copper anywhere, thus the recipes that use it are unaquireable
:cl:
fix: Research doesnt need copper anymore.
/:cl:
=> Copper based circuits for the synthetic insurgeons

code/game/area/Off Station Areas.dm, maps/tether/tether_areas.dm
yadda yadda funny copyright is funny
=> removes copyrighted nintendo music

code/modules/mob/living/simple_mob/subtypes/slime/xenobio/subtypes.dm
having a slime phase gas through windows is annoying
=> dark purple slime detonations now use an atmos floodfill instead of view() 

code/modules/busy_space/air_traffic.dm
someone please fix this when they can be bothered to, this is causing runtimes every trigger.
=> if you cannot code your air traffic spam right it does not deserve to exist

_maps/map_levels/140x140/fueldepot.dmm
The basic touchups as stands.
Changes things around in the Fuel station, primarily to make it functional.
As stands, the only way for the fuel station to get power is to manually refill the APC. Despite solars being available. This remedies that.
:cl:
tweak:Replaces the shuttle airless tiles with proper airless tiles, allowing the wires to actually exist.
tweak:Replaces the APC with the No Alarm variant. No more hearing it.
tweak:Named the pumps and ports with what they dispense.
add:Adds some vending machines.
add:Adds some registers at each arm, with a description of price.(Price is just something I made for the time being. Economy can be discussed later if need be.)
add: Adds railings to make the depot OSHA compliant.
/:cl:
=> Touchup the Fuel Station

code/modules/nifsoft/software/13_soulcatcher.dm
=> [requested] soulcatcher reexamine surroundings + multiline environments

_maps/map_files/tether/tether_plains.dmm
since mapdiff farted itself to sleep:
- Adds a consistent shell of external walls to the plains map
- Adds random pockets that are adjacent to air, and those walls
- Removes the 1-tile-thin upper rock layer between the top walls and the rest of the map
the planet won't be on fire (we are boring)
:cl:
fix:forest fires
/:cl:
=> ok admin man (adds open edge walls to virgo plains)

code/modules/mob/living/carbon/human/species/station/human_subspecies.dm, code/modules/organs/subtypes/subspecies_graver.dm, code/modules/organs/subtypes/subspecies_spacer.dm, vorestation.dme
Name is just to meme, actually it reenable the human subspecies for selection.
Reeenables the human subspecies, its really minorly varied version of humans.
Variaty I guess
:cl:
add: Space-Adapted Humans are avaiable as a playable species
add: Grav-Adapted Humans are avaiable as a playable species
add: Vatgrown humans are avaiable as a playable species
/:cl:
=> [RFM] Readds the Human Subspecies (Space/Grav-adapted, Vatgrown)

code/datums/supplypacks/misc.dm, code/game/objects/items/weapons/melee/misc.dm, code/modules/vehicles/skateboard.dm
Maybe having a debug skateboard buyable though cargo isn't great
Cleaning up
:cl:
fix: Fixed debug skateboard in crate
/:cl:
=> Adds new basic skateboard subtype

code/modules/power/singularity/particle_accelerator/particle_smasher.dm
can now multicraft
no longer buggy as shit
no longer literally nulls everything in it instead just takes what's necessary
more sanity checks for fuck's sakes
=> particle focus QoL overhaul [REQUIRES TESTMERGE]

code/game/jobs/job/captain.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/exploration.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/offduty.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm
Removes double department designations
:cl:
tweak: Debloats the manifest
/:cl:
=> Debloats the manifest

code/game/jobs/job/captain.dm, code/game/jobs/job/engineering.dm, code/game/jobs/job/exploration.dm, code/game/jobs/job/medical.dm, code/game/jobs/job/offduty.dm, code/game/jobs/job/science.dm, code/game/jobs/job/security.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#3575
This is quite literally intended behavior.
=> Revert "Debloats the manifest"

code/modules/food/food/drinks.dm, code/modules/food/food/drinks/bottle.dm
adds functionality to implement custom opening sounds for drinks. someone wanted this in admin chat
now you can set a path in a drink subtype's custom_open_sound variable to have it open to a specific sound that isn't the same can sound you hear by default
https://user-images.githubusercontent.com/42501819/141416405-f97abeba-0ff0-4271-ad63-60ab4d3e72e0.mp4
:cl:
/:cl:
=> custom drink opening sound qol

code/game/objects/items/devices/translator.dm
=> fixes omni translators

_maps/templates/engines/triumph/triumph_engine_sme.dmm
Removed extra pipes from the engine submap to match the rest of the sub maps.
Removed extra pipes from the engine submap to prevent silly overlap.
Consistency is nice. Double pipes bad.
:cl:
del: Removed two pipes from the SME Engine Submap.
/:cl:
=> Update Triumph SME Engine Submap.

_maps/templates/shuttles/overmaps/generic/cruiser.dmm, code/game/machinery/atmoalter/scrubber.dm, code/game/machinery/vending.dm, code/modules/reagents/reagent_containers/pill_vr.dm, maps/tether/tether_things.dm
About what it says, pulled my changes from silicones test merge so there might be some pain from that. Fixes a number of things like the external airlocks, weird anomalous space turfs in the middle of the ship, etc etc
:cl:
/:cl:
=> Triumph map fixes, changes, and button smashing

code/datums/outfits/jobs/security.dm, code/game/objects/structures/crates_lockers/closets/secure/security.dm
adds the fucking very important forensic instrument on a station where every mfer is gloved
idk they could do their JOBS
:cl:
add:forensic fucking gloves s2g
/:cl:
=> adds forensic gloves to detective lockers and to their starting outfits

code/game/objects/structures/stool_bed_chair_nest/chairs.dm
from red to black, almost everywhere
red ugly
:cl:
tweak: makes default sofa color black
/:cl:
=> makes the default sofa black

code/game/objects/items/weapons/implants/implant.dm, code/modules/projectiles/guns/energy/sizegun_vr.dm, code/modules/vore/eating/living_vr.dm, code/modules/vore/eating/vore_vr.dm, code/modules/vore/eating/vorepanel_vr.dm, code/modules/vore/resizing/resize_vr.dm
title
i get some people like this
i'll probably leave this on most of the time myself
however, frankly, i had 10 minutes of time to burn and i'd rather just get this over with than wait for the next complaint about  combat size gun usage.
These prefs don't do anything if you're <= 75% size, because there has to be some downside for intentionally being an unclickable micro.
:cl:
add: size prefs 
/:cl:
=> sizeguns, trampling, and pickups (when >= 75% scale) are now all preferences 

_maps/map_files/triumph/triumph-03-deck3.dmm, _maps/map_files/triumph/triumph-04-deck4.dmm, _maps/map_files/triumph/triumph-05-flagship.dmm, _maps/map_levels/140x140/talon/talon1.dmm, _maps/map_levels/140x140/talon/talon2.dmm, code/modules/maps/talon/talon_jobs.dm, maps/nsv_triumph/submaps/_triumph_submaps.dm, maps/nsv_triumph/talon_jobs.dm, maps/nsv_triumph/triumph.dm, maps/nsv_triumph/triumph_defines.dm, maps/nsv_triumph/triumph_overmap.dm, maps/nsv_triumph/triumph_shuttle_defs.dm, maps/nsv_triumph/triumph_shuttles.dm, maps/tether/talon_jobs.dm, maps/tether/tether.dm
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/3621 but it goes into triumph branch
FUCK I'm stupid
=> Correct branch

code/game/turfs/simulated.dm, code/game/turfs/simulated/lava.dm, code/modules/atmospherics/datum_pipeline.dm, code/modules/atmospherics/pipes/he_pipes.dm, code/modules/atmospherics/zas/variable_settings.dm
See changelog
People have been wanting HE Pipes on Lava interactions,
and it allows for more environmental plays with turfs.
:cl:
add: HE pipes now interact with lava turfs to gain temperature
code: Adds easy way to add more turf to HE-pipe interactions
admin: Adds variables to make turf interactions more or less efficent
/:cl:
=> Turf based temperature change in HE pipes

code/game/objects/structures/crates_lockers/closets.dm
guess my gimmick dies today 
(this isn't tested but it should work)
=> fixes locker exploit so cargo suffers more 

_maps/map_files/triumph/triumph-02-deck2.dmm, _maps/map_files/triumph/triumph-03-deck3.dmm, _maps/map_files/triumph/triumph-05-flagship.dmm, _maps/map_files/triumph/triumph_misc.dmm, _maps/map_files/triumph/triumph_ships.dmm, maps/nsv_triumph/triumph_defines.dm
Hot fix for issues in recent testmerge, fix supply shuttle runtime, fixes docking port runtimes with numerous shuttles
Fixes things
:cl:
/:cl:
=> Testmerge hotfix, docking port runtime fix, mapseeding fix

code/game/machinery/doors/airlock_electronics.dm
Why are we access locking who can or cannot make a door.
:cl:
tweak: removes access  locks from airlock electronics
/:cl:
=> no more access locks on airlock electronics

code/modules/vore/resizing/resize_vr.dm
=> moves a check around to stop unneeded message spam

code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm
fixes shadekin verbs, shadekin players rejoice
the way its intended to be, fixes a bug reported on discord
:cl:
fix: shadekins now get their verbs
/:cl:
=> shadekin verb fix

code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
=> : --> || in protean blob say_understands

code/modules/power/fission/engine.dm
Guys, a reactor exploded.
Stop hardcoding shit.
Stop hugboxing shit.
Go handle it IC.
And seriously? Who the fuck wrote THIS? Test your goddamn code.
:cl:
balance: Fission reactors are good for exploding again, even if they're a bad power source.
/:cl:
=> unhugboxes fission reactor explosions

code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm
=> woops accidentally made proteans unable to regen at all oh well maybe they deserve it

code/game/objects/structures/window.dm
fixes windows not rebuilding zones
engineering's bane.
=> how many coders does it take to fix atmos bugs with windows?

code/game/turfs/simulated/lava.dm
Makes it possible to bridge over lava, right now you cant built on lava without dying
:cl:
add: Added catwalk construction on lava
/:cl:
=> Allows for catwalk construction on lava

code/modules/clothing/chameleon.dm
Title
MY GOD how do you people tolerate going through this list
:cl:
tweak: Sorts the chameleon clothing list.
/:cl:
=> sorts the goddamn chameleon clothing list

code/game/machinery/atmoalter/pump.dm
You either know what this does or don't, if you don't it won't affect you.
It's annoying.
=> makes pump stop stealing focus during process() calls

code/game/dna/dna_modifier.dm
=> fixes dna modification re-referencing lists rather than cloning them

code/datums/recipe.dm
y'all are why we can't have nice things
=> microwaves were coded by satan himself

code/modules/admin/verbs/SDQL2/SDQL_2.dm
=> fixes me making SDQL2 waste CPU for no reason

code/modules/food/kitchen/cooking_machines/fryer.dm, code/modules/food/kitchen/cooking_machines/grill.dm, code/modules/food/kitchen/cooking_machines/oven.dm
I am fairly certain the long ass heating times weren't appreciated by anyone, in particular ovens.
:cl:
tweak:Ovens, fryers and grills now all heat up 3-5x faster
/:cl:
=> Makes the oven, fryer and grill all heat up ~3-5x faster

code/game/objects/structures/window.dm
fixes windows for real this time
=> how many coders will it take to fix atmospherics bugs in engineering (electric boogaloo)

code/modules/keybindings/keybind/movement.dm
we really, really need to get a sanitizer in savefiles at some point
=> fixes movement keybind defaults

code/modules/admin/verbs/SDQL2/SDQL_2.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#3660
=> Revert "SDQL_var microoptimizations (experimental)"

code/game/machinery/status_display_ai.dm
It doesnt work, and hardly anyone uses it.
Fixes #2708
:cl:
fix: fixed #2708
/:cl:
=> [Ready for (test-)merge]Fixes the ai_attack from the AI Display

code/modules/maps/tg/reader.dm
adds macro helpers for list handling to reader.dm
in hopes of fixing the frequent integration test failures, or at least mitigating the issue
Makes creating PRs less annoying, hopefully
:cl:
fix: Fixes Integration failures
code: Macro list access to prevent invalid index access in reader.dm
/:cl:
=> [Ready for merge]Adds macro helpers for list handling to reader.dm

code/game/machinery/atmoalter/canister.dm, code/modules/atmospherics/gasmixtures/gas_types.dm
Nebula gases work as reagents as well, we currently dont have the mechanics for that, I might add it to a later point
MOA!
:cl:
add: Added a varaity of gases
/:cl:
=> Adds Nebula Gas types without most effects

code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
replaces it with hugging noise
dogborgs don't need to be even more annoying
:cl:
tweak: dogborg booping now doesn't sound like a slip
/:cl:
=> replaces dogborg booping noise with something that isn't ridiculously goddamn obnoxious

code/modules/mob/living/carbon/human/species/outsider/event.dm, code/modules/mob/living/carbon/human/species/outsider/replicant.dm, code/modules/mob/living/carbon/human/species/outsider/skeleton.dm, code/modules/mob/living/carbon/human/species/station/teshari.dm
1. _Adjusts the Minimum Age data for various species._
2. _Increases the Maximum Age for Teshari._
1. All species' minimum ages are standardized.
2. Raises Tesh max age to 75.
:cl:
tweak: Standardizes hardcoded minimum ages.
/:cl:
=> Minor Species Age Alterations

code/game/objects/structures/window.dm
fixes fulltile windows disallowing exiting/reach
=> engineering pet peeves: window CheckExit() bug edition

code/game/atoms_movable.dm
applies text only ghosts can see.
Probably isn't, but it's funny.
=> adds ghost_tag() for admin shennanigans

code/__HELPERS/global_lists.dm
=> sorts hair alphabetically like any civilized codebase

code/modules/clothing/ears/ears.dm
=> powercreeps headphones

code/modules/surgery/surgery.dm
players keep complaining
:cl:
fix: fixes #3724 
/:cl:
=> corpsemend for cyborgs

code/__HELPERS/global_lists.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station/station_special.dm, code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm, code/modules/mob/living/carbon/human/species/station/traits/positive.dm, code/modules/mob/living/carbon/human/species/station/traits/weaver_objs.dm, code/modules/mob/living/carbon/human/species/station/traits/weaver_recipies.dm, vorestation.dme
:cl:
add: Adds the weaver abilities from vore.
/:cl:
=> Weaver abilities from vore

_maps/map_levels/140x140/tradeport.dmm, code/__DEFINES/machinery.dm, code/__DEFINES/misc.dm, code/datums/world_topic.dm, code/game/area/Off Station Areas.dm, code/game/machinery/suit_storage/suit_storage_prepared.dm, code/modules/maps/misc_maps/space/levels/trade_station.dm, code/modules/maps/misc_maps/space/levels/trade_station_jobs.dm, maps/nsv_triumph/triumph_defines.dm, maps/nsv_triumph/triumph_overmap.dm, maps/nsv_triumph/triumph_shuttles.dm, maps/tether/tether_defines.dm, vorestation.dme
Creating a new PR as #3715 was having _map conflicts_. This essentially does what the last PR did but includes all of Blue's fixes and such  
Nebulous station is nice
:cl:
add: More areas, new job role for nebulous gas, and such
fix: Wonky wire, people should be able to land now
code: Touched up on some code for job roles, didnt go full out and make nebulous its own job class like talon (I looked into preference code and it causes me fear)
/:cl:
=> Nebulous Gas PR 2 Electric Bogaloo

code/__HELPERS/text/scramble.dm, code/__HELPERS/type2type.dm, code/game/machinery/suit_storage/suit_cycler.dm, code/game/machinery/syndicatebeacon.dm, code/modules/atmospherics/components/valve.dm, code/modules/atmospherics/mainspipe.dm, code/modules/flufftext/TextFilters.dm, code/modules/mob/living/carbon/human/emote.dm, code/modules/power/singularity/singularity.dm, code/modules/vore/eating/leave_remains_vr.dm
:cl:
fix: fixed 16 warnings generated after an update
/:cl:
=> fixes sdmm warnings

code/modules/overmap/champagne.dm, code/modules/shuttles/shuttle_console.dm
:cl:
fix: fixed that champagne doesnt interact with shuttle consoles
/:cl:
=> should fix champagne not interacting with shuttles

code/game/machinery/doors/phoronlocks.dm
:cl:
fix: Fixed the Phoronlock Stationary scrubber cooling gas instantly
/:cl:
=> Phoronlock scrubber nolonger cool gas instantly

code/game/machinery/atmoalter/scrubber.dm
:cl:
fix: portable scrubbers can now scrubb the new gases out.
/:cl:
=> Adds the new gases to the scrubbing gas list

maps/nsv_triumph/triumph_defines.dm
I updated the announcements on common comms about the status of the shift transfer shuttle.
No more Schrodinger's Shuttle.
:cl:
fix: shrodinger shuttle removal/transfer shuttle tells us when it arrives at ship.
/:cl:
=> Marksman seriously needs to stop lying out the status of transfer shuttles

_maps/templates/engines/triumph/triumph_engine_burnchamber.dmm
Main work was dont my @ktoma36 in the pr #3746 
:cl:
balance: Reworks the burnchamber and gives it a minimalistic guide.
/:cl:
=> Burnchamber rework done and over

config_static/jukebox.json
like 18 songs go in, per Jackson#4111 's request. they all work and the list is alphabetically sorted
more songs more variety
:cl:
add: 18 songs to jukebox config
/:cl:
=> Adds songs to the country/western genre in jukebox

_maps/map_levels/140x140/Class_D.dmm, _maps/map_levels/140x140/frozen_planet.dmm, _maps/submaps/level_specific/virgo2/CrashedSmuggler.dmm, code/modules/power/smes.dm
It's frankly just unmaintained and terrible code, as well as flat out unnecessary at this point.
=> removes smes power alerts

code/modules/reagents/machinery/chem_master.dm
1. *Created Autoinjectors are now empty by default.*
1. _The autoinjector type used by the machine came with a default reagent. Changing it to empty allows the machine to fill it properly._
:cl:
fix: Fixes autoinjector bug.
/:cl:
=> Fixes Autoinjector Bug

code/modules/gamemaster/actions/infestation.dm
Funny challenges
:cl:
fix: Fixed Lizard infestions being the laughing stock of the server.
/:cl:
=> gives lizards steroids

code/game/jobs/job/exploration.dm
=> Containment Specialist as alt title

code/__DEFINES/_planes+layers.dm, code/game/atom_vv.dm, code/game/atoms.dm, code/modules/mob/death.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/mob/living/living_powers.dm, code/modules/mob/living/simple_mob/simple_mob_vr.dm, code/modules/mob/mob.dm, code/modules/mob/mob_grab.dm
you can now shift behind/infront of mobs on the same base layer/plane as yourself
pointing now animates
=> adds relative layer shifting + pointing animations

_maps/map_levels/140x140/Class_P.dmm, _maps/submaps/level_specific/class_p/archaictemple.dmm
1. *Isolating CI failures linked to mobspawn and POI anomalies.*
1. _These never appeared during initial checks._
:cl:
fix: CI breaking errors.
/:cl:
=> Class P CI Hotfix

code/datums/components/crafting/recipes/recipes_misc.dm, code/modules/mining/alloys.dm
1. *The Brass Alloy Machine Actually Produces Brass.*
1. _There was a line missing which resulted in consumption but no product._
:cl:
fix: Brass alloying fixed.
/:cl:
=> Fixes Alloying Brass to Actually Produce Brass

code/controllers/subsystems/lighting.dm
needless to say this does need a testmerge.
=> lighting subsystem is slightly more bulletproof

_maps/templates/engines/triumph/triumph_engine_fission.dmm
=> why would you put an eject button you'd wanna hit fast behind reinforced borosilicate glass tho

code/modules/reagents/reagent_containers/hard_candy.dm
Makes lollipops work with their intended use-case, being in your mouth.
why i gotta bite this shit lol
:cl:
fix: we are now capable of the succ
/:cl:
=> Spessmen are now capable of succ through mechanical means

code/modules/projectiles/guns/projectile.dm, code/modules/projectiles/guns/projectile/automatic.dm
Projectile-based weapons can now be tactically- and speed-reloaded. A tactical reload is exchanging a magazine in your hand for the one in the gun (useful if you want to change to a full magazine while keeping a partially-full one on you), while a speed reload drops the magazine in the gun onto the floor while quickly reloading it with one in your hand (useful for dumping an empty magazine and quickly putting a new one in).
When on **help** or **disarm** intent, nothing is changed.
When on **grab** intent, clicking a gun in your hand with the appropriate magazine will initiate a tactical reload. This will start a 1-second timer, after which the magazine in the gun and the magazine in your hand will swap places. You must remain still while doing this.
When on **harm** intent, clicking a …
=> Add tactical and speed reloads to projectile weapons

code/modules/atmospherics/components/binary_devices/heat_pump.dm
:cl:
fix: Fixes heat pumps being able to pump heat into empty pipe grids
/:cl:
=> Should prevent energy sinks

code/game/machinery/computer/skills.dm
guys c'mon can we please check what we're deleting??
=> fixes skills removal having removed player employment records from being printed

code/controllers/subsystems/ai.dm, code/modules/mob/mob_defines.dm
should safe some processing time for unused Zs
:cl:
fix: fixed mobs processing as high priority on default
/:cl:
=> makes mobs not process with high priority on default

code/game/objects/items/storage/mre.dm
1. *Adds Water Bottles to MREs*
1. _Drink mixes and stuff have an actual utility._
:cl:
add: Adds water bottles to MRE bags.
/:cl:
=> Adds Water Bottles to MREs

code/modules/client/preference_setup/loadout/loadout_donator.dm
=> Adds existing in-game item for donator loadout

maps/nsv_triumph/triumph_defines.dm
triupmh -> triumph
triupmh -> triumph
:cl:
spellcheck: triupmh -> triumph
/:cl:
=> fix misspelled name in crew transfer

code/game/turfs/turf_changing.dm, code/modules/atmospherics/environmental/zas/fire.dm
=> cleans up fire garbage collection 

code/modules/client/preference_setup/loadout/loadout_general.dm, code/modules/client/preference_setup/loadout/loadout_uniform.dm
Makes the uniform tab swimsuit actually give you swimsuits
And adds the capsules to the 'general' tab, so don't rage at me
Is it?
:cl:
add: Added the swimsuit capsule selection to general loadout tab
fix: fixed loadout swimsuits giving capsules instead of the suits
/:cl:
=> Swimsuit salt

code/modules/admin/callproc/callproc.dm
helps me when i'm debugging decade old shitcode a lot okay
=> admin proccalls that return a datum will give a VV link

code/game/machinery/telecomms/telecomunications.dm, code/modules/research/designs.dm, code/modules/research/research.dm, code/modules/research/server.dm, code/modules/unit_tests/_unit_tests.dm, code/modules/unit_tests/research_tests.dm
=> once again, looking at the research department's code makes me get unwise

code/game/turfs/simulated/wall_attacks.dm
You punch the wall!
Your left hand hurts.
=> attack_hand is called attack HAND for a reason, not "unhandled item attack, assume they used their bare hands"

code/modules/reagents/Chemistry-Reagents.dm
:cl:
fix:fixes hungry vampires being unable to drink blud
/:cl:
=> fixes hungry vampires being unable to drink blud

code/modules/client/preference_setup/loadout/loadout_general.dm, code/modules/client/preference_setup/loadout/loadout_uniform.dm
1. *Reasserts a PR that was wiped by a refactor.*
1. _As above._
:cl:
fix: Fixes PR overwrite.
/:cl:
=> Swimsuit Salt Hotfix/Reassertion

code/game/turfs/turf_changing.dm, code/modules/atmospherics/environmental/zas/fire.dm
=> fixes zasfire again

code/modules/client/preference_setup/loadout/loadout_uniform.dm, code/modules/clothing/under/miscellaneous.dm
1. *Restoring the original code resulted in a strange bug.*
1. _It seems we inherited a really odd bug from upstream regarding swimsuits. Namely that since they utilize capsules, apparently no one thought there should be a baseline/debug variant. This led to the swimsuit selection menu being pretty weird. This fixes that._
:cl:
fix: Lack of swimsuit debug item.
/:cl:
=> The Hotfix To the Hotfix

code/modules/mob/new_player/sprite_accessories.dm
1. *Makes Emo-Half Shaved tieable.*
1. _I dunno. I kinda just want it._
:cl:
tweak: Emo half shaved can be tied into a ponytail.
/:cl:
=> Makes My Preferred Hairstyle Able to be Tied

code/__DEFINES/_lists.dm, code/__DEFINES/controllers/_subsystems.dm, code/__DEFINES/dcs/signals.dm, code/__HELPERS/unsorted.dm, code/datums/datum.dm, code/game/area/areas.dm, code/game/atoms.dm, code/game/turfs/simulated/walls.dm, code/game/turfs/turf.dm, code/game/turfs/unsimulated/walls.dm, code/modules/mob/login.dm, code/modules/mob/mob.dm
Nothing surface level, just documenting and modernizing some minor things.
=> Some code cleaning.

code/modules/mob/mob_defines.dm
=> emergency hotfix - mob refs are all the same

code/modules/mob/dead/observer/observer.dm
=> fixes ghosts not seeing other ghosts

code/modules/reagents/Chemistry-Machinery.dm
=> grinders start with beakers again

code/datums/perspective.dm
Woops
need a null/valid loc check!
=> fixes roundstart being a black screen

code/modules/mob/new_player/login.dm, code/modules/mob/new_player/logout.dm, code/modules/mob/new_player/new_player.dm
using perspectives instead for new player, no more login/logout fuckery.
=> fixes lobby being a black screen

code/modules/cargo/supplypacks/misc.dm
for when there's no chaplain
this is expensive enough for 100 units of a relatively worthless liquid anyways
bartenders rejoice
:cl:
tweak: cargo now has holy water in chaplain equipment crate
/:cl:
=> adds holy water to cargo

code/modules/projectiles/projectile/beam/beams.dm
:cl:
fix: stun beams no longer play laser sfx
/:cl:
=> stun beams no longer play laser impact sfx

code/game/atoms_movable.dm
=> removes infinite recursion bug on acid_act

code/modules/mob/living/silicon/ai/ai.dm, code/modules/mob/living/silicon/pai/pai.dm, code/modules/mob/living/silicon/silicon.dm, code/modules/mob/login.dm, code/modules/mob/perspective.dm
=> Fixes mecha locking clent.eye to it on exit

code/modules/atmospherics/components/binary_devices/massive_gas_pump.dm
can we please stop making snowflake machines
=> this is not going to fix massive gas pumps but atleast it'll fix the interface not reporting when it's broken

code/_rendering/parallax/parallax_holder.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/perspective.dm
im going to lose it
there's literally no way to optimize perspectives even further
ah well, i'll worry about it when i see it on top 50 on the profiler
eugh.
=> emergency fix to some complicated backend logic

code/modules/mob/living/carbon/human/human_species.dm
flags aren't species flags
whoever wrote this can eat a dick
=> fixes human dummy runtime 

code/game/objects/structures/mineral_bath.dm
why does venus have **PHORON**
=> fixes adherent bath runtime

code/modules/admin/verbs/smite_vr.dm
1. *Reactivates the Autosave Smite.*
1. _This was disabled because it is allegedly broken and "would be fixed" later. It has not been fixed for probably around a year. So I'm restoring it until someone does fix it, because it won't get done otherwise._
:cl:
add: Restores Autosave smite.
/:cl:
=> Reactivates the Autosave Smite

code/game/landmarks/landmarks.dm
:cl:
fix: observers spawning in space
/:cl:
=> actually fixes observers spawning in space

_maps/map_files/rift/rift-02-underground1.dmm, _maps/map_files/rift/rift-03-surface1.dmm, _maps/map_files/rift/rift-05-surface3.dmm
uh wuh?
fixes stuff changes stuff
=> fixes frostlocks, maint changes

code/__DEFINES/carbon/species.dm, code/modules/mob/living/carbon/human/species/station/station.dm
Fixes Sergals to fit current lore. Simple as.
=> Makes Sergals great Again

code/game/turfs/unsimulated/sky_vr.dm
eugh this is bad but no choice yet, no ztraits to deal with this proper with /turf/simulated/open/chasm or w/e
=> monkey patches skyfalling to work with flight until multiz rework
