- code/game/machinery/spaceheater.dm
INTERACTION_FLAGS WHEN?????
oh wait, that's my problem
FUCK.
> monkey patches space heaters to actually be usable

- code/__HELPERS/unsorted.dm
> fixes turbolifts tearing holes into space

- tools/midi2piano/midi2piano.py
HOW DID I NEVER NOTICE THIS WAS GIMPING ITSELF
> bumps midi2piano max line limit and length to match server sanitization limits

- code/modules/admin/verbs/SDQL2/SDQL_2.dm
> makes sdql2 usable by people on laptops

- code/game/objects/items/devices/defib.dm
Trying to fix defib
:cl:
fix: Defib works?
/:cl:
> maybe fixes defib?

- code/modules/mob/new_player/new_player.dm
> fixes alt title join announce

- code/game/objects/items/devices/defib.dm
> fixes defib timers [existing]

- code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
1. *Removes Protean Ventcrawl*
1. _The discussion around this ability has been contentious and long-lasting, and even includes a prior attempt to do this very thing. This time, it's going through._
:cl:
del: Removes Protean ventcrawl.
/:cl:
> Removes Protean Ventcrawl - For Real This Time

- .vscode/extensions.json
- .vscode/settings.json
Funnee DMI Editor!
tgstation/tgstation/pull/66834
tgstation/tgstation/pull/66862
> VSC DMI Editor + Removing unneeded extension.

- code/modules/clothing/under/miscellaneous.dm
:cl:
spellcheck: name sweater_fem --> sweater
/:cl:
> sweater_fem

- code/modules/xenoarcheaology/finds/find_spawning.dm
> monkey patches archeology finds runtiming during CI until archeology is reworked

- _maps/map_files/rift/rift-02-underground1.dmm
- _maps/map_files/rift/rift-03-surface1.dmm
- _maps/map_files/rift/rift-04-surface2.dmm
- _maps/map_files/rift/rift-05-surface3.dmm
title
:cl:
add: Sec EVA Equipment storage room for Atlas.
tweak: Edited the cafe and access for various areas.
/:cl:
> Sec EVA Equipment, Cafe improvements, various bugfixes

- code/modules/tgui/tgui_window.dm
citaball
:cl:
fix: ping works again
/:cl:
> fixes tgui soft ping

- _maps/map_files/rift/rift-05-surface3.dmm
- tools/ci/check_grep.sh
> fixes errored space tiles, adds linter checks to forbid fuckups

- code/modules/mob/new_player/new_player.dm
come the fuck on this isn't hard.
> damn, ruins the point of having a security token if everyone gets sent it on connect

- .vscode/extensions.json
- Adds the Better-Comments extension into our extensions.json
This allows for various styles of comments that I've been standardizing for a bit now.
Here's a showcase of them I pull from the [extension page](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments)
> I thought everyone saw this formatting, apparently not.

- code/game/objects/items/stacks/stack.dm
i am so sorry
:cl:
fix: stacks no longer delete themselves for no reason
/:cl:
> fixes stack deletion bug after being reminded of it for about a year and a half

- code/game/turfs/simulated/floor.dm
> fixes wires being invisible (also known as my optimizations were a tad too aggro)

- code/__DEFINES/atmospherics/atmos.dm
- code/modules/atmospherics/gasmixtures/gas_mixture.dm
- code/modules/overmap/ships/computers/sensors.dm
- code/modules/power/fission/engine.dm
basically
ZAS was way too permissible with when to sleep
in theory this fixes that
> TESTMERGE THIS FIRST - completely rewrites ZAS equivalency checks

- code/__DEFINES/is_helpers.dm
- code/___compile_options.dm
- code/controllers/subsystem/garbage.dm
- code/game/objects/items/storage/_storage.dm
- code/modules/admin/holder2.dm
we're at 1.5GB on live
it's time to start optimizing dumb things like mining
> adds memory benchmarking procs to the codebase

- code/modules/client/preference_setup/loadout/loadout_suit.dm
fixed a typo on the coat loadout that I added
> Update loadout_suit.dm, typo corrected

- code/game/objects/items/weapons/tools/crowbar.dm
- code/game/objects/items/weapons/tools/screwdriver.dm
- code/game/objects/items/weapons/tools/weldingtool.dm
- code/game/objects/items/weapons/tools/wirecutters.dm
- code/game/objects/items/weapons/tools/wrench.dm
- code/modules/clothing/spacesuits/rig/modules/utility.dm
- code/modules/clothing/spacesuits/rig/suits/alien.dm
- code/modules/clothing/spacesuits/rig/suits/station.dm
- code/modules/research/rigs_vr.dm
Adds a pseudo-switchtool, and a welder to the RIG module list, as well as the respective science thingy, and a set to the CE's RIG.
//shrug//
But in all seriousness, this increases the utility of the hardsuits
:cl:
add: Added RIG toolsets and a way to craft them
/:cl:
> Adds toolsets for RIGs

- code/__HELPERS/misc/sonar.dm
> quick fix - sonar renders directions properly now

- code/modules/paperwork/paper.dm
> maybe fixes paper

- code/__HELPERS/misc/sonar.dm
> sonar layering

- config_static/jukebox.json
Title.
More songs means more variety, more variety is good.
Also, we need more early 2000s rep.
:cl: Cursor
add: Added four new songs to the Jukebox; Off the Meds by EKSE, Masters of War by Bob Dylan, Dice of a Generation by DEMONDICE and Misery Business by Paramore.
/:cl:
> Added four songs to the Jukebox.

- code/_onclick/other_mobs.dm
> fixes admin ai interact

- code/modules/projectiles/gun.dm
> fixes boolean logic in help intent safety

- code/modules/mob/dead/observer/observer_vr.dm
- code/modules/nifsoft/software/13_soulcatcher.dm
reapplies citrp optimizations and QOL that was wiped out by upstream sync
> fixes soulcatcher ERP

- code/game/atoms_movable.dm
> makes ghost tag containers right click ignored

- code/game/objects/items/weapons/traps.dm
should work assuming procs are called right
> fixes beartraps (probably)

- code/game/machinery/atmoalter/portable_atmospherics.dm
atmospherics, now including a QUICK RELEASE VALVE.
> streamlines the most obnoxious part of engine setup

- code/modules/power/apc.dm
at some point we'll need to rewrite APCs for the new system and to be less godawful in general
that day is not today, though
> fixes apc charging logic

- code/modules/power/apc.dm
tl;dr this is the best fix I could do, refactor soon(TM), currently APC cell logic is an utter trainwreck after the power rewrite.
> fixes APC logic (charging stays at 2 when cell is not fully charged)

- code/game/atom_vv.dm
> fixes base layer vv

- code/modules/clothing/spacesuits/rig/suits/station.dm
:cl:
Engineering hardsuit now has a slightly lower deploy time than standard
CE hardsuit now has a deployement time of 8, which was assigned to the standard Engineering hardsuit.
/:cl:
> Why is the Standard Engineering Hardsuit better than the CE hardsuit, AKA Salt PR

- code/modules/mob/hear_say.dm
it probably isn't but it'd be funnier if someone were to make memey emotes
please do not abuse this, this makes zero sense in actual dialogue.
nah
> adds ~strikethroughs~ to say_emphasis (aka ic say formatting)

- code/modules/resleeving/machines.dm
:cl:
fix: You can once again exit resleevers.
/:cl:
> DOORSTUCK - aka you can get out of resleevers

- code/controllers/subsystem/chat.dm
- code/controllers/subsystem/game_master.dm
- code/controllers/subsystem/input.dm
- code/controllers/subsystem/lighting.dm
- code/modules/ai/ai_holder.dm
- code/modules/ai/ai_holder_movement.dm
- code/modules/hydroponics/grown.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_movement.dm
nowhere near a perfect fix but
makes Recover() work where it should
makes a few things called from subsystems async to not block other subsystems
etc
> fixes a few bugs + makes a few things that really should be async async

- code/modules/multi-tile/multi-tile.dm
reworks multi tile hitbox checks
> the anti fun police is here to say that fighters aren't supposed to go through doors

- code/modules/multiz/zshadow.dm
- code/modules/turbolift/turbolift.dm
> fixes zshadow logic

- code/modules/overmap/sectors.dm
- code/modules/overmap/ships/panicbutton.dm
1. *Fixes the distress beacon not announcing its data properly.*
1. _Huge thanks to Kevin, who basically *actually* wrote the fix here. _
:cl:
fix: Fixes distress beacon alert.
/:cl:
> Fixes Distress Beacon

- _maps/map_files/rift/rift-03-underground1.dmm
- _maps/map_files/rift/rift-04-surface1.dmm
1. *Refines the fighter bay.*
2. *Removes vestigial anomaly area.*
3. *Replaces breath gear in civvie airlock with clear gas masks.*
1. _The bay was missing air alarms. While I was there, I added a small ready room with parachutes and exterior survival gear._
2. _This was just like, here, still. Removed it since we're going to be expanding on the Tether model._
3. _Pure aesthetic choice. People seem to like the clear masks more._
:cl: …
> Refinements to Fighter Bay and Adjacent Map Issues

- code/datums/components/crafting/recipes/recipes_primal.dm
- code/game/objects/structures/watercloset.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
1. *Same as the last. Attempts to fix collisions apparent in coffee, tequila, oil, and ash.*
1. _Same as the last._
:cl:
fix: Fixes remaining collisions.
/:cl:
> Attempts to Fix Remaining Reagent Collisions

- code/game/mecha/combat/fighter.dm
Causes a flat amount of damage when fighters collide with objects.
Adds some realism to piloting fighters. Flying a fighter indoors is now properly dangerous to the fighter, unless the pilot is sufficiently skilled as to not collide with objects.
:cl:
add: Added collision damage to fighters
add: Added alert message on fighter collision
/:cl:
> Fighters Collision Damage

- code/controllers/subsystem/planets.dm
> runtime fix: null checks for planet turf adding

- code/modules/mob/living/carbon/breathe.dm
at some point we need an error handler room.
> fixes nullspace breathing runtimes

- code/modules/jobs/job_types/station/civillian/librarian.dm
1. *Increases Librarian slots to two.*
1. _The library's pretty big, and we have a pretty versatile line of alt-roles for the job, so I'm adding one more slot._
:cl:
add: Adds a Librarian slot.
/:cl:
> Increases Librarian Slots to Two

- code/__DEFINES/lighting.dm
:cl:
tweak: Tweaked AO Values
/:cl:
> Tweaking Fake AO values to not be shit.

- code/modules/reagents/Drink-Recipes.dm
Fixes the Hot Coco Recipe to use milk instead of water.
Fixes the Hot Coco Recipe
Prevents Confusion with making of Hot Coco
:cl:
Code: Changed the water in the Coco Recipe to milk.
/:cl:
> Updates The Hot Coco Recipe

- code/modules/mob/living/carbon/human/human_organs.dm
race condition woo
:cl:
fix: people have the right blood type again.
/:cl:
> actually fixes blood types

- code/modules/multiz/zshadow.dm
:cl:
fix: you can see mobs from upstairs again
/:cl:
> fixes zhsadows

- code/modules/radiation/radiation.dm
:cl: the fun police
fix: radiation is fixed
/:cl:
> fixes radiation (please, learn to code, people, this is one line)

- code/modules/clothing/spacesuits/rig/modules/modules.dm
- code/modules/clothing/spacesuits/rig/modules/utility.dm
making rig stuff which is far more expensive than normal cutters/drills strictly shittier is just bad design
100 tiles only for a full highcap? really?
:cl:
tweak: rig plasma cutters/mining drills are far, far better (very little cooldown + power cost)
/:cl:
> buffs rig mining equipment

- citadel.dme
- code/controllers/subsystem/throwing.dm
- code/datums/callback.dm
- code/game/area/area.dm
- code/game/atoms_movable.dm
- code/game/machinery/atmoalter/area_atmos_computer.dm
- code/game/objects/effects/decals/Cleanable/fuel.dm
- code/modules/mob/living/living_defense.dm
- code/modules/projectiles/targeting/targeting_mob.dm
- code/modules/recycling/disposal.dm
I'm trying to sprite right now and this is causing me pain.
:cl:
add: Throwing subsystem.
/:cl:
> Minor tweaks so SpacemanDMM stops yelling at me.

- code/modules/clothing/spacesuits/rig/rig.dm
- code/modules/clothing/spacesuits/rig/suits/alien.dm
shitcode galore
we need to refactor this later
> fixes proteans draining 20 cell units/tick while moving from their rigs

- code/modules/power/singularity/collector.dm
this is a web edit, merge at your own risk
Its stupid that they arent dense, making them climbable kinda makes sense and still allows the utility of easy access
:cl:
tweak: Tweaks how atlas engine can be accessed
/:cl:
> Makes collectors dense again, and climbable

- _maps/map_levels/192x192/tradeport.dmm
1. *Changes Landing Pad Size and Rearranges Landmarks*
1. _If you're going to change the shape and size of core shuttles, for God's sake, please update landing pads too._
:cl:
fix: Fixes incorrectly sized landing pads.
/:cl:
> Updates Trading Post Landing Pads

- code/modules/food/food/snacks.dm
- code/modules/mob/living/simple_mob/subtypes/animal/passive/fish.dm
1. *Removes the neurotoxin from fishmeat.*
1. _Kinda sucks to be poisoned every time you fish up something that should be edible._
:cl:
del: Removes toxin from fish meat.
/:cl:
> Makes Normal Fish Meat Non-Toxic.

- code/modules/species/station/tajaran.dm
Local Dumbass mistake.
:cl:
fix: Corrects the tajaran spritesheets being used.
/:cl:
> Tajara Sprite Quick Fix

- code/game/objects/items/devices/flash.dm
> flashes doing 30 burn on people with flash vuln is kind of fucking stupid, am i right @rp coders

- _maps/map_files/rift/rift-06-surface3.dmm
defaults AI to actually have a good SMES that lasts most of the round + auto charges because this is fucking stupid
> let's not have AIs die for the crime of latejoining 

- code/modules/clothing/ears/ears.dm
- code/modules/mob/new_player/sprite_accessories.dm
look man this was the best option compared to a whole refactor or really fiddly snowflaking
tentacool ahahehaehehahuh
:cl:
tweak: every species can now wear skrelltacles
/:cl:
> gives up and strips all skrell hair and accessories of species limits (anyone can have tentahair now)

- tgui/packages/common/storage.js
noticing chat history being shared across codebases when it shouldn't, this _may_ fix it. testmerge first, please.
> attempts to separate tgui store from other servers

- code/datums/announce/_legacy.dm
- code/modules/overmap/sectors.dm
:cl:
fix: fixed Distress signals being way to loud
/:cl:
> No more ear splitting SOS

- code/modules/mob/living/simple_mob/subtypes/animal/space/thrumbo.dm
1. *Fixes issue in icon naming states.*
1. _Renames incorrectly sorted icon states._
:cl:
fix: Fixes icon state naming.
/:cl:
> Fixes Horing Icon State

- code/__DEFINES/mobs/organs.dm
- code/__DEFINES/species/species_flags.dm
- code/modules/client/preference_setup/general/03_body.dm
- code/modules/client/preference_setup/preference_setup.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/organs/external/_external_icons.dm
- code/modules/organs/internal/species/adherent.dm
- code/modules/organs/robolimbs.dm
- code/modules/species/outsider/celestials.dm
- code/modules/species/outsider/vetala.dm
- code/modules/species/species.dm
- code/modules/species/station/adherent.dm
Yes
:cl:
fix: Adherent work as they should.
/:cl:
> Adherent Fixes: You can stop yelling at me Papalus

- code/modules/events/infestation.dm
- code/modules/mob/living/carbon/human/human_organs.dm
- code/modules/mob/living/inventory.dm
> fixes inventory clickdrag to hand + "bioscans have indicated [void] has spawned in [void]" (infestation event)

- tgui/packages/common/storage.js
> i am an idiot (forces tgui store update)

- code/controllers/subsystem/job/job_controller.dm
- code/modules/mob/new_player/new_player.dm
:cl:
fix: fixed spawning issues from local
/:cl:
> Fixes joining issues for characters(hopefully)

- code/modules/xenoarcheaology/finds/find_spawning.dm
- config/config.txt
- config/entries/dbconfig.txt
> fixes config errors

- code/__DEFINES/inventory/procs.dm
- code/game/objects/items.dm
- code/modules/clothing/clothing.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/projectiles/guns/energy.dm
adds spooky var for ghost sliding
> fixes some inventory issues

- code/__DEFINES/_tick.dm
- code/controllers/master.dm
ping me on discord if you want an explanation of how byond works but tl;dr smoother game
> ports far more accurate MC tick limit predictions

- maps/rift/submaps/_rift_submaps.dm
> fixes one of our five planet's baseturfs (mappers please do the rest)

- code/__DEFINES/_flags/atom_flags.dm
- code/__DEFINES/dcs/signals/signals_item/signals_item_inventory.dm
- code/__DEFINES/inventory/procs.dm
- code/game/objects/items/weapons/melee/misc.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/head/hood.dm
- code/modules/clothing/head/pilot_helmet.dm
- code/modules/clothing/suits/hooded.dm
- code/modules/examine/descriptions/armor.dm
- code/modules/materials/material_sheets.dm
- code/modules/mob/freelook/eye.dm
- code/modules/mob/holder.dm
- code/modules/mob/inventory/inventory.dm
- code/modules/mob/inventory/items.dm
- code/modules/mob/living/silicon/ai/death.dm
- code/modules/mob/mob_grab.dm
- code/modules/mob/mob_pull.dm
- code/modules/organs/internal/augment.dm
- code/modules/organs/internal/augment/bio.dm
- code/modules/rigsuits/_rig.dm
:cl:
fix: flags
fix: clothing disappearing
fix: rigs not rendering properly
fix: grabs not forcemoving
fix: orbiting ai eyes
fix: qdel loops in grab/holder, dropped grabs
fix: ai eye examine runtime
fix: grabs making sounds on drop
fix: DROPDEL flag works properly now
fix: augment items making sounds when unequipping
fix: augmented shades
/:cl:
fixes #4320
> fixes a bunch of unrelated issues

- maps/rift/submaps/_rift_submaps.dm
1. *Updates Planetary Baseturfs.*
1. _Kevin alerted me that these needed to be updated. Here we are!_
:cl:
fix: Fixes Baseturfs.
/:cl:
> Updates the Baseturf For Every Other Planet

- code/modules/mob/living/carbon/human/human_damage.dm
tl;dr we care about if you use the proc or not now (because you should be using the healing proc instead of the damaging proc.)
> fixes alkysine

- code/modules/admin/DB ban/functions.dm
omg so true oomfie (this is why i shouldn't be trusted to touch SQL)
:cl:
fix: admins can unban people again
admin: oops
/:cl:
> *un*banning people is now possible again

- code/game/objects/structures.dm
- code/game/world.dm
- code/modules/admin/verbs/smite_vr.dm
- code/modules/modular_computers/file_system/programs/engineering/rcon_console.dm
- code/modules/power/smes/smes.dm
- code/modules/power/smes/smes_construction.dm
:cl:
fix: long running loop in smes decon
fix: vore smite breaking the game
code: removed useless code in structs
/:cl:
> fixes a bunch of uh really bad bugs

- code/game/objects/items/robot/robot_upgrades.dm
S Q U I D  G A M E S
:cl:
Cyborgs can now speak Vibrant when upgraded with the language module. Supposedly. Consistency between the Omni-Translator and the Language Module for Cyborgs
/:cl:
> Giving cyborgs more power, or how I learned to stop worrying and gave cyborgs the ability to understand Cephalopod Activities

- code/modules/games/cards.dm
on god i hate old coders
this entire file needs a rewrite but i can't be assed to today so have your 10 minute fix.
> fixes cards bricking people's hands

- code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
Tin
Stamp....
:cl:
add: smacked a stamp up in that cargo locker bruh
/:cl:
> adds cargo stamp to cargo locker

- code/modules/organs/organ.dm
> fixes rounding errors in organ health

- code/game/objects/structures/stasis_cage.dm
> you can now wrestle mobs into stasis cages

- code/game/objects/items.dm
read the code and find out why i said "pocket computer" instead of laptop.
> fixes pocket computers

- _maps/map_files/rift/rift-07-west_base.dmm
- _maps/map_files/rift/rift-08-west_deep.dmm
Should work fine. Not completely hugboxed, ((and indeed, I'd like this space to have new threats added eventually)) but it serves future purpose.
EM request
:cl:
/:cl:
> Story-progression-map-changes

- code/modules/mob/living/carbon/human/human_damage.dm
> fixes alkysine doing brain damage instead of healing it

- code/modules/mob/dead/observer/observer_vr.dm
- code/modules/nifsoft/software/13_soulcatcher.dm
tin
this is one of those things like anti-ghost emotes that i planned to add years ago and forgot about but coincidentally it's because it takes 15 minutes to add so i decided to wait until someone makes me want to add it
:cl:
tweak: advanced vis toggles for soulcatchers
/:cl:
> adds visibility toggle/blacklist/whitelist to soulcatchers

- citadel.dme
- code/__DEFINES/typeids.dm
- code/__DEFINES/vv.dm
- code/datums/appearance.dm
- code/modules/admin/view_variables/debug_variables.dm
- code/modules/admin/view_variables/topic_basic.dm
- code/modules/admin/view_variables/view_variables.dm
> adds byond internal appearance VVing via barely-documented black magic

- code/modules/vore/eating/vore_vr.dm
- code/modules/vore/fluffstuff/guns/cell_loaded/nsfw_cells.dm
tl;dr bugfix
but
i also decided to default them on
"but why, people just grief with these"
at some point having it defaulted off is probably akin to removing the items entirely which i am not doing, so.
> [s] finally hooks stripper gun prefs, defaults stripper/sizegun to on

- code/game/objects/items/weapons/handcuffs.dm
1. **Fixes a typo in handcuff description.**
1. _Self explanatory._
:cl:
fix: Fixes a typo.
/:cl:
> Fixes a Typo In Handcuffs

- code/game/world.dm
> attempts to stop the reboot crashes by giving rust_g hopefully 1 second to close all its threads

- code/modules/recycling/disposal.dm
Reduces the suction height of the disposals for airborne objects to pass through.
(Just makes items able to be thrown over disposals with overhand throw)
Why not.
> Disposal circumference suction reduction 

- code/modules/species/station/promethean/promethean_blob.dm
fixes protean emoting
also jesus christ blobform code continues to be utterly pants on head dumpster
> pov the slimegirl metagang sabotaged the protean erpers yet again

- code/__HELPERS/do_after.dm
- code/modules/rigsuits/_rig.dm
- nano/templates/hardsuit.tmpl
> [s] hardsuit fix

- code/game/machinery/pipe/construction.dm
- code/game/objects/items/devices/multitool.dm
> fixes some issues

- code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
1. **Reduces recipe cost of Tyrmalin Large charge.**
1. _Minor tweaks to charge cost for balance._
:cl:
tweak: Adjusts charge cost.
/:cl:
> Reduces Cost of Tyrmalin Heavy Charge Crafting

- code/game/turfs/unsimulated/sky_vr.dm
1. **Adjusts Skyfall to properly check turfs.**
1. _Turns out my prior fixes weren't actual fixes and somehow I was just getting really good odds on my redundant testing. Or I wasn't testing enough. Who knows!_
:cl:
fix: Enables turf checking for skyfall.
/:cl:
> The Final Skyfall Fix - Big Thanks to Kevin and Free!!!

- code/modules/xenoarcheaology/finds/special.dm
my disappointment is inmeasurable and my day is ruined
> a thousand curses upon the coders of eld

- code/__HELPERS/unsorted.dm
new turf translation system when??? shuttle rewrite when???
> fixes turf decal copying

- code/modules/cargo/supplypacks/supply.dm
1. **Raises Tyrmalin Mining Crate cost to 300.**
1. _120 is a little cheap for what it can do._
:cl:
tweak: Changes cost of Tyrmalin mining crate.
/:cl:
> Raises the Tyrmalin Mining Crate Cost

- _maps/map_files/rift/rift-01-underground3.dmm
- _maps/map_files/rift/rift-02-underground2.dmm
- code/game/area/Space Station 13 areas.dm
- code/game/machinery/doors/phoronlocks.dm
- maps/rift/rift_areas.dm
Im a dummy and forgot to put access on the lower airlock of mining. I also went ahead and put an actual cycling airlock in (Though its not working too well so Im still working on it, exterior cycling is not working properly). Also removed the delay on the elevator since it just kinda... holds the door shut longer which while funny isn't really fun. 
Fixes access and a few small things on the stationside of my earlier map edits
:cl:
fix: Access to mining underground area and airlock
/:cl:
> Lower Mining Access fix and airlock fix

- code/modules/species/xenomorphs/alien_powers.dm
:cl:
fix: fixed plasma transfer only working at a distance
/:cl:
> Fixes Plasma transfer

- code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
you know those super fast and agile xenomorphs? yeah, their slightly less lethal cousins cant even jump a table, well, they couldnt but now they can
:cl:
tweak: tweaked xenomorph hybrids to pass over tables like teshari
/:cl:
> gives xenohybrids the ability to pass over tables like tesh

- code/modules/mob/inventory/stripping.dm
tl;dr
we shouldn't be trying to open panel on ourselves.
> fixes stripping

- code/modules/lore_hardcoded/faction.dm
Fills in the blanks for factions! Yay!
1. **Fills In Faction Data.**
1. _As per instructions._
:cl:
add: Adds faction data.
/:cl:
> Adds Faction Data

- _maps/map_files/rift/rift-04-surface1.dmm
Prior to the addition of Virology medical had but 2 small psychiatric cells that were removed with the addition of Viro. As there is still use for psychiatric facilities on the station for both RP and gameplay purposes, I have added a full sized psych ward, with facilities for both monitoring and securing the mentally unwell.
:cl:
add: Psychiatric wing at the back of medical.
/:cl:
> Adds Psychiatric Ward

- SQL/database_schema.sql
- SQL/database_schema_prefixed.sql
- code/modules/admin/verbs/check_customitem_activity.dm
- code/modules/client/client_procs.dm
sorry we don't trust ckeys in this household it's time for unified `player` in a bit
> renames player table to player_lookup so we can do proper player table later

- code/game/objects/effects/mines.dm
1. **Adds Chlorine Gas Mines.**
1. _It's time to start experimenting with chemical warfare!_
:cl:
add: Adds chlorine gas mines.
/:cl:
> Project Picnic Sandwich

- code/modules/mob/living/bot/medibot.dm
No more broken medibot sprite for Toxin the medibot
:cl:
fix: Toxins Medibot Now Uses Right Skin name
/:cl:
> Fixs Toxins Medibot

- code/game/objects/items/weapons/grenades/chem_grenade.dm
- code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
1. **PR Got Merged A Bit Early.**
1. _Adds a gas grenade that was supposed to be included in PPS._
:cl:
add: Adds chlorine gas grenade.
/:cl:
> Lost Part of Project Picnic Sandwich

- config_static/jukebox.json
look at me im coding :)
Fixes the link for Year of the Rats by WittyUsername
Because music is good.
:cl:
add: "url": "https://files.catbox.moe/9kd1dl.m4a",
del: "url": "https://files.catbox.moe/0rlr3j.m4a",
/:cl:
> fix funny rat song link in jukebox.json

- code/modules/projectiles/guns/projectile/rocket.dm
1. **Fixes Collapsible Rocket Refiring**
1. _Should, anyhow._
:cl:
fix: Fixes issue with rockets firing even after expended.
/:cl:
> Fixes Collapsible Rocket Launcher

- code/modules/clothing/suits/hooded.dm
1. **Updates Storage Lists for Hooded Suits.**
1. _Synths shouldn't overheat if they want to dress up like a cute carp for Halloween._
:cl:
tweak: Tweaks storage contents for hooded suits.
/:cl:
> Updates Storage Contents for Hooded Suits

- code/modules/projectiles/guns/projectile/rocket.dm
1. **Fixes broken path in rockets.**
1. _I broke this, and I feel bad about it._
:cl:
fix: Fixes bad path in rocket unload proc.
/:cl:
> Hotfix for That Missile Launcher Fix, Because I'm Pretty Silly

- code/modules/atmospherics/machinery/components/binary_devices/heat_pump.dm
:cl:
tweak: tweaked heat pumps to connect to aux and normal pipe layer
/:cl:
> allows Heatpumps to connect to the normal and the aux pipes

- code/game/objects/items/stacks/nanopaste.dm
> probably fixes infinite nanopaste exploit

- dependencies.sh
Lots of goodies
https://www.byond.com/docs/notes/514.html
:cl:
server: Byond Minor Version bumped to 1588.
/:cl:
> Bump BYOND to 514.1588

- code/game/objects/structures/bonfire.dm
:cl:
fix: fixed a the fireplace and bonfire eating its fuel basicly instantly
/:cl:
> Fixess fuel consumptions

- code/modules/multiz/movement.dm
we'll make this better later like making flying mobs auto-unbuckle or whatever
> awful fix for buckled mobs not taking damage when their buckled object falls off a cliff

- code/modules/admin/DB ban/functions.dm
understandably "probably" is not the word you want to see in a SQL PR
but nothing bad can happen from this, so.
> (probably) fixes ban lookups

- code/modules/lore_hardcoded/citizenship.dm
- code/modules/lore_hardcoded/origin.dm
This adds the entries someone should need to make a character from Sol on the new lore system. 
Namely, OriCon citizenship and one Origin for each currently (unofficially?) lore'd (inhabited) body of the Solar System.
OriCon citizenship is a base necessity for this system in general, and this distills all of the proposed Sol Codex entries into a less-technically-written choice of Origin for Sol characters. 
(as always, this is not meant to be an exhaustive list, but there's already a catch-all "custom" Origin for this).
:cl:
add: Added Orion Confederation Citizenship.
add: Added Venusian Origin.
add: Added Terran Origin.
add: Added Lunarian Origin.
add: Added Martian Origin.
add: Added Phobian Origin.
add: Added Cererian Origin.
add: Added Jovian Origin.
add: Added Europan Origin.
add: …
> Adds OriCon Citizenship, 19 Solar System Origins.

- .github/workflows/ci_suite.yml
- .github/workflows/update_tgs_dmapi.yml
Read tgstation/tgstation/pull/70463
TL;DR - Some stuff got deprecated so we update so github doesn't complain.
> Updating Github Actions to V3

- _maps/map_files/rift/rift-06-surface3.dmm
1. **Puts Renault Back In the Captain's Quarters.**
1. _People miss this fuzzy boy._
:cl:
add: Returns Renault.
/:cl:
> Returns Renault

- code/modules/jobs/job_types/station/engineering/station_engineer.dm
I waited months for Maintainers to decide if I should add this, no information given back to me so I'm doing it anyways. Fuck you.
It's propably not, tbh. I just want a funny title.
Also, this is a webedit. I didn't test it since nobody else does. If Zandario or Kevin are reading this:
:cl:
add: Senior Engineer alt-title for Station Engineer.
/:cl:
> Señor Engineer

- code/modules/clothing/clothing.dm
in reality we need to dump the restriction system or rework it but whatever i'm busy
> laxes species restricted on refit for helmets

- code/modules/mob/living/carbon/human/update_icons.dm
1. **Removes update_icons check for cyberpsychosis.**
1. _This'll fix the check that's runtiming in update icons, by virtue of just removing it._
:cl:
del: Removes update_icons check for cyberpsychosis.
/:cl:
> Removes Update_Icons Check for Cyberpsychosis

- code/__DEFINES/admin.dm
- code/modules/admin/verbs/smite_vr.dm
1. **Changes Redspace Abduction to Darkspace.**
1. _This is just a change to bring the code in line with the lore. Hopefully it'll prevent confusion going forward._
:cl:
tweak: Changes Redspace Abduction to Darkspace.
/:cl:
> Changes Code References to Redspace

- _maps/map_files/rift/rift-05-surface2.dmm
- code/game/landmarks/spawnpoint/station/jobs.dm
Created and mapped in spawners for Lord_Papalus's senior positions Head Nurse and Senior Researcher. LordME is doing the Senior Engineer spawners and mapping them in
Necessary for people to spawn shift start as these roles
:cl:
add: Spawners for Senior Medical and Science positions
/:cl:
> Senior job Spawners for Head Nurse and Senior Researcher Mapped in

- code/modules/food/food/snacks.dm
- code/modules/food/recipes_microwave.dm
1. **Adds the Three Puddis.**
1. _I saw these icons when I was adding peas and shrimp a few days ago, and I liked them. So I added some recipes that make them work now!_
:cl:
add: Adds three pudding recipes.
/:cl:
> Adds Three Pudding Recipes

- _maps/map_files/rift/rift-04-surface1.dmm
- _maps/templates/shelters/shelter_2.dmm
- _maps/templates/shelters/shelter_3.dmm
- _maps/templates/shelters/shelter_a.dmm
Fixes:
Trader Airlock pipe connection
Shelter capsule corner window that's blocking movement
Bar shelter capsule now comes with an unlocked Booze vendor, like the bar
I've been inconvenienced, so I'll make some map fixes.
:cl:
tweak: Changed access on Bar shelter capsule Booze Mar
fix: Fixed pipes for the trader airlock
fix: Fixed corner glass piece blocking movement in the luxury shelter capsule
/:cl:
> Small map fixes v2

- code/modules/lore_hardcoded/citizenship.dm
> Adds the Naramadi Ascendancy into the list

- code/modules/lore_hardcoded/faction.dm
Funny cheese mans
Guilds are for: Cargo and Engineering.
OSS&Necropolis are for: Science and Medical
> Adds Naramadi Guilds and OSS/Necropolis to the list

- code/modules/atmospherics/environmental/zas/zone.dm
I may have stupid syndrome and it may be terminal.
> zas no longer shits out vis_contents when it doesn't need to

- code/modules/client/client_defines.dm
Apparently when I updated view_data I forgot the most important part, the client var.
> How Did I forget to add the client var for view-data

- code/game/objects/items/weapons/handcuffs.dm
Fixes cyborg cuffs not working.
bugfix
:cl:
bugfix: Cyborg cuffs will now work again.
/:cl:
> Fixes borg cuffs

- code/game/atoms/atoms_movable_movement.dm
Runtime Fix
Yell at me if I did something wrong, tested locally and worked out well 
:cl:
fix: Runtime fix
/:cl:
> Small runtime fix causing by picking up pulled items in a certain fashion

- _maps/map_files/rift/rift-05-surface2.dmm
- code/game/area/Space Station 13 areas.dm
Oh my god I hope this works please scream at me on discord if it doesn't. Also does this need pictures? 
Yeet
> Adds a pool!!! (and moves sauna)

- config/entries/game_options.txt
I'd like my local instance have the same fov as our server. Also for what is defined in the config_entry
:cl:
config: Set default widescreen configs to actual defaults.
/:cl:
> Set default widescreen configs to actual defaults.

- code/modules/lore_hardcoded/origin/hegemony/naramadi
Please
Review
🆑 
My
Pr
add: Naramadi Origins
🆑
> Origins - Naramadi (Merge this before factions)

- code/modules/lore_hardcoded/faction.dm
pain
lore
:cl:
I hate coders I hate coders
/:cl:
> Naramadi Faction whitelist for Origins (merge after origins PR)

- code/modules/lore_codex/news_data/main.dm
As part of the ongoing attempts to better structure the lore, I am beginning semi-regular updates to teh Daedalus newscaster item which shoudl now see more regular updates with a more used IC-bulletin. This updates adds 2 news stories and switches out an existing Adverstisement. Here is to many more new stories.
:cl:
add: Two more News Stories
tweak: Ironhammer ad swapped with NIF ad as Ironhammer is being replaced with Five Star Security.
/:cl:
> In The News 11/8/2566

- code/modules/organs/external/_external.dm
alright gamers
here's where we're at
- this wasn't a thing before i refactored ticking
- this is now a thing
- i don't know how i made it a thing
- i want it to eventually be a thing
- .... but i don't have time right now to make it a thing proper
hence, removing until the upcoming surgery & organ refactor.
> temporarily removes infection damage from the dead

- code/modules/organs/internal/brain.dm
> fixes prommie revival (again)

- _maps/map_files/rift/rift-03-underground1.dmm
Elizondo the flying mouse can no longer fly and has been moved to somewhere more reasonable
Maintainer Request
> Elizondo the Flying Mouse is now moved

- code/modules/preferences/preference_setup/general/03_body.dm
> shims robolimb customization to work for nonhumans

- _maps/map_files/rift/rift-04-surface1.dmm
- code/game/area/Space Station 13 areas.dm
- code/modules/events/infestation.dm
Little bugs in relation to the Infestation event that I could fix at once
QOL
:cl:
add: New cargo hallway area type
tweak: The area Engineering Infestation can fire
tweak: Cargo area change for the hall to the dock
/:cl:
> Misc. fixes for infestation

- code/modules/preferences/preference_setup/vore/08_traits.dm
this was triggering on render-only copy to's
this shouldn't even be here but i'm not able to refactor rn.
> fixes log spam for trait stat gathering

- code/__HELPERS/_logging.dm
- code/controllers/failsafe.dm
- code/game/statistics.dm
- code/game/verbs/who.dm
- code/modules/admin/DB ban/functions.dm
- code/modules/admin/admin.dm
- code/modules/admin/admin_ranks.dm
- code/modules/admin/holder2.dm
- code/modules/admin/topic.dm
- code/modules/admin/verbs/adminhelp.dm
- code/modules/admin/verbs/adminpm.dm
- code/modules/admin/verbs/adminsay.dm
- code/modules/admin/verbs/pray.dm
- code/modules/client/client_procs.dm
- code/modules/client/verbs/ooc.dm
- code/modules/mob/logout.dm
- code/modules/paperwork/faxmachine.dm
i also removed devs/EMs/mods from the adminwho system because *it's a stupid system and we don't need it*
> admins are now shown as afk while afk; also converts admins to managed global

- code/modules/mob/living/carbon/human/human.dm
- code/modules/organs/external/_external.dm
- code/modules/preferences/preference_setup/general/03_body.dm
refer to code comment for how this works
this is shitcode
i accept it's shitcode
and there's jack shit we can do about it because frankly fuck organ code.
refactor coming in the next few months.
> fixes prosthetic limb customization

- code/controllers/subsystem/job/_legacy_job_stuff.dm
- code/controllers/subsystem/ticker.dm
see byond ref Login() for why this was a horrible thing
> optimizes roundstart

- code/modules/maps/tg/map_template.dm
god damnit 
fix that doesn't look/feel like shit on maploader refactor.
> monkey patches loading map templates sometimes not making zones

- code/modules/species/station/standard/naramadi.dm
Kevin approves
Please review my PR
Cheese lore Cheese lore
:cl:
tweak: Changed temperature limits for Naramadi to fit homeworld better.
tweak: Naramadi appearance now fits lore: People cannot see difference between male and female at a glance, aka ambiguous_genders = TRUE, aka other races can't tell what gender a Naramad is.
/:cl:
> Cheese changes: Temperature Edition

- code/__DEFINES/_flags/item_flags.dm
- code/game/objects/items/devices/communicator/communicator.dm
- code/modules/mob/living/carbon/human/inventory.dm
> comms watch can now be worn one handed

- code/modules/reagents/machinery/chem_master.dm
- tgui/packages/tgui/interfaces/ChemMaster.tsx
:cl:
tweak: Putting max reagent count for bottle creation in the Chem Master back to 60.
fix: Chem Master printed bottles use correct sprites.
/:cl:
> Chem Master Patches

- code/modules/mob/login.dm
Webedit alert!
Just read this: https://github.com/tgstation/tgstation/pull/63317
> Fixes random hell Move() call counts, removes the parent call from mob/Login

- code/game/objects/items/weapons/RCD.dm
see: why would we not allow this and make it worse in every way to use the ammo compared to, say, electric RCDs
man RCDs need a rework don't they.
> rcd ammo cartridges are now equivalent to just inserting the materials

- code/__HELPERS/global_lists.dm
- code/__HELPERS/names.dm
- code/datums/mind.dm
- code/game/machinery/computer/security.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/jobs/access.dm
HELLO yes we use SSjobs now no more random lookups in unmanaged globals PLEASE and THANK YOU.
i recommend testmerging this for a bit just in case, seems to work fine but hey.
> removes yet another copy of all jobs being held in memory for no reason

- code/modules/mob/living/bot/medibot.dm
There's always a catch, and I'm the best there is.
There's always a catch, and I'm the best there is.
:cl:
spellcheck: Fixed a typo for one of the medibot's voice lines.
/:cl:
> Fix medibot typo

- code/modules/jobs/job_types/station/civillian/chaplain.dm
- code/modules/jobs/job_types/station/security/warden.dm
1. **Removes some Alt-Titles.**
1. _Currently just removes Paracausal Scholar and Brig Governor alt titles. May remove more after re-review._
:cl:
del: Removes some alt-titles.
/:cl:
> Removes Some Alt-Titles

- code/modules/mob/hear_say.dm
whoever wrote this code needs to learn from bobby tables
> [s] regex quotes names

- .github/workflows/size_labeling.yml
If this doesn't work, our tokens are more fucked than expected
> Trying pull_request_target on size_labeling.yml

- code/modules/preferences/preference_setup/vore/08_traits.dm
:cl:
fix: traits left on prefs displays counts your traits once more
/:cl:
> fixes traits left render (probably)

- code/modules/mob/living/simple_mob/subtypes/animal/roach/roach.dm
1. **Fixes Icon Bug.**
1. _A minor typo made one type of roach invisible._
:cl:
fix: Fixes a typo.
/:cl:
> Fixes Bug in Roach Icons

- code/modules/clothing/glasses/_glasses.dm
> fixes goggles not having phoronguard for like the 20th time

- code/modules/ai/ai_holder.dm
prometheans/proteans ruined everything as usual
> (probably) adds automatic grab resist to ai

- code/game/objects/items/weapons/towels.dm
tl;dr lets you wear towels without jumpsuit again
> gives towel beltlink ignore

- code/modules/preferences/preference_setup/loadout/loadout_role_restricted.dm
flube
Webedit, please review my PR
Fixes shit
:cl:
fix: Fixes Senior Roles not being able to use departement-locked loadouts
/:cl:
> Hopefully fixes Senior Role Loadouts

- code/game/objects/structures/janicart.dm
fixes things being nullspace'd if your hands are full
> changes janicart to use new checked inventory helpers

- code/game/gamemodes/changeling/changeling_powers.dm
- code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/_giant_spider.dm
- code/modules/mob/living/simple_mob/subtypes/animal/passive/fish.dm
- code/modules/mob/living/simple_mob/subtypes/mechanical/disbot_vr.dm
- code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/odysseus.dm
- code/modules/mob/living/simple_mob/subtypes/vore/bee.dm
- code/modules/reagents/reagent_containers/borghydro.dm
- code/modules/reagents/reagent_containers/hypospray.dm
- code/modules/reagents/reagent_containers/syringes.dm
Being injected (by a syringe, hypospray, spider, etc.) now causes a minuscule amount of pain, as being stabbed with a needle tends to do. Based on https://github.com/Baystation12/Baystation12/pull/28917.
Adds a bit of flair, and also helps make it clearer that you got injected for syringes.
:cl:
add: Being injected now hurts a little bit.
/:cl:
> Being injected now hurts

- code/modules/organs/external/_external.dm
- code/modules/organs/external/standard.dm
same issue as before, only properly fixed
tl;dr lets you robotize limbs forcefully
yes this is shitcode
no i don't care because i can't do it better without refactoring organs.
i'm refactoring organs next month
fuck this shit
so done with it
> fixes some robolimb stuff

- code/modules/paperwork/paper/tag.dm
please be patient i don't test my code
> fixes paper tags

- code/game/machinery/computer/arcade/_arcade.dm
- code/game/machinery/computer/arcade/claw_machine.dm
> fixes claw machines

- code/modules/food/food/drinks/bottle.dm
> fixes unathi juice runtime

- code/__DEFINES/_planes+layers.dm
I keep doing this in my canceled PRs. So I felt I should just do a formatting only PR, no value changes.
> Formatting _planes+layers.dm so it doesn't look bad.

- code/modules/mob/living/carbon/human/traits/positive.dm
tl;dr
WHY are you setting flags???
FLAGS ARE A BITFIELD
YOU DO NOT **SET** FLAGS
you **ADD** to them.
+ this is compile time checked now
> fixes hard feet trait being utterly terrible

- code/modules/admin/ckey_vr.dm
tl;dr
there's an issue where it's grabbing null clients
(ok honestly, the issue might be that we have null clients in player list but uh, this is a fix anyways)
edit: the thing that broke was clients leaving midway while this is running.
> adjusts set ckey

- citadel.dme
- code/__DEFINES/MC.dm
- code/__DEFINES/_flags/turf_flags.dm
- code/__DEFINES/atmospherics/atmospheres.dm
- code/__DEFINES/turfs/turfmakers.dm
- code/__DEFINES/turfs/type_generation.dm
- code/controllers/master.dm
- code/controllers/subsystem.dm
- code/controllers/subsystem/air.dm
- code/controllers/subsystem/emergency_shuttle.dm
- code/controllers/subsystem/events.dm
- code/controllers/subsystem/garbage.dm
- code/controllers/subsystem/mapping/obfuscation.dm
- code/controllers/subsystem/overlays.dm
- code/controllers/subsystem/processing/chemistry.dm
- code/controllers/subsystem/tgui.dm
- code/controllers/subsystem/timer.dm
- code/game/area/area.dm
- code/game/turfs/change_turf.dm
- code/game/turfs/turf.dm
- code/modules/atmospherics/atmosphere/_atmosphere.dm
- code/modules/atmospherics/environmental/public.dm
- code/modules/atmospherics/gasmixtures/gas_mixture.dm
- maps/~map_system/maps.dm
/indoors - tin
/outdoors - tin
/overhang - not outdoors, but outdoors atmos
/default - use area defaults
default is currently inefficient (5  bytes per var :/) but whatever
as of right now everything uses zlevel default atmos for outdoors, and indoors uses STP
we'll have better stuff on level side later
> adds standard turfmakers

- code/modules/mob/inventory/rendering.dm
> fixes rendering

- code/modules/species/promethean/promethean.dm
- code/modules/species/protean/protean_species.dm
- code/modules/species/species_shapeshift.dm
- code/modules/species/xenochimera/xenochimera.dm
Should work this time
Basically adds a shapeshifter verb for secondary ears
Less need to shuttle back and forth
:cl:
add: Gives shapeshifters the ability to change their secondary ears
/:cl:
> Secondary ear shapeshifting

- _maps/map_files/rift/rift-05-surface2.dmm
- code/modules/projectiles/guns/projectile/shotgun.dm
1. **Adds Guns to Armory.**
2. **Removes Holster Flag from Warden's Shotgun.**
1. _Adds eight spare tasers and four more LTL gunboxes to the Armory._
3. _This is apparently my fault. It appears to have come over with the initial port, but it's possible I assigned the flag myself. Either way, it's not an intended feature and I'm surprised it took this long for anyone to mention it._
:cl:
add: Adds more guns to the Armory.
del: Removes Warden's Shotgun's holster flag.
/:cl:
> Adds More Guns to Armory & Removes Erroneous Holster Flag for Warden's Shotgun

- code/__DEFINES/typeids.dm
i hate this game engine so much you wouldn't understand for real no cap
> don't try to typeid a number

- code/datums/repositories/crew.dm
makes my life easier when writing sop/corporate regulations.
server policy doesn't revolve around erp, but it helps if the code doesn't make it relevant to the game loop in the first place.
> vore now blocks suit sensors

- code/modules/clothing/head/_head.dm
> fixes helmet icon updates

- code/modules/jobs/job_types/station/civillian/assistant.dm
been there
done that
let's not do that
> unlimits assistant

- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/mob/living/silicon/translation.dm
> fixes translation context init & pais being awful

- code/modules/mob/living/carbon/human/update_icons.dm
> maybe fixes scaling fuzzy-ness

- code/modules/organs/internal/kidneys.dm
> fixes kidney runtimes

- code/modules/maps/templates/submaps/class_p/class_p.dm
Removes allow_duplicates from the base template to stop the game from trying to place it until it runs out of iterations. Also went ahead and put the two largest POI's together in a template group and made them priority spawns. 
:citaball: Bug fix
:cl:
fix: fixes class P submap spawning
/:cl:
> Fixes Class P submap generation to stop constant iterating

- code/controllers/configuration_old/configuration_vr.dm
- config/legacy/config.txt
We removed the code for it in #4871 so uh yeah.
> Removes configs for assistant/visitor limiters

- code/modules/overmap/ships/computers/sensors.dm
- code/modules/overmap/ships/engines/gas_thruster.dm
there's literally no way of in round fixing this
atom damage soon tm
> makes overmaps stuff indestructible for now

- code/__HELPERS/sanitize_values.dm
- code/modules/preferences/preference_setup/global/01_ui.dm
salt pr why can't i be cool and pink (i did this on main too, see https://github.com/Citadel-Station-13/Citadel-Station-13/pull/15788)
it's not. you can have pure white text, but you can also have pure black text to fuck over dark mode users so whatever. 
:cl:
tweak: admins can have unrestricted ooc colors
/:cl:
> remove sanitize_ooccolor

- code/modules/organs/organ.dm
while this is frowned upon i will allow it because i don't want to force sanitization math everywhere
> organ runtime

- code/modules/lore_hardcoded/_hardcoded.dm
- code/modules/lore_hardcoded/origin/hegemony/naramadi.dm
- code/modules/preferences/preference_setup/background/language.dm
jokes on me for thinking this wouldn't be necessary, oops.
> adds max language mods to lore datums

- _maps/map_levels/192x192/tradeport.dmm
title
i love having to run to the only two working pipe connectors
:cl:
fix: nebula gas no longer has random inexplicably missing pipes in the phoron refueling area
/:cl:
> fix tradeport phoron pipes

- tgui/packages/tgui-panel/styles/components/Chat.scss
> Improved <blockquote> CSS

- code/game/atoms/atoms_movable.dm
Stealing a tweak from Lohikar again. Appreciate you dork.
> Add Entered Event to non-mapload init on movables

- code/modules/holidays/christmas_loadout.dm
- code/modules/holidays/halloween_loadout.dm
1. **Populates Christmas Holiday Loadout List.**
1. _I noticed today that our Christmas loadout list was entirely blank, unlike our Halloween one. With some help from Kevin we were able to locate the issue, and I have since been able to populate this list with delightful Christmas themed clothes for everyone to enjoy. Please be sure to thank Kevin! Even though this PR is a bit late, now we can expand and celebrate extra well for next year!_
:cl:
add: Adds Christmas loadout item list.
/:cl:
> Populates the Christmas Holiday Loadout List

- code/__DEFINES/movement.dm
- code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
- code/modules/catalogue/cataloguer_visuals.dm
- code/modules/keybindings/bindings_atom.dm
- code/modules/mob/mob_defines.dm
- code/modules/mob/movement.dm
- code/modules/movespeed/movespeed_modifier.dm
:cl:
add: smooth movement (thanks lohikar)
fix: unnecessary movement compensation causing stutter
/:cl:
> smooth movement

- code/_onclick/item_attack.dm
warning: untested
so foam weapons don't need 1 force anymore (this pr doesn't change the fact they have it, though!)
:cl:
add: non-lethal tapping
/:cl:
> you can now lightly smack people with non-damaging weapons

- code/game/objects/items/weapons/material/bats.dm
- code/game/objects/items/weapons/material/material_weapons.dm
tin
it probably really isn't
:cl:
balance: the plastic penetrator now has attack damage. we recommend not swinging at each other for no reason..
/:cl:
> the dildo bat now has the standard ss13 hitforce

- code/__DEFINES/radiation/simulation.dm
current settings result in huge amounts of penetrating through doors and walls
honestly i like super dangerous radiation but i'm going to drop it for now since most sources don't really need this anyways
> nerfs radiation a bit (increases falloff)

- code/controllers/subsystem/ticker.dm
> fixes roundend transfer vote popping up after roundend

- code/modules/mob/movement.dm
> fixes movement

- code/game/turfs/simulated/floors/snow.dm
> fixes snow memory leak

- code/__HELPERS/datastructs/bodytypes.dm
dogborg code is shit but we should do this anyways just in case
> fixes bodytypes struct double compiles runtiming

- .github/guides/MAPS.md
- .github/workflows/auto_changelong.yml
- .github/workflows/ci_suite.yml
- .github/workflows/compile_changelogs.yml
- .github/workflows/conflicts.yml
- .github/workflows/update_tgs_dmapi.yml
- _maps/_basemap.dm
- tools/validate_dme.py
Workflows should work as intended.
Added a DME validator by Mothblocks
Added the ability for CI to cancel when a new commit is pushed
> More Workflow stuff

- code/game/objects/items/devices/PDA/PDA.dm
:cl:
fix: fixed pathfinder PDAs spawning with an invalid iconstate
/:cl:
> Fixes pathfinder PDA bug

- code/modules/mob/living/carbon/human/human_powers.dm
:cl:
add: Added the option for psychic whispers to be projections
/:cl:
> Psychic Whisper extention

- code/modules/materials/material_recipes.dm
I am repaying my sins against the Teshari Hivemind
Makes Teshari Nests buildable
:cl:
add: Adds Teshari Nests to the steel construction list
/:cl:
> Soothes the Teshari Hivemind

- code/modules/mob/living/silicon/robot/robot.dm
> gives robot eal hardcoded again

- code/__HELPERS/lists/string_lists.dm
- code/controllers/subsystem/zmimic.dm
- code/game/turfs/baseturfs.dm
- code/game/turfs/change_turf.dm
- code/game/turfs/simulated/floor_types.dm
- code/game/turfs/simulated/misc/fancy_shuttles.dm
- code/game/turfs/turf.dm
- code/game/turfs/unsimulated.dm
- code/game/world.dm
- code/modules/mapping/map_helpers/baseturf.dm
- code/modules/multiz/open_turf.dm
> optimizing turf/Initialize(), ChangeTurf, and assemble_baseturfs

- code/__DEFINES/radiation/simulation.dm
i over-nerfed it
testmerge for a bit pls
> buffs radiation

- code/modules/preferences/preference_setup/general/01_basic.dm
- code/modules/preferences/preference_setup/general/03_body.dm
- code/modules/preferences/preference_setup/general/04_equipment.dm
- code/modules/preferences/preference_setup/general/05_background.dm
- code/modules/preferences/preference_setup/global/01_ui.dm
- code/modules/preferences/preference_setup/vore/01_ears.dm
- code/modules/preferences/preference_setup/vore/03_egg.dm
- code/modules/preferences/preference_setup/vore/08_traits.dm
- code/modules/preferences/preference_setup/vore/10_misc.dm
:cl:
qol: many list inputs in the char setup now use tgui inputs with search functions
/:cl:
> tgui_input_list for the loadout

- code/modules/organs/robolimbs.dm
MORE LORE!
DSI is a VORE leftover. We hate VORE leftovers.
:cl:
replace: Replaces DSI with OSS.
/:cl:
> Replaces DSI with OSS

- code/game/objects/items/stacks/marker_beacons.dm
> yandere developer

- code/game/objects/items.dm
> Make blood overlay caching not completely insane

- code/modules/materials/definitions/unsorted_materials.dm
marble isn't a valid table icon.
> Fixes Hardwood tables

- code/__DEFINES/_planes+layers.dm
- code/game/turfs/simulated/walls/dungeon.dm
- code/modules/mining/mine_turfs.dm
Fixes wall edges being below turf AO
> Fixes Wall Edges

- code/modules/species/station/standard/human.dm
tin
:cl:
fix: probably fixes human subspecies not being able to wear hardsuits
/:cl:
> gives human subspecies the same bodytype as human

- code/modules/busy_space/organizations.dm
Pain
Pain
:cl:
fix: Fixes shuttle names being combined with shuttle prefixes
/:cl:
> Busy_space code is dumb and requires an empty space coded in

- code/game/atoms/atoms_movable.dm
> ghost tag improvement

- code/game/machinery/doors/door.dm
> fixes throwing people through doors

- code/game/turfs/simulated/floors/lava.dm
- code/game/turfs/simulated/floors/snow.dm
- code/game/turfs/simulated/floors/water.dm
- code/game/turfs/turf.dm
- code/modules/mob/living/carbon/human/human_movement.dm
- code/modules/mob/living/simple_mob/simple_mob.dm
- code/modules/multiz/open_turf.dm
> fixes movement cost 

- code/controllers/subsystem/ao.dm
Authored by Lohikar
We realized I did our SSao dirty, so they rewrote it better.
> SSao Tweaks

- code/__HELPERS/view.dm
- code/_rendering/clickcatcher/clickcatcher.dm
- code/_rendering/fullscreen/fullscreen.dm
- code/_rendering/parallax/parallax_object.dm
- code/game/objects/items/devices/PDA/PDA.dm
- code/game/objects/items/stacks/stack.dm
- code/game/objects/structures/railing.dm
- code/modules/client/client_procs.dm
- code/modules/materials/definitions/unsorted_materials.dm
- code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
- code/modules/overmap/ships/computers/ship.dm
- code/modules/tgui/modules/overmap.dm
- engi point vendors
- overmap runtimes
- overmap view
- overmap ships sometimes going into nullspace
> fixes a few things

- code/_onclick/click.dm
- code/_onclick/items.dm
- code/game/atoms/atoms_movable_movement.dm
- code/game/objects/structures.dm
- code/game/objects/structures/railing.dm
> fixes guns & not being able to climb over railings

- code/modules/keybindings/setup.dm
- interface/interface.dm
- interface/skin.dmf
maybe webediting this is a bad idea but uhhhhh surely this won't go wrong
:cl:
fix: hotkey toggle button
/:cl:
> fixes toggle hotkey button maybe

- code/game/atoms/atoms_movable_pulling.dm
- code/modules/mob/mob_pull.dm
If you Ctrl+Click something, you begin to pull it.
Now, if you Ctrl+Click it again, you will stop pulling it.
Another, quicker way to stop pulling something, other than clicking on the HUD element or hitting the delete(?) key.
:cl:
qol: Trying to pull something you're already pulling will now make you stop pulling it.
/:cl:
> Trying to pull something you're pulling will stop pulling it

- code/modules/busy_space/organizations.dm
Tin
As far as I can tell, these names just weren't capitalized correctly. ~~If this is intended, I can just close this PR.~~
Edit: Not intentional.
> Fixing ship name capitalization

- code/game/gamemodes/changeling/powers/epinephrine_overdose.dm
- code/modules/reagents/Food-Recipes.dm
- code/modules/reagents/Misc-Recipes.dm
- code/modules/reagents/chemistry/_readme.dm
- code/modules/reagents/chemistry/chemical_reactions.dm
- code/modules/reagents/chemistry/helpers.dm
- code/modules/reagents/chemistry/holder.dm
- code/modules/reagents/chemistry/reagents.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Core.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Modifiers.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Other.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Toxins.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Topical.dm
- code/modules/reagents/chemistry/reagents/other/cleaner.dm
- code/modules/reagents/chemistry/reagents/pyrotechnics/thermite.dm
- code/modules/reagents/distilling/Distilling-Recipes.dm
I forgot I did this yesterday after reagents were being talked about in Nebula's discord.
> Literally just removing var/ in the args for reagent procs

- _maps/map_files/rift/rift-02-underground2.dmm
- code/game/area/Space Station 13 areas.dm
I hated this path for way too long.
Also adds a preemptive measure for turbolifts not to smooth with other things.
> Fixes Cryo Rooms being fullbright and not smoothing.

- code/game/objects/items/devices/gps.dm
- tgui/packages/tgui/interfaces/Gps.tsx
local_mode was missing & it was reading the wrong var instead
> fixes a tiny bug with GPS

- code/modules/mob/living/carbon/human/human.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
:cl:
fix: fixed pepperspray affecting beings without eyes as if they have eyes
fix: fixed people not breathing because they have no lung from coughing
/:cl:
> Pepperspray and smoke effects

- code/datums/components/cyberpsychosis.dm
1. **Fixes CRS Organ Tabulation.**
1. _Corrects a recent issue with Cyberpsychosis counting all limbs, instead of only robotics._
:cl:
fix: Fixes cyberlimb tabulation.
/:cl:
> Cyberpsychosis Count Correction

- code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
Makes Alt Xeno Hybrids able to wear suits in a way less obtuse then the first PR
:cl:
fix: Alt Xenohybrids now can wear suits.
/:cl:
> Makes AltXenoes Able to Wear Suits (v2)

- code/__DEFINES/callbacks.dm
- code/datums/callback.dm
- code/game/objects/items/weapons/nullrod.dm
ports https://github.com/DaedalusDock/daedalusdock/pull/196
less lag
:cl:
code: invoke_async is now improved
/:cl:
> invoke_async performance boost

- code/datums/mind.dm
- code/game/machinery/computer/timeclock_vr.dm
- code/modules/jobs/alt_title.dm
- code/modules/jobs/job.dm
- code/modules/preferences/preference_setup/occupation/occupation.dm
read comments for what they do
they're also marginally faster now
> makes background restricted alt titles far less awful

- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/species/shadekin/shadekin.dm
- code/modules/species/shadekin/shadekin_blackeyed.dm
:cl:
fix: radiation immunity for shadeking & radiation traits
/:cl:
> fixes radiation mod & makes shadekin rad immune again

- code/modules/cargo/supplypacks/hospitality.dm
https://www.youtube.com/watch?v=RovF1zsDoeM
We have a in universe name for vampires now, lets use it
> Renames a single Cargo supplypack

- code/modules/holomap/generate_holomap.dm
- code/modules/holomap/holomap_area.dm
I'm going to forget about this if I don't PR it now.
No functional changes, this should just approximately double holomap init speed. Yes, you're still paying for their init even though you don't have any mapped in.
> Holomap performance tweaks

- tgui/package.json
- tgui/yarn.lock
I didn't get the memo that this is a critical asap issue: tgstation/tgstation/pull/73457
> [CRITICAL ] Updates webpack to latest

- _maps/map_files/rift/rift-06-surface3.dmm
- code/game/objects/items/storage/bags.dm
- code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
This PR:
- Adds botanical gloves to botany lockers
- Makes botany plant bags an exception to the plant bag weight thing, they'll stay pocketable now even if full
- renames botany's 'cow' to 'Betsy'
- Remaps botany
Makes Botany just ever so slightly less ass to play.
:cl:freestylalt
tweak:remaps botany
add:adds back Betsy
/:cl:
> Botany tweaks (also map)

- _maps/map_files/rift/rift-04-surface1.dmm
Title. Xenobotany has the wrong vendor currently.
:cl:
fix: Xenobotany Vendor
/:cl:
> Changes the seed vendor in Xenobotany to the Xenobotany variation

- code/modules/mob/living/silicon/robot/robot_modules/_robot_modules_defs.dm
- code/modules/mob/living/silicon/robot/robot_modules/station/science.dm
:cl:
fix: Sciquad nanopaste works again.
/:cl:
> Fix quad nanopaste

- code/modules/mob/new_player/new_player.dm
oops
no changelog
we should have a config for this later
> changes the warning prompt for character setup to only trigger on ready, rather than unready

- code/modules/ai/ai_holder_targeting.dm
> maybe fixes ai holders targeting asleep people who are allies

- code/modules/mob/living/simple_mob/subtypes/animal/roach/roach.dm
- Retaliate and cooperation only Works if said mob can survive the hit. (I am Passive > I am Hit > I am Aggressive >Help Me Brothers)
- Hit and Run should probably be called "Cloak" since its for managing cloaking mobs (Won't Even Activate Without Cloak, they will just be passive)
Makes Roaches slightly more engaging to fight. They won't just stand around and wait to be shot now.
:cl:
tweak: Adjusted Roach AI, Larger Roaches are actually aggressive now.
fix: Replaces Broken Roachs AIs
/:cl:
> Updates Roach AI

- code/__DEFINES/spaceman_dmm.dm
Stealing documentation from: tgstation/tgstation/pull/71783
> Documents spacemanDMM defines

- code/game/objects/items/circuitboards/machinery/research.dm
> adds a revolutionary ability to ACTUALLY build NTNet Quantum Relays.

- code/modules/clothing/suits/hooded.dm
:cl:
fix: winter coat recolor
/:cl:
> fixes hooded clothing not syncing color

- _maps/map_files/rift/rift-05-surface2.dmm
- code/modules/resleeving/computers.dm
- code/modules/resleeving/mirror.dm
it's on the tin and in the CL
I like QOL.
In short, this updates the description of the tool and console to note that you can use the tool directly on the console to transfer a mirror. This was always the case, but now it's easier to tell. It also allows you to load or unload mirrors  the old way, IE using it in hand, and now also allows you to click the tool with a mirror to load it like a weapon magazine. I also made it so using the tool on a console won't slap the console, which means the feedback for loading that has existed for a year and a half that no one seems to notice is a bit more noticeable.
Also adds a note in the resleeving room with basic instructions.
:cl:
tweak: the mirror tool can now be loaded/unloaded like you would a gun magazine.
qol: updated descriptions for the …
> Initial QOL changes for mirrors and their respective tools.

- code/modules/preferences/preference_setup/loadout/loadout_donator.dm
> Adds donor request

- code/controllers/subsystem/emergency_shuttle.dm
- code/game/machinery/computer/communications.dm
- code/modules/busy_space/air_traffic.dm
- code/modules/security levels/security levels.dm
Fixes the ATC relay toggle.
ALSO changes the broadcasted message, because I feel like turning off a comms relay shouldn't result in rerouting traffic in the system. Just, stop telling random fucks on station about it
i hate random messages breaking up conversations....
:cl:
fix: fixed atc relay toggle
/:cl:
> Small changes to fix the never functional ATC Relay toggle.

- .github/workflows/stale.yml
Making the stale action a bit more user-friendly and more verbose with labeling.
> That looks good to me

- code/modules/projectiles/guns/projectile/shotgun.dm
> fixes shotguns

- code/controllers/controller.dm
- code/controllers/failsafe.dm
- code/controllers/globals.dm
- code/controllers/master.dm
- code/controllers/subsystem.dm
Fixes the subsystem sorting. Also did a lot of documentation/formatting cause you know I can't atomize.
> Subsystem Sort Fix + Documenting

- code/modules/admin/verbs/SDQL2/SDQL_2.dm
- html/statbrowser.html
> maybe fixes statpanel clicking to be better at it

- code/game/machinery/computer/timeclock_vr.dm
- code/modules/jobs/job.dm
tl;dr logical failure
also fixes some potential ID nullspacing's.
> fixes not being able to swap back onto the original title of a job 

- code/modules/mob/living/bot/farmbot.dm
:cl:
fix: farmbots work again
/:cl:
we really need to clean up astar, add SSpathfinder, and add JPS huh.
> fixes farmbots

- code/modules/reagents/machinery/dispenser/dispenser.dm
- tgui/packages/tgui/interfaces/ChemDispenser.tsx
the anti maxcap protection was getting in the way of high reagent amount macros
> fixes chemistry dispenser macros

- code/modules/lore_codex/news_data/main.dm
And IC News Articles for ingame worldbuilding. 3 New news story covering the Tajara, Keisani and the Xenohybrid and a new ad for DONK CO Riot Darts. Maybe people will actually use the Daedalus newscasters to you know help learn about the background lore. Maybe we need to point new players toward it in some way?
:cl:
add: More News! 3 News Stories and an Ad
/:cl:
> In The News 2/13/2023

- code/datums/world_topic.dm
I said I would do this like at least half a year ago.
> Adds Round ID to jsonstatus

- code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
Adds a crafting recipe for the data knife using the exploration survival knife ALA a greenlit suggestion thread.
Data knives are cool, I guess.
:cl:
add: Data knives can be crafted from survival knives via the crafting menu.
/:cl:
> Craftable Dataknife

- code/modules/preferences/preference_setup/loadout/loadout_gloves.dm
- code/modules/preferences/preference_setup/loadout/loadout_role_restricted.dm
- code/modules/preferences/preference_setup/loadout/loadout_shoes.dm
- code/modules/preferences/preference_setup/loadout/loadout_uniform.dm
no ' 
:cl:
fix:makes some loadout clothes editable (like bounty hunter)
/:cl:
> quick and dirty fix to making stuff tweakable

- code/modules/mob/living/carbon/human/human_movement.dm
temporary measure while we figure out our permanent balancing for combat.
:cl:
tweak: halloss and damage now slow you down less.
/:cl:
> nerfs pain / health slowdown

- code/modules/reagents/machinery/dispenser/dispenser.dm
> fixes dispenser bashing

- code/game/objects/items/inducer.dm
> fixes inducer rates

- code/modules/reagents/reagent_containers/spray.dm
Similar issue as with syringes and guns. Firemode got fucked :eyes:
> Fixes: Spray bottles, Pepperspray and Super Soakers

- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/robot/life.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/resleeving/mirror.dm
Bug
:cl:
fix: made AI's not see fullbright
balance: silicons don't become a traitor anymore on HUD UPDATES WHY
code: changes the call structure of cyborgs and moves life code down to silicon level in some places, to make AI code work better.
fix: only human types are effected by mirror implants
/:cl:
> makes AI experience not fullbright and fixes AI runtiming because they receive a mirror implant

- code/modules/jobs/job_types/station/offduty/command.dm
> removes off duty from command

- code/game/objects/structures/stool_bed_chair_nest/bed.dm
- code/modules/surgery/robotics.dm
- code/modules/surgery/surgery.dm
it's really silly you need 3 items out of the entire game to do surgery, even on the dead
now you just fail really hard.
> you can now do surgery without a literal surgical table / roller bed. synth repairs can now be done anywhere.

- code/game/objects/items/weapons/cigs_lighters.dm
i really should have just did on_attack_self.
> fixes lighters

- code/modules/reagents/reagent_containers/syringes_vr.dm
> fixes syringes actually

- tgui/packages/tgui/interfaces/ChemDispenser.tsx
by tune up i mean unfuck the part where I used math.random for the keys
never doing that again lazyness is a mistake
> tunes up chem ui

- code/game/gamemodes/changeling/powers/epinephrine_overdose.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Toxins.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Topical.dm
its funny how you can take a bit of tramadol and undergo surgery without feeling all that much, this PR remedies is so, that only the strongest active painkiller actually has an effect
> makes painkillers not stack on themselves

- code/modules/power/singularity/particle_accelerator/particle.dm
jokes on me for not reading the rest of the file
i didn't realize they uh, well, didn't use forceMove.
> fixes accelerated particles but actually

- code/datums/browser/color_matrix_picker.dm
> fixes matrix orientation

- code/datums/locations/qerrvallis.dm
- code/datums/locations/vir.dm
- code/modules/examine/descriptions/devices.dm
- code/modules/lore_codex/lore_data/important_locations.dm
- code/modules/lore_codex/lore_data_vr/important_locations.dm
- code/modules/mob/living/carbon/human/emote.dm
:cl:
refactor: Refactors files containing non UTF-8 characters to now be UTF-8 Compliant
/:cl:
> UTF 8 Cleanup

- maps/map_files/rift/rift-04-surface1.dmm
- maps/map_files/rift/rift-05-surface2.dmm
- maps/map_files/rift/rift-06-surface3.dmm
Babe it's 2 PM time for your weekly "Thing that only bothers nicc" PR!
I like when things have consistency. Naming of office doors was either just the title, or "Title's Office" and I chose the former and unified it
:cl:
tweak: tweaked office door names
/:cl:
> Unifies names of office doors

- code/datums/components/crafting/crafting.dm
- code/modules/reagents/chemistry/holder.dm
allows crafting recipes to properly check for reagents/use them
craft
:cl:
fix: reagent checks for crafting
/:cl:
> Fixes crafting so it now checks for reagents properly

- code/modules/species/promethean/promethean.dm
I thought slimes at one point couldn't, but I guess I was wrong
They can't be knocked out for surgery + this kinda (?) makes sense??
> Prometheans can no longer feel pain

- code/datums/components/atoms/radiation_listener.dm
- code/game/atoms/movable/movement.dm
- code/game/turfs/turf_movement.dm
- code/modules/mob/living/simple_mob/defense.dm
- code/modules/multiz/structures.dm
we need to rewrite movement backend later
> hotfix for simplemob armor + stairs

- code/modules/mob/living/silicon/robot/robot.dm
april fool's is over c'mon now
> Revert "Dogborgs now CRUSH people's heads VERY RARELY when sharing a tile and resting."

- code/game/machinery/floor_light.dm
more than one color!
:cl:
add: Added new floor light version that changes colors every 0.5 seconds
/:cl:
> add a color shifting variant of the floor light

- code/datums/autolathe/general.dm
:cl:
add: Added Fairy light bulbs to the autolathe
/:cl:
> Adds Fairy light bulbs to the autolathe

- code/__DEFINES/callbacks.dm
- code/__DEFINES/rust_g.dm
- code/__HELPERS/animations.dm
- code/__HELPERS/icons.dm
- code/__HELPERS/nameof.dm
- code/__HELPERS/vfx/flick.dm
- code/__global_init.dm
- code/controllers/configuration/config_entry.dm
- code/controllers/subsystem/job/_legacy_job_stuff.dm
- code/controllers/subsystem/ticker.dm
- code/game/atoms/say.dm
- code/game/turfs/turf.dm
- code/modules/library/lib_machines.dm
- code/modules/mob/floating_message.dm
- code/modules/mob/living/carbon/human/death.dm
- code/modules/mob/living/silicon/robot/life.dm
- code/modules/mob/living/simple_mob/subtypes/animal/space/thrumbo.dm
- code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/mecha.dm
I swear if I have to do this again.
> 515 Compatability but touching only required stuff.

- code/modules/examine/descriptions/armor.dm
> fixes armor examine formatting

- code/__DEFINES/misc.dm
- code/game/gamemodes/cult/runes.dm
- code/game/machinery/holopad.dm
- code/game/objects/items/circuitboards/circuitboard.dm
- code/game/objects/items/circuitboards/frame.dm
- code/modules/preferences/preference_setup/background/_background.dm
fixes conference calls
fixes long ranged ones becoming normal ones
> fixes some holopad stuff

- code/modules/vore/fluffstuff/guns/bsharpoon.dm
telescience update will deal with the rest
unfortunately people won't stop gaming with this so
:cl:
balance: bluespace harpoons now have a 5 second activation delay
/:cl:
> adds a delay to bluespace harpoons

- code/game/objects/items/devices/gps.dm
I'd rather not leave this feature antag-only.
It recently came to my attention that this was being used to track other players.
Given we're trying to move towards intrigue and stealth, I'd really rather not.
> All GPSes can hide signals now.

- code/modules/maps/overmap/space/centcom.dm
Updates the Demeter's description to better reflect NT's power in the Lythios System, as well as it's function for the Atlas.
> Updates the Demeter's description

- code/controllers/subsystem/job/access.dm
> fixes rds being able t ogive all access

- code/modules/sprite_accessories/hair/_hair.dm
don't copy paste without checking kids
:cl:
fix:zone hair available again
/:cl:
> makes Zone hairstyle available again

- maps/map_files/rift/rift-01-underground3.dmm
> Removes messy signs that were previously invisible

- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- code/modules/projectiles/guns/projectile/revolver.dm
1. **Fixes Name of Combat Revolver.**
1. _The name of this revolver was changed during a clean-up of other gun names. However, the designation is a coincidence born of a specific naming pattern. I'm intent on enforcing that naming pattern._
:cl:
fix: Fixes name of combat revolver.
/:cl:
> Fixes Name of Combat Revolver

- code/modules/projectiles/guns/energy/pulse.dm
- code/modules/projectiles/guns/energy/special.dm
- code/modules/projectiles/guns/projectile/automatic.dm
- code/modules/projectiles/guns/projectile/revolver.dm
1. **Renames NT Weapons**
1. _We want to put the manufacturing name in the description now, I suppose._
:cl:
tweak: Tweaks the name of several NT weapons.
/:cl:
> Renames Several NT Weapons

- maps/map_files/rift/rift-11-orbital.dmm
CC needs a holodeck that isn't on the shuttle.
> CC Demeter Holodeck

- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/movement.dm
> ghosts can suffer from slowdown

- code/__DEFINES/controllers/_subsystems.dm
- code/controllers/subsystem/DPC.dm
- code/controllers/subsystem/ai.dm
- code/controllers/subsystem/chat.dm
- code/controllers/subsystem/icon_smooth.dm
- code/controllers/subsystem/input.dm
- code/controllers/subsystem/processing/projectiles.dm
- code/controllers/subsystem/throwing.dm
- code/controllers/subsystem/timer.dm
- code/game/machinery/holopad.dm
1. de-tickers basically everything that doesn't need to be a ticker (so most of them)
2. makes SSdpc not awful (thanks @Lohikar)
> subsystem changes

- code/datums/components/crafting/recipes/recipes_misc.dm
1. **Makes Candles Craftable.**
1. _You can now use cloth and two wax sheets to make a candle._
:cl:
add: Makes candles craftable.
/:cl:
> Makes Candles Craftable

- citadel.dme
- code/controllers/subsystem/processing/moving_cameras.dm
- code/modules/tgui/modules/camera.dm
> tgui cameras now follow the camera if they're moving

- code/controllers/subsystem/chat.dm
> fixes chat subsystem not firing in lobby

- code/__DEFINES/preferences/savefiles.dm
- code/modules/preferences/migration.dm
- code/modules/species/station/standard/nevrean.dm
- code/modules/species/station/standard/zorren.dm
it really just prevents people from selecting them and forces old characters to be custom species
:cl:
del: Removed Zorren
del: Removed Nevreans
/:cl:
> removes Zorren and nevreans

- code/game/mecha/mecha.dm
Dunno, heard lore was talking about removing it, and Mech UI is a pain to understand, so I did it before someone does is half right
:cl:
del: Removed Mech DNA lock
/:cl:
> [RFM] Removes DNA lock from mechs

- code/modules/mob/living/carbon/human/examine.dm
why this is good for the game:
while i respect this is a character customization thing, some of us would like to not have to read this in full graphic detail
> makes the fat examine less descriptive

- code/modules/reagents/chemistry/reaction.dm
Synthesizable Nicotine to fill potential prescriptions.
> Synthesizable Nicotine

- code/game/machinery/vending.dm
- code/modules/hydroponics/seed_datums.dm
- code/modules/hydroponics/seed_storage.dm
1. **Restores the Tobacco Plant.**
1. _Sometime ago someone removed the tobacco plant and didn't remove its seeds. This fixes the tobacco plant's removal._
:cl:
fix: Restores tobacco plant.
/:cl:
> Restores Tobacco Plant

- code/datums/ability.dm
- code/datums/action.dm
- code/modules/mob/living/defense.dm
- fixes unused abilities counting on CD due to world.time / null not being checked
- adds a currently unimplemented hidden var for tgui panel
> quick abilities fixes

- code/datums/outfits/outfit.dm
- code/modules/maps/overmap/space/trade_station/trade_station_jobs.dm
:cl:
fix: fixed traders not having the access they require (apparently)
/:cl:
> fixes trader access

- code/modules/fishing/equipment/rod.dm
> fixes being unable to fish people

- code/modules/xenobio/machinery/processor.dm
this might work, this might not
> you can now insret monkies directly into processors

- code/modules/vore/resizing/resize_vr.dm
also adds a cooldown for as long as the resizing is on going
:cl:
fix: fixed resizing working much faster than intended
/:cl:
> fixes the time it takes for resizing to finish

- code/__DEFINES/directional.dm
- code/__HELPERS/icon_smoothing.dm
- code/game/objects/structures/window.dm
Windows properly block you from walking through them.
:cl:
fix: Windows properly block you from walking through them.
/:cl:
> Fix Window Blockage

- code/__DEFINES/_core.dm
- code/modules/mob/movement.dm
- code/modules/movespeed/movespeed_modifier.dm
please be patient, my brain is sludge
> makes movement not clip sub-0.5 second delays again, and STACK_TRACE

- code/controllers/subsystem/xenoarch.dm
- code/game/atoms/atom.dm
- code/game/atoms/movable/movable.dm
- code/game/objects/items/devices/PDA/PDA.dm
- code/game/objects/items/weapons/other.dm
- code/game/objects/items/weapons/towels.dm
- code/game/objects/objs.dm
- code/game/turfs/change_turf.dm
- code/game/turfs/turf.dm
- code/modules/atmospherics/machinery/machinery.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/head/_head.dm
- code/modules/clothing/spacesuits/void/void_vr.dm
- code/modules/clothing/suits/eventclothing.dm
- code/modules/clothing/suits/hooded.dm
- code/modules/clothing/under/accessories/accessory.dm
- code/modules/mining/mine_turfs.dm
- code/modules/mob/inventory/rendering.dm
- code/modules/mob/mob_defines.dm
- code/modules/power/cable.dm
- code/modules/projectiles/gun.dm
- code/modules/recycling/disposal.dm
- code/modules/rogueminer_vr/zonemaster.dm
- code/modules/xenoarcheaology/boulder.dm
- code/modules/xenoarcheaology/sampling.dm
- code/modules/xenoarcheaology/tools/geosample_scanner.dm
- removes geosample: no one ever used this and it needs a way better system than this
- atom colours are only applied to obj and mobs by default now, there's no point tracking for further up stuff, as they probably have their own systems
- turns a bunch of lists into lazylists
> aggressive memory optimizations

- code/modules/mob/ssd.dm
basically my head is empty and maybe i should test my code for once
sorry :(
> fixes ssd overlay override not working

- code/modules/mob/status_procs.dm
> adjusts status procs to not break

- code/modules/mob/living/carbon/human/emote.dm
> *roll emote typo fix

- code/modules/lore_codex/news_data/main.dm
For background plot progression and to tie into both past events and foreshadow future events.
:cl:
add: Two news stories
/:cl:
> In the News - 4/25/2023

- code/modules/mob/living/carbon/brain/brain.dm
- code/modules/mob/mobility.dm
> fixes soulcatcher emoting

- config_static/jukebox.json
Getting "Beneath The Mask" by Shoji Meguro from Persona 5 and Persona 5 Royal onto the jukebox under the "Jazz" category. 
Fairly popular game and franchise, and the song is audible in a café within the game. Fairly relaxing song that allows for a more chilled vibe, and also provided more songs to be within the Jazz playlist. 
:cl:
soundadd: added "Beneath the Mask" to the jukebox
/:cl:
> "Beneath the Mask" on the jukebox

- code/modules/mob/living/carbon/human/life.dm
1. **Comments Out Darkness Hallucinations.**
1. _These spam Ashlanders, and there are questions about whether maint hallucinations are really thematically appropriate for an HRP environment. I've commented it out, but if the test is agreeable I'll probably just remove the block entirely._
:cl:
tweak: Removes Darkness Hallucinations.
/:cl:
> Removes Darkness Hallucinations

- code/modules/power/supermatter/supermatter.dm
PLEASE, GAME.LOG IS BEGGING FOR RELEASE
> better supermatter logging

- maps/map_files/rift/rift-03-underground1.dmm
why the fuck did we have a snowflake ass vorestation fluff item injector that monkies you without the genetics system?
> removes monkey injector from maint

- code/game/objects/items/weapons/material/material_armor.dm
> hotfix to material armor

- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
title
hot coco has a bunch of properties that it's intended to have but does not because it doesn't call the parent function
:cl:
fix: hot cocoa works properly now
/:cl:
> Fixes hot cocoa not calling ..() in its affect_ingest

- code/__HELPERS/matrices/transform_matrix.dm
- code/modules/mob/death.dm
- code/modules/mob/ssd.dm
> fixes ssd indicator visuals appearing below mobs that are laying down/appearing on death

- code/modules/nifsoft/nifsoft.dm
> fixes compliance disks *vomit

- code/modules/cargo/supplypacks/contraband.dm
remember cloaker meta back in the day?
nah, not having that.
> removes chamo projector from cargo

- code/modules/jobs/job_types/station/security/security_officer.dm
What it says on the tin.
Desc. text by Merne23
Allegedly they aren't the same thing as a Junior Officer.
:cl:
add: Gives Security Cadets a job description.
/:cl:
> Gives Security Cadets a job description

- code/game/objects/structures/crates_lockers/closets/secure/security.dm
- code/modules/nifsoft/nifsoft.dm
- code/modules/preferences/preference_setup/loadout/loadout_ears.dm
- code/modules/preferences/preference_setup/loadout/loadout_role_restricted.dm
Adds new blueshield NIF (medical and sec huds, but no records)
Lets blueshields access security/seccom restricted loadout gear (sunglasses and similar)
Makes earwear visible on the loadout menu
> Blueshield QOL

- config_static/jukebox.json
Adjusting the url + duration of the song to the right version.
Getting "Beneath The Mask" by Shoji Meguro from Persona 5 and Persona 5 Royal onto the jukebox under the "Arcade" category.
Fairly popular game and franchise, and the song is audible in a café within the game. Fairly relaxing song that allows for a more chilled vibe, and also provided more songs to be within the Arcade playlist.
:cl:
/:cl:
> Beneath the Mask on the jukebox

- code/__HELPERS/misc/sonar.dm
slight (10%) reduction to migraine causes to sonar users
:cl:
/:cl:
> makes mobs red in sonar

- code/game/area/rift_areas.dm
- maps/map_files/rift/rift-05-surface2.dmm
Fixes minor mapping issues in sec
Added a bolt button to sec bathroom
Fixed EVA storage lighting
Removed the maint door that led to a flat wall
Added emergency shutters to a few sec doors around the break room
> minor mapping issues in sec

- code/controllers/subsystem/ticker.dm
This was annoying me.
:cl:
qol: The New Player Panel automatically updates when the round starts.
/:cl:
> The New Player Panel automatically updates when the round starts

- code/modules/research/mechfab_designs.dm
Makes everything half or more as cheap in plasteel, without changing other materials
Too much plasteel for how weak the ship is.
> Pinnace costs less plasteel

- code/game/objects/items/robot/robot_upgrades.dm
- code/modules/mob/living/silicon/robot/robot.dm
- Makes V-tec speed them up to roughly Teshari equivalent
It's a walking block of ignored game mechanics, it shouldn't be coming at you at borderline hoverboard speeds
:cl:
tweak:Borg V-tec speed lowered
/:cl:
> Nerfs upgraded borg speed

- code/__HELPERS/datastructs/armor.dm
- code/__HELPERS/misc/sonar.dm
- code/modules/automata/__automata.dm
- code/modules/automata/sonar.dm
- code/modules/client/client_procs.dm
basically, uses a lot less renderers
> speeds up sonar for the client

- code/modules/mining/mine_turfs.dm
> fixes a warning about unused variable

- code/modules/preferences/preference_setup/loadout/loadout_head.dm
Adds blueshield berets to the item loadout menu.
> Blueshield beret loadout option

- code/modules/clothing/head/misc.dm
- code/modules/clothing/head/misc_special.dm
Title. Literally just a three line addition.
Helps give players alternate outfits they can use to go outside with.
:cl:
fix: Ushankas and beanies now protect your head from the cold properly.
/:cl:
> Fixes ushanka and beanie cold protection

- code/modules/keybindings/keybind/living.dm
- code/modules/keybindings/keybind/mob.dm
- code/modules/keybindings/keybind/movement.dm
- code/modules/preferences/_preferences.dm
Sets default FPS to 40 for new players instead of 0(server default, which is 20 currently)
Creates/Sets default rest keybinding to V
Sets default Move upwards keybinding to shiftC
Sets default Move downwards keybinding to ctrlC
Creates/Sets default subtler anti-ghost keybinding to 7
> Preference Defaults and Keybinding support/defaults

- code/modules/clothing/under/accessories/oricon.dm
- code/modules/clothing/under/accessories/torch.dm
- code/modules/preferences/preference_setup/loadout/loadout_accessories.dm
Adds a bunch of departmental uniform accessories into a selection.
Adds a colorable selection for the 4 designs.
> Insignia Accessory Selection

- code/game/objects/structures/crates_lockers/closets/secure/security.dm
- maps/map_files/rift/rift-05-surface2.dmm
Swaps permit and paperwork locations.
Fixes gear being mapped in instead of coded in.
Moves headsets from cosmetic locker to gear locker.
> HOS office touchups

- maps/map_files/NSV_Euthenia/Euthenia_Deck_1.dmm
extremely minor changes to a WIP map.
> Euthenia_Deck_1 minor change

- code/modules/species/station/standard/tajaran.dm
Changes to tajaran hunger to be 2x the hunger
Tajara have cold resistance so they need to eat more often but not as often as tesh
:cl:
tweak: Increased tajaran hunger to be 2x
code: tajaran.dm
/:cl:
> Tajaran hunger increase

- code/modules/lighting/lighting_atom.dm
fixes closing doors/curtains not updating lighting
> fixes a lighting bug

- code/modules/mob/say_vr.dm
i've had enough of the debate around this.
main server methodology of individual logging is best, but since no one has the time / energy / care to do that, i am going to just remove it instead until someone does.
until then, this is already logged, in the actual game logs. abuse can be quickly handled.
nothing player-facing.
> removes admins being able to see subtlers 

- code/modules/power/supermatter/supermatter.dm
- code/modules/tgui/modules/supermatter_monitor.dm
- tgui/packages/tgui/interfaces/SupermatterMonitor.js
I have added graphs for the major variables involved with the supermatter.
[I just think they're neat.](https://www.youtube.com/watch?v=DrQqajtiRt4)
> Supermatter Monitoring Computer Graphs

- code/modules/mob/living/simple_mob/simple_mob.dm
- code/modules/preferences/preference_setup/general/06_flavor.dm
> fixes a bunch of bugs

- code/_rendering/plane_masters/plane_master.dm
- code/game/turfs/change_turf.dm
- code/game/turfs/turf.dm
- code/modules/clothing/glasses/_glasses.dm
experimental, testmerge please.
> fixes some runtimes

- code/_rendering/perspectives/perspective.dm
silicons api be like "TODO: MODIFY THIS READ ONLY BYOND VARIABLE" lmfao
> removes unnecessary bit of perspectives

- code/modules/reagents/Drink-Recipes.dm
:cl:
fix: fixed a broken drink recipe
/:cl:
> fixes the recipe for mocha bubbletea

- code/modules/mob/living/carbon/human/traits/neutral.dm
Switches the darksight var for the new and improved whatever it is.
According to testing, it doesn't do anything
Or I'm bad at testing
:cl:
fix: fixed Vetalan darksight using the old var
/:cl:
> Vetalan darksight "fix"

- citadel.dme
- code/__HELPERS/_logging.dm
- code/controllers/configuration/entries/shadowban.dm
- code/controllers/subsystem/job/roundstart.dm
- code/game/objects/items/devices/communicator/messaging.dm
- code/modules/admin/verbs/adminhelp.dm
- code/modules/client/client_data.dm
- code/modules/client/verbs/ooc.dm
- code/modules/ghostroles/role.dm
- code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/mob/observer/dead/dead.dm
- code/modules/mob/say.dm
> client onboarding update 

- code/modules/donatorreskins/donatorclothing.dm
- code/modules/preferences/preference_setup/loadout/loadout_donator.dm
It showed up in the loadout somewhere it shouldn't, this fixes it.
Fixing a bug of my own creation.
:cl:
fix: donatornoahcloak loadout bug.
/:cl:
> fixes loadout bug with donatornoahcloak

- code/modules/random_map/noise/ore.dm
- maps/sectors/miaphus_192/miaphus_192.dm
> small memory optimziations

- code/modules/mob/observer/observer.dm
oops, I fucked up and it broke invisimin since they initial().
> fixes observers not having the right invis values

- maps/rift/levels/rift-05-surface2.dmm
Adds some navy blue Pcarrier pouches
The one thing missing from Navy armor stuff.
:cl:
add: Added navy blue pcarrier pouches to general sec storage
/:cl:
> Navy Pcarrier Pouches

- code/controllers/subsystem/processing/projectiles.dm
- code/modules/projectiles/projectile.dm
tweaks projectiles to not be so slow
we are not all neo.
fast boolet.
> bumps projectile speed up

- code/datums/armor/station/exploration.dm
tweaks pilot suit resistances
Tweaks pilot suit rad resist from 100% to 90%,  because my god why was it 100%???
See above, why did they have 100%?
:cl:
/:cl:
> Pilot suit tweak

- code/modules/preferences/preference_setup/loadout/loadout_event_rewards.dm
Adds an event reward from when they were broken over a year ago
idk
> Ancient Event Reward

- code/modules/tgui/modules/general/cardmod.dm
i fucked up, this results in dupes.
> fixes a tgui cardmod issue

- code/modules/admin/verbs/SDQL2/SDQL_2.dm
oh boy this was a long time coming
> fixes sdql not asyncing calls

- code/modules/power/apc.dm
yeah so turns out i forgot to convert overlays.cut() to cut_overlays() and eventually the apc would just have ten thousand overlays until ssoverlays gave up.
this fixes that.
> fixes apc overlays

- code/modules/reagents/machinery/dispenser/dispenser.dm
> fixes chem dispensers swapping

- code/game/objects/structures/crates_lockers/__closet.dm
- code/game/objects/structures/crates_lockers/closets/utility_closets.dm
- code/game/objects/structures/crates_lockers/crates.dm
fixes closets not rendering in the map right / some having no icon
> fixes closets being wonky

- code/game/machinery/doors/airlock_subtypes.dm
fixes base type of glass doors having opacity = true and therefore not actually being see-through.
whole fuckin' file needs cleaning up but this is a bandaid
FIX.
I will make a big compendium PR with these in the future. Please do not merge those until I say so.
Please.
> glass door bugfix

- maps/rift/levels/rift-06-surface3.dmm
Stretches the AI room by 1 tile and gives them a jukebox.
Simply stretches the AI's core room by one tile, allowing room to fit a Jukebox in there.
As an AI main, I'm often sitting there in complete silence. This will at least give the AI players something to listen to.
:cl:
tweak: Stretches the AI room by 1 tile.
tweak: Had to move how the buttons in the secure sector were placed, visually.
add: Adds a Jukebox in the secure sector of the AI room.
/:cl:
> Gives the AI a Jukebox

- maps/rift/levels/rift-05-surface2.dmm
adds navy blue armpads, legpads + blue large pouches to armory
no blue stuff in that sense, would like blue stuff. would fit blue vests.
> adds navy blue armpads, legpads + large pouches to armory

- maps/triumph/levels/flagship.dmm
fixes missing texture floor tiles via replacing them
it installs counter strike source (no more missing textures)
> TRIUMPH central command floor fix

- code/__HELPERS/_logging.dm
- code/modules/mob/say_vr.dm
title
has two functions:
sends the emote to anyone in any of your vore holders
sends the emote to the person who owns the vore holder you are in (if you are in one)
goes along with some other subtle changes and this means we still have a way to keep vore silent while other subtles will make a "X did something subtly" or whatever
:cl:
add: adds vore subtle verb
/:cl:
> adds vore subtle verb

- code/__DEFINES/access.dm
- code/game/machinery/turnstile.dm
Prefabs for mappers
Helpful for later, but marionette still needs to fix the access checks on the turnstiles, I think. Even when varedited they're not checking for access requirements before allowing the mob to pass through.
> Turnstile Access Prefabs

- code/game/machinery/lathes/lathe.dm
atleast if they don't allow insert item
todo: make insert item return TRUE / FALSE / NULL and only allow it on null.
> fixes using items on lathes like rpeds

- code/controllers/subsystem/mapping/maps.dm
- code/modules/mapping/map.dm
- code/modules/rogueminer_vr/controller.dm
- maps/triumph/triumph.dm
triumph levels are unmaintained. this adds the more big and maintained ones.
> triumph 192x192 + adds atlas levels instead of triumph levels

- maps/triumph/levels/deck1.dmm
:cl:
tweak: tweaked deck 1 of triumph to use low_walls under windows, and department color walls
/:cl:
> Deck one baywallification

- maps/triumph/levels/deck2.dmm
:cl:
tweak: tweaked deck 2 of triumph to use low_walls under windows, and department color walls
/:cl:
> Deck two Baywallification

- code/modules/mob/observer/dead/orbit.dm
- tgui/packages/tgui/interfaces/Orbit.tsx
:cl:
fix: fixed follow menu drawing needless amounts of performance
/:cl:
> follow menu performance hotfix

- code/controllers/subsystem/characters/_characters.dm
- code/controllers/subsystem/characters/character_species.dm
- code/controllers/subsystem/characters/storage.dm
- code/controllers/subsystem/job/access.dm
- code/controllers/subsystem/job/job_manager.dm
- code/controllers/subsystem/job/spawnpoints.dm
- code/controllers/subsystem/mapping/allocation.dm
- code/controllers/subsystem/mapping/boot.dm
- code/controllers/subsystem/mapping/level_helpers/air.dm
- code/controllers/subsystem/mapping/level_helpers/attributes.dm
- code/controllers/subsystem/mapping/level_helpers/baseturf.dm
- code/controllers/subsystem/mapping/level_helpers/linkage.dm
- code/controllers/subsystem/mapping/level_helpers/lookup.dm
- code/controllers/subsystem/mapping/level_helpers/traits.dm
- code/controllers/subsystem/mapping/levels.dm
- code/controllers/subsystem/mapping/maps.dm
- code/controllers/subsystem/mapping/obfuscation.dm
- code/controllers/subsystem/mapping/reservations.dm
- code/controllers/subsystem/persistence/_persistence.dm
- code/controllers/subsystem/persistence/bunker.dm
- code/controllers/subsystem/persistence/objects.dm
- code/controllers/subsystem/persistence/objects/unique_string.dm
i decided i'm following in stylemistake's light
the files in this pr are entirely written by me instead of regurgitated tgcode;
i'm also marking a lot of other files but they're in their own prs (inventory module in hand pr, materials/atom damage related stuff in atom damage, etc)
> relicenses a bunch of files written entirely by me to MIT

- code/modules/clothing/chameleon.dm
title
tested
fixes a bug
:cl:
fix: fixes chameleon gun sprite disappearing when fired
/:cl:
> fixes chameleon gun sprite disappearing when fired

- code/game/mecha/mecha_construction_paths.dm
title
tested (i just slapped a piece onto the chassis because i don't know robotics, but it actually lets you put parts on the chassis now which was the issue)
fixes a bug
:cl:
fix: fixes firefighter building
/:cl:
> fixes firefighter building

- code/modules/detectivework/tools/evidencebag.dm
honestly they still suck but this stops them from breaking so they work as intended
fixes a bug
:cl:
fix: fixes evidence bags
/:cl:
> fix evidence bags

- maps/triumph/levels/deck3.dmm
> Deck three fixes windows and baywalls

- maps/triumph/levels/flagship.dmm
:cl:
tweak: tweaked CC z-level
/:cl:
> Fixes CC active edges, and halfwall windows

- code/modules/nano/nanoui.dm
> nanoui no longer strips im/proper

- code/game/objects/structures/crates_lockers/closets/secure/security.dm
:cl:
add: Added warrant projectors to the Security officer Lockers
/:cl:
> Warrant projectors in SO locker

- code/modules/modular_computers/hardware/nano_printer.dm
As title. It won't ask for bundles, just for individual sheets.
It's too easy to click on a laptop or tablet with a paper and destroy stuff written on it.
:cl:
qol: added a prompt to ask if you're sure you want to destroy paper with a nano printer
/:cl:
> Makes nano printer ask before recycling paper

- tgui/packages/tgui/interfaces/machines/Holopad.tsx
adds scrollbars and layouts it properly
> makes holopad interface not utterly horrifying

- code/modules/integrated_electronics/subtypes/manipulation.dm
every few years we look back at circuits and realise there's random unsanitized parts
fixes a bug
> fixes a small bug in circuits

- tgui/packages/tgui/interfaces/common/Color.tsx
it'll now reject bad strings instead of error
> fixes loadout error on invalid color strings

- maps/triumph/levels/deck1.dmm
- maps/triumph/levels/deck3.dmm
- maps/triumph/levels/deck4.dmm
"Haha you died to a funny murder crate on the station your employer send you too" isnt very good for the game to begin with.
:cl:
del: Removed mimics from inside the triumph
/:cl:
> Removes all mimics from the triumph

- maps/triumph/levels/deck1.dmm
> low wall coloring on deck 1 and plating under the atmos windows

- code/modules/mob/observer/dead/orbit.dm
- tgui/packages/tgui/interfaces/Orbit.tsx
:cl:
add: Added Overmap shuttles to the ghost follow menu
/:cl:
> Ghosts can follow overmap shuttles

- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
Just divided all the effects by 5. Beer should not be killing people with one gulp, probably, even with intolerance.
"whoops I didn't think coding in 1u of vodka as part of this food item would cause some crew members to literally die"
:cl:
balance: Alcohol intolerance now 1/5 as powerful
/:cl:
> Makes alcohol intolerance slightly less intolerable

- maps/triumph/levels/deck2.dmm
> colors the halfwalls on deck two, adds a colormate

- code/modules/tables/bench.dm
:cl:
add: Added new mechanics or gameplay changes
qol: made something easier to use
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:
> fixes benchs projecting depth

- maps/tether/levels/station1.dmm
:cl:
add: Added the right shield generator to tether
/:cl:
> tether shield gen

- code/modules/mob/living/silicon/pai/mobility.dm
- code/modules/mob/living/silicon/pai/pai.dm
when a pAI unfolds, place them on the turf so they don't just get stuck in the void, didn't notice this because it only happened in weird cases
fix a clothing bug where snowflake_worn_state wasnt being set
fixes more bugs
:cl:
fix: fixes some misc pAI bugs
/:cl:
> fixes some more pAI stuff

- code/controllers/subsystem/job/spawnpoints.dm
:cl:
fix: Fixed the subsystem not registering overflow spawnpoints
/:cl:
> fixes overflow spawnpoints not being registered

- code/modules/research/designs/mining_toys.dm
corrects mining equipment design spelling
it's just a one line fix, just look at it.
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
:cl:
spellcheck: mining eqiupment design > mining equipment design
/:cl:
> Spellcheck protolathe design: eqiupment > equipment

- code/game/machinery/teleporter/pad.dm
this entire system needs a refactoring but i don't have time rn so here you go lol
> emergency teleporter fix

- code/game/area/Off Station Areas.dm
- code/game/area/Space Station 13 areas.dm
- code/game/area/asteroid_areas.dm
Corrects some spelling issues regarding areas.
muh immersions
:cl:
spellcheck: Spellchecks for offstation and Triumph
/:cl:
> Spellcheck: Triumph, Offstation

- code/game/area/rift_areas.dm
- maps/rift/levels/rift-07-west_base.dmm
- maps/rift/levels/rift-08-west_deep.dmm
- maps/rift/levels/rift-09-west_caves.dmm
Corrects some spelling issues regarding areas.
muh immersions
:cl:
spellcheck: Spellchecks for Rift map, such as Undergound > Underground & Maintenence & Maintnence > Maintenance
/:cl:
> Spellcheck: Rift Map Areas

- maps/generic/shuttles/ferry/belter.dm
it's annoying to wait half a minute
> upgrades belter move speed

- code/game/objects/items/weapons/explosives.dm
:cl:
fix: fixed seismic charges trying to install on coats
/:cl:
> stops seismic charges trying to install on coats

- code/game/machinery/computer/arcade/orion.dm
dear ten millionth person to walk into the crowded bar and spam the shit out of the kill button
you are not funny
it is has been done to death
i like my ears not bleeding profusely
> make orion trail gunshot noise local and half the volume

- code/modules/mob/living/simple_mob/subtypes/animal/space/carp.dm
Is as what the title says
Stun mechanics are pretty bad and carp's are both spammed enough and fast enough that they're just not fun to fight against. Also this is in prep for some more serious carp migration events for shipmap stuff
> Commenting out Carp Stun

- citadel.dme
- code/modules/atmospherics/machinery/components/unary/vent_scrubber.dm
- code/modules/atmospherics/machinery/components/unary/vent_scrubber_vr.dm
:cl:
code: Minor Code clean up
/:cl:
> remove a _vr file for unary scrubber

- code/modules/mob/say_vr.dm
title
they have no reason to see it
> stops observers seeing the "X did something subtly" message

- code/game/gamemodes/changeling/powers/bioelectrogenesis.dm
- code/game/gamemodes/technomancer/equipment.dm
- code/game/gamemodes/technomancer/presets.dm
- code/game/gamemodes/technomancer/spells/shield.dm
- code/game/objects/items/weapons/RCD.dm
- code/game/objects/items/weapons/material/material_armor.dm
- code/game/objects/items/weapons/stunbaton.dm
- code/modules/atmospherics/environmental/zas/edge.dm
- code/modules/atmospherics/machinery/components/binary_devices/heat_pump.dm
- code/modules/atmospherics/machinery/components/binary_devices/massive_heat_pump.dm
- code/modules/integrated_electronics/subtypes/power.dm
- code/modules/mob/living/silicon/robot/robot_items.dm
- code/modules/power/crypto_miner.dm
- code/modules/power/supermatter/supermatter.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/shieldgen/shield_gen.dm
- code/modules/shieldgen/shield_gen_external.dm
- code/modules/shuttles/web_datums.dm
- tgui/packages/tgui/interfaces/ExodroneConsole.tsx
- tgui/packages/tgui/interfaces/heat_pump.js
Efficiently replaces all misspellings of efficient with the correct spelling.
Fixed spelling good.
:cl:
spellcheck: Fixed all misspellings of Efficient to efficiently become the correct spelling.
/:cl:
> Spellcheck: Efficent > Efficient

- code/datums/uplink/hardsuit_modules.dm
- code/game/objects/items/storage/uplink_kits.dm
- code/modules/hardsuits/modules/utility.dm
- code/modules/hardsuits/rig_verbs.dm
- code/modules/materials/material_synth.dm
Title
fixed spelling good
:cl:
spellcheck: Typo fixed: Synthesiser > Synthesizer
/:cl:
> Spellcheck: Synthesiser > Synthesizer

- code/modules/food/food/snacks.dm
Pizza shows in the box.
Fix good.
:cl:
fix: Pizza now shows in pizzaboxes again. Also the tag thing shows.
/:cl:
> Fix pizzabox overlays

- code/modules/nifsoft/nif.dm
Title.
Saves people the trouble of having to do it themselves when they want people to talk to them.
You can always mute your commlink if your character doesn't want to socialize.
closes #5515 
:cl:
qol: Commlinks are now initialized upon NIF calibration completion.
/:cl:
> Commlinks are initialized upon NIF calibration completion

- code/modules/hydroponics/spreading/spreading_growth.dm
> fixes plant stacking

- code/modules/power/singularity/particle_accelerator/particle.dm
normally i'd do a more elegant fix but this is legacy code awaiting refactor anyways
> fixes a runtime with particles radiating ghosts

- code/modules/mob/living/silicon/pai/pai.dm
title
actually atomizing my changes for once
fixes a bug
:cl:
fix: fixes wide pAIs being offset incorrectly when buckled
/:cl:
> fixes wide pAIs being offset incorrectly when buckled

- code/modules/power/crypto_miner.dm
:cl:
tweak: Cryptominer now accepts Helium, Vimur and phoron
/:cl:
> Cryptominer now accepts Helium, Vimur and phoron

- maps/rift/levels/rift-06-surface3.dmm
Fixes wiring to the AI core
Fixes the wiring leading to the AI core, it was messed up from someone mapping it wrong by accident. (This time, the PR's not on the same branch with other random PR's oopsie)
:cl:
fix: re-mapped a wire back into the AI core.
/:cl:
> Actually Fixes AI Wire

- maps/rift/levels/rift-06-surface3.dmm
This one involves an airlock at the explorer area leading to the courser shuttle's storage area on the Atlas.
When is it not?
:cl:
fix: explo courser storage airlock fixed
/:cl:
> I'll unfuck all these wide airlocks eventually. :^)

- code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
- code/game/objects/items/devices/gps.dm
- code/game/objects/items/weapons/material/knives.dm
- maps/rift/levels/rift-04-surface1.dmm
- maps/sectors/tradeport_140/levels/tradeport_140.dmm
- maps/sectors/tradeport_192/levels/tradeport_192.dmm
- maps/submaps/level_specific/virgo2/CrashedSmuggler.dmm
1. **Retypes the Data Knife and Adjusts its Description.**
1. _I don't know who made an addition to the description. It might've been me and I've just forgotten, but I really didn't like the way it was originally phrased. While I was editing it, I realized the Dataknife lost its GPS abilities due to the GPS rework. After dabbling with it some, I've realized that the best way to retain the original features is to just make the dataknife a GPS subtype, rather than a knife subtype. I've done this before with the survival knife, so I'm pretty familiar with the process and efficacy._
:cl:
tweak: Retypes the data knife to a gps subtype.
tweak: Tweaks the description of the data knife.
/:cl:
> Retypes to the Data Knife and Adjusts Description

- code/__DEFINES/languages/ids.dm
- code/__DEFINES/languages/legacy.dm
- code/modules/language/languages/species/celestial.dm
- interface/stylesheet.dm
- tgui/packages/tgui-panel/styles/goon/chat-dark.scss
Renames the Daemon name to Dremic in compliance with lore discussions, ffixes the description, and changes the color of the language to a different purple shade.
Brings the Dremachir language up to lore standards.
:cl:
spellcheck: Renames and reflavors the Daemon language to Dremic
/:cl:
> Renames Daemon to Dremic

- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/carbon/human/update_icons.dm
title
fixes a bug
:cl:
fix: fixes wing spreading
/:cl:
> fixes wing spreading

- maps/rift/levels/rift-06-surface3.dmm
1. **Fixes a Stray Ladder in Maint.**
1. _This ladder was presumably misplaced. It drops down into a wall in Security, ie; it doesn't work. Removed it._
:cl:
fix: Removes ladder from Maint that goes nowhere.
/:cl:
> Fixes Maint Ladder Issue

- code/game/objects/structures/crates_lockers/crates.dm
- maps/rift/levels/rift-05-surface2.dmm
1. **Restores Old Biohazard Bin sprite.**
1. _I really don't like the new biohazard bin. It has none of the depth and spirit of the original. It looks like a plain laundry cart. So I've added the old biohazard crate back in._
:cl:
add: Adds old Biohazard bin.
/:cl:
> Restores Old Biohazard Bin

- code/datums/character_profile.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/admin_set_headshot.dm
- code/modules/mob/living/living_defines.dm
- code/modules/preferences/_preferences.dm
- code/modules/preferences/preference_setup/general/01_basic.dm
> better admin tooling and character profiles

- code/modules/atmospherics/gasmixtures/gas_types_hardcoded.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/login.dm
> fixes gas reagents + action buttons when dead

- code/game/machinery/biogenerator.dm
- tgui/packages/tgui/interfaces/Biogenerator.js
fixes bluescreen
fixes stack size incrementing by 1 when you print 5
fixes bugs
:cl:
fix: fixes bluescreen
fix: fixes stack size incrementing by 1 when you print 5
/:cl:
> biogenerator fixes

- code/game/objects/structures/crates_lockers/crates.dm
1. **Restores Old Crate Sprites.**
1. _The new system is aesthetically displeasing, in my opinion. There has been some considerable support for reverting to the old sprites. I've left most of the new system's generative infrastructure in place because it's still a fine system. I just can't stand the tiny color-shifted sprites any more._
:cl:
tweak: Reverts crate icon generation to the old system.
/:cl:
> Restores Old Crate Sprites, Leaves New Render System Intact

- code/modules/atmospherics/machinery/air_alarm.dm
> allows -1 in air alarm tlv again

- code/modules/species/station/xenochimera.dm
title
i will do content changes to xenochimeras but im getting this out of the way first so i don't lump code rewriting in with content changes because that's terrible nobody wants that
it makes me irrationally angry reading it
:cl:
code: tidied the xenochimera species file
/:cl:
> tidy the xenochimera species file

- code/modules/fishing/sources/ocean.dm
1. **Updates Fishing List.**
1. _Tries to update the fishing list to return classic fish to it. I couldn't test it locally due to intense lag in the fishing minigame. So I need to get it testmerged to confirm._
:cl:
add: Adds classic fish back to the fishing list
/:cl:
> Adds Classic Fish Back to the Fishing List

- code/modules/species/station/xenochimera.dm
title
qol don't lock yourself out for 10 minutes by accident
:cl:
qol: add a confirmation to using hatch stasis
/:cl:
> add a confirmation to using hatch stasis

- code/modules/food/drinkingglass/metaglass.dm
- code/modules/reagents/Drink-Recipes.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/bad_alcohol_reagents.dm
Tiiiitle.
alcohol intolerant person drinks a gibb float and instantly starts losing their liver how smart and good random crap must always be alcoholic
:cl:
fix: obviously-not-supposed-to-be-alcoholic drinks are not alcoholic
/:cl:
> Adds a unit test to squash alcoholic drinks made with only non-alcoholic reagents

- code/modules/atmospherics/machinery/air_alarm.dm
they're obnoxious, see reasoning in files changed.
> disables air alarm sounds 

- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Core.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
- code/modules/species/promethean/promethean_blob.dm
As title
Not an intentional mechanic, kinda lame and bad
:cl:
fix: Prommie slimes no longer instadie when sprayed
/:cl:
> Fixes prommie slimes dying instantly to water

- maps/triumph/levels/deck3.dmm
1. **Adds a sink to Triumph Robotics surgery.**
1. _Not sure why it's missing, but I only noticed yesterday. Need a sink for cleaning gloves, NIFs, etc._
:cl:
add: Adds a sink to Triumph Robotics surgery.
/:cl:
> Let That Sink In (Adds A Sink to Triumph Robotics Surgery)

- code/modules/mob/living/silicon/silicon.dm
this is not futureproofed as dynamically generated languages won't be included, but whatever.
> ais, pais, and cyborgs can all speak translation class level 1 languages now

- code/modules/vore/fluffstuff/custom_clothes.dm
1. **Fixes Latex Maid Outfit.**
1. _Player request. Apparently it's been broken. Someone changed it to the new rendering system without bothering to actually change the code. Not sure who did that or why._
:cl:
fix: Fixes Latex Maid Outfit
/:cl:
> Fixes Latex Maid Outfit

- code/modules/food/drinkingglass/metaglass.dm
- code/modules/reagents/Drink-Recipes.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
I just added rum to the recipe before, because they were made entirely with non-alcoholic ingredients. Banana mama in particular was as strong as absinthe but made using ingredients any reasonable person would recognize as the basic ingredients for a *banana milkshake*, which is goofy. I added alcohol to the recipe but I figure it's better to keep the old recipe for familiarity's sake but just make them non-alcoholic.
Changing recipes without informing people is a bit annoying but lemme tell you "you thought you were making a safe non-alcoholic drink but actually you're getting super drunk" is unbelievably bad vibes
:cl:
tweak: Silencer/banana mama are non-alcoholic (old recipe restored)
/:cl:
> Makes banana mama/silencer non-alcoholic

- code/modules/research/designs/prosfab_designs.dm
> fixes a prosthetics printing bug

- code/__DEFINES/atmospherics/machinery/alarm.dm
:cl:
tweak: tweaked air alarms to allow 0.001 moles of any gas before raising alarms
/:cl:
> Airalarms now tolerate small amounts of toxic gas

- code/controllers/subsystem/vote.dm
- tgui/packages/tgui/interfaces/Vote.tsx
sometimes you wanna make the end result a surprise
:cl:
add: Added option to make votes secret
/:cl:
> allows admins to make cast votes invisible to normal users

- code/modules/holidays/halloween_loadout_masquarade.dm
1. **Adds Fake Changeling Claw Gloves.**
1. _Player request to help put a costume together._
:cl:
add: Adds Costume Changeling Claw Gloves
/:cl:
> Adds Fake Changeling Claw Gloves to Masquerade

- code/modules/materials/definitions/organic/wood/plank.dm
i don't know how ci didn't catch that, is it because i'm lazy initing????? shouldn't be right???
> fixes wood recipe gen

- code/modules/food/food/snacks.dm
1. **Fixes Inheritance of Sealed Traits.**
1. _Whoops. When I abstracted these types I forgot to put the traits that affect the sealed foods on the abstract._
:cl:
fix: Fixes Inheritance of Sealed Traits.
/:cl:
> Fixes Sealed Food Inheritance

- code/modules/holidays/halloween_loadout.dm
:cl:
add: Added bellydancer outfit in halloween loadout
/:cl:
> bellydancer outfit in halloween loadout

- code/game/objects/items/bodybag.dm
- code/game/objects/items/robobag.dm
title
Stasis bags should be more useful. We can always add a power requirement later if we really want to.
add: stasis bags are now reusable
/:cl:
> fixes stasis bag attack hand, makes stasis bags reusable

- code/game/objects/structures/inflatable.dm
As title. Previous way it did this just assumed that ..() wouldn't actually call the parent's version of the proc, for some reason.
Anti-cheese?
:cl:
fix: Tearing inflatables actually has consequences now
/:cl:
> Fixes inflatables being inflatable when torn

- code/modules/modular_computers/file_system/programs/command/comm.dm
shitcode galore i guess lol
awful
when do i rewrite the concept of computers
> fixes faxes not showing up in command consoles

- code/modules/holidays/halloween_loadout_masquarade.dm
:cl:
add: Added Belly dancer outfit as halloween costume
/:cl:
> Belly dancer outfit as halloween costume

- code/modules/mob/living/say.dm
i really need to refactor saycode.
> fixes signlang

- code/modules/mob/living/simple_mob/subtypes/animal/space/mouse_army.dm
- code/modules/mob/living/simple_mob/subtypes/occult/living_statue.dm
- code/modules/mob/living/simple_mob/subtypes/vore/shadekin/ability_objects.dm
- code/modules/projectiles/projectile/bullets.dm
1. *Nerfs Pyro Mouse Fire Rate and Projectile.*
2. *Gives Living Statue Bespoke Darkness Spell.*
3. *Living Statue Drops Materials On Death.*
:cl:
balance: Pyro Mouse fire rate reduced.
add: Adds Veil of Shadows ability to Living Statue.
tweak: Living Statues drop items on death.
/:cl:
> Nerfs Pyro Mouse and Tweaks/Buffs Living Statue

- code/modules/food/food/snacks.dm
1. **Fixes Abstract Mispath for Wrapped Candy.**
1. _Not sure how this happened. I know for a fact I tested foods for each type at the time. Who knows what caused this._
:cl:
fix: Fixes abstract for wrapped snacks.
/:cl:
> Fixes Abstract Bug for Wrapped Snack Subtype

- code/game/objects/items/bodybag.dm
> fixes stasis bags

- code/modules/organs/external/species/diona.dm
code used to check for a ckey / client and kill the nymph
idk why exactly
nymph scarves (not corpses)
:cl:
/:cl:
> removes automatic diona nymph death

- code/datums/recipe/material_recipes/tools.dm
:cl:
fix: hammer heads are no longer called forks
/:cl:
> fixes hammer heads being called forks

- .github/workflows/ci_suite.yml
Did you know this is pointless to have?
[docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs)
> CI: Skipping is native feature

- code/game/atoms/atom.dm
- code/game/objects/items/devices/gps.dm
- code/modules/multiz/movement.dm
Move() already calls it, so we were double calling
> fixes gpses breaking on flight

- code/modules/power/singularity/act.dm
Funny enough, it was being overridden by the correct one
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/blob/a5ada8e75e396738fb53a1cad39e7d5122f49f79/code/game/objects/items/storage/backpack.dm#L64-L70
> Removes old duplicate backpack of holding singularity_act

- code/controllers/subsystem/planets.dm
- code/datums/unarmed_attack.dm
- code/game/machinery/pipe/construction.dm
- code/game/objects/effects/chem/foam.dm
- code/game/objects/structures/inflatable.dm
- code/game/objects/structures/low_wall.dm
- code/game/objects/structures/tables/bench.dm
- code/game/objects/structures/tables/rack.dm
- code/game/objects/structures/tables/table.dm
- code/modules/atmospherics/machinery/air_alarm.dm
- code/modules/atmospherics/machinery/components/unary/vent_scrubber.dm
- code/modules/food/food/snacks.dm
- code/modules/mob/living/simple_mob/combat.dm
- code/modules/mob/living/simple_mob/simple_mob.dm
- code/modules/mob/living/simple_mob/subtypes/slime/slime.dm
- code/modules/mob/living/simple_mob/subtypes/slime/xenobio/xenobio.dm
- code/modules/mob/observer/observer.dm
- code/modules/planet/planet.dm
- code/modules/reagents/reagent_containers/glass.dm
- code/modules/species/protean/protean_blob.dm
- tgui/packages/tgui/interfaces/common/Materials.tsx
see files changed:
- fixes lowwalls clickblocking
- pipes are now smaller
- fxies some table stuff
- air alarms
- buffs scrubbers
- buffs protean blob structure damage again are you happy now @Ghostcoffeee 
- both buffs and nerfs metal foam
- nerfs inflatables
- fixes weather
> various fixes + tweaks

- code/game/objects/items/storage/_storage.dm
> fixes storage not dropping contents on destruction

- code/game/objects/items/upgradekit.dm
> kevlar upgrades no longer make you immortal

- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Core.dm
As title.
What even is water? Apparently, our characters don't know. Now they do.
:cl:
qol: Gave water a cup name so cups of water now appear as "cup of water" instead of "cup of.. what?"
/:cl:
> Makes cups of water not cups of.. what?

- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
I changed the Vodka flavour.
Because it's really silly (stupid) to say it tastes like grain alcohol.
\- "taste_description = 'grain alcohol'"
\+ "taste_description = 'potato alcohol'"
:cl:
tweak: vodka flavour
/:cl:
> pet peeve solved

- code/modules/reagents/items/hypospray.dm
bandaid; see comment
i'll fix it proper later
> bandaids hypospray

- code/game/objects/structures/tables/materials.dm
- code/modules/power/cable.dm
> fixes tables & poewrnet

- code/__HELPERS/text.dm
makes whatsoever not autocorrect to what'soever
what'soever
:cl:
fix: autocorrect no longer corrects "whatsoever" to "what'soever"
/:cl:
> what'soever

- dependencies.sh
tg did it
this fixes the bootstrap issue
no, we shouldn't do this to fix things
no, i don't care
if someone wants to do it better be my guest i'm not here to do devops unless it's absolutely necessary for me to do so
> downgrades pyhton to 3.9.0

- .github/workflows/ci_suite.yml
well
turns out having jobs stop because the previous one exits is ruining the point
this is honestly a snowflakey patch but we'll deal with it proper later.
> smacks the CI suite with the if: always()

- citadel.dme
- code/modules/mapping/spawner/tcomms_relay.dm
:cl:
add: Added a relay spawner that autoconnects to the station comms
/:cl:
> Adds a relay spawner that autoconnects to the station comms

- code/modules/reagents/machinery/dispenser/supply.dm
As title.
There's booze and soda dispensers, this just seems like an oversight.
:cl:
add: Coffee dispenser crate added to cargo
/:cl:
> Adds a coffee dispenser crate to cargo

- config_static/jukebox.json
Another Jukebox update that adds more songs into the jukebox for players to choose from!
**Alternative:**
Turning Japanese by The Vapors
The Fine Print by The Stupendium
**Arcade:**
…con lentitud poderosa by Chris Christdoulou
Coalescence by Chris Christdoulou
The Rain Formerly Known as Purple by Chris Christdoulou
Roland by Studio EIM
Binah by Studio EIM
Calamari Inkantation by Toru Minegishi and Shiho Fukii
In the Final by Yoko Shimomura
Roland Style by ems' delicious garbage (Emagged)
**Classical and Orchestral:**
Snake Eater by Cynthia Harell
**Country and Western:**
I Wanna Talk About Me by Toby Keith
As Good As I Once Was by Toby Keith
Should’ve Been A Cowboy by Toby Keith
How Do You Like Me Now?! by Toby Keith
Merry Christmas from the Family by Montgomery Gentry
Pancho and Lefty by …
> Jukebox Additions Part Two

- code/game/machinery/floor_light.dm
needless strain on the game, to constantly update the lights on the dancefloor when hardly anyone is ever there
:cl:
tweak: tweaked the gaia dancefloor to start inactive, for performance reasons
/:cl:
> Gaia floorlighting starts offline

- code/modules/mob/living/carbon/human/traits/_trait.dm
:cl:
fix: fixed the game trying to apply traits/autohiss to observers, causing occasional runtimes
/:cl:
> fixes traits applying to observers

- code/datums/radiation_wave.dm
> [TESTMERGE ONLY] Revert "Makes radiation wave decay inverse square instead of exponential"

- code/modules/reagents/items/hypospray.dm
- code/modules/reagents/items/hypovial.dm
title
fixes a bug
:cl:
fix: stop large hypovials going in non-advanced hyposprays
/:cl:
> stop large hypovials going in non-advanced hyposprays

- code/modules/food/recipes_microwave.dm
1. **Fixes Borg-O Recipe.**
1. _The recipe is still using cooking oil. Changed to tallow._
:cl:
fix: Fixes Borg-O recipe.
/:cl:
> Fixes Borg-O Recipe

- .vscode/settings.json
- _mapload/minitest.dm
- code/game/machinery/doors/airlock/airlock_control.dm
- code/game/machinery/doors/airlock/phoronlocks.dm
- code/modules/atmospherics/machinery/portable/scrubber.dm
- maps/minitest/levels/minitest.dmm
- tgui/packages/tgui/interfaces/EmbeddedController.js
:cl:
fix: fixed stationary scrubbers not scrubbing due to missing cells
fix: fixed stationary scrubbers not having a list of gases to scrub
fix: fixed the phoronlock statemachine
tweak: Tweaked phoronlock controllers to care about temperature.
add: added two phoronlock examples to minitest
admin: added file to allow to force minitest to be loaded before compile.
/:cl:
> Fixes stationary portable scrubbers, and the phoronlock statemachine

- code/modules/ghostroles/instantiator.dm
:cl:
fix: fixes ghostrole spawners spawning empty mobs when requirements arent met
/:cl:
> fixes ghostrole spawners spawning empty mobs when requirements arent met

- maps/tether/levels/misc.dmm
:cl:
fix: fixed the supply shuttle not transitioning to station
/:cl:
> fixes the tether supply shuttle not loading in properly when ordered

- code/modules/clothing/shoes/_shoes.dm
1. **The Dataknife Now Fits in Boots.**
1. _Apparently these don't fit in boots. I'm sure I intended that, but eh. Why not._
:cl:
tweak: Dataknife now fits boots.
/:cl:
> Makes the Dataknife Fit Boots

- maps/tether/levels/surface2.dmm
Fixes disappearing wires on surface 2 and adapts the whole level to use the department color walls
:cl:
tweak: adapts tether surface 2 to use the department color walls 
/:cl:
> Baywallifies tether surface 2

- code/modules/species/station/xenochimera.dm
yea
this changes it so if the chimera communes on-station, it will get candidates from the station, otherwise, it'll look for candidates on the same z-level
probably the intended, least weird way to do this 
please no more i dont want to touch that shitty proc anymore
:cl:
fix:commune chimera
/:cl:
> fixes commune not letting you commune to someone 2 tiles away

- code/game/objects/items/devices/tape_recorder/tape_recorder.dm
title
fixes a runtime
:cl:
fix: stops tape recorder attempting to play when nothing is recorded
/:cl:
> stops tape recorder attempting to play when nothing is recorded

- code/game/objects/structures/girders.dm
tries to do a thing on a thing without checking if the thing exists
fixes a runtime
:cl:
fix: fixes a girder runtime
/:cl:
> fixes a girder runtime

- code/modules/mob/observer/dead/orbit.dm
:cl:
admin: Invisimins dont appear in the orbit menu
/:cl:
> Allows silicons(our headcoder) to hide

- maps/tether/levels/mining.dmm
- maps/tether/levels/plains.dmm
- maps/tether/levels/surface1.dmm
> Adapt Surface 1

- maps/tether/levels/surface3.dmm
> adaptation of tether surface 3 for new walls and windows

- maps/tether/levels/midpoint.dmm
> Adapt tether midpoint

- code/game/objects/items/weapons/nullrod.dm
- code/modules/instruments/instruments/item.dm
A few attack verbs use the present tense instead of present perfect. This fixes that.
"Has been smacks with" looks funny
:cl:
spellcheck: Fixed the tense on some attack verbs
/:cl:
> Fixes the tense on some attack verbs

- code/modules/clothing/masks/miscellaneous.dm
As title. ??
It causes runtimes and stuff not to work for no reason
:cl:
fix: Some mask stuff will actually work now probably
/:cl:
> Makes a couple variables not arbitrarily converted to strings for no reason (??)

- code/__HELPERS/icon_smoothing.dm
- code/game/objects/structures/low_wall.dm
- code/game/turfs/simulated/wall/materials.dm
- code/game/turfs/simulated/wall/wall.dm
- code/game/turfs/simulated/wall/wall_icon.dm
- code/game/turfs/simulated/wall_types/wall_types.dm
- code/modules/mapping/map_helpers/paint.dm
Kev keeps begging me to fix walls, so I fixed them
:cl:
fix: Walls no longer loose their paint when updated by neighbors
/:cl:
> Refactoring Baywalls and tweaking smoothing code

- maps/rift/levels/rift-08-west_deep.dmm
> superheated epic gas cave now has a warning sign and also lava instead of water

- code/modules/recycling/disposal.dm
> disposal fixes

- code/modules/power/singularity/emitter.dm
we'll readd the explosion later
> fixes & standardizes emitter integrity

- code/modules/jobs/job_types/station/civillian/clown.dm
- code/modules/jobs/job_types/station/civillian/mime.dm
:cl:
add: Added second mime slot
/:cl:
> Add a second mime slot

- code/game/atoms/movable/throwing.dm
- code/game/objects/items.dm
- code/modules/mob/inventory/items.dm
- code/modules/mob/living/throwing.dm
- knocking items around now only happens on harm
- thrown items will have random offset + orientation when thrown on harm (or by a non-gentle throw source)
> small change to throwing

- code/modules/reagents/Drink-Recipes.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
As title. I scrolled through and fixed things that were bothering me.
Main points:
1. Most drinks now have a bit of nutritional value. Some have a lot. No more are the days when you could drink 50 peanut butter milkshakes and not get fat.
2. Alcoholic drinks were largely rebalanced. I didn't get to all of them, mostly ignored the ones that seemed made-up, but for real ones, I tried to give them strengths that actually line up with their contents. I don't know why wine was stronger than whiskey, but it suuuure was.
Mechanics should at least _sorta_ line up with expectation. The fact that a drink described as "Tyrmalin grog aggressively blended with unfiltered absinthe" was one of the weakest in the game was... weird.
:cl:
tweak: Non-alcoholic drinks now generally add some nutriment
tweak: …
> I went through food/drinks and fixed as I scrolled

- maps/tether/levels/surface1.dmm
- maps/tether/levels/surface2.dmm
:cl:
fix: fixed two doors appearing above walls, instead of floors
/:cl:
> fixes two walls under doors

- code/game/machinery/embedded_controller/airlock_controllers.dm
- code/game/machinery/embedded_controller/airlock_program.dm
:cl:
fix: fixed access control airlocks not cycling
/:cl:
> access controll airlocks have a simplified process proc

- code/game/machinery/doors/airlock/airlock.dm
Technically a regression. Smart overlays do not play nice with doors for reasons unknown.
some overlays actually show up now.
> Fixes airlock overlays not appearing

- code/modules/cargo/supplypacks/hydroponics.dm
1. **Fixes Pathing Bug With Cow Crates.*
1. _It turns out the crate for furnace grubs had the same path as the cow crate, overwriting the crate so that cows became unorderable. This fixes that._
:cl:
fix: Fixes pathing bug with cow crates.
/:cl:
> Corrects Cargo Cow Crate Conundrum

- code/modules/food/food/snacks.dm
- code/modules/hydroponics/grown.dm
:cl:
fix: fixed kitchen knives not working for slicing fruits
/:cl:
> slicing fruits and pizza works with kitchen knifes again

- code/modules/power/smes/smes_construction.dm
3-12 sec down from 10-60
4.5-18 if it has a chance of exploding
I don't think standing still for a minute is good UX.
> smes deconstruction is faster

- code/__DEFINES/mobs/life.dm
- code/modules/mob/living/carbon/human/life.dm
tl;dr i'm stupid
basically, stabilization is hyper, hyper aggressive.
if you're going to be "stabilized" at all the system goes into stabilization calculations for bodytemperature - which then makes you overshoot by, say, 1000 degrees.
this fixes that.
> fixes temperature stabilization killing people in atmos voidsuits

- code/datums/design/designs/machines/circuits.dm
1. **Adds Airlock Electronics to the Autolathe.**
1. _These were missing after the autolathe rework a while back._
:cl:
add: Adds airlock electronics to autolathe.
/:cl:
> Adds Airlock Electronics to Autolathe

- code/modules/maps/templates/submaps/debrisfield/debrisfield_submaptemplate.dm
- maps/sectors/debrisfield_192/debrisfield_192.dm
- maps/submaps/level_specific/debrisfield_vr/clownship.dmm
And it took me this long to look into it. Anyway The Debris Field should now probably spawn more POIs then the Clown Ops ship. 
:cl:
fix: Debris Field POIs spawn properly now.
/:cl:
> Fixes Debris Field POI Spawning

- code/controllers/subsystem/mapping/maps.dm
- code/modules/mapping/map.dm
- maps/euthenia/euthenia.dm
please stop pickign euthenia at random.
> maybe fixes travis

- code/modules/maps/overmap/space/debrisfield.dm
Comments out a Proc that was causing consistent Runtime with the 'Tiny Carrier' POI. Hopefully this greatly reduces debris field runtimes. Can you believe that when I put up the debris field PR I didn't get this runtime at all since the ship didn't spawn in CI tests?
:cl:
fix: broken procs commented out
/:cl:
> Debrisfield Hotfix

- code/__DEFINES/misc.dm
my new character name is too long and its too good to change :/
> max name length 52 >> 64

- .git-blame-ignore-revs
title, also why was this filed copied directly, we dont have those commit hashes
hiding myself from the gitblame
> git-blame-ignore-revs

- code/game/machinery/cryo.dm
:cl:
tweak: cryo cell fuild to change opacity the cooler it gets
/:cl:
> Cryo cell fluid changes opacity

- tgui/packages/tgui/interfaces/GamePreferences/GamePreferenceEntry.tsx
> fixes game prefs

- maps/sectors/admin_planets_192/croatoan.dmm
Makes some edits to the NSB Croatoan Map Template.
Fixes some bugs I didn't catch early on.
Removes fake_stair railings and fixes the High Security stairs so they let you go back down.
:cl:
add: Fixes some bugs with railings and a set of fake stairs.
/:cl:
> NSB Croatoan Map Template Edit-2

- code/controllers/subsystem/mapping/_mapping.dm
:cl:
qol: Mapping subsystem now prints the active map to world, so you know on which map IntTest errors occur
/:cl:
> print map when starting Mapping init

- code/modules/organs/external/external.dm
- code/modules/organs/external/species/slime.dm
- code/modules/species/promethean/promethean.dm
prommies are no longer invuln
fuck
they also lost their ridiculous damage modifiers and have more limb health now.
> fixes limb damage & slight promethean rebalance

- code/controllers/subsystem/preferences.dm
- code/modules/client/client_procs.dm
> fixes prefs early init issue

- code/modules/recycling/disposal.dm
:cl:
fix: fixed disposals doing a hide() and never coming back
/:cl:
> Fixes disposals hiding permanently

- maps/triumph/levels/flagship.dmm
As title.
The marksman has a literal dedicated smoking lounge next door with its own vendor and three entire free packs, dude
:cl:
tweak: Replaced cig vendor in Marksman bar/grill wiht a hacked MRE vendor
/:cl:
> Replaces the cig vendor in the marksman bar/grill with a hacked MRE vendor

- code/__DEFINES/traits/mob.dm
- code/__DEFINES/traits/sources.dm
- code/game/machinery/cryo.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/health.dm
- code/modules/mob/living/mobility.dm
> fixes cryotubes

- citadel.dme
- code/modules/library/hardcode_library/reference/xenomorph_facts.dm
Lore information ingame on my codebase???
:cl:
add: Added a new book, detailing lore information about xenomorphs
/:cl:
> About the life of a xenomorph Part 1

- code/modules/sprite_accessories/tail/species/xenomorph.dm
> fixes the waggable xenomorph tail

- code/modules/atmospherics/machinery/components/unary/heat_exchanger.dm
:cl:
tweak: tweaked heat exchanger density
/:cl:
> changes heat exchanger density so they dont just look like you cant walk over them

- code/modules/overmap/legacy/ships/computers/sensors.dm
:cl:
fix: fixed double init on sensor consoles
/:cl:
> fixes the sensors console double initing papers

- maps/rift/levels/rift-06-surface3.dmm
:cl:
fix: removes bypassing disposalpipe that prevents stuff from being shiped to bar
/:cl:
> removes bypassing disposalpipe that prevents stuff from being shiped to bar

- citadel.dme
- code/game/objects/random/books.dm
- code/modules/library/lib_items.dm
- maps/rift/levels/rift-04-surface1.dmm
:cl:
add: Added new Bookshelf with random lore books inside
/:cl:
> adds a bookshelf that spawns with a number of random lore books

- tgui/packages/tgui/interfaces/JoinMenu.tsx
:cl:
tweak: tweaked minor thing on the latejoin panel
/:cl:
> tweaked minor thing on the latejoin panel

- maps/rift/levels/rift-04-surface1.dmm
- maps/rift/levels/rift-06-surface3.dmm
- maps/triumph/levels/deck2.dmm
- maps/triumph/levels/deck4.dmm
moving the MRE vendor to not be a middle finger to the chef (I was told I couldn't just delete it, otherwise this would just be a removal.)
Removes the MRE vendor in the bar area, shoves it where 2 tables where on surface 1 in a side room so it's still available for those that use it.
I feel like just removing it would be better, but I was told to keep it. Anyhow for moving it out of the bar is done purely because it being right next to the kitchen is basically the biggest middle finger you can give to any chef players. They're already fighting the almighty power that is the fitmax vendor, adding another reason to not interact with them 2 feet away from them is just salt in the wound. If you're going to the bar/kitchen for food items, you are going to interact with service staff. If you …
> moving MRE vendors-ATLAS version (WIP)

- code/modules/frames/frame.dm
- code/modules/frames/item.dm
> fixes some severe frame bugs

- code/game/rendering/screen.dm
The location descriptors already include prepositions.
Genuinely a typo.
:cl:
spellcheck: "On your on your back" etc. fixed
/:cl:
> Fixes all the "on your in your" with internals

- citadel.dme
- code/__HELPERS/thermal.dm
:cl:
code: adds basic helper procs for doing thermal calculations
/:cl:
> adds basic helper procs for doing thermal calculations

- code/modules/atmospherics/machinery/_atmospherics_helpers.dm
- code/modules/atmospherics/machinery/components/binary_devices/heat_pump.dm
- code/modules/atmospherics/machinery/components/binary_devices/massive_heat_pump.dm
- code/modules/atmospherics/machinery/components/unary/env_heat_pump.dm
:cl:
refactor: turns the heat_pump pumping part into a generic atmos proc
/:cl:
> makes standard atmos proc, pump_heat()

- code/game/turfs/turf.dm
Title.
lol my bad
my fault.
:cl:
fix: Silicons will no longer telepathically push walls.
/:cl:
> Fixes silicons being able to telepathically push walls

- code/modules/client/onboarding/age_verification.dm
god damn dude, what the hells.
> tries to make age verify menu more stable and reliable

- code/controllers/subsystem/mapping/levels.dm
> fixes infinite loop in map system

- code/game/machinery/colormate.dm
- code/modules/hardsuits/_rig.dm
Title
Customization good.
:cl:
add: You can now color your hardsuits and radio headsets in the colormate.
/:cl:
> Lets hardsuits and radio headsets be used in the colormate

- code/modules/food/food/ice_cream.dm
- code/modules/food/structures/icecream_cart.dm
it was two lines
they literally do not work right now
:cl:
fix: Ice cream works
/:cl:
> Fixes ice cream carts

- code/__HELPERS/_logging.dm
- code/modules/food/food/ice_cream.dm
- code/modules/food/structures/icecream_cart.dm
- maps/minitest/minitest.dm
*crap*.
also, CI changes are because i'm sick of mysterious CI failures.
> fixes ice cream being unfillable, marks minitest as no-random-draw, adds more CI logging

- code/game/machinery/doors/airlock/airlock.dm
:cl:
fix: fixed airlock glass filling being inconsistent
/:cl:
> fixes some airlocks looking like they dont have glass while they should

- citadel.dme
- code/__HELPERS/math/fractions.dm
- code/___compile_options.dm
- code/controllers/subsystem/timer.dm
- code/datums/looping_sounds/_looping_sound.dm
- code/game/world.dm
- config/legacy/config.txt
i'm pretty sure we're supposed to ceil instead of floor there
(TIMER_LOOP timers are going off the handle)
this doesn't actually fully fix the issue it just fixes one of my fuckups that was causing it
> maybe fixes timer issues, tweaks world fps, timers, etc

- code/game/turfs/simulated.dm
yippeee
hahehsahjhdsafhb nerf
:cl:
tweak: Floor scuffs now take 125 steps instead of 75.
/:cl:
> Nerf floor scuffs to 125 steps to dirty.

- code/game/machinery/doors/airlock/airlock.dm
this fixes the runtime
not the issue.
> fixes airlock runtimes that are breaking CI

- tgui/packages/tgui-panel/styles/goon/chat-dark.scss
Title. Teshari and a few others.
hey let's not use dark tones in a dark background kay?
:cl:
tweak: Teshari font should be brighter.
/:cl:
> Makes a few font settings brighter in dark mode

- code/__DEFINES/objects/objects.dm
- code/game/machinery/beacon.dm
- code/game/machinery/magnet.dm
- code/game/machinery/navbeacon.dm
- code/game/objects/items/devices/radio/beacon.dm
- code/game/objects/objs.dm
- code/game/objects/structures/safe.dm
- code/modules/atmospherics/machinery/machinery.dm
- code/modules/atmospherics/machinery/pipes/pipe_base.dm
- code/modules/atmospherics/machinery/pipes/tank.dm
- code/modules/shieldgen/shield_diffuser.dm
> fixes underfloor + atmos pipe placement

- code/game/objects/structures/curtains.dm
kinda silly otherwise
:cl:
fix: fixed curtains not being anchored by default
/:cl:
> Fixes curtains not being anchored by default

- code/modules/overmap/entity/physics.dm
> being blocked by a wall on overmaps kills motion

- code/datums/design/designs/medical/chemistry.dm
- code/datums/design/designs/misc/drinking_glass.dm
- code/modules/food/drinkingglass/glass1.dm
- code/modules/food/drinkingglass/metaglass.dm
- code/modules/food/drinkingglass/shaker.dm
- code/modules/reagents/reagent_containers/spray.dm
- code/modules/research/designs/weapons.dm
- Adds spray bottles to the autolathe. This also means spray bottle scan get recycled.
- since various items are being an extension of spray bottle, they also get a base material that could be used for recycling or whatever else.
- The metamaterial glass, coffee cup, and fitness cup have also been added to the autolathe.
- The costs of making these glasses have been made cheaper to make it consistent with the other glasses available in the lathe.
"Hold up, giving people spray bottles seems like a bad idea."
So is a chem sprayer, and you can make those in R&D.
At minimum, people can fill it with water and make water messes. They can also do that with a fire extinguisher. In order to cause more chaos, they'd need to have access to touch chemicals, which is only likely if you're a security …
> Adds spray bottle & more glasses to autolathe

- code/modules/food/drinks/bottle.dm
As title
Bottles should work
:cl:
fix: Ambrosia Mead, Wax-Sealed Royal Jelly now contain the proper drinks
/:cl:
> Fixes a copy+paste typo causing royal jelly to be mead and mead to be nothing

- config_static/jukebox.json
Lets get a few more JAMS in in the jukebox. lets GOOOO
Adds the following songs:
(Formatted as follows: Artist - Song [Category])
No, Really - Rust [Folk and Indie]
I, Monster - Lust for a Vampyr [Alternative]
Dubmood - Simple Machine [Electronic]
Darling Violetta - Smaller God [Rock]
*mchitter
*mchitter
*msqueak
*mlaugh
No CL no fun
> Hey. Wanna listen to some TUNES?

- code/controllers/configuration_old/configuration.dm
- code/controllers/subsystem/processing/projectiles.dm
- code/modules/admin/verbs/ticklag.dm
- code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/adv_dark_gygax.dm
- code/modules/mob/living/simple_mob/subtypes/slime/feral/feral.dm
- code/modules/projectiles/projectile.dm
- code/modules/projectiles/projectile/arc.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/hook.dm
makes projectiles faster
adds a tuning variable again
removes a useless button in set-ticklag
fixes homing
optimizes projectiles / makes them easier to reason about
> misc projectiles raycasting tweaks, makes projectiles faster

- code/modules/projectiles/projectile.dm
as title
25% tidi every round because turrets are hard deleting a list per unit in a 15x15 x-ray square around them
:cl:
fix: Optimized projectiles a smidge
/:cl:
> Fixes every projectile hard deleting a list instead of just nulling it when it hits

- code/modules/maps/weather/classg.dm
A planet can't have an atmosphere filled with fuel and oxidizer at the same time, except trace amounts of one or the other. If a planet's atmosphere is sufficient for fire to spread, then a single spark of any sort anywhere (such as, say, lightning, or a rock rolling down a hill just right) will cause the whole planet to catch fire.
This changes the Class G mineral planet so that it's already done that.
I mean having a burn mix planet is genuinely a little funny but it's:
1. Not actually that fun gameplay-wise (it just means nobody ever goes there)
2. Completely goofy setting-wise (for reasons mentioned)
3. Phoron's awful on its own, it doesn't need to catch fire
:cl:
tweak: Oxygen on the Class G Mineral-Rich planet changed to CO2
/:cl:
> Pre-burns the mineral planet

- code/__DEFINES/mapping/levels.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/species/abilites.dm
for EMs
this isn't really ideal and is just a bandaid
real reworks coming soon(tm), gamers!
> adds a ztrait to ban xray vision of any sort

- code/__HELPERS/files/paths.dm
- code/modules/mapping/dmm_suite/dmm_parsed.dm
uh oh
testmerge for a little first but this is a security issue
> experimental maploader changes

- code/modules/integrated_electronics/passive/power.dm
I did a itzy bitzy tiny little wucky fucky when doing the ref push 4 months ago. Now it works, plus blood wasn't doing its thing.
> IC Fuel cell ref push and blood fix

- code/modules/power/cable.dm
> floor wiring fix

- code/modules/integrated_electronics/core/printer.dm
i'm going to throttle whoever coded integrated circuits fuck i hate them
> [s] integrated circuit stuff

- maps/rift/engines/burn.dmm
- maps/rift/levels/rift-04-surface1.dmm
- maps/rift/levels/rift-05-surface2.dmm
Removes a pipe, nodes three APCs
I'm not sure what having two pipes in the same place does, but it can't be good. Noded APCs mean that the engineers won't have to go and manually do it every round.
removed pipe
added wires to reach APCs
:cl:
add: wires and nodes
fix: removed pipe
/:cl:
> Random Assortment of Atlas Fixes

- code/modules/species/station/xenomorph_hybrids/hybrid_resin.dm
:cl:
fix: fixed hybrid resin doors not being visible
/:cl:
> fix hybrid resin doors being invisible

- code/modules/clothing/suits/hooded.dm
:cl:
fix: fixed some hooded coats not being visble while the hood is up
/:cl:
> fixes some coats not having a sprite while the hood is up

- code/game/gamemodes/events/wormholes.dm
- code/game/machinery/computer/specops_shuttle.dm
- code/game/machinery/teleporter/projector.dm
- code/game/objects/effects/portals.dm
- code/modules/shuttles/shuttle_specops.dm
- code/modules/vehicles/sealed/mecha/equipment/tools/wormhole.dm
- code/modules/vore/fluffstuff/guns/bsharpoon.dm
teleportation as a whole is under rework.
The old code is frankly utterly unsalvageable 
So let's have a working machine and care about balancing later
> Removes teleporter (including portal and harpoon) failure and recursive power usage 

- code/game/machinery/teleporter/projector.dm
> fixes my shame

- .github/workflows/update_tgs_dmapi.yml
- Put release notes in PR body
- actions/checkout@v4
- TGS CI bot as committer
Also newer ubuntu
> Update DMAPI Updater

- code/game/objects/items/inducer.dm
I am rechraging Tarot in the engine repair pose.
I am rechraging Tarot in the engine repair pose.
I am rechraging Tarot in the engine repair pose.
:cl:
fix: Rechrage --> Recharge
/:cl:
> No Rechraged Inducer --> Fixes a cute typo

- code/game/machinery/turrets/turret.dm
> fixes turrets

- maps/templates/admin/dojo_001.dmm
it breaks the CI
:cl:
fix: fixed admin template breaking CI due to broken paths
/:cl:
> replaces wall/log with wall/wooden/log

- code/game/click/items.dm
- code/game/machinery/turrets/turret-ai_holder.dm
- code/game/machinery/turrets/turret.dm
- code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
- code/modules/projectiles/projectile.dm
- code/modules/reagents/reagent_containers/syringes.dm
- syringes & blood
- turrets
- a cargo voucher
> fixes some bugs

- code/modules/mining/ore_redemption_machine/equipment_vendor.dm
- code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Removes the Proto Kinetic Accelerator damage modkit from the codebase.
PKA's have been a long standing issue, being able to deal upwards of 60-80 damage in one hit if you use full damage modkits on your PKA. This is completely ludicrous if you're in an area where they can be used, such as vacuum, the outside of Rift (NSB Atlas map) and a few other areas. This is a TEMPORARY SOLUTION until Silicons reworks PKA's. 
:cl:
del: Removes the PKA Damage Modkit.
/:cl:
> Backspaces the PKA Damage Modkit from code

- code/__HELPERS/text.dm
ups the line breaks allowed max in emotes (via upping it in sanitize)
i was regularly hitting this.
this is a rage patch, i admit it.
:cl:
qol: emotes now can have more line breaks.
/:cl:
> ups sanitize line breaks allowed

- code/modules/integrated_electronics/subtypes/input.dm
fixes sign language circuit to hear sign language
fix bug
:cl:
fix: sign language circuit now picks up sign language
/:cl:
> fixs sign language circuit

- code/__DEFINES/loadout.dm
> more loadout slots

- code/game/turfs/simulated/floor/floor_types.dm
sigh
WHY ARE WE USING MUTABLE APPEARANCES FOR THIS
> fixes floor underlays

- maps/rift/levels/rift-05-surface2.dmm
- maps/rift/levels/rift-06-surface3.dmm
electrochromatic linkers got wiped from atlas due to a merge issue
yeah
:cl:
fix: electrochromatic linkers placed back on Atlas.
/:cl:
> electrochromatic linker fix

- maps/rift/levels/rift-04-surface1.dmm
genpop brig doors were missing access helpers
fixes doors
:cl:
fix: Security can now access genpop doors.
/:cl:
> lets security access genpop doors

- code/modules/research/designs/circuits/machines/misc.dm
makes bioprinter creatable through circuit imprinter. I don't see much reason why not, since we can make whole resleeving consoles.
makes bioprinters makeable
:cl:
add: Bioprinter circuit is now makeable through circuit imprinter at 5 biological, 2 data.
/:cl:
> bioprinter circuit in circuit imprinter

- code/game/objects/structures/charge_pylon.dm
- code/game/objects/structures/mineral_bath.dm
- maps/rift/levels/rift-03-underground1.dmm
- maps/triumph/levels/deck2.dmm
:cl:
tweak: tweaked adherent maintenance to be less inviting to get hurt in
/:cl:
> Adjusts Adherent maintenance areas and machines to be less inviting to get hurt

- code/modules/vore/eating/belly_obj_vr.dm
title
ooc escape still gets messaged to admins
i feel like i don't need to explain myself here
:cl:
tweak: changes vore deaths to be logged rather than yelled at every online admin
/:cl:
> changes vore deaths to be logged rather than yelled at every online admin

- code/controllers/subsystem/vote.dm
:cl:
tweak: Tranfer vote ties resolve as extensions.
tweak: If the vote winner is chosen at random an additional message is displayed.
/:cl:
> transfer vote ties now always extend and there is a message for randomly chosen results

- code/modules/food/recipes_microwave.dm
Bioscans indicate that lizards have been breeding in engineering.
silicons asked me to
look ma I'm a contributor
> rewords bad comment

- code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
- code/modules/power/geothermal_power.dm
- maps/rift/levels/rift-02-underground2.dmm
- maps/rift/levels/rift-09-west_caves.dmm
- maps/sectors/lavaland_192/levels/lavaland_192.dmm
- maps/tether/levels/mining.dmm
- maps/tether/levels/station2.dmm
- maps/triumph/levels/deck2.dmm
:cl:
tweak: tweaked the lavaland base to use geothermal power proper instead of the problematic TEG setup
tweak: removes items given to miners two or three times
/:cl:
> New power for lavaland base, and some mining locker cleanup

- code/modules/awaymissions/corpse.dm
Just a small addition for EMs and mappers, as the skeletons are humanoids they can be fully equipped like humans for flavor  or even revived and piloted by EMs if they feel particularly spooky. It also provides an opportunity to make old bodies for enviromental storytelling without fiddling with remains.
:cl:
add: A Skeleton Corpse Spawner. Just that
/:cl:
> Adds Skeleton Corpse Spawner 

- maps/victory/victory.dm
:cl:
fix: fixed the victory elevator using the wrong Z-Levels
/:cl:
> fixes the victory elevator

- citadel.dme
- code/__DEFINES/loadout.dm
- code/modules/loadout/loadout_entry.dm
- code/modules/loadout/loadout_instruments.dm
most normal instruments are now in loadout
> instruments in loadout

- maps/rift/levels/rift-01-underground3.dmm
god damn i'm not even mad this is astonishingly kek
> makes the SM delam chamber not a pipe bomb

- code/modules/client/security.dm
> [s] fixes client security autobans

- code/modules/atmospherics/atmosphere/atmosphere.dm
- code/modules/atmospherics/environmental/public.dm
- code/modules/atmospherics/environmental/turf-share.dm
- code/modules/atmospherics/gasmixtures/_helpers-transfer.dm
- code/modules/atmospherics/gasmixtures/gas.dm
- code/modules/atmospherics/gasmixtures/gas_data.dm
- code/modules/atmospherics/gasmixtures/gas_types/core.dm
- code/modules/atmospherics/gasmixtures/procedural_gas.dm
the files with them were written from the ground up for our purposes but it's still a little close for comfort
the endgame i really have for xgm/zas doesn't really involve dm-side xgm/zas anyways so might as well
> yanks MIT headers from atmos

- code/__DEFINES/_cooldowns.dm
- code/__DEFINES/math.dm
- code/__HELPERS/shell.dm
- code/__HELPERS/time.dm
- code/modules/admin/verbs/playsound.dm
:cl:
code: shello to support unix errors
admin: updated playsound, it will now warn you if someone's playsound is still playing
/:cl:
> shello & playsound

- code/modules/projectiles/gun.dm
yeaaah i'm a little silly i forgot this
this lets you have guns start with attachments.
kinda important, innit.
> adds starting attachment functionality to guns

- code/modules/integrated_electronics/subtypes/reagents.dm
Fix for pocketed circuits not bypassing own armor as intended.
Injector also wont cancel its injection of the owner if they move.
> circuit injector fix and adjustment

- code/modules/mob/living/carbon/human/life.dm
- code/modules/preferences/preference_setup/vore/02_size.dm
- code/modules/vore/eating/living_vr.dm
- code/modules/vore/persist/persist_vr.dm
- code/modules/vore/weight/fitness_machines_vr.dm
never really used on citrp and has confused people more than it's added to any semblance of RP.
in the future, weight will be replaced with a descriptor system.
> removes weight gain/loss mechanics

- code/game/objects/items/weapons/flamethrower.dm
- code/modules/admin/verbs/debug.dm
- code/modules/atmospherics/environmental/zas/edges/edge-simulated.dm
- code/modules/atmospherics/gasmixtures/gas_mixture.dm
- code/modules/atmospherics/machinery/portable/canister.dm
- code/modules/events/atmos_leak.dm
- code/modules/gamemaster/actions/atmos_leak.dm
- code/modules/vore/eating/living_vr.dm
> atmos update_values() enforcement

- code/game/content/factions/corporations/nanotrasen/nanotrasen-supply/hospitality.dm
- code/modules/food/food/snacks.dm
> readds blu's crates

- code/controllers/subsystem/ticker.dm
:cl:
qol: reduces waiting for players spam
/:cl:
> only send delay message once

- code/modules/admin/view_variables/filteriffic.dm
> fix filterrific 

- maps/rift/levels/rift-05-surface2.dmm
:cl:
fix: electrochromatic windows in the ORs tint again
/:cl:
> fixes OR Windows

- code/datums/world_topic.dm
href exploit bad
https://github.com/tgstation/tgstation/pull/88367
> [s] ensure key config is set for any secure request

- maps/endeavour/levels/deck1.dmm
- maps/endeavour/levels/deck2.dmm
- maps/endeavour/levels/deck3.dmm
- maps/endeavour/levels/deck4.dmm
New PR, mostly same changes. Improvements across every deck of Endeavour.
Ship being good on launch is good.
:cl:
tweak: multiple fixes across every deck of Endeavour.
/:cl:
> Last minute Endeavour fixes.

- maps/endeavour/levels/deck1.dmm
- maps/endeavour/levels/deck2.dmm
- maps/endeavour/levels/deck3.dmm
- maps/endeavour/levels/deck4.dmm
More fixes addressing issues reported on Discord during the first round on the ship.
This is an expected part of polishing the map.
:cl:
add: added grills to the garden
add: added more lights, coffee cups and paper to the bridge meeting room
add: added electrochromics to medbay breakroom and reinstated the wall fridge
add: reinstated public departures lounge doors into departures
add: added door into a previously inaccessible maint room on deck 1
del: removed two unintended walls from maint access doors near departures
del: removed engineering tape from disposals chute in medical storage
del: removed locker that was preventing access to other lockers in evidence room.
del: removed pointless adapter near docking arm
del: removed a structural pylon from the bridge
del: removed duplicated …
> Endeavour post-launch fixes

- maps/endeavour/levels/deck4.dmm
Fixes the AI chamber turret controller, so you don't get shot on entering the room
Controllers should work!
:cl:
fix: Fixed the turret controller for the AI chamber access.
/:cl:
> Fixed the turret controller

- code/modules/mapping/map_helpers/access_helper/airlock.dm
- maps/endeavour/levels/deck1.dmm
- maps/endeavour/levels/deck2.dmm
- maps/endeavour/levels/deck3.dmm
- maps/endeavour/levels/deck4.dmm
A lot of small fixes
Because I should have caught them earlier
:cl:
add: Explo sci door helper
add: missing wires in Sec prep
add: door to Detective's office to front lobby
fix: needless doors in maints
fix: many bad doors and paths in maints, multiple decks
fix: lack of airlocks in hallways, added them to aid compartmentalization
fix: added more vents and scrubbers in areas where needed
fix: wonky disposals issue on deck two, fixed dorms disposals
fix: started beautifying the sec lobby. 
fix: added door switch to sec fighter hanger
/:cl:
> aaa fuck me, i'm not that good at this. Multiple fixes.

- citadel.dme
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Core.dm
- code/modules/reagents/reagent_containers/blood_pack.dm
- code/modules/reagents/reagent_containers/blood_pack_vr.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#6889
> Revert "Gives everyone to drink from blood bags(blood is still toxic to non-v…"

- code/modules/integrated_electronics/subtypes/manipulation.dm
Added a sanity check to only mine adjacent things.
Added the abillity to add better drills to the component to improve digging speed for turfs only.
> IC drill update

- tgui/public/tgui.html
new useragent new ui
(( doesnt include ie8 remove, only makes tgui load ))
> 516 tgui support

- maps/endeavour/levels/deck2.dmm
First pass at filling maints on Deck 2, adjusted medical
Gotta do this ship right
:cl:
add: Added new mechanics or gameplay changes
tweak: tweaked a few things in medical to add more maints access, near the paramedic bay
/:cl:
> Endeavour Deck 2 Maints update 1: First pass at filling maints on Deck 2, adjusted medical

- maps/endeavour/levels/deck1.dmm
Filling in Deck 1 maints
:cl:
/:cl:
> Maints update deck 1

- code/modules/species/shadekin/shadekin.dm
never was good lore
pretty sure it isn't lore anymore
even if it is it's still not good
out in the trash it goes
> removes shadekin death qdel

- code/controllers/subsystem/server_maint.dm
- code/game/world.dm
- code/modules/admin/admin.dm
- documents hub stuff
- removes auto hub management
- removes preinit hub disable
for whoever asks me why i just yank random code:
because i'm sick of debugging a near decade old byond bug and there's frankly zero need for us to never be _on_ the hub so here we go.
> maybe fixes the hub

- maps/endeavour/levels/deck4.dmm
Added things to maints on Deck 4, added a pod bay door system
Makes the back end of the ship feel less empty 
:cl:
add: Added more things to deck 4 maints, added pod-bay doors for big engineering work, etc. 
/:cl:
> Endeavour deck 4 maints update

- maps/endeavour/levels/deck3.dmm
More updates to Deck three maints.
:cl:
/:cl:
> Endeavour deck 3 maints update

- maps/endeavour/levels/deck1.dmm
fixing deck 1 stuff
:cl:
/:cl:
> Endeavour Deck 1 maints and wire fixes

- maps/endeavour/levels/deck2.dmm
Fixes a overly large maints area near research, and  a couple airless tiles near xenoflora
:cl:
fix: fixed a few things in deck 2 maints
/:cl:
> Fixes to areas, and a couple bad airless tiles

- maps/endeavour/levels/deck1.dmm
- maps/endeavour/levels/deck2.dmm
- maps/endeavour/levels/deck3.dmm
More map work.
Map development is good.
:cl:
del: Deleted a duplicated airlock in deck 3 maintenance
tweak: Cafe kitchen now starts with milk and coconut milk
tweak: Slight changes to detective's office
tweak: Changes to cafe design
tweak: Changes to deck 3 dorms design
tweak: Changed around some vending machines in deck 3
fix: fixed a non-functional door bolt button in dorm 12
fix: fixed several instances of overlapping wall-mounted objects
fix: runtime now spawns inside the CMO's office
/:cl:
> Further endeavour fixes and tweaks

- code/modules/reagents/chemistry/reactions/Drink-Recipes.dm
:cl:
code: fixed a misplaced backslash
/:cl:
> misplaced backslash fix

- maps/sectors/nebula_tradeport/levels/nebula_tradeport.dmm
Its a very simple PR that should fix the traveler spawns once and for all. I hope.
Its a fix to make sure they spawn on nebula and not on station. Somehow it desnt work well on endeavour.
> Outsider Spawn Update.

- code/datums/status_effects/basic/incapacitation.dm
- code/modules/mob/grab.dm
- code/modules/mob/living/carbon/resist.dm
- code/modules/mob/mobility.dm
- code/modules/mob/status_procs.dm
i'm in deep pain
maybe i should do what tg did which is make sources of mobility blocking traits
but that's a lot of effort and idk what to do with forced-mobility traits.
lol
fuckin sucks tbh
> fixes resist (crappily but it works)

- code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/enigma_hivebot.dm
Nerfs and buffs some ENIGMA Hivebots.
Trooper health decreased from 250 to 200. AI also changed to actually fire instead of charging.
Magnetic Trooper health decreased from 300 to 230.
Marksman trooper health decreased from 200 to 190. Attack cooldown doubled. (No more rapid fire x-ray snipers!!)
P4 mobs received increased health to make them more viable.
Wraith gets a better shield, you can't just kite it now since its shield regenerates 30 health every 5 seconds it's not in combat!
Balance is good, mobs shouldn't be worthless.
:cl:
tweak: hivebot health, speed, attackspeed and viability.
/:cl:
> Enigma Tweaks

- code/modules/vehicles/sealed/mecha/equipment/tools/sleeper.dm
Update the mech sleeper from HTML to NanoUI.
A few notable behavior changes are to mention in that it wont put people to sleep putting them inside, only when stasis is enabled. It can do everything a normal sleeper can plus have additional chem options when the syringe gun scanned new reagents.
> Mech sleeper update

- code/modules/species/station/xenomorph_hybrids/hybrid_resin.dm
:cl:
fix: fixed Xenohybrid nests being pitch black
/:cl:
> Fixes Xenohybrid nests being pitch black

- code/modules/mining/ore_redemption_machine/equipment_vendor.dm
Approved by Silicons, explained via title above.
Adjusts costs of mining points to thaler ratio by 20x. Might decrease it.
Balance and maintaining a believable economy. No more ludicrous amounts of thaler!
:cl:
/:cl:
> Adjusting Mining Points to Thaler ratio

- code/modules/integrated_electronics/subtypes/input.dm
- code/modules/integrated_electronics/subtypes/reagents.dm
Fixes two bugs I have missed in my last PR for the projectile simulator and slime scanner.
Also adds a new circuit component that is able to siphon water from sinks and store it inside.
> IC bug fix and new sink siphon

- code/modules/atmospherics/machinery/portable/canister.dm
whats on the tin
the game shouldnt gaslight players into thinking they were in more danger than they actually were
:cl:
fix: fixed canisters warning people about non existant danger
/:cl:
> ejecting a tank from a canister only warns your, if you would endanger yourself

- code/modules/atmospherics/machinery/portable/canister.dm
- code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
Properly fixes the icon of canisters not updating after removing a tank from it
> Fix cannister sprites after removing a tank

- code/modules/projectiles/guns/gun.dm
- code/modules/projectiles/guns/gun/projectile/ballistic-interaction.dm
- fix internal mag at 0 ammo left
- fixes phase guns wield state
> ballistics hotfix

- code/modules/food/recipes_microwave.dm
replaces the non-existent "pepper" reagent requirement with "blackpepper" 
Allows shrimp cocktails to be made
:cl:
fix: shrimp cocktail recipe
/:cl:
> Fixes shrimp cocktail recipe

- code/modules/species/protean/protean_blob.dm
evil coders broke this CRITICAL FEATURE when they made protean blobs no longer drop items
> readds blob ID

- code/modules/loadout/loadout_utility.dm
Add the one line to automatically equip the utility webbing
It's easier to preview any changes made to it
:cl:
tweak: the webbing in loadout spawns attached and is in the preview.
/:cl:
> Loadout webbing preview

- code/modules/mob/living/living-defense.dm
- config_static/jukebox.json
Swaps the song's title and fixes a string (maybe)
macintosh plus is a pseudonym for Vektroid afaik
It's just accurate I guess
Changes a string in jukebox.json
Changes electrocution text for when you place a wire
:cl:
tweak: song renamed
tweak: electrocution warning ajust
/:cl:
> Correct title for the Floral Shoppe Album Song

- code/modules/hardsuits/modules/computer.dm
- code/modules/mob/holder.dm
- code/modules/species/holosphere/actions.dm
It's a relativly simple change that allows a holosphere in sphere form to be used as the synthetic helping with the controls of it.
I think the system is almost never used, at most by proteans doing their own suit. It currently requires either a full station AI, which would be quite limited to be put in the suit, a brain, not sure if you could bring any person for that, or a pAI, which I think is currently the only realistic option, if rare enough. Allowing the spheres to integrate too means an active player can just quickly switch into it, and being talked to about it. This should help finding problems with it, and gives way for the species to interact with the hardsuits directly, as currently, they can't wear one.
:cl:
add: Holosphere's can now be integrated with a hardsuit through the …
> Allows holospheres to be used with the hardsuit IIS Module

- code/__HELPERS/do_after.dm
> fix do-after bar

- code/__HELPERS/do_after.dm
- code/datums/progressbar.dm
- code/modules/atmospherics/machinery/components/component.dm
- code/modules/tools/_tool_system.dm
> do after tweak

- code/__DEFINES/misc.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#6356
> Nobody likes people with long names >:(

- code/game/rendering/plane_masters/plane_render.dm
As it says on the tin, tell it to always be on the bottom left, worked both for 15x15 and widescreen.
Fixes what 516 broke
:cl:
fix: darksight
/:cl:
> Fixes darksight

- code/modules/mob/living/silicon/robot/drone/drone.dm
:cl:
fix: drones died when ghosting, this made cryoing impossible
/:cl:
> makes drones not die inside cryo

- code/modules/species/holosphere/holosphere.dm
title
stops things attacking the holosphere shell that should not
:cl:
fix: copy holosphere factions over to holosphere shell
/:cl:
> copy holosphere factions over to holosphere shell

- code/game/machinery/gear_painter.dm
changes the minimum luma threshold for recoloured items in the colormate
let people customise their items how they want
> colorgate fix

- maps/endeavour/engines/rust.dmm
- maps/endeavour/levels/deck1.dmm
- maps/endeavour/levels/deck2.dmm
- maps/endeavour/levels/deck4.dmm
Adds the new engines.
It fixes a hole, remasters the R-UST.
Does a lot of shit, check mapdiff
For example, ENGINE, and a breach in medical
:cl:
tweak: fixes venting issue in medical
tweak: tweaks the r-ust and surrounding area
/:cl:
> !!!OH SHIT!!! fix

- code/game/objects/items/melee/types/transforming/energy/ionic_rapier.dm
- code/game/objects/items/melee/types/transforming/energy/saber.dm
- code/modules/mob/inventory/inventory-hands-put.dm
- code/modules/organs/internal/augment/armmounted.dm
- code/modules/organs/internal/subtypes/augment.dm
They are internal organs, not external organs, but the augment menu was searching there. 
Allows something that is there to be actually used, may give robotics something more to do.
:cl:
fix: augment implants can actually be activated
/:cl:
> Allows implant augments to be used

- code/controllers/subsystem/garbage.dm
- code/datums/progressbar.dm
> add dump_harddel_info to progbar

- tgui/packages/tgui/interfaces/GeneralRecords.js
- tgui/packages/tgui/interfaces/MedicalRecords.js
:cl:
fix: medical and employment records are scrollable again
/:cl:
> make records scrollable again

- code/datums/components/items/wielding.dm
- code/game/content/factions/corporations/nanotrasen/guns/nt_protolaser.dm
- code/game/objects/items/offhand.dm
- code/modules/keybindings/keybind/item.dm
- code/modules/keybindings/keybind/mob.dm
- code/modules/mob/mob-keybind-triggers.dm
- adds a proper button and verb for classic mode users
- attempting to pick up an item with a wielded offhand automatically replaces it
> wield update

- citadel.dme
- code/__DEFINES/dcs/signals/signals_atom/signals_atom-throwing.dm
- code/__DEFINES/dcs/signals/signals_atom/signals_movable-update_icon.dm
- code/__DEFINES/dcs/signals/signals_item/signals_item-interaction.dm
- code/__DEFINES/dcs/signals/signals_mob/signals_mob-inventory.dm
- code/__DEFINES/dcs/signals/signals_mob/signals_mob_defense.dm
- code/__DEFINES/materials/misc.dm
- code/__HELPERS/animations/attack.dm
- code/__HELPERS/text/format.dm
- code/datums/components/_component.dm
- code/datums/components/items/wielding.dm
- code/datums/event_args/_event_args.dm
- code/datums/event_args/actor.dm
- code/datums/event_args/examine.dm
- code/datums/soundbytes/effects/combat.dm
- code/datums/status_effects/stacking.dm
removes dead code, fixes descriptions, adds examine event struct, and adds fmttext()
> minor changes from melee refactor branch

- citadel.dme
- code/game/atoms/_atom.dm
- code/game/atoms/atom-radiation.dm
makes the main atom file smaller
> move atom radiation code to its own file

- citadel.dme
- code/__DEFINES/combat/body_zones.dm
- code/__DEFINES/dcs/signals/README.md
- code/game/objects/items/weapons/paiwire.dm
- code/game/objects/structures/fireaxe.dm
- code/game/objects/structures/guillotine.dm
- code/game/objects/structures/morgue.dm
- code/game/objects/structures/tables/interactions.dm
- code/game/turfs/simulated/floor/floor_attackby.dm
- code/game/turfs/simulated/wall/wall-construction.dm
- code/game/turfs/simulated/wall/wall-damage.dm
- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/simple_mob/subtypes/lavaland/goliath.dm
- code/modules/mob/living/simple_mob/subtypes/occult/constructs/juggernaut.dm
> atomize melee pr a bit more

- code/modules/projectiles/guns/firemode.dm
fixes runtimes but it doesn't fix the issue
(the issue fix is to convert every legacy firemode)
> adds varname assertion to firemode sets

- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
- code/modules/reagents/chemistry/reagents/core/ethanol.dm
As title. I should atomize these I might be stupid. It's fine.
Ethylredoxrazine should be purging ethanol from blood, not just the stomach; that's the intent. Ethanol being scannable by e.g. circuits is also, in fact, the intent, or at least my intent.
:cl:
tweak: Ethanol can be scanned by lower tier scanners
fix: Ethylredoxrazine purges ethanol from blood properly
/:cl:
> Fixes ethylredoxrazine; makes ethanol scannable

- maps/endeavour/levels/deck1.dmm
- maps/endeavour/levels/deck2.dmm
- maps/endeavour/levels/deck3.dmm
- maps/endeavour/levels/deck4.dmm
Fixes access requirements on the Gateway room. Fixes the button placements so turrets can be shut off without running a kill box to hit the button. 
Less dead jannie pilots in Explo's gateroom 
Also, fixes up the fighter bay in Sec 
:cl:
tweak: Fixed gate room access and buttons. Added signage to same. 
tweak: Fixed PF suit cycler. Fixed fighter bay in Sec so it they can be accessed. 
/:cl:
> oh god oh fuck not another killroom incident

- tools/ci/download_byond.sh
> Adds a user agent to byond download request

- code/modules/preferences/preference_setup/helpers/species_pick.dm
:cl:
fix: xenohybrid whitelist
/:cl:
> species name check instead of UID check

- code/modules/integrated_electronics/core/printer.dm
- tgui/packages/tgui/interfaces/ICPrinter.js
> fixes circuit printers

- maps/endeavour/levels/deck1.dmm
- maps/endeavour/levels/deck2.dmm
- maps/endeavour/levels/deck3.dmm
- maps/endeavour/levels/deck4.dmm
- maps/endeavour/levels/flagship.dmm
Fixes all paint and catwalk helper errors on Endeavour.
Being able to load the map is good.
-Fixes duplicate catwalks and paint-helper CRASH errors.
:cl:
fix: fixed duplicate catwalks and redundant paint helpers.
/:cl:
> Fix Endeavour map errors

- code/datums/components/custom_transform.dm
title
fixes a bug
:cl:
fix: fixes holospheres getting their camera stuck when untransforming while held
/:cl:
> fixes holospheres getting their camera stuck when untransforming while held

- code/modules/loadout/loadout_mask.dm
> warming mask loadout

- maps/templates/admin/shipcave.dmm
> fixes maps

- code/game/machinery/computer/misc/bioscan.dm
- code/game/machinery/holopad.dm
- code/game/machinery/teleporter/console.dm
- code/modules/economy/machines/ATM.dm
- code/modules/nanites/chamber_control.dm
- code/modules/tgui/modules/general/cardmod.dm
Fixes the cardinal sin of not calling ..() and returning if true
:cl:
fix: Ghosts can no longer screw with TGUI panels they shouldn't be able to.
/:cl:
> Patches remaining TGUI ghost interactions

- code/game/objects/structures/palletjack.dm
Pallet jacks u
also MIT license good
:cl: Bhijn and Myr
tweak: Pallet jacks are now capable of coming in random colors!
/:cl:
> Further Pallet Jack Tweaks (MIT licensing because i mcfuckin Forgot, and also random-colored pallet jacks)

- code/game/machinery/computer/computer.dm
proabbly has some unintended effects but whatever
> computers no longer block clicks

- code/controllers/toml_config/toml_configuration.dm
> Fixes another CI issue

- citadel.dme
- code/modules/clothing/chameleon.dm
- code/modules/mob/holder.dm
- code/modules/species/protean/blob_recolor.dm
- code/modules/species/protean/protean_blob.dm
tint color? It Just Won't Do (Club Mix)
broken icons? they also Just Won't Do (Club Mix)
🆑
tweak: protean blobs can now into matrix color for themself
fix: all mob holder icons
/:cl:
> gives protean blobs matrix recolor for themselves + fixes holder onmobs

- maps/strelka/levels/strelka_deck1.dmm
- maps/strelka/levels/strelka_deck2.dmm
- maps/strelka/levels/strelka_deck3.dmm
- maps/strelka/levels/strelka_deck4.dmm
- maps/strelka/strelka-papers.dm
Fixes : Security, lights, Docking of the decade.
Fixes reported earlier after the test
No engine fixes yet, I may need help on this part.
We love the fixes
> Strelka fix

- code/modules/ghostroles/roles/sdf.dm
- maps/sectors/miaphus/levels/miaphus_beach.dmm
On the SDF vessel : A Airlock was over a Wall. Classic StrongDMM moment. 
Also fixed the dock and the number of people spawning.
Map fix
> SDF : StrongDmm Trolled me.

- maps/endeavour/levels/deck1.dmm
- maps/endeavour/levels/deck3.dmm
- maps/endeavour/levels/deck4.dmm
this is on me for not staring at PRs harder but also i hope we learned a lesson in merge commits
> fixes erroneous revert of endeavour files

- maps/sectors/sky_planet/levels/sky_planet_sky_west.dmm
Fix the stairs at the skyplanet town, and add extra loot in the lab.
Bug fix :D
> stair fix at the sky planet town

- code/modules/mob/living/silicon/robot/robot.dm
Makes the janiquad floorscrubber work again, besides making robot move a bit more efficient
Less copy-pasted code, while fixing a functionality
:cl:
fix: janiquad floor scrubber
/:cl:
> Scrubbing fix

- code/modules/mob/living/carbon/human/human.dm
Title. The previous code was a pretty clear [loop-switch](https://en.wikipedia.org/wiki/Loop-switch_sequence), since every single part of the loop was an explicit condition. This is difficult to read and slower than just having it unrolled, so, unrolled it.
It probably won't affect the game at all, but better code is good.
:cl:
code: Made flavor text loop-switch into a series of if statements instead
/:cl:
> Replaces loop-switch antipattern with something which is easier to read

- code/modules/species/station/standard/moth.dm
fix being unable to select moth as a species
fixes a bug
:cl:
fix: fix being unable to select moth as a species
/:cl:
> fix being unable to select dnin-nepid (moths) as a species

- code/modules/mob/living/carbon/human/traits/neutral.dm
:cl:
del: Removed the not working autohiss traits (character setting stays, just the traits)
/:cl:
> remove autohiss traits

- code/modules/vehicles/sealed/mecha/mecha_control_console.dm
- code/modules/vehicles/sealed/mecha/vehicle_tracking_beacon.dm
> fixes mech control consoles lagging the server
