Citadel-Station-13/Citadel-Station-13-RP

- code/_onclick/cyborg.dm
:cl:
fix: Fixes borg alt-click to show objects on a turf
/:cl:
> Fixes borg alt-click to show turf objects

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/human.dm
:cl:
fix: You'll no longer be "a a gynoid" / "an a android"
refactor: Species examine text is de-duplicated.
/:cl:
> Minor Refactor to human examine/tooltip

- code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
:cl:
tweak: tweaked derlict drone fab dont show on the list until cleared by a player
code: adds a var to drone fabricators to signal them to not show up on the drone list until cleared
/:cl:
> prevents derlict drone fabricators from showing on the join as drone list, until secured

- code/modules/organs/external/_external_icons.dm
:cl:
code: removes an old debug log entry I forgot about....
/:cl:
> removes an old Debug log entry I forgot

- .github/workflows/ci_suite.yml
Github deprecated Node12 for workflows, which DreamAnnotate V1 uses. DreamAnnotate V2 uses Node16 instead. This PR isn't urgent, but shouldn't affect much in theory.
> Updates DreamAnnotate to v2

- code/modules/organs/internal/species/alraune.dm
- code/modules/organs/internal/species/diona.dm
- code/modules/species/station/alraune.dm
- code/modules/species/station/apidaen.dm
Noticed a metric ton of runtimes of null.nutrition from a apidean, found out all our snowflake organs had a unneccessary var for holding the organ's owner, even though we have owner.
:cl:
fix: Alarune and apidaen "cannot read null.nutrition" runtimes.
/:cl:
> Who made organ_owner, we have owner for a reason.

- code/modules/events/spacevine.dm
1. **Increases Vine Announce Time From 1 Min to 2 Min.**
1. _Vines often get caught before they can really spread far enough. This adds one minute to the announce timer to give the vines a better chance. May drop if necessary._
:cl:
tweak: Adds 1min to vine announce timer.
/:cl:
> Doubles Announce Time for Vines

- code/modules/jobs/job_types/station/command/command_secretary.dm
- code/modules/jobs/job_types/station/service/janitor.dm
Alternative titles have a system where they spawn the player with alternate outfits, this is seemingly sparingly selected.
Yes, used would have been a better word, I like alliteration.
Anyway, this uses that system for the Bridge Officer (it'll even select pants or skirt depending on gender) and Maid (I went with the middle ground between sexy maid and janimaid. Mainly because Janimaid is an underused sprite on maid characters.)
Spawning with alternate costumes on alternate titles adds flavour.
:cl:
add: Gave Maid and Bridge Officer spawn outfits.
/:cl:
> Gave Maid and Bridge Officer spawn outfits.

- code/modules/organs/external/species/shadekin.dm
- code/modules/species/shadekin/shadekin_blackeyed.dm
Turns out that while Black-Eyed Shadekin didn't have the Brittle Bones or Hollow Bones trait, they had it hardcoded that all their limbs had between 42% and 57% of the minimum damage needed to break bones.
Giving Black-Eyed Shadekin hollow bones was deemed silly and will now be changed. The values have been replaced to be between 85% and 90% of the original values.
In addition, the Brute_Mod of Black-Eyed Shadekin has been reduced from 1.25 to 1, since having both lower HP and higher damage mod is a lot of pain. The Burn_Mod was intentionally kept.
Crewkin are a powerful species and I am all for nerfing powerful people. But this was more along the lines of CBT.
:cl:
balance: Lowered Crewkin Brute_Mod
balance: Raised Crewkin minimum limb damage to break bones
/:cl:
> Removes Black-Eyed Shadekin hollow bones

- code/modules/jobs/job_types/station/security/warden.dm
Fun Fact: Warden is the one carbon job that has zero alternate titles.
Now they all have them.
The titles are; Brig Governor, Jailor and Dispatch Officer.
Consistency and flavour.
:cl:
add: Adds some Warden alt titles. Brig Governor, Jailor and Dispatch Officer
/:cl:
> Adds some Warden alt titles.

- _maps/map_files/rift/rift-01-underground3.dmm
- _maps/map_files/rift/rift-02-underground2.dmm
- _maps/map_files/rift/rift-03-underground1.dmm
- _maps/map_files/rift/rift-04-surface1.dmm
- _maps/map_files/rift/rift-05-surface2.dmm
- _maps/map_files/rift/rift-06-surface3.dmm
- _maps/map_files/rift/rift-10-west_plains.dmm
Adds phoron glass around the SME core, makes some edits to various parts of the map. Adds a hip holster and an armpit holster to parts of the map. Adds a deep maint bar hidden in the ice, far more ruined than than the current maint bar.
Because some people like to have another maint bar for use when the original one is taken up by someone's scene. Also because holsters are no big deal, they do not start with guns and you can put stuff like stamps in them. And some people were complaining about venting hot air into the cold air in engineering when accessing the rad collectors late into the round, this should fix that.
:cl:
add: Deep maint bar
tweak: Map tweaks, engineering tweaks, ladder fixes.
/:cl:
> Bunch of misc map changes, new deep maint bar

- code/modules/projectiles/guns/energy/laser.dm
Changes it so the Cargo/Security DMR can have the cell changed for reloads, while keeping it so the Exploration DMR can not remove the cell.
I understand that not allowing the DMR to reload was a balancing choice. However, this was deemed negligable and we are going to make it reloadable and see what happens.
:cl:
balance: Made DMR Rifle cell be detachable.
/:cl:
> Enables DMR reloading

- code/modules/species/shadekin/shadekin_blackeyed.dm
Reduces the normal slowdown for Black-Eyed Shadekin to 0, bringing them to human level, and in turn increasing their item slowdown.
I failed to see why they were given that slowdown in the first place.
:cl:
balance: Lowered Black-Eyed Shadekin slowdown by 0.5, increased item slowdown by 0.5
/:cl:
> Change Crewkin Slowdown

- _maps/templates/shelters/shelter_2.dmm
- _maps/templates/shelters/shelter_a.dmm
The Luxury Shelter Capsule has some very nise interior, including a cornerpiece glass. This blocks movement though and to use the pod, one has to destroy the glass.
This PR removes this cornerpiece glass and shifts the rest of the glass a bit to create a smooth corner again.
It's nice to not get blocked as you walk.
:cl:
del: Removed a cornerpiece glass which blocked movement.
/:cl:
> Luxury shelter pod glass fix

- _maps/map_files/rift/rift-02-underground2.dmm
- _maps/map_files/rift/rift-08-west_deep.dmm
- _maps/map_files/rift/rift-09-west_caves.dmm
Surt miners get a Mining Softsuit, Mining Voidsuits were moved to the Belt station.
Added Proto-Kinetic Accelerators to the Belt station.
Added 2nd Binoculars to the Belt station.
Some may call it a change of pace, some may call it balancing by removing the 50 armor voidsuit and bringing it to where people would actually need it.
:cl:
add: 2nd Binocular added to the Belter station
add: Added Proto-Kinetic Accelerators to the Belter station
tweak: Moved Mining Voidsuits to the Belter station
/:cl:
> Mining base changes

- code/__HELPERS/icons.dm
Proc: icon_exists
Checks if the given iconstate exists in the given file, caching the result. Setting scream to TRUE will print a stack trace ONCE.
:cl: Zandario, Kapu1178
code: Added a new proc: **icon_exists** - It checks if a given icon_state exist and can scream bloody murder if it doesn't.
/:cl:
> icon_exists

- code/modules/species/station/standard/unathi.dm
Unathi are now "properly" cold-blooded and do not regulate their body temperature anymore. (Lorally they are mesothermic but that's not a thing in the cold so cold-blooded is the next best thing)
Mechanically this will probably not impact you that much. On the station, the little temperature gauge on the right will be blue to signify that your character is colder than they'd like to be (20c is chilly for the lizarbs), but with no actual effects. But if you step into a cold/hot place, you cannot regulate your temperature so your body will acclimate to the temperature of wherever you stepped into. If this is the outdoors without a suit, you're in for a bad time.
Some internal testing has shown me that with a suit, you are insulated and will not incur any harm. **But if you become freezing, …
> Unathi temperature comfort is now proper

- code/game/objects/items/stacks/stack.dm
This PR fixes sheet stacks overflowing and deleting. Instead they will now simply drop the excess amounts on your feet.
https://user-images.githubusercontent.com/77420409/199358007-a4b391a4-6e07-4250-b5e4-3a47f8c8687e.mp4
Less bugs. 
:cl:
fix: fixed sheet stacks deleting over capacity
/:cl:
> fix sheet stacks

- code/game/machinery/computer/medical.dm
- code/game/machinery/computer/security.dm
- tgui/packages/tgui/interfaces/GeneralRecords.js
- tgui/packages/tgui/interfaces/MedicalRecords.js
- tgui/packages/tgui/interfaces/SecurityRecords.js
Security and medical records are now in their own "section" of the records console. They can no longer be edited and will now display line breaks, similar to employment records.
Wall of text trying to read through someone's medical record is no bueno.
:cl:
tweak: Security and medical records now display in their own section of the records console, display line breaks, and can no longer be edited mid-round.
spellcheck: Fixed capitalization for employment records.
/:cl:
> Fixes user-supplied sec/med records

- _maps/map_files/rift/rift-02-underground2.dmm
- _maps/map_files/rift/rift-04-surface1.dmm
- _maps/map_files/rift/rift-05-surface2.dmm
- _maps/map_files/rift/rift-06-surface3.dmm
Adds denied stamps to all head of staff offices (it's silly to have their head stamp but not a denied one) and pixel shifted them to look nicer.
Also added a paperwork bin to the warden's office, since he literally has paperwork equipment. It replaces the useless retail scanner that he has.
StrongDMM appears to like touching unrelated things. It shouldn't break anything.
Simple qol features for paperwork.
:cl:
add: Added denied rubber stamps to all head of staff offices.
add: Added a paper bin to the warden's office, replacing the retail scanner.
/:cl:
> Touch-up on head of staff offices

- code/game/objects/structures/fence.dm
1. **Fixes Wooden Gate Icon.**
1. _The wooden gate was taking the wrong proc's icon states, leading to wooden gates turning into brown metal fences._
:cl:
fix: Fixes wooden gates.
/:cl:
> Fixes Wooden Gate Icon

- code/modules/clothing/head/hood.dm
- code/modules/clothing/suits/hooded.dm
After complaints from some miners, Blue told me to give the Mining Softsuit the same armor as the Voidsuit had.
In addition, I added some commonly used mining tools to the list of items the Mining Softsuit can carry in its suit storage.
It's really nice for the Mining Suit to be able to carry some Mining tools on its suit slot!
Regarding the armor changes, I'm sure those who complained have their reason, and we hope those complaints get addressed with these changes.
:cl:
tweak: Expanded the Mining Softsuit storage list for some mining tools
balance: Gave the Mining Softsuit the protection the Mining Voidsuit had
/:cl:
> Mining Softsuit Armor and Suit Slot

- code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
- code/modules/preferences/preference_setup/loadout/loadout_role_restricted.dm
1. *Removes Holster Selection from Loadout.*
2. *Adds a Holster to the Pathfinder's locker.*
1. _I have general issues with the existence of this listing to begin with. However, there is a bug in the nature of Selection that causes the machete scabbard to select its longest path, which in this case is a pre-loaded Durasteel machete. This fault, paired with my general dislike of this item being made available in the loadout, has led to this outcome._
2. _Consequently, I have given the Pathfinder a spare holster in their locker, as this was apparently the most frequent use of this loadout option. This is how we should address holster shortcomings - not by giving them out to anyone in a role restricted slot. I will accept further requests to put holsters in lockers within reason._
:cl:
add: …
> Removes Holster Selection from Loadout

- .github/workflows/conflicts.yml
Just tgstation/tgstation/pull/59252
To steal their description
> Fetching mergable is async because idk github and bigger repos take longer to do it so this should fix timeout issues somewhat
We don't have that issue but idk
> Change the merge conflict timeout time

- code/game/machinery/doors/brigdoors.dm
brig timers no longer respect lag basically
why: I was reminded by the corpregs page that lag is a thing
It really shouldn't be a thing for the youtube mechanic.
> makes brig timers use REALTIMEOFDAY 

- code/modules/tgui/external.dm
everyone can now reload;
debug reloading is now logged.
> changes tgui reloading behavior

- code/game/objects/items/weapons/grenades/concussion.dm
Removes the spin procs off concussion grenades
It messes with your settings and doesnt undo its changes forcing you to fiddle about with character verbs to fix. Also spin procs dont work right now properly
:cl:
code: Removed Spin procs from concussion grenades
/:cl:
> Removal of spin procs off concussion grenades

- code/modules/paperwork/paper/paper.dm
- code/modules/paperwork/paper/tag.dm
- code/modules/preferences/preference_setup/background/species.dm
adds paired tags
we'll have language tags after, gamers ;)
:cl:
add: paper tags now auto-close. no more [b]ombing papers with mismatched tags.
refactor: paired paper tags; might be a bit expensive to parse, should rustg it later
/:cl:
> paper tags v2

- code/game/turfs/simulated/flooring/_flooring.dm
ok i'm not even going to go into how decal painters need to be more available + get a QOL update + how decals are shit on the codebase, but:
why it's good for the codebase;
in theory, you only want floors paintable, because you know, why would you paint wood-
oh wait, the mappers put decals. on wood.
and now you have to remove it as a player.
oof.
yeah, at this point, might as well allow by default. you can remove it from flooring when needed.
:cl:
add: most flooring can be painted now
/:cl:
> defaults flooring can paint to true

- code/modules/xenoarcheaology/finds/special.dm
:cl:
fix: /obj/item/vampiric uses an action icon.
/:cl:
> Fixes /obj/item/vampiric

- code/modules/mob/living/carbon/alien/say.dm
- code/modules/mob/living/carbon/brain/say.dm
- code/modules/mob/living/say.dm
- code/modules/mob/say.dm
Reworks the unknown language popup (which appears if you put in a prefix that doesn't match a language that you know) to clarify what has gone wrong and what your options are. Also adds an option to say nothing in case you made a typo. (This is pretty hacky in the code, but it should work?).
Being forced to say something in the wrong language is bad.
:cl:
tweak: Reworked the alert that pops up if you try speaking a language you don't know, and added an option to say nothing at all in case you made a typo.
/:cl:
> Reworks the unknown language popup

- _maps/map_files/rift/rift-05-surface2.dmm
Self-explanatory.
The HOS shouldn't need to steal one from the security EVA prep.
:cl:
add: Added an oxygen tank to the head of security's voidsuit rack.
/:cl:
> Adds oxygen tank to hos suit rack

- code/modules/mob/living/carbon/human/emote.dm
Adds a cooldown to *flip. You can still _try_ to flip during the cooldown, but you just might land on your face.
This also adds the emote chat message back, which was originally removed because of a lack of goon chat message stacking.
This fixes *flip giving you an "Unusable emote" message despite just having been used.
Less LRP emote spamming. Hopefully.
:cl:
add: flip cooldown
/:cl:
> Adds a cooldown to *flip

- code/modules/language/animal.dm
- code/modules/language/antagonist/xenomorph.dm
- code/modules/language/core.dm
- code/modules/language/galactic.dm
- code/modules/language/language.dm
- code/modules/language/monkey.dm
- code/modules/language/species/adherent.dm
- code/modules/language/species/akula.dm
- code/modules/language/species/alraune.dm
- code/modules/language/species/altevian.dm
- code/modules/language/species/birdsong.dm
- code/modules/language/species/celestial.dm
- code/modules/language/species/diona.dm
- code/modules/language/species/human.dm
- code/modules/language/species/moth.dm
- code/modules/language/species/naramadi.dm
- code/modules/language/species/phoronoid.dm
- code/modules/language/species/skrell.dm
- code/modules/language/species/tajaran.dm
- code/modules/language/species/teshari.dm
- code/modules/language/species/unathi.dm
- code/modules/language/species/vasilissan.dm
- code/modules/language/species/vox.dm
- code/modules/language/species/vulpkanin.dm
- code/modules/language/species/zaddat.dm
- code/modules/language/species/zorren.dm
- code/modules/mob/hear_say.dm
- code/modules/preferences/preference_setup/global/setting_datums.dm
Adds a language indicator preference. If you have it enabled and you know the language being spoken, a shorthand name of the language will pop up in the chat to let you know what language the person is speaking in. **This PR is based on https://github.com/Baystation12/Baystation12/pull/20721**.
Hivemind languages do not have these as their names are automatically given with each message. Likewise, machines that transmit without any language (such as station announcements or the ATC) do not have any indicator.
An example of a few languages:
It has been suggested in the past and can be helpful for people who don't know the languages by their colors.
:cl:
add: Added a new preference: Language Indicators. If enabled, a shorthand name of a language will be added whenever someone speaks that …
> [DNM] Adds language indicator preference

- code/controllers/subsystem/nightshift.dm
- code/game/machinery/computer/communications.dm
The nightshift subsystem now works -- it will automatically turn on nightshift lighting at 7:30 PM and beyond, and turn it off at 7:30 AM and beyond.
In addition, added a new option to the Command and Communications console to manually change the nightshift setting. You can override it to be on or off at all times, or switch it back to automatic mode.
Example video is too large for here, look in development-rp for "Nightshift example:" for an example of it.
Nightshift is a cool mechanic, but was broken before. This fixes it and also adds a way for command to manually change it station-wide instead of having to do it APC by APC.
:cl:
fix: Fixed the nightshift subsystem; it will now automatically turn on at 19:30 (7:30 PM) and off at 7:30 AM.
add: Added an option in the Command and …
> Fix nightshift, add option to c&c console

- _maps/map_files/rift/rift-01-underground3.dmm
- _maps/map_files/rift/rift-02-underground2.dmm
- _maps/map_files/rift/rift-08-west_deep.dmm
- _maps/map_files/rift/rift-09-west_caves.dmm
- _maps/map_files/rift/rift-10-west_plains.dmm
- _maps/map_levels/192x192/lavaland.dmm
Adds in Decontamination showers at the science outpost, engineering, lower part of the station's mining elevator, and lava land mining base. Adds in ore processing on mining outpost. Adds in cameras to mining outpost and lava land mining base.
Prep for radiation rework (showers and washing machines for decontaminations). Ore processing as per Silicon's request. Mining network cameras because outpost should have cameras.
:cl:
add: Cameras to outpost, showers in various places, ore processing on mining outpost
/:cl:
> Maintainer Request Bundle - Decontamination showers, ore processing for mining outpost, and more

- _maps/map_files/rift/rift-02-underground2.dmm
Adds a couple folders to the table in the monitoring room, and a photocopier and shredder in the break room.
Having only one measly paper bin for paperwork is a little pathetic.
:cl:
add: Added some folders and paperwork equipment to the engineering department.
/:cl:
> Add paperwork stuff to engineering

- _maps/map_files/rift/rift-05-surface2.dmm
Adds a noticeboard to a bare wall in the security hallway. 
A conspicuous place to put stuff like warrants or other paperwork.
:cl:
add: Added a noticeboard to the security hallway just outside the warden's office.
/:cl:
> Add noticeboard to security

- _maps/map_files/rift/rift-06-surface3.dmm
Adds an APC to the third deck main hallway, which was missing one for some reason.
It's not good for a common area to be without an APC. Plus, on nightshift mode that part of the station stays lit normally, which is bad.
:cl:
add: Added an APC to the Third Deck Central Primary Hallway.
/:cl:
> Adds an APC to third deck hallway

- code/modules/mob/living/carbon/carbon.dm
If someone is intentionally lying down (i.e. resting), shaking them up will no longer force them to stand up.
Sometimes people don't want to be standing. Whether that's to be difficult to security when being arrested, or they want to lie down on the couch, etc.etc. Just like in real life, you can't really force someone to stand up without carrying them.
:cl:
tweak: You can no longer shake someone up on their feet if they are resting.
/:cl:
> You can no longer shake someone up from resting

- code/modules/mob/living/carbon/human/traits/positive.dm
getting +1.67 tiles/second movespeed should not be a trait at all
the rest of the traits will be dealt with as we roll out the new characteristics & modifications system over the next month or two.
in return, haste will have its point value dropped and also made mutually exclusive to hardy.
> nerfs haste

- code/modules/sprite_accessories/hair/_hair.dm
Reenables two hairstyles.
Sabitsuki
Pixie 
Variety.
:cl:
add: sabitsuki & pixie hairstyle
/:cl:
> Reenables hairstyles

- citadel.dme
how did no one notice this wasn't compiled in
:cl:
fix: christmas is un-cancelled
/:cl:
> adds christmas to holidays

- code/modules/materials/materials.dm
"we need it to be able to hit people"
ok then
- fix item attack code instead of add spikes to foam
non-lethal nerf wars
:cl:
tweak: foam weapons no longer do damage
/:cl:
> foam is no longer hard or weighty (basically, foam weapons are now actually nonlethal)

- citadel.dme
- code/__HELPERS/icons.dm
- code/__HELPERS/icons/download.dm
- code/modules/admin/verbs/debug.dm
This will probably never be needed BUT I actually have a use for it on local for uh, reasons
thus I'm making it like, official, rather than juts a // haha todo deprecated soon.
> better icon download system

- code/___compile_options.dm
- code/modules/multiz/zmimic/mimic_movable.dm
`AO_USE_LIGHTING_OPACITY` is incomplete and buggy, it shouldn't be enabled. Also includes a runtime fix that was supposed to be in the main PR.
> Z-Mimic: Fix runtime w/ upward movement + AO fix

- code/game/objects/items/weapons/traps.dm
- code/modules/nano/interaction/default.dm
never in my life did i think someone would genuinely try to make an item be buckle-able 
we really either need to kill this dumb design pattern (items being used as structures)
or have better generic handling for items (this is what will happen on atom damage/attack hand refactor)
because this is fucking stupid
:cl:
fix: beartraps can be removed again
/:cl:
> fixes beartraps not allowing unbuckle & nanoui runtime spam

- code/modules/busy_space/organizations.dm
It should work.
Replaces the Altevian Hegemony with Naramadi Ascendancy for now, as more Moghes Hegemony vessels are being written still
Altevians aren't canon and it's pissing me off that the game keeps referencing them
:cl:
add: Naramadi Ascendancy ship chatter
del: Mentions of the Altevian Hegemony
/:cl:
> Altevians are not canon, why didn't anybody replace them?

- code/modules/maps/weather/rift_lythios-43c.dm
These useful event weather types can be tools EMs like myself can use in the future.
:cl:
add: Fallout and Blood Moon type weathers for Lythios
/:cl:
> Lythios Event Weathers

- code/game/verbs/character_directory.dm
Somehow during the reorg some of the necessary bits that make species display properly in the chardir got eaten. This PR restores the necessary .dm-side code to make it work again.
Fixes a silly bug so there's no longer a useless blank column in the directory. Tested and works.
:cl:
fix: fixed species not displaying in character directory
/:cl:
> Fix species display in character directory

- code/controllers/subsystem/zmimic.dm
- code/game/atoms/atoms_movable.dm
This fixes issues with things like mimics of sparks not being cleaned up.
> Z-Mimic: Add missing deletion hook

- code/controllers/subsystem/overlays.dm
- Fixes an issue where SSoverlays was corrupting humantype layer slots.
- Fixes an issue where SSoverlays was corrupting managed overlays.
- Fixes an issue where `copy_overlays()` runtimed if called on an atom without overlays.
> Overlays fixes

- code/modules/mob/living/default_language.dm
tl;dr it makes no sense to set null| as it's a verb
> removes as null|anything from set default lang

- code/modules/admin/admin.dm
The admin verb `Start Now` will now start the round as soon as possible, if used during server init.
(Setting start_immediately to true sets the pregame timer to 0, which kicks the MC and all that jazz into action.)
Devs don't have to wait for the server to init before using the `Start Now` verb.
:cl:
admin: The "Start Server" verb can now be used while the server is setting up to have the round start ASAP.
/:cl:
> Start Now verb queues during server init

- code/game/landmarks/spawnpoint/station/jobs.dm
- code/modules/mob/transform_procs.dm
AIs currently spawn at the arrival spawnpoints. The reason why is because in order to make a player into an AI, the server calls `AIize()`.
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/blob/856c98845adcdee05b876b3b1ddf866a7fdd7621/code/modules/mob/transform_procs.dm#L84
...which finds valid AI spawnpoints with get_latejoin_spawnpoint.
This PR sets the AI spawnpoint to `latejoin = TRUE`, so that it can be found as a valid spawnpoint. I considered checking whether the game was in the lobby state or in-game, to determine which proc to use, _but_ the game state is set to in-game before characters are spawned in.
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/blob/856c98845adcdee05b876b3b1ddf866a7fdd7621/code/controllers/subsystem/ticker.dm#L278-L279
The spawnpoint …
> AI will now properly spawn in core at roundstart

- code/__DEFINES/machinery.dm
- code/modules/clothing/spacesuits/void/station.dm
- maps/rift/rift_defines.dm
1. **Helmet Cams have been added to Exploration Voidsuit Helmets.**
1. _They've been requested for a while, and apparently they weren't enabled like I thought they were! It makes IC sense for these suits to have cameras mounted on them._
:cl:
add: Adds helmet cams to Explo void helmets.
/:cl:
> Enables Helmet Cams on Exploration Voidsuit Helmets

- code/game/turfs/simulated/wall.dm
- code/game/turfs/simulated/wall_attacks.dm
- code/game/turfs/simulated/wall_icon.dm
Now using images instead of mutable_appearance's.
Wall Damage overlays now works properly, and the cached list is now global.
Also fixes directional reinforcement overlays as they were using the base icon by mistake.
> Tweaks Wall Rendering & Fixes Damage Overlays

- html/statbrowser.html
The bars behind the statpanel text (on buttons) no longer eat the borders of the button, and are now coloured the same as the button (until hovered over).
Also fixes the ellipses wrap not working. (via `calc(98%)`) 
Less visual noise! I think!
:cl:
fix: Statpanel buttons no longer have a coloured bar under the text, unless you hover over the text.
/:cl:
> Statpanel buttons fix

- code/__DEFINES/rendering/zmimic.dm
- code/controllers/subsystem/overlays.dm
- code/controllers/subsystem/zmimic.dm
- code/game/machinery/lightswitch.dm
- code/modules/mining/mine_items.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/multiz/zmimic/mimic_movable.dm
- code/modules/multiz/zmimic/mimic_turf.dm
This is somewhat experimental, but it should mostly eliminate the need to manually set the plane mangling flag on movables.
Also renames the movable level `mz_flags` to `zmm_flags` to fix VV.
~~WIP: I really don't like how many `istype(src, ...)` this code contains.~~
> Z-Mimic: Automatic Plane Mangling

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/human.dm
Ports a couple of bits of code that allow those wearing AR-B glasses (or otherwise somehow having the Command-tier HUD) to easily view the employment records of anyone they examine, similar to how you can easily view medical and security records. It outputs the character's name, assignment (and true assignment if they've been given a funny title), home system, citizenship, primary employer, religious beliefs, and any employment records the player may have provided as part of their character details.
There is a slight catch in that the changes made to records here mean I'm not sure how to hook up home system, citizenship, employer, and beliefs. I'm hoping someone can help me figure that one out. The PR is otherwise locally tested and should be ready to merge.
If possible I'd also like to …
> (WIP) AR-B Employment Records

- _maps/map_files/rift/rift-03-underground1.dmm
Tin
The infestation events are reliant on areas to set where creatures spawn, and the hallway before Atmos was incorrectly mapped with a public hallway area, making spiders spawn in the wrong area. This fixes that.
> Changes area designation in Atmos hallway

- citadel.dme
- code/game/objects/items/trash.dm
- code/global.dm
- code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
- code/modules/mob/living/silicon/robot/emote.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/silicon/robot/robot_modules/_robot_modules_defs.dm
- code/modules/mob/living/silicon/robot/robot_modules/event.dm
- code/modules/mob/living/silicon/robot/robot_modules/event_vr.dm
- code/modules/mob/living/silicon/robot/robot_modules/station.dm
- code/modules/mob/living/silicon/robot/robot_modules/station/cargo.dm
- code/modules/mob/living/silicon/robot/robot_modules/station/drone.dm
- code/modules/mob/living/silicon/robot/robot_modules/station/engineering.dm
- code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm
- code/modules/mob/living/silicon/robot/robot_modules/station/misc.dm
- code/modules/mob/living/silicon/robot/robot_modules/station/science.dm
- code/modules/mob/living/silicon/robot/robot_modules/station/security.dm
- code/modules/mob/living/silicon/robot/robot_modules/station/service.dm
- code/modules/mob/living/silicon/robot/robot_modules/swarm.dm
- code/modules/mob/living/silicon/robot/robot_modules/syndicate.dm
- code/modules/mob/living/silicon/robot/robot_movement.dm
- code/modules/mob/living/silicon/robot/subtypes/lost_drone_vr.dm
- code/modules/nano/interaction/default.dm
This is more of a reshuffling of borg init than a refactor of it, but at least modifying modules should be less painful now.
Other changes:
- Fixed a runtime that could occur when a cyborg used certain non-TGUI consoles.
- Dogborg rest no longer has visual lag.
- Borg movement delay now actually works.
- Some borg actions now have `target` set for do_after progbars.
:cl:
tweak: Targeted borg emotes now only require a partial case-insensitive match, i.e. `*bark-gla` to bark at a `Glass Airlock`. This only applies to borgs using emotes.
add: Dogborgs can now bark at objects.
fix: Module resets should no longer render dogborgs invisible.
fix: Module resets should no longer temporarily break borg inventories.
fix: Some borg emotes that were supposed to have sounds now actually play said …
> Cyborg init refactor + other tweaks/fixes

- code/modules/cargo/supplypacks/security.dm
Turns out a couple gun packs were spawning in unsecured crates
Do I really need to answer this?
> Fixes gun packs spawning with incorrect crate type

- code/modules/admin/admin.dm
Calling the Spawn verb without giving any argument will now warn you that it'll lock up your game for a while.
Won't lock you up for a longass time as it generates a list of EVERY ATOM.
:cl:
admin: If the Spawn verb isn't passed an argument, it will now warn you it'll lock up the game for a while, and give you a chance to cancel.
/:cl:
> Spawn will no longer lock up

- code/modules/mob/living/silicon/robot/examine.dm
Stops the examine text for cyborgs from getting duplicated.
Heehoo shorter and clearer examine profiles.
:cl:
fix: Cyborg examine texts will now only show up once.
/:cl:
> Fixes borg descriptions being duplicated

- code/game/objects/items/storage/_storage.dm
Using a storage object in hand will open/close the inventory, **_IF_** it's not a quick-empty bag, like the hydroponics' plant bag.
QOL~ Don't have to click-drag/alt-click a storage object to yourself if it's in your hands, just to open it.
:cl:
qol: Using most storage items in-hand (ie: bags, boxes) will now open/close the inventory.
/:cl:
> Storage Opening QOL

- code/game/response_team.dm
Due to an error 3+ years ago, ERT could not be called by admins until the round had ended. That's no good.
heehoo oopsie
:cl:
fix: Admins can now call ERT before the round has ended. Oh boy.
/:cl:
> ERT can now be called before roundend

- code/modules/surgery/external_repair.dm
corpsemend surgeries are down to 2 seconds instead of 9-12
if you are on a table being corpsemended instead of being normally medicated (which has far less complications, mind you), it should not take them 15 minutes to fix your 1500 points of brute/burn
i understand being able to fix people that fast on a table is honestly stupid
but our med system is currently buggy as hell and people are dying and coming back with uncapped damage amounts
eventually we want corpsemend to be a "repeatable" surgery so you can do other stuff like talk while doing it instead of continue to click a button but for now i feel this is a viable change.
:cl:
balance: *temporarily* makes corpsemend surgeries take 2 seconds instead of 9-12.
/:cl:
> buffs the everloving heck out of corpsemend surgeries

- _maps/map_files/rift/rift-06-surface3.dmm
Tin, plus adds a mapped in wooden door to the front entrance of the cave
Spider egg sacks spawn 6-24 spiderings PER SACK, which leads to the cave being filled with a incoherent amount of spiders. This leads to pretty much no one actively interacting with the cave more than once, with most either walling off the front entrance for the shift, or walling off the front entrance for the shift, filling the cave with phoron, and torching the spiders out.
This makes it at least more sane as a "Security is bored and want to do something" POI without having it constantly leak out to the station proper/be pretty much impossible to fight through to the queen without cheesing the hell out of the cave.
:cl:
add: Door to spider cave entrance
del: A couple spiders right near the cave entrance tunnel
del: …
> Removes all egg sacks from Spider Cave

- html/statbrowser.html
So what I did originally fixed the ellipses issue, but I think I had conflicting CSS or whatever.
Regardless, this makes it so the text no longer has a visible background until you hover over the button.
> Actually fixes statbrowser button text backgrounds

- _maps/map_files/rift/rift-05-surface2.dmm
1. **Nerfs Tactical Armory.**
2. **Adds Alternate Body Armor.**
3. **Adds Corporate Security tags to carrier rack.**
1. _I've begun to notice the frequent usage of an automatic shotgun by Security. The first time, I assumed it was bought from a Trader. The second time, I took notice. It turns out that there were **two** automatic shotguns in the Tactical Armory. Autoshotguns don't belong on the map period. They've both been removed. The number of map spawn Advanced SMGs has also been reduced by half. The number of map spawn marksman rifles has, again, been reduced by half as well._
2. _A Security player requested access to alternate Security vests. Since this change is (should be) cosmetic, I've added four of these vests to the Security ready room._
3. _As with the above, Security plate …
> Map Adjustment: Armory Tweak/Nerf Edition

- code/game/objects/items/storage/bags.dm
tl;dr bags won't scale to amount of storage used
because this ruins the point of using a bag.
> buffs bags again

- _maps/map_files/rift/rift-05-surface2.dmm
Fixes the month-old issue of Science Front Door needing RnD access to open, while the RnD Door needs general Science access.
So Explorers can no longer just walk into RnD to print stuff, but instead get access to Science's front door.
:cl:
tweak: Changed Science Airlock outer door access
tweak: Changed Science Airlock inner door access
tweak: Changed Science RnD labs access and name
/:cl:
> Fix RnD Access

- code/modules/integrated_electronics/subtypes/manipulation.dm
title
Circuitry is pretty much already impossible to counter when people do funny combat drones.
I don't consider making them also impossible to disable when the only way of reasonably disabling them is to screwdriver them open after picking them up as good balance.
:cl:
balance: Removed circuitry maintenance hatch locks.
/:cl:
> disables maintenance hatch locks from circuitry

- code/modules/multiz/movement.dm
the correct fix is to make it use forcemove as you usually do
however I don't have time to refactor multiz outside of the maploader PR
so
this is the best we're getting for now.
> multiz movement now hooks onTransitZ properly

- code/modules/cargo/supplypacks/engineering.dm
Ordering the Fusion core or fuel injector would give you the wrong board. When ordering the fuel compressor you have no means to build it thanks to missing parts.
> Fusion Cargo Fix

- code/game/objects/structures/girders.dm
- code/game/turfs/simulated/wall.dm
This PR adds allows costume material walls to now also have modified radiation resistances, while keeping normal steel and reinforced plasteel walls on their old values of 0.5 and 0.25. This involves girders, plating and reinforcements
A snow packed wall for example now has a value of 0.93
A lead wall: 0.23
A reinforced lead wall: 0.19
:cl:
add: Material type of girders, plating and reinforcement now influence radiation resistance
/:cl:
> Rad insulation for material walls

- code/__DEFINES/misc.dm
- code/modules/mob/living/carbon/human/traits/positive.dm
- code/modules/species/station/standard/teshari.dm
Values are experimental
Since I anti fun'd two races and am about to anti fun rigs and proteans I might as well fully rebalance the most common sources of movespeed mods to make things more equal.
Teshari's old modifier accounted for their old speed. This more accurately reflects where they're at right *now*.
Major Hardy is next on the chopping block after Haste.
Sorry, this is anti fun, but I'd rather encourage people to work on unique species than continue to have Custom Species be the absolute meta with its value tweaks.
In exchange, I'm also lifting the maximum amount of traits you can take for *now*.
All values are subject to change as we roll out rig / species updates in the next few months.
:cl:
tweak: Teshari are more resistant to slowdown now to match their nerfed speed.
tweak: …
> more cursed movespeed rebalancing (teshari buff), slightly, slightly buffs custom species trait selection temporarily

- _maps/map_files/rift/rift-02-underground2.dmm
tin
it's a fucking engine that benefits from rad collectors
why does engineering/atmos not have a phoron tank dispenser
> phoron tank dispenser added to engineering

- code/modules/jobs/job_types/station/science/research_director.dm
Clipboard spawns in the same spot as the Protean box containing the PAN. At the same time, the RD office has clipboards, so spawning with one is not really needed.
Please do not make me repeat myself
:cl:
remove: Removes clipboard from the RD standard loadout. Powergamers rejoyce.
/:cl:
> Fixes Proteans loosing their PAN when playing an RD

- code/modules/projectiles/projectile/scatter.dm
Sniper laser was tame.
This is bullshit. Splurting out 180 damage with high AP with no delay is not okay. Its as bullshit as most FCU we had. Mainly removed scatter on high powered lasers and bloody stuns so the scatter lense may stay for the mining tool (as there is no way to increase firerate on a projectile.
Ever got hit at close range by the particle defender on main? Yeah that is not fun. 
:cl:
balance: Scattershot on high powered weapons nerfed. Heavy laser and laser cannon beam and electrode now wont create submunitions. Stun beam submunition count lowered.
/:cl:
> Scattershot nerfs

- code/modules/projectiles/projectile/beam/beams.dm
Buffs Excav laser module. Inconsisten with the one hit of rocks. Hopefully this ammends it specially since scatterlenses are getting removed (although nobody used them in combat yet.)
Scatter lense gone, legitimate mining tool needs a buff. The other options (Phoron Bore) are a sick joke with how slow clunky they are to use.
:cl:
balance: Meatier sound on excav laser. Higher excav power to consistently one shot rocks.
/:cl:
> Buffs Excav Laser Module

- code/modules/research/designs/weapons.dm
Sorry.
Science fun, but science needs a rework.
It's at the point where I have to choose between science having fun with their more than 200 DPS weapons, or the rest of the server not living under dealing with this.
Science has more guns, on that note, that are actually just as bad or worse.
I'm not touching them until they're clearly an issue, as promised. With modular weapons, it's clearly an issue already.
This removal isn't permanent. I think a guncrafting system is cool.
I just don't feel leaving this in is a healthy thing to do anymore. It isn't an administrative matter either, because if a powerful item exists, science *exists* to hand it out.
> Disables most of modular weaponry.

- code/modules/species/shadekin/shadekin_traits.dm
Shadekin energy modifiers have been set up inversed. The Values for Light and for Dark were mixed.
In addition, some of the recharge values were pure CBT, which is not needed for an adminspawn role.
This way the regeneration rates actually fit with the description of the traits. Also, it removes unnecessary CBT, which is always good.
:cl:
fix: fixed Shadekin energy regen inversion
tweak: tweaked Shadekin energy regeneration
/:cl:
> Update Shadekin energy regenerations

- code/modules/clothing/suits/hooded.dm
- code/modules/mining/ore_redemption_machine/equipment_vendor.dm
- code/modules/projectiles/guns/energy/nuclear.dm
- code/modules/projectiles/projectile/beam/beams.dm
- code/modules/projectiles/projectile/scatter.dm
Introduces the Mining Carbine to items that the Mining Vendor can vend, and also creates the Mining Carbine.
Unless a miner uses explosives to mine, their job lasts pretty long and is quickly repetative.
The Mining Carbine is supposed to be an alternate to the Phoron Bore, which can also be bought at the Mining Vendor, allowing miners to have a little bit more variety.
Different firing modes allow the miner to mine specifically a single ore, or mine a cluster of ores or rocks.
While I was at it, I also massively reduced the amount of damage the Scatter Mining Laser does, since it had no reason to be that high, and also changed the firing sound to something that'd hurt the ears less at continuous use.
Suggestion for the Mining Carbine was made in Discord and was greenlit.
:cl:
add: Created …
> Creates and adds the Mining Carbine

- code/datums/components/horror_aura.dm
1. **Makes some adjustments to range.**
1. _Apparently witnessing an otherworldly entity downloading itself into reality via a profane obsidian statue or a big pile of writhing meat shouldn't have such a big area of effect. I dunno._
:cl:
tweak: Slightly reduces range of Horror Auras.
/:cl:
> Minor Tweaks to Horror Aura

- code/modules/mob/living/simple_mob/simple_mob_vr.dm
- code/modules/mob/living/simple_mob/subtypes/animal/space/gaslamp_vr.dm
- code/modules/species/protean/protean_blob.dm
- code/modules/vore/eating/living_vr.dm
- code/modules/vore/eating/simple_animal_vr.dm
- code/modules/vore/eating/vore_vr.dm
- code/modules/vore/eating/vorepanel_vr.dm
vore as a mechanic exists only for player to player roleplay
i'm not interested in maintaining or entertaining mechanical vore from mechanical ais. it's not rp for the players.
players retain the ability to vore each other as a mob.
:cl:
del: mobvore
/:cl:
> removes AI-controlled mob vore

- code/modules/species/protean/protean_species.dm
proteans can't be mirrored; their brain serves as their mirror.
:cl:
balance: proteans now drop their brains on death, always.
/:cl:
> proteans now always drop brains on death, fixes runtime

- maps/map_levels/192x192/lavaland.dmm
1. **Replaces Surt Mining Airlock with a Retention Field.**
1. _Due to lasting issues with the Surt airlock, it will now use a retention field with blast doors to keep the staging area secure._
:cl:
tweak: Replaces Surt Mining airlock.
/:cl:
> Replaces Surt Mining Airlock.

- code/game/objects/items/stacks/sandbag.dm
Fixing a typo, it resulted in a type of
```dm
/obj/item/stack/sandbags/singular
name = "sandbag"
```
instead of
```dm
/obj/item/stack/sandbags
singular_name = "sandbag"
```
> Fixing singular_name for sandbags

- code/datums/components/crafting/recipes/recipes_misc.dm
- code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
1. **Restores Reagent Cost to Some Recipes.**
1. _Thanks to Nicc fixing some issues in the code, reagents can now be used in crafting recipes. This restores costs to a few recipes where I removed it in the past._
:cl:
fix: Fixes crafting recipes that need reagents.
/:cl:
> Fixes Some Crafting Recipes Lacking Reagents

- code/modules/reagents/reagent_containers/glass.dm
1. **Enables Overlay that Shows When a Bucket Has Liquid In It.**
1. _Just a nice little QOL thing. Or really just an aesthetic thing, really._
:cl:
tweak: Enables check for water overlay on buckets.
/:cl:
> Buckets Now Reflect When They're (Mostly) Full of Liquid

- code/modules/ghostroles/instantiator.dm
- code/modules/ghostroles/roles/ashlander.dm
- code/modules/ghostroles/roles/pirate.dm
1. **Ashlander players may now spawn in with their custom slots without admin intervention.**
2. **Pirates use the same system.**
1. _Following tons of requests, I have finally sat down and figured out the Player Static instantiator with Kevin's help. Players can now set up Scorian character slots and load in using them directly._
2. _The same as the above, but for pirates. Pirates necessarily have less racial restrictions. I want to blacklist certain races, but I'm having issues with the code._
:cl:
tweak: Changes ghostrole spawning to allow slots.
/:cl:
> Ashlanders and Pirates Now Spawn In With Character Slots.

- code/modules/mob/living/silicon/robot/robot.dm
Bet
It'd probably be very rare and pretty funny ss13 soul to have incidents revolving around getting injured by machinery you climbed under. 
:cl:
add: Added a very small chance to have mechanical incidents with dogborgs. 
/:cl:
> Dogborgs now CRUSH people's heads VERY RARELY when sharing a tile and resting.

- code/modules/reagents/machinery/dispenser/dispenser.dm
we really need to have INTERACT_MACHINE_REMOTE_SILICON instead huh
> fixes chem dispensers not being used by silicons

- maps/map_files/rift/rift-11-orbital.dmm
- maps/map_levels/192x192/piratebase.dmm
1. **Adds holopads to Spec Ops and Pirate Shuttles.**
1. _These two were overlooked in the update._
:cl:
add: Adds holopads to Spec Ops and Pirate shuttles.
/:cl:
> Adds Holopads to Spec Ops and Pirate Shuttles

- code/controllers/subsystem/overlays.dm
- code/game/objects/effects/map_effects/portal.dm
- code/game/objects/structures/map_blocker.dm
- code/game/turfs/simulated/wall_types.dm
- code/modules/multiz/zmimic/mimic_movable.dm
- code/modules/multiz/zmimic/mimic_turf.dm
- Fixes a runtime with ZM and move-up.
- Some types that don't make sense to mimic have been marked IGNORE.
- Mimics can no longer get wet from the pool.
- AO should no longer look weird around diagonal shuttle walls.
> Z-Mimic (and AO): Minor fixes

- code/modules/vore/fluffstuff/custom_items.dm
telescience update will deal with the rest
unfortunately people won't stop gaming with this so
:cl:
balance: translocators now have a 5 second activation delay when teleporting others
/:cl:
> adds a delay to translocators

- code/modules/jobs/job_types/station/admin/centcom_officer.dm
- code/modules/jobs/job_types/station/admin/emergency_responder.dm
- code/modules/jobs/job_types/station/service/botanist.dm
Fixes Botanist, CCO, and ERT spawning with two PDAs instead of one.
> Double PDA fixes

- code/modules/integrated_electronics/core/assemblies.dm
before, the entire server would be notified if an assembly had a null value in its assembly_components list while it was checking its power consumption. although funny, this was also annoying. this pr stops it from doing that by just deleting that line
Bad assembly_components entry in [src].  Has remove() been called incorrectly?
> removes dumb assemblies debug message

- code/modules/admin/verbs/map_template_loadverb.dm
- maps/templates/shuttles/overmaps/generic/bearcat.dmm
- maps/templates/shuttles/overmaps/generic/cruise_ship.dmm
- maps/templates/shuttles/overmaps/generic/cruiser.dmm
- maps/templates/shuttles/overmaps/generic/curashuttle.dmm
- maps/templates/shuttles/overmaps/generic/gecko_cr.dmm
- maps/templates/shuttles/overmaps/generic/gecko_sh.dmm
- maps/templates/shuttles/overmaps/generic/generic_shuttle.dmm
- maps/templates/shuttles/overmaps/generic/hybridshuttle.dmm
- maps/templates/shuttles/overmaps/generic/itglight.dmm
- maps/templates/shuttles/overmaps/generic/mackerel_hc.dmm
- maps/templates/shuttles/overmaps/generic/mackerel_hc_skel.dmm
- maps/templates/shuttles/overmaps/generic/mackerel_lc.dmm
- maps/templates/shuttles/overmaps/generic/mackerel_sh.dmm
- maps/templates/shuttles/overmaps/generic/mercenarybase.dmm
- maps/templates/shuttles/overmaps/generic/mercship.dmm
- maps/templates/shuttles/overmaps/generic/salamander.dmm
- maps/templates/shuttles/overmaps/generic/screebarge.dmm
- maps/templates/shuttles/overmaps/generic/shelter_5.dmm
- maps/templates/shuttles/overmaps/generic/shelter_6.dmm
- maps/templates/shuttles/overmaps/generic/vespa.dmm
1. **Replaces all Shuttle Template APCs with 'No Alarm' variants.**
1. _Turns out people who mapped these didn't put 'No Alarm' APCs in. Had to fix it myself._
:cl:
fix: Fixes No Alarm APC lack.
/:cl:
> Fixes Shuttle Templates Missing 'No Alarm' APCs

- code/modules/preferences/preference_setup/loadout/loadout_accessories.dm
- code/modules/preferences/preference_setup/loadout/loadout_utility.dm
Adds holsters to the loadout's accessory menu, and adds matrix recolorable/renamable rigs to the utility section.
Yes the bug with machete holsters spawning filled was fixed, ping me if people somehow find a way to spawn with them since it should be impossible. Would likely be a result of some witchcraft, and very intentional abuse of the loadout system.
> Holsters and Rigs

- code/modules/mob/living/carbon/human/emote.dm
1. **Adds the new emotes to the cyborg *help list.**
1. _Tired of hearing people complain about not seeing all the emotes. Physician, heal thyself._
:cl:
fix: Updates cyborg/synth emote list.
/:cl:
> Updates Cyborg/Synth Emote List.

- code/game/turfs/simulated/floors/water.dm
surely no one would be deranged enough to have put two crucial subtypes in the fishing overrides file instead of in the file it is **actually supposed to be in** am I right gamers?
> fixes it snowing indoors

- code/game/objects/effects/traps.dm
1. **Increases Trap Lethality/Maiming Ability.**
2. **Fixes Bugs With Traps.**
1. _Certain traps, namely pop-up pillar and buzz-saw traps, now dismember people struck by them._
2. _Leg breaker traps now actually break legs, traps that tripped even when covered have the correct checks put in place now, and the falling log can be cut by any sharp object/actually updates its icon when broken._
:cl:
add: Adds dismemberment to blade traps.
fix: Fixes bugs in trap code.
/:cl:
> Fixes Several Bugs With Traps and Increases Lethality

- code/__DEFINES/jobs/spawnpoints.dm
- code/game/landmarks/spawnpoint/station/misc.dm
- maps/map_files/rift/rift-02-underground2.dmm
- maps/map_files/rift/rift-06-surface3.dmm
- maps/map_levels/192x192/Class_M.dmm
Placed shuttle dock spawns instead of arrival shuttle spawns. Moved shuttle dock, placed arrival spawns where they used to be.
Class M dorms had linked door bolts on 1/3rd of dorm rooms. Fixed here.
> Rift Arrival spawn fix + classm dorms

- code/modules/species/station/standard/human_subspecies.dm
Lowers the vatborn default hunger rate from 700% to 50% higher than the baseline human.
The comment makes me believe they were originally intended to have a *lower* hunger rate than humans. I feel like it's fine to keep them higher, this is the same value as grav-adpated humans have, without being ridiculous with how much you have to eat.
:cl:
balance: Balances the vatgrown hunger rate
/:cl:
> Adjusts the vatborn hunger_rate

- code/modules/mob/inventory/inventory.dm
unlike the other slot IDs, there's a valid use case since this "abstract" type is used by worn slot detection, so it's valid to be passed around as either an ID or a typepath, since things can grab it out of the inventory system.
the other abstract slots cannot be grabbed out of inventory.
> allows abstract insertion to hands via ID

- code/game/mecha/combat/fighter.dm
- maps/map_files/rift/rift-06-surface3.dmm
- maps/map_levels/140x140/tradeport.dmm
- maps/map_levels/192x192/tradeport.dmm
- maps/nsv_triumph/triumph_overmap.dm
- maps/overmap/shuttles/pirateskiff.dm
- maps/rift/rift_shuttles.dm
Replaces Zorren lore with Skrellian for the Allure Fighter.
Removes a buggy wall mount that blocks a locker on the trade ship
Removes a duplicate turret control panel on the exploration shuttle, and moves it to a more visible location.
Gives most overmap shuttles a unique color, except for civilian shuttles.
> Shuttle colors, Allure Skrell lore, and more

- code/game/machinery/computer/timeclock_vr.dm
:cl: 
tweak: Job on/off duty swapping is now a 3 minute lockout instead of 10.
/:cl:
> further drops job switch lockout (10 to 3 minutes)

- code/game/machinery/cryopod.dm
- maps/map_files/rift/rift-03-underground1.dmm
- maps/map_files/rift/rift-04-surface1.dmm
- maps/map_files/rift/rift-05-surface2.dmm
1. **Adds Lights and Air Refill System to Hammerhead.**
2. **Adds Psych Ward Cryo Computer.**
3. **Adds Air Connector Ports to Recharging Zones.**
1. _General QOL changes for Hammerhead. Also makes its holopad visible._
2. _Started getting a warning that this was missing, so I made one for the psych ward cryopod._
3. _Fighters and mecha should be able to replenish air. It turns out you can just hide these under recharging pads, which is neat._
:cl:
add: Adds air connector ports to charging pads for mechs/fighters.
add: Psych Ward cryo computer.
tweak: Adjusts Hammerhead layout for QOL.
/:cl:
> QOL Improvements to Hammerhead & Air Connector Ports for Mechs/Fighters

- code/modules/atmospherics/machinery/pipes/he_pipes.dm
As title. HE pipes now stop working if they're less than 0.01K off from the environment instead of less than 20K.
HE pipes that only work with a less-than-20K delta are _completely worthless_ for any actual, practical use. Imagine a heater that only works if you're above 40C or below 0C; that is _literally_ what HE pipes are right now. Even worse, it's not hysteresis, they _stop working_ if they get within that range. It's really, really bad.
One might be concerned about performance issues, of course; well, I tested this, live, on the server, only vaguely informing everyone that it would happen, and measured the effects in profiling and the MC. It had no overall effect on performance, and only a marginal effect in the profiler even though I had, earlier in that round, set up a huge HE …
> Made HE pipes 20000x as sensitive

- code/modules/atmospherics/machinery/pipes/vent.dm
as title. instead it just only does its parent processing if it has a pipenet. worst case scenario is that you have like two vents in the entire map separated from a pipenet and repeatedly doing a single null check every 2 seconds, who cares, that's not a real problem actually, god i hate premature optimizers so much
because believe it or not microoptimizations that can ruin rounds for people and don't actually improve performance any are a bad idea. GOD I HATE PREMATURE OPTIMIZERS SO MUCH
:cl:
fix: passive vents no longer break with no feedback intentionally for reasons unfathomable to the user
/:cl:
> Makes passive vents not permanently kill themselves if they can't find a pipenet for one (1) tick

- citadel.dme
- code/__DEFINES/traits/mob.dm
- code/modules/mob/living/carbon/human/traits/neutral.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
Whoops I accidentally did a balance change with my please-don't-trigger-me PR.
Adds alcohol intolerance, a trait that prevents proper metabolization of most alcohol ingredients; instead of effects simulating drunkenness, you get _immediate_ liver failure, toxin damage, pain and vomiting. Yes, I actually do prefer that personally.
Certain drinks now have their effects modified by the *effective dose* calculated in the main ethanol affect_ingest and affect_blood procs, rather than just sort of guessing at it or doing completely wrong things (deathbell was doing `if(dose * strength > strength)`, which is to say, `if(dose > 1)`, for example).
honestly it's mostly just a personal thing, don't want my character to get drunk. The doses thing should be good, though, since it actually makes …
> Effective dose works for alcohol subtypes' effects, + alcohol intolerance

- code/modules/food/food/drinks.dm
grab soda can
put in backpack
"this needs to be opened to pour it"
fixes a bug
:cl:
fix: stops drinks saying they need to be opened if target is not something that can be poured into
/:cl:
> stops drinks saying they need to be opened if target is not something that can be poured into

- code/modules/events/event_container_vr.dm
1. **Moves Screaming Signals and Pirate Boarders to Disabled Event List.**
1. _I want us to move away from non-curated Human on Human combat. Or humanoid, whatever. Same thing. This random event also just kinda sucks for the cult from a storytelling perspective and needs re-evaluation. I'm moving it to disabled - along with pirates - so that they can be manually triggered from now on, instead of using RNG._
:cl:
balance: Moves Cult and Pirate RNG to Manual Trigger.
/:cl:
> Removal of Cult RNG Attack

- code/modules/preferences/preference_setup/loadout/loadout_eyes.dm
:cl:
fix: fixed prescription glasses missing from the loadout
/:cl:
> readds prescription glasses

- code/modules/xenoarcheaology/misc.dm
- maps/map_files/rift/rift-04-surface1.dmm
- maps/map_files/rift/rift-05-surface2.dmm
- maps/map_files/rift/rift-06-surface3.dmm
- maps/map_files/rift/rift-08-west_deep.dmm
One-way teleport that requires command permission is pretty neat compared to Qpad sillyness. ESPECIALLY for events. First step is fixing our existing teleporter, though.
Current beacon locations are: Exploration shuttle, Corser scout shuttle, gateway prep, and the cargo warehouse.
I avoided putting one in the bridge/teleporter room/hammerhead due to security reasons.
All beacons are anchored, and unable to be moved.
> Bridge teleporter fix, and more beacons.

- code/game/objects/items/gunbox.dm
- maps/map_files/rift/rift-05-surface2.dmm
Adds an armor vest selection box, and maps it into the general sec storage area. 
In-character, there is only one vest per box. 
**Do not propagate scenarios where you're magically selecting one of three vests** like some kinda bluespace magic. You're all better than that.
> Security Armor Vests

- code/__DEFINES/items/nifs.dm
- code/modules/admin/verbs/debug.dm
- code/modules/nifsoft/nif.dm
- Changes the durability of bioadaptive NIF to 50% of a normal NIF instead of 25%.
- Adds a bioadaptive VeyMed NIF that's about 10 times more durable than a normal bioadaptive NIF. Exists only through adminspawn only, like the other VeyMed NIF.
- Also updates the Quick NIF admin tool to be "compatible" with this update. _(it just removes the NO_SCAN check. It's an admin tool, it probably didn't need this check to begin with.)_
- Corrects a spelling issue.
While it makes sense that a bioadaptive NIF is less durable than a normal one, as it struggles with the biology of a species that it can't assess very well - it's also a bit _too_ low of durability. Those who have one have one and frequently install programs either through NIFSoft uploaders or other methods generally have to get …
> buffs bioadaptive NIF durability, adds veymed variant of bioadaptive NIF

- code/modules/power/smes/smes.dm
This PR changes the icon file used from power.dmi to power_vr.dmi, which has the more modern SMES icons. 
I just think it looks better aesthetically.
:cl:
tweak: SMES Units now user the newer icons.
/:cl:
> Changes SMES Units to use more modern icons

- code/global.dm
Modifies the global/list/acceptable_fruit_types to allow grass, this is the same list that (I BELIEVE) alraune's use to grow fruits. This lets them grow grass, thats it.
Alraunes being able to grow grass would allow them to spontaneously make flowers and other vegetation, by harvesting the grass, and using it in hand to make grass tiles, which can make vegetation like flowers on the floor.
:cl: Colfer
add: Makes alraune able to grow grass using fruit gland
code: changed global.dm to allow grass in acceptable_fruit_types
/:cl:
> Alraune can now grow grass

- code/modules/projectiles/guns/ballistic.dm
Drops mags when self-attacking an item (Z) that doesnt have a firemode selector, instead of putting it into your other hand. 
A bug would cause putting it into a filled offhand to delete the magazine, and it made me realize it didnt make sense to do it in the first place. Pulling the mag out yourself with a click makes more sense than hotkey pulling. So instead, you now drop a mag from the gun via hotkey, and manually pull it from the gun via click. Slower reload for less tense situations, when its beneficial to keep your magazine.
> Dropping magazines

- code/modules/preferences/preference_setup/loadout/loadout_xeno.dm
There are no mechanical advantages people could exploit and it still follows the job requirements. This has been green lit.
> Remove Teshari xeno wear restriction

- code/game/objects/items/gunbox.dm
- code/modules/clothing/suits/hooded.dm
- code/modules/clothing/under/accessories/holster.dm
Rewords some of the gunbox text to properly convey what the player/character is seeing/doing.
Makes armor plates spawn within covert carriers instead of outside.
Alters holster descriptions.
Covert carriers no longer hide holsters on inspect.
> Armor gunbox touchups

- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Other.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Toxins.dm
Reduces probability of message spam for alraune species consuming specific things. Especially milk, which didn't even have any probability and just sent the message per tick or metabolism or something.
:^)
:cl:
fix: Alraune know that they are nourished by milk. Shut up.
/:cl:
> [Salt PR?] Shut the FUCK up about milk nourishment.

- maps/map_files/rift/rift-02-underground2.dmm
- maps/map_files/rift/rift-05-surface2.dmm
- maps/map_files/rift/rift-06-surface3.dmm
- maps/map_levels/192x192/lavaland.dmm
Which pets are gone?
Renault(captain) Brutus (hos) Lisa(pathfinder)
Added polly to reactor control room, moved Tom and (added) jerry to the engineering area of lavaland/surt instead of the bar area.
What else?
The clown room outside of security maint is replaced with a more normal-looking maint room.
Why?
These 3 pets exist solely to make dirt appear on the floor, or bait for less than desirable actions. Leaving all the other pets that are interesting and/or have unique mechanics (runtime, Ian, Kendrick, ect.)
Polly has unique mechanics, readded.
The clown room left me asking 'why is this here' more times than what's healthy. The answer is probably just "funny tg clown beating, get it?"
> Removing a few non-standard pets

- maps/map_files/rift/rift-05-surface2.dmm
fixes a plating tile in a substation that was breaking atmosphere/making it snow indoors. it was marked as a lythios turf
> Snowtile fix

- maps/map_files/rift/rift-05-surface2.dmm
Removes a door sitting in the middle of the floor in sec maint.
Swaps NIF box with handcuffs and evidence bags so that it's easier to see during prep.
> sec maint floor door

- code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
- code/modules/mining/ore_redemption_machine/survey_vendor.dm
:cl:
del: Removed precursor tech item from the equipment vendors
/:cl:
> removes precursor tech from the equipment vendors

- code/modules/admin/admin.dm
:cl:
admin: Prevents empty admin announcemnts
/:cl:
> Adds a trim check for admin announcements

- code/modules/power/crypto_miner.dm
the encryption reinforcing heater was supposed to be an additional challenge for engineers, not a, lets put it outside and forget about it machine, this pullrequest makes it so that it requires to be in at least 50% helium atmosphere to function
makes the ERH more that just a, who can build the largest power output engine challenge
:cl:
balance: Cryptominer cant be run in standard atmosphere anymore
/:cl:
> Finally fixes the encryption reinforcing heater

- code/modules/clothing/suits/hooded.dm
:cl:
fix: fixed the game trying to create a null type hood
/:cl:
> fixes random hood runtime

- code/modules/species/protean/protean.dm
Just a quick 2-line change that makes proteans regenerate their face along with their wounds.
Could've made it an ability, but it's a mess already
I don't have to ask for aheals everytime I fall down the ravine and lose my markings
:cl:
add: Added the ability for Proteans to fix disfigurement
/:cl:
> Makes Proteans pretty again

- code/game/objects/items/circuitboards/machinery/mining_drill.dm
- code/modules/mining/drilling/drill.dm
- code/modules/mining/ore_datum.dm
- code/modules/research/designs/xenobio_toys.dm
Would you believe me if I hadn't updated my git in about 400 years, and had to blow the old version of my repo up?
Yes? No? It doesn't matter.
Anyways! Meat and potatoes of this:
Allows players to make gene and plant discs freely in the protolathe. Since we do not have a dedicated genetics, this will help the pains of actually doing genetics by giving us storage solutions for genes.
Fixes a problem with brass also creating slag when compressing, by setting the copper alloy flag to 1.
And finally: Allows you to upgrade the braces! If your brace has T3 or better, a single brace can hold an entire drill. All credit goes to Hatterhat for this one, as I pretty much wholesale ripped it from his buff of the big drill™ on Virgo.
Not making slag is ALWAYS good. It saves on material, too.
Having …
> Take 2: Some fixes and QoL

- code/modules/vore/resizing/resize_vr.dm
this confused me at first too then i realised in this proc:
/mob/living/proc/attempt_to_scoop(var/mob/living/M)
M is the doing the scooping, not the one being scooped
so it has been checking the wrong persons prefs for um two years
fix bug
:cl:
fix: makes the instant pick up pref actually work
/:cl:
> makes the instant pick up pref actually work

- maps/rift/levels/rift-02-underground2.dmm
Fixes the vent button. It's frankly ridiculous that it was an issue for as long as it was.
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/assets/25853190/99bc2e7f-f7aa-4f0e-8257-8ad96d2fd33b
Why do you think?
:cl:
fix: Fixed the emergency supermatter engine core vent button.
/:cl:
> Fixes SM ejection vent button

- code/modules/admin/verbs/randomverbs.dm
:cl:
admin: Cryo-Player uses tgui list inputs, instead of byond list inputs
/:cl:
> make cryo player use tgui list select

- code/game/objects/items/storage/belt.dm
One line PR, does what it says on the tin.
Should work for all types of hypovial.
Makes sense that these should fit on the belt.
:cl:
tweak: Hypospray vials now fit on medical belts.
/:cl:
> Makes medical belts able to hold hypospray vials.

- code/__DEFINES/preferences/misc.dm
- code/modules/preferences/preference_setup/general/03_body.dm
please don't give yourself 184 markings
please don't give yourself 184 markings
:cl:
add: adds a limit to the number of markings you can have (30)
/:cl:
> adds a limit to the number of markings you can have (30)

- code/game/objects/items/weapons/handcuffs.dm
You can now apply handcuffs on a mob that is lying down. This can be because they are intentionally lying down, because they collapsed from being magdumped by shitsec, etc.etc.
This should ideally make it easier for security to arrest someone after the fight is over. Currently, even when someone is lying down and in painshock they can still mash resist to stop you from getting a grab on them, which means you have to keep tasing them until they pass out. That is probably not ideal, so this makes it much easier to handcuff a downed suspect (and also makes high-risk arrests a little easier to pull off).
:cl:
add: You can now handcuff someone who is lying down without needing to grab them first.
/:cl:
> You can now handcuff a lying mob

- code/modules/materials/material_recipes.dm
it's a horse post made out of bone and sinew found in the crafting menu intended for ashlanders to make use of
it gets deconstructed into bone still which is what caused it to get reported in bug-triage in the first place
it's um made of bone so you should probably not be able to make it from wood (but someone making a wooden one would be neat!)
:cl:
del: removes the recipe for the horse post that requires wood, because it is made out of bone and sinew
/:cl:
> removes the wood recipe for the (bone) horse post

- .github/workflows/ci_suite.yml
as it stands we do not actually run integration tests on windows
all it's doing is deploying the server artifact
given we are not tg we really, really do not actually need this
so it's probably better to throw this out and make our CI runs a good deal faster.
> removes windows build from actions / ci_suite

- code/modules/mob/living/carbon/human/health.dm
- code/modules/organs/organ.dm
- code/modules/species/species.dm
- code/modules/species/station/xenochimera.dm
title
regarding NIFs:
xenochimera removing NIFs is intended, nobody ever coded (emergent gameplay!), now it actually removes it instead of sending it to the shadow realm
aheals removing markings and NIFs was never intended so um yes
why would you lose them
:cl:
fix: makes markings transfer over when ahealed/regenerating
/:cl:
> makes markings transfer over when ahealed/regenerating + aheals dont remove NIFs

- code/__DEFINES/color/lights.dm
- code/controllers/subsystem/nightshift.dm
- code/modules/power/lighting/lights.dm
- maps/rift/levels/rift-05-surface2.dmm
- maps/rift/levels/rift-06-surface3.dmm
brightens nightshift lighting from 0.4 to 0.6 (dayshift is 0.8)
Nightshift was too dark, and blue adds atmosphere (It overwhelmingly won the vote too)
:cl:
tweak: Changes nightshift color to blueish
tweak: Changes nightshift brightness from 0.4 to 0.6
/:cl:
> Nightshift Color/Brightness

- citadel.dme
- code/__DEFINES/rust_g.dm
- code/__HELPERS/icons/metadata.dm
- code/modules/mob/inventory/slot_meta.dm
- dependencies.sh
- maps/rift/levels/rift-06-surface3.dmm
- maps/tether/levels/station2.dmm
- tools/ci/install_rust_g.sh
- tools/deploy.sh
- tools/tgs4_scripts/PreCompile.sh
~~so back when i did inventory slot refactor i added this thing called a render state cache
it basically allows for lazy people to default when needed and don't default when not needed~~
~~problem is
to facilitate this we need to icon_states
which seems to be using just an exorbitant amount of memory.~~
byond icon_states bad
replaced with rustg icon states
there's a massive footgun in that it's obviously going to be slow due to the fcopy() but for the use case of inventory it should be fine.
frees about 400MB.
also fixes us just having bad shuttle paths
> updates rust_g; adds rustg-based icon_states; fixes unit tests

- code/modules/power/singularity/singularity.dm
radiation update made it too useless.
> buffs singularity radiation

- tgui/docs/component-reference.md
- tgui/packages/tgui/backend.ts
- tgui/packages/tgui/components/Module.tsx
- tgui/packages/tgui/layouts/Modular.tsx
allows override section props because the containing element usually knows more about the context than, y'know, the module itself
we should configure modules to take up all available space at some point but i'm lazy so project for later.
> small patch to TGUI modules

- maps/triumph/engines.dm
:cl:
del: Removed fission from triumphs engine rotation
/:cl:
> comments out triumph's fission engine until its fixed (it never will be)

- code/modules/mob/observer/dead/orbit.dm
:cl:
add: Added silicon players to the ghost follow menu
/:cl:
> Follow menu now shows AI and robots/cyborgs

- code/controllers/subsystem/mapping/maps.dm
stops crashes/harder reboots from preventing map swaps.
> SSmapping now writes next map immediately when admin-verb change map'd

- code/modules/mob/living/silicon/pai/defense.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/pai/verbs.dm
1. clothing name now has (pAI) appended to it because i really don't want someone to name their pAI after an item of clothing and be indistinguishable, that's not okay
2. when you use clothing on a pAI, it notifies the person who did so if it was successful, the pAI gets a similar message
3. copied clothing now copies the colour of the item as well
2/3 are some good qol stuff, 1 is because we have a clear rule of "don't be a creep", it's a ghost role, and is easily open for abuse which i would rather not happen
:cl:
tweak: pAI clothing has (pAI) appended to its name, copies colour when copying other clothing items, and notifies the pAI and user when you scan a piece of clothing on a pAI
/:cl:
> pAI clothing adjustments

- code/modules/mob/living/say.dm
title, tested
fixes a bug
:cl:
fix: fixes mute trait not working
/:cl:
> fix mute trait not working

- code/datums/character_profile.dm
- code/game/machinery/holopad.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/admin_set_headshot.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/robot/examine.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/preferences/_preferences.dm
- code/modules/preferences/preference_setup/general/01_basic.dm
- code/modules/vore/eating/living_vr.dm
- tgui/packages/tgui/interfaces/CharacterProfile.tsx
Tidies up character profiles considerably.
Adds options for either a headshot, or a full-sized reference (portrait only, limitations of max width 500px and max height 1000px)
Makes flavor text work. Turns text boxes into collapsible sections.
Adds character profile link to AI holograms.
Replaces the 'OOC Notes' link in examine, rolling that functionality into the profile. Vore prefs and flavor text viewing are untouched, for the moment.
I have more experience with tgui now so it's a good time for me to clean up my mess.
> Character Profile Tweaks

- code/modules/food/food/snacks.dm
title
fixes missing sprite
:cl:
fix: makes the wings box sprite point to food.dmi instead of storage.dmi
/:cl:
> makes the wings box sprite point to food.dmi instead of storage.dmi

- maps/triumph/levels/deck4.dmm
Fixes the security equipment storage once again with hopefully no conflicts this time. It adds plate carriers, helmet cameras, survival knives, ETC, while also removing some uneeded items. 
Removed some unneeded items from the HoS's office
replaced shuttles in the podbay with barons 
good riddance
> TRIUMPH - Secquipment storage fix - slight HoS office edit - sec shuttle replacement

- code/datums/world_topic.dm
- code/game/objects/items/devices/paicard.dm
title
pAIs are still not crew, and not on the crew manifest, this just makes them show up for things like the discord bot
oh also it makes the pAI actually get deleted when you wipe the personality (tested)
makes the manifest a bit more accurate without editing the in-game crew records
:cl:
add: makes pAIs appear on the api call used by APIs such as the discord bot
/:cl:
> makes pAIs appear on the api call used by APIs such as the discord bot

- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/silicon/silicon.dm
As title. Just says "adjusts their posture" when pose is changed.
Set pose feels a bit underused, I dunno? Because it's awkward to manually /me "sets their pose" or LOOCing or whatever.
:cl:
tweak: Setting pose shows a visible message.
/:cl:
> Visible emote on setting pose

- maps/triumph/levels/misc.dmm
Fixes the rotations of the Holodeck windoors for the Triumph.
Simply fixes the rotation of the windoors in the holodeck.
OCD
:cl:
tweak: rotates the windoors to proper orientation on the holodeck.
/:cl:
> Holodeck Windoors

- maps/sectors/tradeport_140/levels/tradeport_140.dmm
- maps/sectors/tradeport_192/levels/tradeport_192.dmm
Modifies both tradeport_140 and tradeport_192
-Replaces all multi-tile firelocks with single tile firelocks. --Multi-tile firelocks are invisible ingame and potentially defunct.
-Rotates all firelocks to be the correct direction for baywall effects.
-Headbashes the Baruang bridge shutter control button to no longer be loyal to the syndicate (Access id change from 150 to 160)
-Mirrors the Beruang bridge 'sector holopad' to the tradeport_140 version, it was on the 192 version only before.
-Buffs trader
-Fixes nasty visual bugs in emergency equipment
-Replaces all multi-tile firelocks with single tile firelocks on tradeport_192 & tradeport_140
-Rotates all firelocks to be the correct direction on tradeport_192 & tradeport_140
-Adds a sector holopad to the bridge of the Beruang on …
> Tradeport mapfixes and rotations.

- code/modules/tables/interactions.dm
instead of waiting for the automatic process to handle it, we tell it to update the moment it is placed on a table
boy i sure love seeing two sprites when i place something on a table just for one to magically disappear a second later
:cl:
fix: stops mob holders being buggy when placing a held mob onto a table
/:cl:
> stops mob holders being buggy when placing a held mob onto a table

- code/game/machinery/doors/airlock.dm
Title.
BEFORE:
AFTER:
This PR does not modify the Triumph map files.
No more funny misrotated airlocks.
:cl:
fix: Roundstart-airlocks will be rotated respectively to nearby airlocks.
/:cl:
> Doors/airlocks added to list of things airlocks will autorotate to (fixes Triumph hallway airlocks)

- code/modules/mining/shelter_atoms.dm
Restores:
- Survival pod sleeper
- The special snowflake table
- The survival pod storage
Finally, people will know a sleeper actually exists in there!
:cl:
fix: Sprites of the sleeper, the table, and the storage in the survival pod have been fixed and are now visible.
/:cl:
> Fixes missing survival pod sprites

- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/silicon/silicon.dm
title, says "**Foo Bar** Adjusted their posture." instead of "**Foo Bar** adjusted their posture" right now. This fixes it.
this is literally the worst thing i have ever added to the game and fixing it will get me into heaven
:cl:
fix: changed a couple "A"s to "a"s
/:cl:
> Fixed the erroneous capital A on posture adjustment

- code/modules/clothing/under/_under.dm
Suit sensors are loaded to the player's preference again instead of starting off with none.
was broken since loadout was updated. It's fixed now.
:cl:
fix: Characters spawned in will now have their preferred suit sensors again.
/:cl:
> Spawned character w/ loadout clothes suit sensor init fix

- code/modules/mining/mine_turfs.dm
Title. Part of something that broke due to the great baywalls change. Fixed it.
@Mazianni 
fix good.
:cl:
fix: Xenoarchaeology nodes and excavation indicators are no longer invisible due to incorrect icons.
/:cl:
> Fixes invisible xenoarchaeology nodes and excavation indicator sprites

- code/modules/food/food/cans.dm
Replaces ammonia with diethylamine in the Loam Nutri-Juice can.
This will make it no longer react into space cleaner because ammonia isn't there combining with water anymore.
fixes #5532
:cl:
fix: Loam Nutri-Juice is now filled with rich, rich diethylamine instead of ammonia. This also results in no more poisonous space cleaner incidents.
/:cl:
> Loam Nutri-Juice no longer poisons Alraune

- code/game/objects/items/weapons/RCD.dm
- code/modules/hardsuits/_rig.dm
- code/modules/hardsuits/modules/utility.dm
Title. 
Cause of Sprinter bug: 
- The hardsuit process constantly changed the slowdown to its default value.
Solution:
- I added the sprinter modifier to the value.
Cause of RCD bug:
- attackby doesn't seem to work for it.
Solution:
- I made it use use_rcd instead. I don't think anyone plans to bash someone with the mounted RCD.
Fix good.
:cl:
fix: The Sprinter and RCD modules for the hardsuit/RIG are now functional again.
/:cl:
> Fixes RCD and Sprinter hardsuit modules

- code/game/rendering/legacy/radial.dm
Title.
Specifically, this was done so that macro/micros don't have to deal with fucky radials when they're using the switchtool or whatever else. 
I don't think this will break anything. I've tested the switchtool on local testing and it seems fine.
Fix good.
:cl:
fix: Radials no longer resize based on size of atom it's attached to.
/:cl:
> Radials no longer resize based on size of atom it's attached to

- code/modules/mob/mob.dm
- code/modules/vore/resizing/resize_vr.dm
HUDs won't resize with a micro/macro. They'll remain at the same size now.
Macros/micros will no longer have HUDs that are hovering well above them, or are hardly able to be seen if they're a micro.
Fix good.
:cl:
fix: Macros/Micros no longer have HUDs in extremely awkward positions, like several pixels away from a macro.
/:cl:
> Fixes resized human HUD offsets

- code/modules/nifsoft/software/13_soulcatcher.dm
Title.
Specifically, it's all based on the PoV of the person they're in.
Snowflake mechanics still need to be fixed.
:cl:
fix: Soulcatcher people can see their own projections again.
/:cl:
> Fixes soulcatcher people being unable to see their own projections

- code/game/turfs/simulated/floors/snow.dm
i'm not sure who thought this was a good idea
but it turns out blindly step()ping people on enter on a spammed turf
is a bad fucking idea????
this is causing infinite recursion problems, so, it gets to Go, and stay Go.
> removes forced movement from ice

- code/game/objects/items/storage/toolbox.dm
- code/modules/species/promethean/promethean.dm
- code/modules/species/station/standard/zaddat.dm
- All lunchboxes now have the same storage space as a box/toolbox would. They're boxes. So are the cardboard boxes.
- Lunchbox damage is nerfed to 7 melee, 8 thrown instead of 10/10 like a toolbox would have.
- Fixes a loadout bug relating to lunchboxes where people could obtain the Zaddat lunchbox by simply... removing the Zaddat variant of the lunchbox. Too lazy to make a blacklist.
- Zaddat's received glucose hypopens are relocated to when they get their survival gear equipped instead.
- Prometheans now start with a prybar.
- More storage space at the cost of no longer having a roundstart toolbox-damage weapon, whether it be given through being a specific species or via loadout. Not that that matters much on a server with no antags.
- Fixes good. No powergame shenanigans.
- Prometheans …
> Various changes relating to lunchboxes and species who use them

- code/datums/components/_component.dm
- code/datums/components/atoms/fishing_spot.dm
- code/datums/components/atoms/radioactive.dm
- code/datums/components/crafting/crafting.dm
- code/datums/components/gps_signal.dm
- code/datums/components/items/wielding.dm
- code/datums/components/movable/aquarium.dm
- code/datums/components/riding/riding_filter.dm
- code/datums/components/riding/riding_handler.dm
- code/datums/datum.dm
- code/modules/mob/living/simple_mob/subtypes/lavaland/gutshank.dm
- code/modules/mob/living/simple_mob/subtypes/lavaland/stormdrifter.dm
- code/modules/mob/living/simple_mob/subtypes/vore/corrupt_hounds.dm
- code/modules/mob/living/simple_mob/subtypes/vore/horse.dm
- code/modules/mob/living/simple_mob/subtypes/vore/otie.dm
DCS now registers based on its registered type, as opposed to at every subtype.
Dupe mode is no longer considered realistically usable unless if-and-only-if all var pre-setting behavior is considered - which is not the case on the majority of citrp-made components outside of /datum/component/radioactive
Components are a generic way to attach datums to things.
The common practices included:
- No getcomponent
- Use signals for all interaction
- Don't subtype, set vars on initialization
This resulted in components, while being quite stable, being also quite rigid, in my opinion. Given we don't use components for the same things, and probably never will, I think it's better for us to get the optimizations from not supporting what's honestly behavior that we shouldn't rely on in the first …
> Completely changes how DCS types works

- maps/rift/levels/rift-08-west_deep.dmm
Yet another airlock I missed. This one is at the abandoned Lythios facility base thing that's radioactive as heck.
Fix good.
:cl:
fix: Fixes a wide airlock's rotation at the abandoned Lythios facility.
/:cl:
> Fixes a stray wide airlock's rotation on the Rift map

- code/game/objects/effects/decals/remains.dm
title
at whoever did this: want them to not turn into ash? add a different sprite instead of just breaking this item
fixes a bug
:cl:
fix: robotic remains now turn to ash when interacted with like all other remains
/:cl:
> robotic remains now turn to ash when interacted with like all other remains

- code/game/objects/objs.dm
As title. Hold something in one hand, start climbing, swap hand, you will instantly climb onto the thing you're trying to climb. Any and all interruptions to climbing will cause instant climbing instead of preventing climbing.
Kind of an obviously dumb exploit.
:cl:
fix: Climbing no longer succeeds if interrupted
/:cl:
> Fixes climbing interruptions letting you climb anyway

- maps/tether/tether.dm
192x192 is too big for a 480x480 slate
in the future we need pda holomaps that auto-update while you move a la TGMC's anyways.
this'll fix the CI errors.
> disables tether holomap smooshing

- code/modules/clothing/masks/gasmask.dm
- code/modules/loadout/loadout_mask.dm
Finally splits the opaque gas mask into one without any gas being filtered out, and one which is designed for nitrogen breathers.
People requested the opaque mask be given a no-filter version for a long while but nobody even tried to do it. Also brings the filter list up to date.
:cl:
add: New variant of the Opaque Mask
fix: Fixes gas paths for the Filtered version
/:cl:
> Fixes and creates variants of the Opaque Gas Mask

- maps/sectors/lavaland_192/levels/lavaland_192.dmm
1. **Replaces Surt Emergency Double Airlock.**
1. _These airlocks are no longer using the same sprites as they used to, and that makes the airlock functionally invisible. This removes the double and places in two new shutters._
:cl:
fix: Replaces Surt emergency double airlock.
/:cl:
> Replaces Surt Emergency Double Airlock

- code/modules/species/abilites.dm
remember that sonar only persists for like a half second
if we boost the image persist time we should make this slower but uh, it's kind of hard to use without
> makes sonar pulses cooldown faster

- code/modules/loadout/loadout_role_restricted.dm
:cl:
fix: removes atmospheric technician and chief engineer access limit on pleated skirts
/:cl:
> Fixes Engineers being unable to select pleated skirts

- code/game/objects/items/weapons/material/material_weapons.dm
i don't know who thought this was a good idea but this makes no sense and is shitty, and interferes with a lot of autodetection.
> removes automatic material scaling on /obj/item/material

- code/modules/cargo/supplypacks/contraband.dm
no more awoo.
Specifically this just removes the wolfgirl crate from being orderable by Cargo. It doesn't remove wolfgirls from the code, so maybe admemes can spawn them still.
you can debate the ethics of orderable humanoids in a different world. It ain't happening here, even if it's contraband.
:cl:
del: The wolfgirl crate is no longer orderable from Cargo.
/:cl:
> Removes wolfgirl crates from Cargo

- code/controllers/subsystem/pathfinder.dm
- code/modules/integrated_electronics/core/assemblies.dm
- code/modules/integrated_electronics/core/helpers.dm
- code/modules/integrated_electronics/subtypes/converters.dm
- code/modules/integrated_electronics/subtypes/input.dm
- code/modules/integrated_electronics/subtypes/output.dm
- code/modules/integrated_electronics/subtypes/smart.dm
This PR aims to bring integrated circuits not only to a more up to date version but also fix some features that weren't working.
For this I have used Baystations current circuits as a working reference. I have compiled, tested and checked for runtimes.
Fixes include
- Tile analyzer and examiner being able to handle tiles
- Reference encoder and decoders doing their job
- Advanced pathfinder being able to path through access restricted doors
- The EPv2 circuit using an incompatible name for cloning
As a consequence for the advanced pathfinder I had to readjust how access is given to circuits which now allows them to read the passkey of ID's, store them, send them and so on. A minor tweak also adjusts the TTS circuit to 1 second. Additionally, I have added an advanced signaler that while it …
> Integrated circuits fixes and changes

- code/modules/species/protean/protean_blob.dm
similar stuff might have to be done for slimes at some point
> puts a mutex on protean blob transforms

- code/game/atoms/atom.dm
- code/game/atoms/movable/movable.dm
- code/game/objects/structures/stool_bed_chair_nest/bed.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/mob.dm
- code/modules/vore/resizing/resize_vr.dm
> fixes alignment issues with macros/micros/etc

- maps/rift/levels/rift-02-underground2.dmm
- maps/sectors/lavaland_140/levels/lavaland_140.dmm
- maps/sectors/lavaland_192/levels/lavaland_192.dmm
- maps/triumph/levels/deck2.dmm
1. **Triumph and Atlas Jump Pads Made Accessible By Other Departments.**
1. _I have recieved a very reasonable request to make the telepad to Surt more accessible to respond to emergencies. I have rearranged both departments to allow for Security, Medical, and Science access to Surt proper._
:cl:
tweak: Triumph and Atlas Jump Pads Made Accessible By Other Departments.
/:cl:
> Rearranges Surt Jump Pads For Accessibility

- maps/tether/levels/surface2.dmm
- maps/tether/levels/surface3.dmm
- maps/triumph/levels/deck4.dmm
:cl:
add: Triumph: Removes four security voidsuits from the security EVA storage and replaces them with two hazard rigsuits. Adds one hazard rigsuit to the HoS' EVA storage.
add: Tether: Adds two hazard rigsuits to the level 1 (blue) armoury. Adds one hazard rigsuit to the HoS' EVA storage.
/:cl:
> Re-adds security RIGsuits

- code/modules/jobs/job_types/station/command/command_secretary.dm
they now actually default to bridge officer, to prep for the upcoming changes over the next few months
> the bridge officer title update

- code/game/machinery/computer/arcade/orion.dm
title
don't blow the bar up by accident with an item you can find in maintenance
:cl:
tweak: changes emag orion trail reward from a 1,2,4 explosion to a 0,0,2 explosion
/:cl:
> changes emag orion trail reward from a 1,2,4 explosion to a 0,0,2 explosion

- citadel.dme
- code/datums/recipe/crafting_recipes/recipes_primal.dm
- code/game/objects/items/stacks/sheets/leather.dm
- code/modules/materials/definitions/crystals/diamond.dm
- code/modules/materials/definitions/crystals/glass.dm
- code/modules/materials/definitions/metals/copper.dm
- code/modules/materials/definitions/metals/durasteel.dm
- code/modules/materials/definitions/metals/gold.dm
- code/modules/materials/definitions/metals/hydrogens.dm
- code/modules/materials/definitions/metals/iron.dm
- code/modules/materials/definitions/metals/lead.dm
- code/modules/materials/definitions/metals/osmium.dm
- code/modules/materials/definitions/metals/plasteel.dm
- code/modules/materials/definitions/metals/platinum.dm
- code/modules/materials/definitions/metals/silver.dm
- code/modules/materials/definitions/metals/steel.dm
- code/modules/materials/definitions/metals/titanium.dm
- code/modules/materials/definitions/metals/uranium.dm
- code/modules/materials/definitions/organic/chitin.dm
- code/modules/materials/definitions/special/clown_planet.dm
- code/modules/materials/definitions/special/morphium.dm
- code/modules/materials/definitions/special/phoron.dm
- code/modules/materials/definitions/special/supermatter.dm
- code/modules/materials/definitions/special/valhollide.dm
- code/modules/materials/definitions/special/verdantium.dm
- code/modules/materials/fifty_spawner_mats.dm
- code/modules/materials/material_sheets.dm
- code/modules/mob/living/simple_mob/subtypes/lavaland/gutshank.dm
- Gives bananium and silencium material properties, thus allowing them to actually spawn, whether by in-game or admin means. They couldn't before.
- Retypes insect chitin to become a material - because material chitin seemed to have existed already, which imply this was in plans probably. Spiders actually did have "chitin" as their bone type when you butchered them, but it was a material chitin that didn't work until now. Scorians rejoice, you can make chitin foldable chairs for whatever reason.
- This also changes most materials to have their IDs use their defines for code consistency.
Open to suggestions regarding the material's properties if they could be changed at all.
Fix good.
:cl:
fix: Bananium and silencium is actually spawnable now as they've been given material properties.
fix: …
> Makes bananium, silencium actually spawnable - retypes chitin to be a material

- code/modules/power/generator.dm
The TEG soundloop now respects opacity and won't make noise through walls and two screens away, making the entire engineering department a low hum.
I want to be able to RP in my department, but that hum gets grating after 20 minutes. 
tweak: The TEG soundloop will no longer play through walls
/:cl:
> Makes the TEG soundloop not go through walls

- code/game/objects/items/weapons/implants/implant.dm
death alarms are adjusted to work across the whole sector, which makes more sense than having crystals detect deaths across those distances
:cl:
tweak: tweaked a death alarms to broadcast over larger distances
/:cl:
> buffs death alarms

- tgui/packages/tgui/interfaces/PowerMonitor.js
Adjusts the Javascript to make the power monitoring program display in kW correctly. Additionally, adjusts the default "PEAK_DRAW" to match the change from amounts being displayed in watts to kilowatts, which makes the progress bars actually useful. I hope to also make the number display with our better render_power method, but this is ready to be testmerged and will immediately make the program useful again. Testmerge only until I either figure it out or give up.
Whoever coded the Javascript for the interface decided to make it do math directly rather than make the dm file providing the number do it. This caused the power manager's supply/draw numbers to be divided by 1,000 (and any decimals cut off), which made it pretty useless. This fixes it.
fix: The supply/draw …
> Makes the power monitor display supply/draw correctly

- maps/rift/levels/rift-04-surface1.dmm
- maps/rift/levels/rift-06-surface3.dmm
- tgui/packages/tgui/interfaces/PowerMonitor.js
Pretty sure these are my fault, but there's a few space tiles on Atlas. This removes them.
Space tiles bad
fix: Atlas no longer has space tiles in its maints
/:cl:
> Urgent: Removes space tiles from Atlas

- code/modules/food/food/snacks.dm
1. **Adjusts Openable Snack Traits.**
1. _Somehow, Palpatine came back. I mean, uh, somehow fruits and grown snacks were being affected by the openable trait. I'm not exactly sure how that happened, since I didn't subtype them at all. However upon review and discussion with Kev, we decided not to tie Opening into the open container flag for foods at all. So I've reworked the proc to just check for a sealed variable._
:cl:
fix: Fixes Openable Snack Traits Passing to Fruit
/:cl:
> Fixes Openable Snack Traits Passing to Fruit

- code/game/mecha/components/actuators.dm
- code/game/mecha/components/armor.dm
- code/game/mecha/components/electrical.dm
- code/game/mecha/components/hull.dm
- code/game/mecha/components/lifesupport.dm
1. **Mecha Components Can Now Be Recycled via Autolathe.**
1. _I'm tired of mecha components just taking up space as total junk. Now they can be recycled via the Autolathe for 50% value._
:cl:
tweak: Makes Mecha Components Recyclable
/:cl:
> Makes Mecha Components Recyclable

- code/modules/atmospherics/gasmixtures/gas_types/core.dm
Sets the max1 threshold for phoron to 0.25, making air alarms not freak out at the tiniest amount of the gas
Vox breathing and solved air crises won't permanently make a room orange atmos alert
:cl:
fix: Air Alarms no longer freak out at infinitesimally small amounts of phoron
/:cl:
> Makes air alarms tolerate tiny amounts of phoron

- code/game/objects/items/toys.dm
1. **Fixes Toy Sword Icon and Rewrites Procs to use E-Sword.**
1. _The toy sword off icon was broken, so I looked into it and it's using an outdated sprite name. So I changed it, but then I looked over the proc, and I realized it would be more fun if the toy sword had some of the real one's traits - like the rainbow thing if you multitool it, and alt-click color change support. So I started adding those, but I didn't like putting all of it in one attack_self proc, so I've instead just cloned over the procs from the esword and adjusted them to suit the toy instead!_
:cl:
fix: Fixes broken toy sword icon and changes its procs.
/:cl:
> Fixes Toy Sword Icon & Rewrites It to Use E-Sword Procs.

- code/modules/mob/say_vr.dm
not everyone has 20 WIS with a perception advantage to notice tiny things happening 7 tiles away
:cl:
tweak:subtler notif now happens at 3 tiles not all of the screen
/:cl:
> adds a range (3 tiles) to subtle notification message

- maps/rift/levels/rift-02-underground2.dmm
- maps/rift/levels/rift-04-surface1.dmm
Moves the APC for lower medbay maints to where there's actually a power line and gives it a wire node. Additionally gives the CE and CMO offices a request console so they can make announcements from their respective desks.
Fixes a couple minor issues with Atlas
Fix: Lower Medbay Maints has power now on Atlas
Add: CE and CMO have request consoles in their office now on Atlas
/:cl:
> Connects Lower Medbay Maint, adds CE/CMO request consoles

- maps/triumph/levels/deck1.dmm
Gives the SMES room in engineering on the Triumph the wiring needed to more easily add more SMESes, like the Atlas does. Also makes that flooring catwalks so the wiring is more visible.
The setup of the engine room makes it a pain to add more SMESes, especially if someone else first built a single SMES and you want to add a second. This makes it easier.
:cl:
tweak: Make the wiring in the SMES room on Triumph easier for adding additional SMESEs.
/:cl:
> Gives the Triumph SMES room expansion wires

- code/__DEFINES/fishing/fishing.dm
- code/modules/fishing/equipment/hook.dm
As title. Approximately half of the fish weren't actually being counted as fish.
It makes sense that trout, pike, etc. are fish
:cl:
fix: A few more fish actually count as fish
/:cl:
> Makes more fish count as fish for fishing

- code/modules/atmospherics/gasmixtures/gas_mixture.dm
Exactly what it says on the tin. Gas analyzers will now show the volume of what they're analyzing
Knowing the volume is often helpful for atmos, it's the one major variable we can't easily see.
add: Gas analyzers show the volume of gas in what they scan.
/:cl:
> Make gas analyzers show volume

- code/modules/power/smes/smes.dm
- maps/rift/levels/rift-03-underground1.dmm
- maps/tether/levels/surface2.dmm
- maps/triumph/levels/deck1.dmm
Give the tcomms substations with power in them to start, as well as breakers that start deactivated. This means that the comms will run for about 1 hour even if nobody starts power immediately. While I did adjust the Tether tcomms, this PR was not actually tested there since it isn't a server we currently run, I just didn't want to leave it behind on this particular change. The power usage (and therefore expected uptime) there should be similar.
People shouldn't be rendered unable to communicate over radio within 5 minutes of roundstart because engineers aren't around or aren't capable of immediately generating power. This gives the facility about an hour of leeway before the comms die, making it still important to get main power running but not something that's going to immediately …
> Gives the tcomms substations starting power

- code/modules/loadout/loadout_role_restricted.dm
- code/modules/loadout/loadout_xeno.dm
Senior engineer isn't allowed any station engineer/atmos tech-specific items (that is, items specific to just those two); this fixes that
This was probably intended in the first place, so I'll say "bug fix"
:cl:
fix: Gives senior engineers access to some missing engineer loadout entries
/:cl:
> Gives senior engineer access to some loadout entries

- code/modules/jobs/job_types/station/command/captain.dm
This PR directly reverts #6056's changes to the Facility Director (i.e. renaming the default title to Captain, among a couple other things). This fixes a bug where none of the FD-specific loadout items could be equipped even as the Captain, as those items were checking for the "Facility Director" title, not the "Captain" title. (Alt-titles don't count toward this.) This same bug may be present in other jobs that have had their default titles changed, but that is beyond the scope of this PR.
This PR has been tested locally.
Nothing else in the community (i.e. the wiki or other parts of the code) have been updated to reflect this sudden change to the default title of the head of the facility, so I think that should be taken care of first/at the same time. In addition, the bug that I am …
> Reverts 6056's changes to Facility Director

- code/datums/recipe/crafting_recipes/recipes_primal.dm
1. **Makes the Bone Knife Craftable.**
1. _Someone pointed out to me that this was missing from the list! Gonna add it to the general crafting lift for primal recipes._
:cl:
add: Adds bone knife to crafting menu.
/:cl:
> Makes the Bone Knife Craftable

- code/modules/power/smes/smes.dm
Exactly what it says on the tin. Makes the tcomms SMES start with input turned on so that it can utilize secondary power sources without engineering being present. This will increase the time before tcomms runs out of power but decrease the time for the rest of the station (since it's pulling in a consistent 100kW)
Apparently folks on shifts without engineering were having power in tcomms run out before the rest of the station because the SMES wasn't charging and tcomms was segregated from the rest of the grid.
:cl:
tweak: tcomms SMESes now start with input toggled on
/:cl:
> Makes the Tcomms SMES start with input on

- code/game/atoms/say.dm
-Fixes atom_say() scrambling all messages when a language datum is input. Mobs will now receive the correct message if they understand the language and not the gibberish version.
Fixing bugs is good.
I need this to work for multi-lingual televisions.
-Fixes atom_say() scrambling all messages when a language datum is input. Mobs will now receive the correct message if they understand the language and not the gibberish version.
:cl: _Shadowcat_
fix: fixed atom_say() language input fluency
/:cl:
> Fixes fluency error in atom_say() proc

- code/modules/atmospherics/machinery/portable/powered.dm
It didn't check for if there's actually a cell.
runtimes bad
:cl:
fix: Powered atmos machines now check if there's a cell before trying to drain it
/:cl:
> Fixes a runtime in powered atmos machines

- code/modules/mob/living/simple_mob/subtypes/animal/sif/racoon.dm
- code/modules/tables/presets.dm
- maps/rift/levels/rift-04-surface1.dmm
- maps/rift/levels/rift-05-surface2.dmm
- maps/rift/levels/rift-06-surface3.dmm
1. **Fixes Directional Sprites for Cameras, Vendors, and Fire Alarms.**
2. **Adds Dexter, the Xenobio Pet.**
3. **Adds Carbon Table Presets.**
1. _These off-direction sprites have been driving me crazy.._
2. _This cute little guy got spawned from a gold slime just today, and everyone loved him so much I decided to make him a permanent pet for Xenobio._
3. _Adds carbon table presets because I like the black on white look._
:cl:
fix: Fixes mislaid directional sprites.
add: Adds Dexter, a pet for Xenobio.
add: Adds carbon table presets.
/:cl:
> Fixes Mapped Directional Sprites, Adds Pet, General Mapping Bug Fixes

- maps/templates/shuttles/overmaps/generic/curashuttle.dmm
- maps/templates/shuttles/overmaps/generic/mercship.dmm
- maps/templates/shuttles/overmaps/generic/vespa.dmm
1. **Remaps Alarms on Multiple Shuttle Submaps.**
1. _Some shuttle submaps are not using hidden alarms. This is gonna take a little live testing and stuff._
:cl:
fix: Replaces shuttle submap alarms with hidden variants.
/:cl:
> Adjusts Alarms on Shuttles

- code/modules/loadout/loadout_role_restricted.dm
- code/modules/loadout/loadout_utility.dm
Puts all the missing backpacks (default versions) into the utility tab for matrix recoloring. Equipping a backpack from the loadout and setting yourself to spawn with the same backpack in the main screen will overwrite, and autoequip the backpack+equipment.
Adds security backpack to role restricted section.
You can now matrix default backpacks automatically at round start.
I would have just made it a selection for all types, but there are some that aren't meant to be accessed based on role and faction. I don't want to bloat the role restricted section THAT much, yet.
> Backpacks in Loadout

- code/game/objects/items/storage/medical/hypokit.dm
Makes hypokits able to be put on the belt slot
First aid kits already do this. If we were worried about abuse via belt storage we'd prevent kits from accepting vials.
> Hypokit placeable on Belt Slot

- code/modules/mob/inventory/inventory.dm
- code/modules/mob/inventory/items.dm
- code/modules/mob/inventory/slot_meta.dm
- fixes some grammar issues with nodrop
- fixes messages for 'reconsider xyz' calls
> minor inv fixes

- code/modules/food/food/snacks.dm
1. **Removes Carpotoxin from Fish-Based Dishes.**
1. _It's easy to forget about this and poison the crew. Carpotoxin in these foods made sense when we only had poisonous space carp, but now that we have a broad fishing system it doesn't do anything for us to have noob trap food items on the menu._
:cl:
del: Removes carpotoxin from fish-based dishes.
/:cl:
> Removes Carpotoxin from Fish-Based Dishes

- code/game/objects/structures/window.dm
Reverts the change from #5235 that makes reinforced windows drop metal rods.
Reinforced glass involves metal rods, this is true, but deconstructing reinforced windows gives you 100% of the reinforced glass back already. The extra metal rods are free, you can just generate infinite rods this way. No need for 'em.
:cl:
fix: Deconstructing reinforced windows no longer gives free rods
/:cl:
> Reverts reinforced windows dropping metal rods

- code/game/dna/dna2.dm
Genetics DNA bounds were improperly set.
See line 499 for why this is a problem.
This is the reason why toggling genetics powers in the admin player panel sometimes fails to toggle to on, as well as some other grievances.
> Byond lists start at 1

- code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
Increases the charge gained from Borg'Os from 250w to 1kw
250w is roughly 1.6% of a cyborg's starting cell of 15kw, which is basically nothing. I wanted to at least make the borg specialty kibble do something without making it super good at charging cell. I think 6% of the base cell is good enough without being OP.
:cl:
tweak: Increased the charge gained by cyborgs for Borg'Os
:cl:
> Buffs Borg'Os

- code/modules/mob/observer/mobility.dm
>be a ghost
>pixelshift
>living people cant go past you now
there's no actual reason anything should be stopped by a ghost so it's better to let this always return true
fixes a bug
:cl:
fix: makes it so you can always move through ghosts
/:cl:
> makes it so you can always move through ghosts

- code/game/objects/items/storage/backpack.dm
Title
They weren't meant to weigh you down. Recent encumbrance changes made it so this actually was done. This fixes that.
:cl:
fix: Black duffelbag encumbrance is now their proper amount.
/:cl:
> Fixes black duffelbags not being lightweight

- code/modules/food/kitchen/smartfridge.dm
title
i don't like how drying racks work but that's not the point of this PR
fixes a bug
:cl:
fix: stop drying racks taking more than one sheet of leather at a time
:cl:
> stop drying racks taking more than one sheet of leather at a time

- code/__DEFINES/inventory/carry_weight.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/mob/living/carbon/human/movement.dm
- code/modules/species/station/alraune.dm
- code/modules/species/station/diona.dm
- Alraune and Diona are given physiologies that improves their carrying strength and reduces their penalty for items they're carrying. This is mostly consistent with the item_slowdown_mod mechanic that they used to have.
- Alraune now have a reduced penalty for moving in water and snow. Combined with winter boots or swimming fins, this penalty is negated in light snow, and shallow water. This is consistent with how the diona's penalties are negated in these same areas.
- Winter boots were meant to reduce slowdown when walking in snow. However, someone fucked up somewhere. This PR fixes that.
- Additionally, the swimming fins have been buffed to reduce slowdown in water. They're fucking flippers. Yes, this also means the Skrell and Akula, who have reduced slowdown in water, outright gets a …
> Adds plantpeople physiologies, buffs alraune in snow and water turfs, turf slowdown fixes & additions

- code/modules/atmospherics/machinery/components/binary_devices/heat_pump.dm
For some reason I can't build on my system anymore so I can't test this locally or else I would. It's annoying.
This changes two things about heat pumps:
1. As their efficiency decreases, they don't only heat partway to their goal--they'll use more power to reach their goal, up to their standard cap. This leads to identical behavior if you're trying to superheat with them (i.e. set their temperature to either cap) but much "nicer" behavior if both sides are close in temperature. This is a buff to their actual usability but a nerf to their power usage.
2. Heat pumps now try to heat the *entire target network* to the given temperature instead of just the output air of the heat pump itself, much like passive gates. This should make them much more capable of actually reaching the target …
> Heat pump rebalance (TESTMERGE)

- code/game/objects/structures/trash_pile.dm
makes it so that trashpiles flip a coin on whether or not to have a mouse spawner.
Honestly mice are hardly any use in game, aside from the rare character eating them, and the occasional griefer throwing tonnes of them into the bar after storing them in backpacks.
Additional I dislike the constant squeeking trying to walk through maint.
:cl:
tweak: tweaked trash piles to not always spawn mice
/:cl:
> Reduce the amount of mobspawners in trashpiles by 50%

- code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
- code/modules/mob/living/bot/SLed209bot.dm
- code/modules/mob/living/bot/cleanbot.dm
- code/modules/mob/living/bot/floorbot.dm
- code/modules/mob/living/bot/secbot.dm
- Security-type bots will check for a human's inability to act rather than a human laying down before cuffing the human. Resting humans can still crawl around after all.
- Slime securitrons will no longer beat slimes until they're dead. Fucking abusive as hell lab assistant.
- Cleanbots will actually properly remove dirt rating from turfs.
- Floorbots can now be constructed fully again.
- You can turn off bridge mode on Floorbots.
It's worth noting that floorbots are a little scuffed right now and need more fixes than this, but this would be the first few steps to fixing them.
Fixes good.
:cl:
fix: People can no longer exploit security bots by laying on the floor. They WILL ensure your compliance.
fix: Slime securitrons and their bigger brother will stop beating slimes after they've …
> A few fixes for bots

- code/modules/admin/verbs/smite.dm
10 seconds is a bit unelastic
:cl:
admin: The autosave smite now takes a duration input.
/:cl:
> Autosave duration is now configureable

- code/modules/power/cell.dm
- code/modules/power/powernet.dm
TL;DR
Shock damage being an RnG value hard capped at 1MW with "jumps" in damage at certain breakpoints was weird so I smoothed out the math. Overall, damage is uncapped but does a little less damage.
Extended answer:
The old method returns burn damage to the victim in a series of five "tiers" based on the available power at the time.
These tiers roll a random with disadvantage, the thresholds in question were as follows:
Note that these values are rolled with disadvantage.
1kW to 50kw = 10-20
50kW to 100kW = 15-40
100kW to 200kW = 20-60
200kW to 1MW = 25-80
1MW+ = 50-160
I've replaced the math with a logarithmic that looks like this
burn damage = log(1.1, power) - log(1.1, (log(1.1, power)*1.5))
which results in a smoothed out damage curve with a plateau around 1MW, as follows:
1kW = 5 …
> Replaces the RnG of electric shocks with a more sane calculation

- code/game/click/observer.dm
- code/game/objects/items/devices/paicard.dm
the role you can set in character setup doesn't seem like it has a real use but if anyone badly wants it to show on examine i can do that
ease of use, plus having descriptions on pAIs is nice as you can give a bit of a visual description to differentiate them
:cl:
add: when loading into a pAI card you can now choose to use a saved name and description
/:cl:
> when loading into a pAI card you can now choose to use a saved name and description

- maps/triumph/levels/deck1.dmm
minus ce because that is sorta-kinda one of a kind (atleast before cargo gets their hands on stuff)
> removes access locks from engi rigsuits on triumph

- code/modules/food/food/snacks.dm
Wasabi contains no capsaicin. Its heat-inducing ingredient is [allyl isothiocyanate](https://en.wikipedia.org/wiki/Allyl_isothiocyanate).
We don't have that, so I'm keeping capsaicin as the literal ingredient for the pain-causing. But still. It shouldn't be explicitly listed as a taste.
My immersion !
:cl:
tweak: Wasabi peas no longer taste like "capsaicin"
/:cl:
> Replaces "capsaicin" with "wasabi" in wasabi peas' taste description

- code/modules/species/station/xenochimera.dm
Gives xenochimeras the /mob/living/proc/set_size verb, allowing them to switch sizes as if they had the Sizeshift trait.
It definitely feels like something that can be reasonably explained in the lore, as chimeras can manipulate their own mass pretty competently already. I would've liked to implement a nutrition cost system on positive size alteration, but I'm not skilled enough to pull that off.
:cl:
tweak: Added set_size to xenochimeras
/:cl:
> Gives xenochimeras set_size

- code/__HELPERS/global_lists.dm
- code/modules/mob/living/carbon/human/traits/negative.dm
- code/modules/preferences/preference_setup/vore/08_traits.dm
Self-explanatory PR. Ya no longer need to be a custom species to take negative traits!
There's a few extra changes in here, as well. Notably, the trait selector will no longer show you traits that are exclusive to certain species if you are not that species (like the shadekin traits, for instance). Additionally, being a non-custom species will simplify the "neutral traits" button to just "traits", with the selector having both neutral and negative traits merged together.
As a treat, we've also gone the extra mile and made four negative traits available to all: monochromancy, blindness, deafness, and muteness.
Some negative traits, especially notably the disabilities, can make for genuinely interesting RP in some cases! So this makes a few directly available, and makes it *much* easier to …
> Allows negative traits to be available for everyone (+ makes a few disabilities available to all + related tweaks)

- code/modules/food/food/snacks.dm
As title. Right now, if you use a small-enough item on any slicable food, you hide the item in the food, gone until it's sliced or eaten. This feature basically only exists to be annoying and, I assume, for "slip the prisoner breakout tools" meme. The former's bad and the latter's very, very rare. This adds a confirmation to it.
Making a super annoying feature much, much less annoying
:cl:
qol: There is now a prompt before you try to hide something in food
/:cl:
> Adds a confirmation prompt for hiding items in food

- code/modules/mob/living/silicon/robot/robot.dm
Adds a verb to borgs allowing them to lock/unlock their own covers
I was told this is a salt PR. I think there might be legitimate reasons to only allow roboticists/emags to do it, so I don't know if it's good for the game, actually. But I was told to salt PR it, so I did.
:cl:
add: Cover lock/unlock verb for borgs
/:cl:
> Toggle cover verb for borgs

- code/game/machinery/doors/airlock/phoronlocks.dm
Title.
22C is too hot for comfort for some species and the phoronlock heaters are so incredibly powerful that they inevitably heat the entire station to their temperature, and it really doesn't take long to do so. This is above the comfort point for some species, so this is an annoyance.
Plus, it being 22C doesn't make it work faster or better or anything. It's pointless. It runs at max power until it reaches the target temperature anyway. Turning up the thermostat to make it heat faster doesn't work in real life or in-game, sorry.
:cl:
tweak: Phoronlock heaters go to 20 instead of 22
/:cl:
> Makes phoronlocks go to 20C instead of 22

- maps/rift/levels/rift-05-surface2.dmm
Space saved: 2 tiles vertical, 4 tiles horizontal. 
Removes two of the six spaces for fighters. 
Removes the refillable air canister.
> Shrinking the hammerhead (slightly)

- code/modules/clothing/under/accessories/armor.dm
Totally fixes a game breaking issue.
They're blue not red, clearly that's why redshields are a thing
:cl:
tweak: Changes the blueshield tag from 'red' to 'blue'
/:cl:
> Fixes blueshields being red

- citadel.dme
- code/__DEFINES/ability.dm
- code/datums/ability.dm
- code/datums/ability_handler.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_defines.dm
- code/modules/species/species.dm
- code/modules/species/station/xenochimera.dm
Adds a way for abilities to be targetable, including range.
Currently works using a carbon/human datum that is used as a middleman between the abilities and the clicks. Currently no ability uses it.
Ability versatility! 
:cl:
add: Ability targeting
/:cl:
> Adds Ability targeting

- config_static/jukebox.json
Adds ["Hush (ft. Mizz Fish)" by kroh](https://www.youtube.com/watch?v=Qflixb8ss3Q) to the hacked jukebox songs, under the Electronic tab. It's a secret song since the lyrics directly reference the Syndicate (although it's not actually technically our Syndicate), so probably not NT-approved.
It's a cool song. Also the syndicate reference is kind of on the nose.
> Adds "Hush (ft. Mizz Fish") by kroh to the hacked jukebox songs

- code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
Adds the following to the engineering points vendor (crypto thing):
1. Vodka
Removes the following:
1. Whiskey
2. Absinthe
3. Special blend whiskey
4. Random booze
5. Injector (L) - Glucose
6. Injector (L) - Trauma
7. Nanopaste tube
1-4 are because it's kiiinda immersion-shattering that you're explicitly operating heavy equipment and dangerous gases to be able to buy strong alcohol, which the dang regulations say you're not allowed to use on-duty. 5-7 are because they're *really* obviously geared for miners: engineers don't really have any use for any of that.
**However**, vodka replaced the boozes, because it has the rad cure element. That's at least a *little* flavorful. 
Clutter removal, making it less obvious that the engineering points vendor is a copy+pasted mining points vendor …
> Changes around some engi points vendor options

- code/game/objects/items/weapons/candle.dm
- code/game/objects/items/weapons/nullrod.dm
1. **Reassigns Updated Sharp/Edge Stats to Null Rod Variants.**
2. **Fixes Names for Colored Everburn Candles.**
1. _There was an edged weapon refactor and nullrod variants were missed in the editing. This updates the relevant weapons to match the new flags._
2. _Black and white everburn candles have been wrongly named red for a while._
:cl:
fix: Updates damage flags for nullrod variants.
fix: Fixes names of black and white everburn candles.
/:cl:
> Minor Fixes to Chaplain Equipment

- code/modules/mob/living/simple_mob/subtypes/lavaland/stormdrifter.dm
1. **Fixes Stormdrifter Bull Melee Immunity Bug.**
1. _When Stormdrifter Bulls were coded to become rideable, I forgot to set up the check so that it passed into a normal attack if conditions were properly met. This led to Stormdrifter Bulls becoming unkillable in melee, as you would simply attempt to amputate their tendrils over and over. I have now fixed the issue._
:cl:
fix: Stormdrifter Bulls are no longer immune to melee.
/:cl:
> Fixes Stormdrifter Bull Melee Immunity Bug

- code/modules/mob/living/carbon/human/traits/positive.dm
- code/modules/species/species_attack.dm
This PR resolves the issue of the traits attacks not applying as well rebalancing them to be a meaningful change.
As for the reason as to why: A basic human attack does 5 to 10 damage. A claw attack does 5 damage. A sharp bite does 3 damage. The numbing bite injects ~2.5 numbying enzyme per hit with 20 being the OD
So not only would it mean that spending 1 point on sharp attacks would actually nerf you. But also if you went the extra mile to take the numbing bite, it would take roughly 8 hits just to reach the OD threshold. A mere toolbox does 10 damage already, a welder even 15. So you would be able to put someone into crit with just 7 hits using a welder. Making the whole trait obsolete by the most basic items.
Instead I have given claws and bites a fixed damage number of 10 with a …
> Melee trait fix and balance

- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
Before: strength of the booze didn't matter, just how much you took, and damage went up quadratically with dose. This was mostly because I didn't understand how the actual dose system worked, ha.
After: damage is 50*species mod*amount metabolized/strength. This is balanced around 1 tox damage per unit of beer; you get 5x as much from deathbell, 3.333... times as much from vodka, and so on.
It rarely, if ever, comes into effect, but it's best that it acts in a way that's predictable.
:cl:
tweak: Alcohol intolerance damage now makes more sense
/:cl:
> Makes intolerance values way more "logical", easier to follow

- code/game/objects/structures/tables/flipping.dm
Title
Table unflipping failing should fail to unflip the table
:cl:
fix: Table unflipping now fails if it fails
/:cl:
> Makes table unflipping actually fail if it fails

- maps/sectors/tradeport_192/levels/tradeport_192.dmm
I'm swinging back into playing and that means more tradeport edits. This fixes some outdated junk items on the tradeship like suit cyclers and floor tiles that permanently stain reality red.
This purely benefits trader gameplay. Entirely a self motivated PR with zero real effect on the rest of the game proper.
Shadow Trader Money Gang
-Replaces old_cargo red floors that would stain space with a red tint forever with similar functional tiles that dont do that.
-Removes old suit cyclers and replaces with lockers (Old suit cyclers are invulnerable and cannot be deconstructed, also allows easier access to two tables now due to room geometry) 
-Swaps the supermatter coin case and the fullbody agent suit tie so people can see it exists. 
-Adds another poster for the future station ad revenue …
> Minor Tradeport Fixes.

- code/game/turfs/simulated/floor_types/water.dm
Title
Swimming pools being stocked with fish is silly
:cl:
fix: Swimming pools can no longer be fished in
/:cl:
> Fixes fishing in pools

- code/modules/food/food/snacks.dm
Alcohol's only going to be in beer batter if it's literally raw. It's not gonna taste alcoholic, come on.
My immersion
:cl:
spellcheck: "Alcoholic" changed to "yeasty"
/:cl:
> Makes beer batter shrooms not "alcoholic" tasting

- code/game/mecha/combat/fighter.dm
- code/game/turfs/simulated/wall_types/wall_types.dm
- code/modules/power/apc.dm
- code/modules/power/lighting/lighting.dm
- maps/rift/levels/rift-05-surface2.dmm
Redesigns the hammerhead somewhat to be more like a patrol and response carrier, with a more streamlined design for carrying personnel and detainees. 
Brings the Rift to parity with other maps for security EVA by replacing the spare security officer lockers in EVA storage with an additional security voidsuit and two hazard rigs, plus a hazard rig in the HoS' office.
Increases the Baron's integrity by 200 (from 400 to 600) to offset the damage impacting a wall causes (which is the only way to stop in space currently), and increases the Duke's integrity by 400 to match the intended double armour value.
:cl:
tweak: Redesigned the Hammerhead Patrol Barge
tweak: Increased armour values for the Baron and Duke space fighters
balance: Added an additional voidsuit and three hazard rigs to security …
> Hammerhead Upgrade + Rigsuits + Baron Integrity Increase

- code/game/objects/items/weapons/melee/energy.dm
Darth Maul didnt trip when he did his spinning. We shouldnt either. Its dumb.
Also TG fixed this ages ago when the flip had a chance to fail. Dual eswords here are not nearly as strong as they are on TG.
Should (TM) remove the pointless flip. 
Fixes dual esword users (as rare as they are cause there are better alternatives) being massive bottoms and accidentally tripping on accident infront of the enemy leaving them in a compromising position.
Randomly getting stunned is not fun. Randomly getting stunned because you faced west randomly due to a proc that is running isnt fun at all since you have zero way to counter it other than picking more viable alternatives. This should diversify weapon choice for both event characters and in the off chance somebody uses a dual chargeblade for …
> Stops dual esword users from accidentally tripping on accident infront of the enemy

- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
As title. Twice as strong injected than ingested, since that feels it ought to be worse.
Weird quadratic damage uncorrelated with actual amount of alcohol is weird
:cl:
fix: Alcohol intolerance is now consistent between injection/ingestion
/:cl:
> Makes alcohol intolerance work properly with blood

- code/game/objects/items/id_cards/station_ids.dm
- code/game/objects/structures/crates_lockers/closets/secure/genpop.dm
:cl:
qol: made the genpop lockers use tgui inputs when setting up prisoner IDs
fix: fixed prisoner IDs missing the GENPOP_ENTRY access
/:cl:
> fixes prisoner IDs not having genpop entry permissions

- code/game/objects/effects/debris/cleanable/blood.dm
- code/modules/mapping/submaps_legacy.dm
- code/modules/maps/overmap/space/debrisfield.dm
- maps/sectors/miaphus_192/levels/miaphus_192_beach.dmm
- maps/submaps/level_specific/debrisfield_vr/debris14.dmm
Fixes a couple runtimes that frequently occure during IntTests
:cl:
fix: fixes wrong fake stairs on miaphus beach
fix: fixes duplicate lattice on debris14.dmm
fix: adds extra check to submap seeding, checking if the tiles are empty
fix: adds check when adding blood writing, to make sure we arent using to many instances per tile
fix: fix rename_areas for the tiny carrier should happen during lateload to avoid not finding the shuttle
/:cl:
> fixes wrong fake stairs on miaphus beach

- code/modules/vehicles_legacy/skateboard.dm
Updates skateboard injuries after discussion. If you crash, you now receive some surface injuries regardless. If you are not wearing a helmet, you will receive minor brain damage from knocking your head around, and there is a 5% chance to suffer a severe head injury (your skull automatically fractures and you receive significant brain trauma).
hehe funny skaetberd
:cl:
tweak: Crashing on a skateboard without proper protection is now much more dangerous.
/:cl:
> Update skateboard injuries

- code/game/objects/items/id_cards/station_ids.dm
Fixes some typos and moves the sentence description to within the examine box, and puts it at the bottom. Having it at the top makes it harder to read and easier to miss.
sentance
:cl:
tweak: Minor improvements to the way prisoner IDs look when examined.
/:cl:
> Minor update to prisoner IDs

- maps/rift/levels/rift-03-underground1.dmm
- maps/rift/levels/rift-04-surface1.dmm
- maps/rift/levels/rift-05-surface2.dmm
Fixes a disposal chute in processing.
Localized entirely within genpop:
Removes airlock next to genpop watchtower.
Adds more fire extinguishers/alarms.
Fixes some spline.
Adds cards/dice to table.
Adds 2 sets of vent/scrubbers to top floor and bottom floor, one per.
Replaced glass cell doors with solid steel.
> genpop QOL updates

- code/game/verbs/suicide.dm
remove's pAI suicide verb because they already have the wipe-software verb which handles pAI 'suicide' properly
fixes a bug by just removing the verb causing the issue
we don't need two verbs for this
:cl:
fix: remove's pAI suicide verb because they already have the wipe-software verb which handles pAI 'suicide' properly
/:cl:
> remove's pAI suicide verb because they already have the wipe-software verb which handles pAI 'suicide' properly

- citadel.dme
- code/__DEFINES/rendering/zmimic.dm
- code/controllers/subsystem/zcopy.dm
- code/game/atoms/movable/movement.dm
- code/modules/admin/verbs/mapping.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/multiz/turf.dm
- code/modules/multiz/turfs/open.dm
- code/modules/multiz/zmimic/mimic_movable.dm
- code/modules/multiz/zmimic/mimic_turf.dm
This is largely just synchronizing ZM with the latest upstream version, though I also renamed SSzmimic to make updates like this easier.
Changes:
- It is no longer possible to outrun Z-Mimic, except now without the cost of doubling ZM init time.
- `ZMM_LOOKBESIDE` is now supported to handle wide mobs as well as long mobs. Use `ZMM_WIDE_LOAD` for both wide and long, such as scaled up atoms.
- It is now possible for a turf to override its Z-Mimic appearance.
- `MZ_TERMINATOR` can now be specified to cause a turf to act as the bottom of a ZM stack. 
- `MZ_NO_SHADOW` can be specified to opt out of Z-M's darkening effect, though lighting copy and AO are still active.
- Some bugs in layering caused by atoms moving up or down z-levels have been fixed.
- Z-Mimic now has a basic performance …
> Z-Mimic Season Pass 1

- code/modules/lore_hardcoded/citizenship.dm
- code/modules/lore_hardcoded/origin.dm
- code/modules/lore_hardcoded/religion.dm
Adds Altam (the homeworld of the vulpkanin) as an origin under the misc tab, the Vulpkanin United Star as a citizenship option, and Alverrtcheff as a religion option under the misc tab.
Currently this is not species-locked and anyone can pick it.
Races having their lore represented in-game is a good thing
:cl:
add: Added new background options for the Vulpkanin.
/:cl:
> Add vulpkanin background info

- maps/triumph/levels/deck3.dmm
"Re"-adds the medical hardsuit to the spare rack in the triumph's emt bay even though it looks like there never was one there.
The Mandela effect is strong
:cl:
add: Added a medical hardsuit to the Triumph's EMT bay.
/:cl:
> "Re"adds medical hardsuit to triumph

- code/modules/reagents/Drink-Recipes.dm
Gin Fizz and Gimlet had the exact same recipe (`"gin" = 1, "sodawater" = 1, "limejuice" = 1`). Gimlet's recipe now is `"gin" = 1, "limejuice" = 1, "sugar" = 1` because it made sense. And because I saw on the internet that sugar goes with it. I don't drink. I don't even know what gimlet is, I just looked it up
Fixes #6264 
:cl:
fix: Gimlet can actually be made now, since it doesn't share the same recipe as Gin Fizz anymore.
/:cl:
> Fixes gimlet recipe

- code/modules/mob/living/carbon/human/blood.dm
If you remove all of someone's blood, they no longer have blood. At all. Ever. It's gone. You cannot add it back.
this bug has existed for 6 years
:cl:
fix: Blood added with IV to bloodless people that should have blood no longer disappears into the aether never to be seen again
/:cl:
> Makes exsanguination not make blood uninjectable

- code/modules/maps/overmap/space/trade_station/trade_station.dm
- maps/sectors/tradeport/shuttles.dm
- maps/sectors/tradeport_192/levels/tradeport_192.dmm
-Fixes explo shuttle being unable to dock with Nebula Gas (Oopsies)
-Adjusts the docks to allow all default spawn shuttles on Triumph and Atlas to dock with at least 1 hanger at Nebula Gas.
-Swaps out the Beruangs walls for shuttle rwalls since I'm here touching the map.
-Adds a crate of assorted carpets and a few 50 stacks of basic materials to the warehouse so Traders can drip out their ship.
The suffering of Pathfinders will now end. Exploration can purchase phoron and cheesy honkers from the gas station once again.
Also everyone else can go to the gas station now.
-Fixes explo shuttle being unable to dock with Nebula Gas.
-Adjusts the docks to allow all default spawn shuttles on Triumph and Atlas to dock with at least 1 hanger at Nebula Gas.
-Swaps out the Beruangs walls for shuttle …
> Fixes Nebula Docking issues.

- code/modules/organs/external/species/slime.dm
- code/modules/species/promethean/promethean.dm
1. removes the inexplicable speed increase and item...not-slowdown, from prommies
2. nerfs their limb hp **(~~literally arbitrary placeholder values picked for rn til people come up with a comfy number, i think somewhere from 25 to 30 feels good and hits a good threshhold but who knows.~~) 25 is probably good**
we already spent a long time talking on discord about this but the tl;dr is that promethean is a really, really strong species at base, and has the added benefit of not suffering from baymed. 
event managers have expressed a bit of frustration at how strong the species is and i also agree w/ it. this is what was eventually settled on, while people work on adding other stuff to them in the background. (i think them having pain would also be cool since they're literally a fully …
> promethean number tweaks

- maps/rift/levels/rift-09-west_caves.dmm
as the above. is now 2 scanners normally named and an IC note w/ more instruction
one of these scanners was just named 'Craft me!' with 0 elaboration, at best seemed a little unintuitive and ooc.
yeah.
:cl:
tweak: scannernotethingatlas
/:cl:
> removes weird ooc 'Craft me!' scanner module in atlas geothermal, replaces with note

- code/modules/hydroponics/spreading/spreading_growth.dm
As title. Right now it does that. This still sorta does that but it just sorta destroys vines if there's more than one on the same tile.
I tried testing this but my computer bluescreened so uhh. Testmerge wisely.
Infinite vines instantly killing people is... bad, actually.
:cl:
fix: No more infinite funny vine stacks
/:cl:
> Prevents vines from infinitely spreading from below

- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
As title. Was 10% per 5 minutes (>50% every 35 minutes), now 1% per 5 minutes (>50% every 345 minutes).
Paroxetine is the strongest hallucinogen in the game. This is not an exaggeration: the supermatter caps at the amount paroxetine _adds_. An exploding supermatter is more powerful, but only _if you're on top of it_. Putting _supermatter into the R-UST_ causes less hallucinations.
I think this is appropriate given the flavor text, but the chance is way too high right now; there's a 96% chance per (max-length) round of it happening _at least once_, and this reduces it to a mere 24% chance, which is _still_ pretty high, actually.
:cl:
balance: Paroxetine now causes a complete mind-whammy every 6 hours instead of every 30 minutes on average
/:cl:
> Reduces chance of paroxetine hallucination

- code/modules/mob/living/carbon/carbon_defense.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/organs/external/external.dm
- code/modules/organs/subtypes/nano.dm
- code/modules/power/cell.dm
- code/modules/projectiles/projectile/special.dm
- code/modules/species/protean/protean.dm
- code/modules/species/protean/protean_blob.dm
here i go again
- emps once again hit everything in someone (lessening in severity for things inside backpacks)
- emps no longer entirely annihilate cells like before
- non-synths can now be emp'd properly
- protean blob speed scaling and attack speed scaling changed yet again 
- protean values are tweaked to be more consistent (3 shot blob, 1-2 shot cripple + limb explosion with ion, 1-2 sev 1 emps to fully cripple)
the proper emp rework will come soon (tm)
> fixes emps, tweaks protean balancing number sagain

- code/modules/organs/external/subtypes/standard.dm
Exploding a person will delete their head before their hair causing a null access runtime.
Removes a spawn(1) that makes a check stale.
Maybe Testmerge this first. I don't think this should cause any problems but I know some icon ops need a delay to work?
Blowing heads without error is a critical citadel feature.
-Deletes apparently pointless and buggy spawn(1) delay
:cl: Shadowcat
fix: fixes a runtime in the cleanup code for exploding carbon mobs
/:cl:
> Blowing your head no longer runtimes the server

- code/modules/vore/fluffstuff/custom_guns.dm
fixes improperly set unloaded icon for the JSDF rifle
things should work
:cl:
fix: fixed JSDF rifle unloaded icon state
/:cl:
> JSDF Rifle unloaded state fix

- code/modules/loadout/loadout_general.dm
- code/modules/mob/living/carbon/human/human_organs.dm
As title. This makes it so that a cane/crutch can be used to fully support a one-legged person, instead of requiring two.
If both legs are missing, two crutches still won't be enough. I don't know if that's what the old system was supposed to "fix", but it's trivial to fix if you give it some thought, so I kinda doubt it.
the previous mechanics make amputees literally completely unplayable for no reason
:cl:
balance: Crutches/canes now provide more support
/:cl:
> Makes canes/crutches usable for amputees

- code/datums/sun.dm
- code/modules/power/solar.dm
only tested with the rift with Noon and clear weather where it produced about 280kW
no more pseudo science
probably need to buff solars output a bit
:cl:
tweak: tweaked solars to work off /datum/planet instead of SSSun
/:cl:
> makes Planetary solars use the local time and weather for calculations, instead of some random subsystem in the background

- maps/rift/levels/rift-02-underground2.dmm
Removed two buttons, one that was over a disposal bin in engine monitoring and another that was inside the rock walls deep behind maintenances. Also added an autolathe in tool storage that I requested several times, I used to just build my own until it got too repetitive, and the spot I chose I think it's the best I could choose. I also removed the mass driver. It's a machine that shoots items into space, it doesn't belong on a planetary ground base.
This makes the life of engineers who expand rooms or simply build machinery easier without being slaves to science's whim. It also removes two buttons and a mass driver that existed for no reason, and were mistakes, this is all pretty much another pet peeve of mine.
* Removed shutter button over bin in engine monitoring
* Removed shutter …
> Goodbye Questionable Buttons inside Walls and Bins, Hello Atlas Engineering Autolathe

- code/modules/mob/living/carbon/carbon_movement.dm
- code/modules/mob/living/carbon/human/movement.dm
running still does (same amount as before)
Walking does not get slowed down from hunger
walking around doesnt draw additional hunger
running still does (same amount as before)
Walking does not get slowed down from hunger
:cl:
tweak: tweaked walking to not draw extra nutrition (running still draws the same amount as before)
tweak: tweaked walking to not get slowed down from hunger
/:cl:
> walking around doesnt draw additional hunger

- code/modules/admin/admin.dm
:cl:
admin: Player Notes admin verb now uses tgui_list to  select the ckey to view
/:cl:
> Makes the playernote selection from the player notes admin verb use tgui list selector instead of old browse

- citadel.dme
- code/game/machinery/vending/loadout.dm
- code/modules/clothing/masks/_mask.dm
- code/modules/clothing/masks/breath_warmer.dm
- code/modules/clothing/masks/gasmask.dm
- code/modules/mob/living/carbon/breathe.dm
- code/modules/mob/mob_defines.dm
- maps/rift/levels/rift-04-surface1.dmm
- maps/sectors/frozen_192/levels/frozen_192.dmm
As it says in the title, the heating power of 1kW is picked arbitrary to allow the mask to actually help on atlas atmos, it might be adjusted later to use a more realistic system
We have gas masks that filter hostile gases, why not have one that warms your breath. Now that we spend most of our time on a snowball planet?
:cl:
add: Added new mask for warming breath
code: removes a redundant check in breath code
refactor: renamed the filter_gas() proc on masks to process_air()
/:cl:
> adds a mask that warms breath as you take it

- code/modules/vore/fluffstuff/life_crystals.dm
Title. The life crystal never got set off if the owner ever gets gibbed. This is most common with prometheans, but it can easily apply to anyone else.
Fix man good.
:cl:
fix: Life crystals will now detect owners who vanished out of existence via gibbing or some other means like dusting... provided the crystal survived.
/:cl:
> Fixes life crystals not detecting gibbed owners

- code/modules/reagents/machinery/dispenser/synthesizer.dm
Title
- Water is fucking water.
- You could already make iced tea using a soda dispenser. You can make iced tea using tea and ice with the cafe dispenser. Might as well allow you to skip a step.
- Sugar is used often in coffee and tea based recipes. Pretty sure a majority of cafes in the current world uses sugar too.
:cl:
add: Water, iced tea, and sugar are added to the cafe synthesizers.
/:cl:
> Adds water, iced tea, and sugar to the cafe synthesizer

- code/modules/jobs/job_types/station/science/roboticist.dm
- code/modules/jobs/job_types/station/supply/shaft_miner.dm
Title
I'm considering robotics and shaft mining complex enough to need these titles so players new to these jobs will have people hopefully go easy on them and will teach them the ropes.
:cl:
add: Apprentice titles are added to the Shaft Miner and Roboticist jobs.
/:cl:
> Adds apprentice titles for shaft miners and roboticists

- code/game/area/area.dm
Title
if they're meant to stay on, they're MEANT TO STAY ON. No more endless Atlas Cargo garage loops and Surt airlock loops.
:cl:
fix: Fixes atmospheric retention fields that are meant to stay on turning off after atmospheric alarms are settled.
/:cl:
> Fixes atmos retention fields meant to stay on turning off after atmospheric alarms are settled

- code/game/machinery/biogenerator.dm
Title. Basically, if plant bags interacted with the biogenerator, it'd eventually lose storage size gradually because the biogen wasn't using the right procs for transferring storage over. Also probably fixes beakers not being inserted properly.
Fixes good.
:cl:
fix: Fixes biogenerator shrinking the storage size of plant bags.
fix: Beakers can be inserted and ejected from the biogenerator properly now.
/:cl:
> Fixes biogenerator not properly updating storage cache for bags

- maps/triumph/levels/flagship.dmm
:cl:
add: Added a few handrails to the Triumph escape shuttle to account for crew who can't sit in seats, and to make emergency shuttle surgery more viable in the shuttle medbay.
fix: Corrected the position of the lights on the Triumph escape shuttle to account for old-style walls.
/:cl:
> Triumph Emergency Shuttle Handrails and Lights

- code/game/turfs/turf.dm
Lets silicons nudge pulled objects around like human mobs can.
They tend to struggle with moving certain things without this feature. Let them have it.
:cl:
qol: Station-bound synthetics can now nudge objects they're pulling around.
/:cl:
> Allows station-bound silicons to nudge pulled things around

- code/modules/clothing/suits/labcoat.dm
:cl:
fix: Fixed the blue-edged labcoat not having an item sprite
/:cl:
> fixes the blue trimmed labcoat not having an icon sprite

- code/modules/power/fusion/core/core_control.dm
Right now there's a button that says "Bring field offline." Any reasonable person would assume this is the button you press to shut it down if something's going wrong, since shutting things down is usually one of the first steps in the process of things going wrong. This button causes it to explode. That is its entire purpose. It does nothing but make the R-UST explode. Exploding the R-UST is the purpose of the button. The game indicates this none.
The "explode the R-UST" button being properly labeled is a good thing
:cl:
qol: the "explode the R-UST" button in the R-UST UI is now labeled properly
/:cl:
> Makes the R-UST tell you that turning it off makes it explode

- code/__DEFINES/inventory/carry_weight.dm
- code/modules/species/station/alraune.dm
- Alraune can use internals again. The reason why they couldn't was because their snowflake code was trying to check to see if the alraune was able to take from the environment first before making them depend on internals. I've decided to wipe that code - if the alraune want to use internals, let them just use internals. Who cares if it might be wasteful?
- Boosted alraune and diona physiology again. They're stronger now, to compensate for that slowdown.
- Alraune burn modifier changed from 1.5 to 1.1
I may also do something to increase their pain tolerance, or just negate their pain altogether, but I'll need to ponder on that.
Fix good.
Also, alraunes too slow. Let's not make alraunes slower.
:cl:
balance: Alraune physiology is boosted again to carry even more without being slowed down. …
> Alraune internals fix and some buffs

- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Core.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
This makes blood no longer toxic to consume for all except skrell.
In addition, it also:
- Allows all to benefit nutritionally from it, some specific species more than others. Unathi, alraune, and xenochimera benefit the most from it.
- Drinking blood provides some hydration, but not really as much as just drinking a drink.
- It also heals some brute damage.
- Vetalan are healed and hydrated more from blood.
- The skrell follow the original behavior of blood being toxic to them.
Humans in real life do in fact, consume blood, especially in specific foods like gelatin. I can't really see why they shouldn't be able to drink blood in a game.
You can make a case that drinking raw blood is actually in fact bad for a human to do, but so is eating raw meat. There currently isn't any mechanical …
> Makes blood no longer toxic to consume for all except skrell

- code/modules/mob/living/carbon/human/emote.dm
If you empty out your pose or don't change it at all, it'll still say "adjusts their posture". It probably only should when you actually change stuff and when there's something to read.
Less "adjusts their posture" spam is probably good
:cl:
tweak: "Adjusts their posture" only shows up when pose actually changes, and not to the empty string
/:cl:
> Make set pose only show adjust when appropriate

- code/__DEFINES/spans.dm
- code/controllers/subsystem/vote.dm
- interface/stylesheet.dm
- tgui/packages/tgui-panel/styles/goon/chat-dark.scss
- tgui/packages/tgui-panel/styles/goon/chat-light.scss
Adds a slightly bigger, slow pulsing title text for the vote notification. It's animated, making it stand out a bit more.
Some players were saying that the vote notification wasn't noticeable enough. Let's try this.
:cl:
tweak: The vote notification text should be slightly more noticeable.
/:cl:
> Makes the font for a vote notification more noticeable

- code/game/turfs/simulated.dm
Laziest PR ever because the janitor mains need work.
:cl:
tweak: Dirtying happens sooner, at 75 steps instead of 500.
/:cl:
> Buff floor dirtying to take 75 steps instead of 500.

- maps/rift/levels/rift-02-underground2.dmm
This adds the cargo permission to the maintenance airlock into the mining refinery on Riftmap
Because we don't want people going in and just swiping everything from the refinery, or stealing unclaimed points.
Can no longer enter refinery from the back as anything but cargo.
:cl:
fix: fixed maintenance airlock permissions for mining refinery
/:cl:
> Adds Cargo-only permission to the entrance into Mining Refinery on Atlas

- code/modules/mapping/map_helpers/access_helper/airlock.dm
- maps/rift/levels/rift-05-surface2.dmm
- maps/triumph/engines/burn.dmm
- maps/triumph/engines/fission.dmm
- maps/triumph/engines/rust.dmm
- maps/triumph/engines/sme.dmm
- maps/triumph/levels/deck1.dmm
- maps/triumph/levels/deck2.dmm
- maps/triumph/levels/deck3.dmm
- maps/triumph/levels/deck4.dmm
- maps/triumph/levels/flagship.dmm
- maps/triumph/levels/misc.dmm
This PR is a continuation of #6462 and aims to replace each and every access var with access helpers. This is the 2nd of 3.
Also adds `research_lab` access helper and grants Pathfinders access to Rift's RnD (and every map's RnD from now on).
Access vars are obsolete and really complicated for mappers to use.
:cl:
add: Added access helpers to every airlock on Triumph.
add: Added additional maintenance airlocks & hatches to Triumph's engine chamber.
add: Pathfinders now have access to Rift's RnD
del: Removed Triumph's airlocks access vars, and replaced them with access helpers.
/:cl:
> Replaces airlocks access vars with access helpers on Triumph (2/3)

- maps/rift/engines/burn.dmm
- maps/rift/engines/rust.dmm
- maps/rift/engines/sme.dmm
- maps/rift/levels/rift-06-surface3.dmm
This PR drains the nitrogen filling the hot loop, burn chamber and core of the combustion engine twice and tokamak respectively, fixes a camera in AI upload and nodes unnoded PowerNet Sensors in the engine bay for the three engines
It's QOL for Engineers, if they want the Nitrogen in, it's easier to put it in than remove it if they don't want it. The PowerNet Sensors were meant to be noded, they were already in the map but they weren't connected to the grid. Fixes a floating camera in AI Upload, nobody ever goes there so it went unnoticed probably.
Switched all engine chambers tiles for airless tiles in the R-UST and Burn Chamber.
Fixed Camera orientation in AI Upload.
Noded Engine Power and Engine Output power sensors in all three engines.
:cl:
add: added nodes under the two sensors in …
> "Nitrogen Filling my Engines", AI Upload Floating Camera and Noded Engine PowerNet Sensors 

- code/__DEFINES/mapping/system.dm
- code/controllers/subsystem/mapping/allocation.dm
- code/controllers/subsystem/mapping/boot.dm
- code/controllers/subsystem/mapping/levels.dm
- code/controllers/subsystem/mapping/reservations.dm
- code/controllers/subsystem/spatial_grids.dm
- code/datums/components/movable/spatial_grid.dm
- code/modules/mapping/turf_reservation.dm
non-player facing
we're going to need fast lookups for "is this thing in range of this other thing" at some point, for things like telecomms
this current solution consumes about 16KB per reservation level
we also add the capability to use spatial grids to quickly get atoms on a level.
spatial grids are also at 16KB per grid, per world level
all in all worth it in my opinion.
> fast turf reservation lookups & aligned spatial grid lookups

- citadel.dme
- code/__DEFINES/controllers/spatial_grids.dm
- code/controllers/subsystem/mapping/reservations.dm
- code/controllers/subsystem/spatial_grids.dm
- code/datums/components/turfs/reservation_border.dm
- code/datums/components/turfs/transition_border.dm
- code/modules/mapping/turf_reservation.dm
adds the ability to specify a special border around turf reservations
by default,
1. if the border is specified but no initializer is specified, it's a selflooping border
2. if the border isn't specified, **you can fly out of reservations.**
yes, we have no safety guards anymore by default.
this is because turf reservations are a very low level concept and the user of the API is meant to deal with potential reservation escapes.
reservations are still aligned to chunks; though the actual playable area is no longer chunk-aligned.
this may change in the future. this is the case now because we don't want reservations to take up significantly more chunks than they otherwise would have.
> turf reservations - borders

- maps/triumph/levels/deck1.dmm
As title. The nacelle burn chambers have by-default on scrubbers in them.
What do you do with the burn chambers? You pump in oxygen and phoron, at a 3:2 ratio, to burn into carbon dioxide, which is very hot, to heat up some other phoron so you can use it as fuel.
What does the scrubber do? It pulls out phoron and carbon dioxide and puts it into the scrubbers loop, making it no longer usable and filling the scrubbers loop with hundreds of kPa of thousands-of-kelvin phoron/CO2.
This is not just pointless, it's actively detrimental, a gotcha whose entire point is to dunk on new players for not considering that someone might do something so incredibly stupid as to put a device into a burn chamber whose entire purpose is to remove the fuel and the hot stuff.
:cl:
tweak: Turned off the …
> Turns off the scrubbers in the nacelles on Triumph

- code/game/machinery/doors/door.dm
It's rly silly that screwdrivering a door makes it impossible for anyone without a screwdriver to get past it. Waist-high fence type beat
:cl: Bhijn and Myr
qol: Doors/airlocks can now be bump-opened while their panel is open
/:cl:
> Allows doors/airlocks to be bump-opened when their panel is open

- citadel.dme
- code/controllers/subsystem/persistence/persistence.dm
- code/controllers/subsystem/persistence/prototype_lookup.dm
- code/game/atoms/atom.dm
- code/game/objects/items/id_cards/emag.dm
- code/game/objects/items/stream_projector/medichine.dm
- code/game/objects/items/stream_projector/stream_projector.dm
- code/game/objects/items/toys.dm
Adds a system for persistence to bind to things without requiring the type to never change
Usually we to finalize stuff like typepaths before persisting because that's the smart thing to do
But for volatile things like organs that are under constant refactoring by necessity this doesn't work
So we do this to allow type changes to not throw out data
At some point we'll also need a versioning system for serialize / deserialize and semantics on when to "full serialize" / "full load", as an example if someone serialized an organ with 100 maxhealth but code changes made it 200, what then?
> prototype ids

- code/game/objects/items/storage/belt.dm
- code/game/objects/items/weapons/material/swords.dm
- code/game/objects/items/weapons/melee/misc.dm
- The Officer's Sabre is now a material item, which means it can be upgraded with better materials. It starts off as plasteel, with a base damage of around 25 due to funny material calculations. That does mean the starting damage does get nerfed a little from the original 30. But it can go up to around 44 if upgraded with durasteel.
- The sabre now has a 60% chance of parrying melee attacks, and a 50% chance of deflecting projectiles. For reference, the energy sword has a 65% chance of projectile blocking. Should the captain encounter someone trying to kill them, they can perhaps depend on the sabre to defend themselves.
- Fixed the sabre not being sharp (now causes bleeding, now can butcher mobs). Fixed the sabre's sheath not updating their icon.
- Drawing the sabre from a storage …
> Facility Director's/Officer's Sabre changes

- code/datums/components/horror_aura.dm
- code/game/gamemodes/changeling/powers/lsd_sting.dm
- code/game/gamemodes/cult/runes.dm
- code/game/machinery/computer/arcade/orion_event.dm
- code/modules/mob/living/carbon/brain/life.dm
- code/modules/mob/living/carbon/human/human_damage.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/living.dm
- code/modules/power/fusion/fusion_reactions.dm
- code/modules/power/supermatter/supermatter.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Other.dm
- code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Toxins.dm
- code/modules/species/promethean/promethean_blob.dm
- code/modules/virus2/effect.dm
- Functionalizes hallucination adjustment to firmly establish rules on hallucinations. Any code that changes hallucinations uses this function now.
- Caps hallucination at 400. It's annoying until it gets a rework.
- Synthetics will no longer experience hallucinations. (Horror aura causes EMPs, so synthetics already have a shitty end of the stick when dealing with horror mobs. Also this is intentional Sili recommendation.)
- Species that aren't meant to receive hallucinations will no longer experience hallucinations effects at all. 
- There was some comment somewhere saying that hallucinations should be reduced faster when you're sleeping/unconscious, so I made it do that.
- Prometheans can no longer "recall" items using promethean blobform. They were able to just teleport items from a …
> Fixes relating to hallucinations, and prommie blobform

- code/modules/cargo/supplypacks/hospitality.dm
The donut supply crate contains 3 donut boxes.
The condiment supply crate contains several condiments.  View the code to see which ones, since there's a good bit of them. Salt, pepper, and space spice are provided 3 times.
A few of the condiments included in the condiment box currently isn't renewable at all during a shift. This is one solution that's provided until hydroponics gets some plants coded in that can involve that.
As for the donut boxes - donuts are a common thing from stores. It'd also make sense that NT would let you order more donuts since they tend to stock the crew with several donuts shiftstart already.
:cl:
add: Donuts and condiments can now be ordered from Cargo in the hospitality category.
/:cl:
> Adds Donut & Condiment Supply Packs for Cargo

- code/datums/components/riding/mob/human.dm
as title
"you can't fireman carry someone who's handcuffed" - words of the utterly deranged
:cl:
fix: You can now fireman carry incapacitated people--you know, the ones fireman carry was designed for
/:cl:
> Makes restrained mobs carriable

- code/game/atoms/atom.dm
- code/modules/client/statpanel.dm
(There's currently no notice at all that something has extra examine information. Which in turn means it's *very* easy to miss information that would otherwise prevent incidents like what the above image represents the prelude of)
:cl: Bhijn and Myr
qol: When examining something that has extra info, the examine box will now contain a link that opens up the examine tab
/:cl:
> Adds a link to the examine tab when examining things that have extra examine info

- code/datums/recipe/material_recipes/tools.dm
- code/game/objects/items/storage/wallets.dm
- code/modules/clothing/under/accessories/bracelets/material.dm
- You can craft bracelets using materials again.
- Allows rings, bracelets, and necklaces to be put into wallets.
Fix good.
:cl:
tweak: Wallets can now hold rings, bracelets, and necklaces.
fix: You can now craft bracelets using material sheets again.
/:cl:
> Fix bracelet crafting, allows wallets to hold jewelery

- code/game/machinery/floodlight.dm
- code/game/machinery/fossilrevive.dm
- code/game/machinery/holoposter.dm
- code/game/objects/structures/curtains.dm
- code/game/objects/structures/dancepole.dm
- code/game/objects/structures/fence.dm
- code/game/objects/structures/flora.dm
- code/game/objects/structures/flora/rocks.dm
- code/modules/mining/mine_outcrops.dm
- Rocks are attackable.
- Outcrops are attackable.
- The two above can also be instantly destroyed by a proto-kinetic accelerator.
- "Ausbushes" are attackable.
- Floodlights are attackable.
- Curtains are attackable.
- Fences are attackable.
- some other random things are attackable.
- gives feedback when using the fossil machine
- removed redundant code from curtains
get this snowflake no-melee nonsense out of my way.
there's probably a lot more to be sorted out but some of these are the more egregious examples because they're usually obstructive in some way.
:cl:
fix: A few rocks, plants, and some other things are able to be removed via harm intent melee. You can now blast rocks with PKAs as well.
/:cl:
> Makes some things attackable via melee, code tweaks

- code/game/atoms/atom.dm
- code/game/machinery/doors/multi_tile.dm
- code/game/machinery/fire_alarm.dm
- code/modules/mapping/dmm_suite/dmm_context.dm
- code/modules/mapping/dmm_suite/dmm_parsed.dm
- code/modules/mapping/dmm_suite/dmm_preloader.dm
- code/modules/multiz/structures/stairs.dm
- code/modules/turbolift/turbolift_map.dm
Previously:
- A lot of unnecessary code to thread and repeatedly add orientation-related variables to the preloader.
- dmm_parsed previously modified its own args, then used arglist(args) This is bad energy -- as far as I can tell, this was was relying on the fact that _load_impl didn't use the modified values.
- Fire alarms were hardcoded to deal with east/west incorrectly
Now:
- These variables now live in the dmm_context.
- _load_impl takes fewer unnecessary args, and all its args are explicit
- A few variables have been removed or had their scope limited.
- Fire alarms aren't hardcoded to do that anymore.
Bugs I didn't fix:
- When a map is rotated EAST or WEST, signs spawn in an overlapping fashion that's really ugly.
Fire alarms were spawning sideways when rotated EAST or WEST and …
> Fix hovering fire alarms, refactor DMM rotation code

- code/controllers/subsystem/job/_legacy_job_stuff.dm
- code/datums/outfits/outfit.dm
- code/datums/uplink/announcements.dm
- code/game/objects/items/id_cards/contractor_ids.dm
- code/game/objects/items/id_cards/guest.dm
- code/game/objects/items/id_cards/station_ids.dm
- code/game/objects/items/id_cards/syndicate_ids.dm
- code/modules/mob/living/carbon/human/traits/_trait.dm
- code/modules/mob/living/carbon/human/traits/negative.dm
- code/modules/mob/living/carbon/human/traits/neutral.dm
- code/modules/mob/living/carbon/human/traits/positive.dm
- code/modules/preferences/_preferences.dm
- code/modules/preferences/preference_setup/vore/08_traits.dm
- code/modules/vore/fluffstuff/custom_items.dm
- maps/submaps/mountains/crashedcontainmentshuttle.dmm
- maps/submaps/mountains/crashedcontainmentshuttle_vr.dmm
This PR reworks how IDs are displayed, allows for traits to be displayed within IDs, fixes a few things, and generally makes 'em look nicer. This was primarily motivated by https://discord.com/channels/161574200581029888/1262064135110398032
The screenshot above is how the new IDs look ingame, featuring a few snippets of what a few traits display as within. IDs now properly display the photo (and the generation for said photo has been fixed!), IDs will now show your pronouns, and IDs now have a confidential information section (of which visibility can be toggled by alt-clicking the ID).
Additionally, the new feature where traits are displayed on your ID card is something that can be controlled in character generation, under the new "ID-visible traits" section. This section lists all traits …
> ID rework - trait information on IDs, confidential information toggle, and more

- code/game/objects/items/weapons/cigs_lighters.dm
- code/modules/atmospherics/environmental/atom.dm
As title. Right now, lighters work anywhere. It's a bit silly.
there's an entire atmos system with fuel gases and oxidizers, i'm using it (and yes, this is my only justification)
:cl:
tweak: Lighters no longer work in oxygenless environments
/:cl:
> Makes lighters require oxidizer

- code/modules/client/client_procs.dm
- code/modules/client/onboarding/age_verification.dm
title
our options are:
1. wait an arbitrary amount of time and then make the tgui input
2. use a non-tgui age gate
testmerge only for the sake of i want to be able to throw a test account at it on the server which has DB access because i'm not setting up a local db connection for this (see: i'm lazy)
fix issues with the prompt loading with tgui
:cl:
fix: fixes loading issues with the age gate (new players can just get stuck and unable to join)
/:cl:
> non-tgui age gate

- code/modules/integrated_electronics/subtypes/input.dm
It changes the tag used on circuit advanced signalers to use a number like the normal signaler. 
This improves reliability and fixes a few core bugs with the advanced signaler design such as non-responsive outputs in some scenarios.
This **will** minorly break pre-existing JSON exports for circuits that use advanced signalers, but is easily gotten around by printing the assembly and adding a number to where the ID tag previously went.
It makes advanced signalers far more reliable and standardized than how they were before. Primarily, it also fixes a few issues with getting circuits to output and receive data when using advanced signalers reliably.
:cl:
tweak: Circuit's Advanced Signaler now uses a number for its ID Tag; which is now labeled code.
fix: Advanced signalers are now more …
> Circuit advanced signaler changes

- code/modules/integrated_electronics/core/helpers.dm
- code/modules/integrated_electronics/core/pins.dm
- code/modules/integrated_electronics/subtypes/converters.dm
- code/modules/integrated_electronics/subtypes/data_transfer.dm
This fixes a issue with data writing to circuit component pins where it would store a raw reference instead of a weakref. This also fixes an issue with demux's where they would write a raw reference.
less random refs instead of weakrefs in circuits. also bug fixz
:cl:
fix: Demux pins write valid weakrefs to outputs.
fix: Circuit data written will always be in a weakref state instead of a ref.
tweak: Circuit ref converters will check if the data is a valid input before attempting conversions.
/:cl:
> Circuit demux fix & data to pin ref fixes

- code/modules/integrated_electronics/core/integrated_circuit.dm
Clicking on remove in the circuit component UI itself (not the assembly) would end up not properly removing the component like how clicking remove in the assembly would.
It fixes a bug.
:cl:
fix: Clicking on remove in a circuit component's UI will now properly remove it from a assembly.
/:cl:
> Integrated circuit removal bug

- code/__DEFINES/research/integrated_circuits.dm
- code/controllers/subsystem/processing/circuits.dm
- code/modules/integrated_electronics/core/saved_circuits.dm
If you attempted to make blueprints off of electronic components like an electronic jumpsuit or similar clothing, it would end up not working at all and making a fake assembly object. This lets the component able to be properly put into a blueprint and loaded back in.
It makes it possible to actually use electronic clothing and blueprint it. This means that the item works as needed, and you won't run into issues when you inevitably realize it isn't copying properly, losing 4 hours of work. 💀
:cl:
fix: Electronic clothes will now save and load from a blueprint.
/:cl:
> non standard circuit support

- code/modules/integrated_electronics/core/saved_circuits.dm
If you try to load a blueprint as is and have a renamed component in it, it's likely that the component won't output a sanitized text correctly to compare because it uses sanitizeName which capitalizes the first letter; which isn't particularly the correct behavior. sanitizeSafe seems to be the proper one to use here. (correct me if I'm wrong)
Doesn't really make sense that components HAVE to have an uppercase first letter either; so this fixes that.
If I'm using the wrong proc tell me :slime:
Cuts down on confusion regarding circuit names and arbitrary restrictions.
:cl:
change: Circuit components loaded in from a blueprint no longer require an uppercase first letter to load in properly.
/:cl:
> Circuit component blueprint name validation fix

- code/modules/integrated_electronics/subtypes/input.dm
- code/modules/integrated_electronics/subtypes/manipulation.dm
- code/modules/integrated_electronics/subtypes/reagents.dm
This lets you interact properly with some components including attacking and having the correct references passed in when you do.
It also fixes a small issue with weapon manipulators where you couldn't take out the weapon without wholly tearing out the component.
It makes some interaction in the assembly interface work, and it lets you not ruin wires if you need to change out a weapon manipulator's gun.
:cl:
fix: Flipped arguments in assembly's ask_for_input due to how arguments were actually put in; so that user is being passed in, instead of an obj.
change: You can now click on the interaction button for weapon manipulators to take out the loaded weapon.
/:cl:
> Circuit interaction input fixes.

- code/modules/integrated_electronics/core/assemblies.dm
- code/modules/integrated_electronics/core/integrated_circuit.dm
Circuit debugger on ref mode wouldn't copy a circuit reference if you pressed debugger scan because of invalid clickchain flags
less bug. Also lets you use circuit debugger on built-in components as it should be able to easily.
cl:
fix: Circuit Ref debugger will now properly copy references inside a circuit.
/:cl:
> circuit debugger ref copy UI fixes

- code/modules/integrated_electronics/core/tools.dm
This adds very basic list functionality to circuit debuggers. It was an option already present, but just didn't do anything. I made it only support string, num & nulls. Theoretically could support refs in the tool, but that would cause the code to balloon badly.
Now you don't have to make a whole separate assembly to put together a list in a circuit; unless you want a ref in it; in which case, you probably should use an assembly for obvious reasons.
:cl:
add: Circuit Debuggers now have a working list functionality.
/:cl:
> Circuit debugger list functionality

- code/modules/integrated_electronics/core/assemblies.dm
Moving a circuit to the bottom of the assembly would occasionally overwrite another component's slot with itself as a duplicate; especially if you spammed it. This prevents that behavior entirely.
It makes less of a bug.
:cl:
fix: Moving a circuit component to the bottom of the assembly won't cause the occasional overwrite & duplicate.
/:cl:
> circuit move to bottom fix

- code/modules/integrated_electronics/core/integrated_circuit.dm
- tgui/packages/tgui/interfaces/ICAssembly.js
- tgui/packages/tgui/interfaces/ICCircuit.js
This lets you rename circuit components and have the UI reflect their changed name where important. This includes in button displays on the assembly itself, and in wire connections in the circuits.
Previously, the behavior was bugged to either not update; or not display the renamed component's new name as it should.
i also didn't really see a reason rename_component should have been a verb; as it was wholly being used like a proc anyway.
It makes it a lot easier to make sense of circuits if you can rename circuits and have easy connections of 'this addition circuit goes to this specifically named list'. It was also questionably bugged to not update before in most cases.
it was also just partially bugged to not update.
:cl:
tweak: Circuit wire connections will display displayed_name …
> Circuit displayed name fixes & tweaks

- code/modules/integrated_electronics/core/helpers.dm
- code/modules/integrated_electronics/core/pins.dm
- code/modules/integrated_electronics/core/saved_circuits.dm
- code/modules/integrated_electronics/core/special_pins/lists_pin.dm
- code/modules/integrated_electronics/core/special_pins/ref_pin.dm
- code/modules/integrated_electronics/subtypes/filters.dm
- code/modules/integrated_electronics/subtypes/input.dm
- code/modules/integrated_electronics/subtypes/lists.dm
- code/modules/integrated_electronics/subtypes/logic.dm
- code/modules/integrated_electronics/subtypes/manipulation.dm
- code/modules/integrated_electronics/subtypes/memory.dm
- code/modules/integrated_electronics/subtypes/reagents.dm
- tgui/packages/tgui/interfaces/ICCircuit.js
This fixes a few problems that still remained (or got implemented by bugged behavior being fixed) with circuits.
Particularly, it makes sure pins display their output text properly; a bug I accidentally introduced earlier.
Circuit components loading will also load their data before being put in a assembly proper. (that way, names display correctly.)
It also makes sure that where applicable, circuits will actually use the helpers for data screwyness.
As a side effect, the above (with a few tweaks) also fixes an issue where raw references were getting stored in lists.
Finally, list cooldowns were reduced to the standard (otherwise this makes them *very* awkward to work with.)
Theoretically I could atomize this PR further, but, uh, a lot of it was just bug fixes.
fixes a variety of bugs.
For …
> A variety of circuit fucky wuckys fixes.

- maps/rift/levels/rift-02-underground2.dmm
The ore silo is a good idea on paper but it sucks because it is an extra menu to click through (though its not as bad its just not efficient aaaaa) and science still need to wait for a miner to open the door or risk that one fun police member (security) decides they shouldn't be hacking in to get their materials so they can do work that actually has merit unlike Xenoarcheology. This fixes the "You still need mining to access the silo as somebody who is the main consoomer"
"Premats done. Upgraded the Geothermals. I am heading home because no miners and Xenoarcheology, Xenobotany and Xenobiology are not real science" gets prevented maybe, at least somewhat. Note that this does NOT fix a ton of other underlying issues with both cargo and science gameplay that often involve getting degraded …
> Ore Silo door accessible by Science :3

- code/modules/integrated_electronics/core/assemblies/clothing.dm
circuit assemblies with an action circuit didn't work because the action bar didn't create a spot. After all, you don't have the electronic assembly equipped, but rather the clothing itself. this rectifies that, and attaches the behavior to the electronic clothing instead.
it fixes an otherwise non-functional circuit.
:cl:
fix: Electronic Clothing will now properly show on the action bar.
/:cl:
> Electronic Clothing now displays on action bar.

- dependencies.sh
This pull request updates the vendored Node version from 14 to 20.
The primary reason for staying on Node 14 was Windows 7 support, a feature only MSO cares about. He isn't a CitadelStation developer and doing a quick poll of the CitadelStation Discord led me to the impression that the other CitadelStation developers also don't care about this.
Switching to Node 20 unbreaks a bizarre behavior I have started seeing when I run the tgui-eslint target. Here's how it looks on Node 14:
```
>BUILD.cmd tgui-eslint
Using vendored node v14.16.1
:: Juke Build version 0.8.1
:: Skipping 'dm' (up to date)
:: Skipping 'yarn' (up to date)
=> Starting 'tgui-eslint'
:: Skipping 'tgui' (up to date)
Oops! Something went wrong! :(
ESLint: 8.54.0
C:\Nyeogit\Citadel-Station-13-RP\tgui\.yarn\cache\@typescript-esl …
```
> Use Node 20

- citadel.dme
- code/__HELPERS/_logging.dm
- code/__HELPERS/unsorted.dm
- code/datums/variable_settings/variable_setting_controller.dm
- code/datums/world_topic.dm
- code/game/verbs/advanced_who.dm
- code/game/verbs/who.dm
- code/modules/admin/admin.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/holder2.dm
- code/modules/admin/verbs/antag-ooc.dm
- code/modules/admin/verbs/deadsay.dm
- code/modules/admin/verbs/server/admin_reboot.dm
- code/modules/admin/view_variables/topic.dm
- code/modules/admin/view_variables/topic_basic.dm
- code/modules/client/client-admin.dm
- code/modules/client/verbs/ooc.dm
- code/modules/mob/mob_helpers.dm
this is admittedly not a usual use of stealth mode but it's nice to not pop on/off the list when deadminned
(this is nice for event rounds since you're supposed to deadmin if in a conflict role)
> admin stealth mode now works while deadminned

- code/modules/integrated_electronics/passive/power.dm
- code/modules/integrated_electronics/subtypes/lists.dm
**Solar cell power output has been changed from 1W back to 30W of its original design.**
It being reduced down to 1W made it practically useless for any real design. A lot of even basic components use roughly 30W per second.
**Change back sizes from tesla chargers to small and medium respectivly**
There never really was a need for it and tesla power is rare outside the station.
**Change the list deletor to 0.1 seconds**
A fairly lightweight circuit for what it does and it ensures it can be used together with at List running at the same speed.
> Revert some IC balance from Virgo

- code/modules/projectiles/guns/energy/laser.dm
I always found it weird how this gun gets outclassed easily by even the dinky explo holdout phasers. Reason for it being is its stupid low energy efficiency. You can squeeze out 5 shots out of it. This is laughably low. I suggest therefor the capacity is doubled and the exploration flavor text for the gun is slightly altered. Degraded yes, but not underperforming and being outclassed by shit explo has as backup.
Kinda rare find and usually only brought by traders. Dissappointing energy efficiency. Yeah comes with a voidcell but that too has attrocious charging rates. Feels more like a silly trophy instead of something you'd use.
:cl:
balance: Halfs energy cost per shot for precursor sidearm, effectively doubling its capacity on a weapon cell. Cutely.
/:cl:
> Buffs the Precursor Sidearm

- code/modules/integrated_electronics/subtypes/output.dm
- code/modules/integrated_electronics/subtypes/reagents.dm
- code/modules/projectiles/gun.dm
3 bugs and 1 minor QoL change
Fire_userless proc now plays the projectile sounds. This affects circuit guns and sawing off a loaded shotgun.
Beaker slots now works as intended with its UI buttons. Inserting and removing.
Circuit clothing can now emit light with a light component when worn. I tried to cheese it by removing the components and so on, light resets as it should.
Beaker slots now also accept hypovials
> fix IC fire sound, beaker slot, clothing light

- code/game/machinery/buttons.dm
- code/modules/materials/definitions/metals/steel.dm
This allows window tint controls to be makeable by using 4 steel sheets, and the same construction process as a light fixture.
You can make electrochromatic windows, but not the actual switch / control which seems whatever. By adding it, it also adds a little bit of fashionable flair someone can use to make cute little rooms.
:cl:
add: Window Tint Control is makeable by using 4 steel sheets and the same construction process as a light fixture.
/:cl:
> Window tint controls now have a in-game construction process.

- code/modules/projectiles/guns/energy/nuclear.dm
The AEG currently is pretty much hot garbage. Yeah LTL mode is 10 shots sure. But lethal? 5 shots. Which suffer through bay missing (not for long anymore). Which also suffer from attrocious recharge rates (This is the real issue). A bit more micro and a stock G40 laser carbine with a inducer outclasses this gun in every way for lethal applications. This gun is unfortunately one of the many currently useless guns in the RnD Roster.  The thing is also not small in size and cannot be onehanded nor fit in holsters....... so whats the point on printing it ever in its current state with 5 shots lethal mode. The cell revolver has the same is more versatile can reload on the fly and can also be recharged by an inducer. Theres currently no point in ever using the AEG unless you get emped 50 times …
> Cutely buffs AEG (Lethal shot count from 5 to 10)

- code/modules/integrated_electronics/core/assemblies.dm
- code/modules/integrated_electronics/core/helpers.dm
- code/modules/integrated_electronics/core/integrated_circuit.dm
- code/modules/integrated_electronics/core/pins.dm
- code/modules/integrated_electronics/core/special_pins/lists_pin.dm
- code/modules/integrated_electronics/subtypes/input.dm
- code/modules/integrated_electronics/subtypes/smart.dm
Fixes a few bugs, notably with ID card readers not properly filling info out from an ID. Also it untypes the data from /datum/weakref. This wasn't always a /datum/weakref, but was typed as it for ??? reasons, primarily relevant for Zandario who was having issues while trying to do some stuff.
fixes bugs. also doesnt have something randomly typed as something it's not.
:cl:
tweak: Circuit data isn't typed as /datum/weakref anymore.
tweak: ID card readers now have a data output of rank, which is the non-alternative job title.
fix: ID card readers now properly read a job and assignment from an ID.
fix: Removing a circuit component by its own 'remove' ui button now properly removes it from the assembly UI.
tweak: Removing a component from the UI doesn't brick a UI component in place in …
> Circuit bug fixes & data untyping

- code/modules/power/fusion/fusion_reactions.dm
Engineering asked for it. I trust our engineering players know what they are talking about.
Lowers energy req to run H2-H2 fusion reaction so its actually more sustainable. (Its not runable without the change unless you are a masochist...)
Same for boron-h2
Also obligatory "Irkalla when do u code real shit?"
When I am done with job obligations and have holidays.
Engineering asked for it.
:cl:
tweak: 117000  for new energy reqs for H2-H2. Boron-H2 lowered to 78500. I trust engineering players enough to know what they are talking about. Its actually unrunable apparently without the change. The rust apparently runs on abstracted real world parameters yet temperatures cannot be reached ingame proper. Amazing.
/:cl:
> Rust adjustment (H2 energy level to ACTUALLY obtainable power reqs)

- maps/triumph/levels/deck3.dmm
This is a bunch of changes to the Triumph to try to unshit parts of it at least. Here's a number of science QoL and mild mapping changes to correct small nitpicks or issues in it. This is part one of Probably Many, I'll do the changes department by department probably, until I get to general ones.
Here's a list of ALL the changes.
cardboard stack in r&d
labeler in r&d
another toolbelt & welding goggles in r&d
labeler in xenobotany
slimesky in xenobio by default
xenobio killbox removed, replaced with 3 more pens. (i dont think it was very useful, vs using a chem sprayer or cryogun. more pens also is More Logical.)
xenobio has a box of beakers & syringes.
xenobio has two sets of slime batons & taser guns instead of one.
xenobio welding tank removed.
all xenobio pens have dividers that are …
> Triumph Science Mapping changes

- code/modules/projectiles/guns/projectile/pistol.dm
Done by kev's instructions
:cl:
tweak: Security LTL ballistics can now load lethal magazines when needed, no more needing to get the same weapon issued but in lethal flavour.
/:cl:
> Removes magazine locks from Security's ballistic sidearms

- code/modules/integrated_electronics/subtypes/input.dm
raises cd on examiner circuit; because examining is expensive. it probably shouldnt be able to spam every 0.1 seconds. its now 5 seconds. realistically i'd ideally make examine less expensive but uh.
lol
:cl:
tweak: examiner circuit cd is now 5 seconds
/:cl:
> giga cd on examiner

- code/game/content/factions/corporations/nanotrasen/nanotrasen-supply/supplies.dm
- code/game/objects/items/weapons/grenades/explosive.dm
Helbera asked for it cutely.
Adds 2 bulkbuy crates. 75 Thaler per charge. Bulkcrate of 5 and one of 10. 50 Thaler = 1 point according to siwicons.
The mining crate is only bought for charges. 2 charges per crate and it quickly lags up cargo. Kinda sad. QOL kinda.
:cl:
add: Some Tyrmalin explosives experts now decided to bulk ship their mining charges.
/:cl:
> Adds 2 tyrmalin charge bulk crates

- maps/triumph/levels/deck1.dmm
The Nacelles were basically burn engines, but not actually like, burn engines?? For some reason they didn't have borosillicate against the edges to prevent the nacelles from blowing the fuck up 💀 . Also, this expands them a bit. They also now have floors inside with no air. An additional can of phoron / air was added next to them.
This also removes the excess doors on the Triumph engines; as engines all have their own doors (and would stack 2x doors).
this way, the nacelles dont blow out if you decide to get a little spicy, or refill them. the size increase is to fit the borosilicate. admittedly its a little larger still, but that's more of a space efficiency thing / making it look good (and it's only by like. 3-4 bonus tiles.)
:cl:
tweak: Triumph Nacelles now have borosillicate linings. …
> Triumph Engineering Tweaks

- code/modules/mining/ore_redemption_machine/equipment_vendor.dm
- code/modules/projectiles/guns/energy/kinetic_accelerator.dm
adds PKA Capacity modes, that increase total capacity at the cost of damage
Adds a mod capacity mod for Proto Kinetic Accelerators, increasing capacity by 15 and decreasing damage by 6 each with a maximum of 2 installable mods.
This adds an option that fills the gap for the to be removed damage increase mod, exchanging damage for more customization, ultimately giving a small but useful increase in options. The 6:15 damage to mod capacity means it will not be viable to increase damage if damage mods end up being preserved
:cl:
add: PKA Capacity Mod 
:add: Mining vendor sells PKA Capacity Mod
/:cl:
> Adds PKA capacity mods

- code/modules/mapping/spawner/window.dm
- maps/rift/levels/rift-11-orbital.dmm
- maps/triumph/levels/flagship.dmm
Non-map changes:
- Fixed electrochromatic window spawners not passing the given ID over to the windows they're spawning.
Both:
- Adds fire safety equipment
- Window spawners come with a low wall now.
Triumph:
- Moves the vendors back to the other wall
- Replaces the cigarette vendor with an MRE vendor (don't encourage smoking in a shuttle.)
- Changes up the bridge to be significantly less garbage
- Medbay's surgery table is replaced with a sleeper. Medbay's beds are now rolling beds, and IV drips with anesthetic tanks are set beside them. A blood vendor's been added.
- Lets people in the bridge see people outside in the passenger section.
- Adds point defense system
- Adds electrochromatic windows in the medbay, security, and command sections. Completely toggleable.
- Adds brig section in …
> Triumph + Rift Departure Shuttle renovations & fixes

- code/modules/xenoarcheaology/finds/talking.dm
title
If normal objects don't annoy ghosts who have Ghost Ears enabled, I don't see why these things should either.
:cl:
fix: Xenoarcheology's parroting objects will no longer annoy ghosts who have Ghost Ears enabled.
/:cl:
> Stops xenoarcheology talking objects from annoying ghosts

- code/modules/materials/definitions/metals/steel.dm
if u deconstruct racks, they drop 2 steel. however, they only take 1 steel to make. hmm. now they cost 2 steel to make.
unduplicates ur matter
:cl:
tweak: Rack now costs 2 steel to make.
/:cl:
> racks construct costs 2 steel

- code/game/objects/items/weapons/implants/implant.dm
- code/modules/mob/living/simple_mob/subtypes/animal/borer/borer.dm
- code/modules/resleeving/mirror.dm
- code/modules/surgery/implant.dm
shrapnel is no longer rng + u can pick what to grab. theres also now a proper proc for removing something surgically.
no reason for rng in ideal circumstances. u already get penalized for improper tools so like why have more rng. also a needed proc for slightly less shitcodedness.
:cl:
add: shrapnel / etc removal now goes through a surgically_remove proc.
qol: shrapnel removal is no longer rng
qol: shrapnel removal now lets u pick what item to remove
/:cl:
> shrapnel is no longer rng + u can pick what to grab

- code/modules/vehicles/sealed/mecha/mecha.dm
it lets mechs interact with blast door buttons
they can already interact with airlocks and stuff. its kind of stupid you have to eject like four times and get back in four times to get a mech out properly.
🥺 
:cl:
qol: mechs can now operate blast door controls
/:cl:
> lets mechs open blast doors

- code/game/machinery/atm_ret_field.dm
atmosphere retention field touch message is now toucher only
it was an aoe msg with first person structure
:cl:
fix: atmos field touching msg is now toucher only
/:cl:
> atmosphere retention field touch message is now toucher only

- code/game/machinery/pointdefense.dm
allows point defense control to be properly registered by checking if the new indent is taken, instead of the current tag. also makes sure that the batteries themselves dont check for id taged controllers with their own tag???? idk why that was a thing. im guessing copy paste.
fixes bug where both were unregisterable.
:cl:
fix: point defense control now can be set.
fix: point defense battery can be set to a new ident tag.
/:cl:
> fixs point defense registering

- maps/away_missions/140x140/snow_outpost.dmm
- maps/away_missions/archive/blackmarketpackers.dmm
- maps/away_missions/archive/jungle.dmm
- maps/away_missions/archive/spacebattle.dmm
- maps/away_missions/archive/stationCollision.dmm
- maps/minitest/levels/minitest.dmm
- maps/rift/engines/burn.dmm
- maps/rift/engines/rust.dmm
- maps/sectors/admin_planets_192/croatoan.dmm
- maps/submaps/level_specific/debrisfield_vr/tinycarrier.dmm
- maps/submaps/level_specific/virgo2/Blackshuttledown.dmm
- maps/submaps/wilderness/Blackshuttledown.dmm
- maps/submaps/wilderness/Blueshuttledown.dmm
- maps/templates/admin/ert_base.dmm
- maps/templates/admin/mercbase.dmm
- maps/templates/admin/skipjack.dmm
- maps/templates/archive/tradeship.dmm
- maps/templates/shuttles/overmaps/generic/curashuttle.dmm
- maps/templates/shuttles/overmaps/generic/generic_shuttle.dmm
- maps/tether/levels/misc.dmm
- maps/tether/levels/station2.dmm
- maps/tether/levels/surface3.dmm
- maps/triumph/levels/flagship.dmm
- maps/triumph/levels/misc.dmm
- tools/ci/check_grep.sh
byond lets you put two /turf's on one turf, which makes one turf look like the other
i don't know why it does this but this is never used in ss13 because it's absolutely horrible to deal with as you now have turfs using 1. underlays (ss13 doesn't) and 2. doing different things than it should
this removes all cases of it, and adds a lint.
this will not catch cases where there's more than two turfs but they're not adjacent but here's hoping people don't fuck up so royally hard that they somehow cause non-continuous turfs.
> lints against turf overlaying

- code/modules/hydroponics/trays/tray_process.dm
for some reason trait_requires_nutrients / requires_water just stops the health. instead of like. just stopping nutrient/water intake. (which I would like it to do)
so farm bot would just go schizo
I also dont think it actually works as it should as it was before.
you also had no way of telling what the actual drain of both was, because the trait removes the visibility of intakes from the scanner.
This PR just basically makes the trait more obvious in what it does by making plants not drain their respective resource if they have that gene trait.
the trait was super obscured and actually just sort of made it impossible to restore your plants, making the trait sort of a negative one. now it's a lot more obvious as to what it's doing, and it correlates better to its actual name so the …
> xenobotany requirement traits stop water / nutriment depletion.

- maps/triumph/levels/deck1.dmm
it floated off the wall, now it don't.
no more floating camera :D 
:cl:
fix: makes a camera not float in triumph's engineering.
/:cl:
> fixes a cam dir in engineering of triumph

- code/modules/research/designs/misc.dm
Adds size standardization bracelets to the protolathe, giving them an in-game method of being made, instead of requiring admin spawn or loadout equip. I made the recipe kinda cheap because it's mostly a fluff item / makes life less of a living hell.
seems useful for events and / or just general purpose.
:cl:
add: Size standardization bracelets can now be made in the protolathe.
/:cl:
> Adds size standardization bracelets to protolathe

- code/modules/reagents/distilling/distilling.dm
this makes the atmos setting not require 1000 kpa to do anything with temp
u do not want me putting enough gas to fill the triumph 3x over at 14 kelvin into a distillery.
:cl:
tweak: The distillery atmos setting will now adjust the temperature at fifteen kPA or greater pressure instead of 1000 kPA or higher.
/:cl:
> makes distilling not require 1000 pressure for temp changes

- code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
- code/modules/power/generator.dm
:cl:
tweak: tweaked atmos circulators to work in both directions.
/:cl:
> Makes TEG Circulator bidirectional

- code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
- code/modules/power/generator.dm
Reverts Citadel-Station-13/Citadel-Station-13-RP#6764
It literally does not work as advertised. It doesn't work at all. There's only one output side, it always puts into the output side. It can take from the output side, and then it puts it back into the output side. This is a non-functioning PR. Test your PRs properly.
> Revert "Makes TEG Circulator bidirectional"

- code/modules/mob/living/simple_mob/subtypes/animal/roach/roach.dm
Decreases ranged attack speed of roaches by 80%. No more MG roaches
Due to a coding bug that for some reason was never squashed. Ranged roach subtypes were able fire faster then most mercenaries with machine guns. As one type used a primarily agony damage attack this resulted in a roach that could chain stun you, the other spammed a poison projectile capable of rapidly killing an unarmored target faster than most gun armed opponents. Both of these are oversights and this PR corrects them.
:cl:
fix: Ranged Roaches attack 80% slower.
/:cl:
> Fixes Ranged Roach Attack Speed

- maps/rift/levels/rift-06-surface3.dmm
- maps/triumph/levels/deck4.dmm
Slight amounts of map housekeeping regarding the exploration department.
Things being wrong is bad.
:cl:
del: Deleted mapped-in binoculars spawns for exploration, as they are now included in explo-related job lockers via code per #6796
del: Removed a toxin treatment pouch from Atlas Explo Shuttle.
add: Gave SAR & Explorers some Hand Labelers on both Atlas and Triumph.
tweak: Touched up some of the erroneous or incomplete floor markings in Atlas exploration.
/:cl:
> Exploration Mapping Tweaks

- code/controllers/subsystem/zcopy.dm
- code/modules/multiz/zmimic/mimic_movable.dm
There's still some update ordering issues that seem connected to lighting, but I'm not sure if this is actually an issue with ZM/O7L itself or seeker having a moment.
Also fixes some issues with new atom notifications in ZM not working with recursive mimic properly.
> Z-Mimic: Speculative fixes for glass turfs

- code/modules/food/food/lunch.dm
as title
shouldn't be a roulette to take a basic loadout item and sometimes it just kills you
:cl:
tweak: Nuclear Waste and A Desire To Die are no longer options for loadout flasks
/:cl:
> blacklists Drinks That Kill You from flasks

- code/game/objects/structures/morgue.dm
Fixes a bug that caused crematoriums to permanently lose their trays if someone stood in front of the crematorium while opening it. Also prevents morgues from being open and unanchored simultaneously. 
An unusable crematorium is, well, unusable. 
The morgue unanchor mechanic is pretty obscure (I didn't even know it existed till now), but dragging an open morgue causes the tray to detatch and I'm not sure why someone would need to move a morgue before closing it.  
:cl:
fix: NanoTrasen has issued a mass recall on its Phoron War-era crematoriums and morgues amidst complaints about disappearing crematorium trays and unfounded reports of 'bluespace body snatching'. 
/:cl:
> Fixes crematoriums disintegrating

- code/controllers/subsystem/ticker.dm
Unless more than 0 Players have stated their intention of playing the round, the round will delay by 1 minute, then check again.
Hopefully reduces the amount of dead dead rounds during low population hours
:cl:
add: Add a requirement of one player ready for the round to start
/:cl:
> Add a requirement of one player ready for the round to start

- code/modules/projectiles/guns/legacy_vr_guns/custom_guns.dm
The screenshake RN is extremely heavy handed. Its nausea inducing. The gun itself is more of a meme on itself (you cannot print its ammo). Mostly used for CDDA or Milsim larpers anyhow. 
It still has considerable screenshake but hopefully not so much that it makes the JSDF rifle fan puke. It is really *that* bad. Don't believe me? Give it a try, try using it with lots of stuff on the screen, it is quite nauseating. And its a thing waiting to happen till John Explorer goes looc: "brb puking due to JSDF screenshake".
Rename it to "Metaphysical Sickshot Battlerifle" because it manages to affect the "It" every character has.
:cl:
balance: JSDF rifle shouldnt induce motion sickness IRL anymore when firing it.
/:cl:
> Lowers the recoil on the JSDF Rifle because it makes JSDF rifle users motion sick

- code/modules/integrated_electronics/subtypes/input.dm
Revert #6684 while also addressing the performance concern.
Turns out that the proc examine was called for nothing since it never worked in the first place.
The examiner is not only used for desc. Many circuit concept rely on a very fast and responsive x and y relative cordinate and or distance feedback so having the cooldown on 5 severly crippled many designs.
> Optimize circuit examiner and revert CD

- citadel.dme
- code/__DEFINES/vv.dm
- code/modules/gateway/stargate/stargate-station.dm
- code/modules/mapping/spawner/gateway.dm
- code/modules/mapping/spawner/tcomms_relay.dm
:cl:
add: Added a spawner that sets a functioning away gate up
admin: Added a VV option to start the station gateway up without having to interact with it
/:cl:
> gateway spawner

- code/modules/mapping/map_helpers/access_helper/airlock.dm
- maps/rift/levels/rift-02-underground2.dmm
- maps/rift/levels/rift-04-surface1.dmm
- maps/sectors/lavaland_192/levels/lavaland_192.dmm
- Explorers can no longer enter Research and Development. Explorers entering R&D is not intended to be the norm and got changed by mistake when access helpers came to pass a few months ago. Pathfinders can still enter it.
- Corrects Xenobotany's access on Atlas
- Corrects infirmary access on Atlas
- Chemistry lab changed to Xenobotany/Xenobiology ("genetics") access on Atlas ( sorry explorers. :^) )
- Everyone who can enter Surt can toggle the blast doors from the outside instead of just the inside now.
Fix gud.
I swear this isn't just some "explorers get no rights" PR.
:cl:
fix: A few access corrections on Atlas and Surt/Lavaland.
/:cl:
> Fixes R&D related access, some Atlas Science access, and a button's access in Surt

- code/modules/reagents/chemistry/reagent_holder-reactions.dm
- code/modules/reagents/distilling/Distilling-Recipes.dm
- code/modules/reagents/distilling/distilling.dm
This adds feedback messages for the distillery reactions.
The examine radial was removed because it didn't work and gave no relevant info.
It also fixes start_ticked_reaction with an if statement that won't runtime.
It also makes the distillery adjust the reagent_holder's temperature instead of having a current_temp var.
makes distillery work and not be hell.
:cl:
tweak: Distilleries now adjust their reagent_holder's temperature instead.
fix: Ticked reactions will now properly start up.
qol: Distillery reactions will now give feedback of starting up, still running, and stopping.
/:cl:
> Ticking reactions will now proper begin & distillery QoL

- code/__DEFINES/reagents/reagent.dm
- code/game/machinery/Sleeper.dm
- code/modules/reagents/chemistry/reagent.dm
- code/modules/reagents/chemistry/reagent_holder.dm
adds reagent filter backend
adds sleeper filter flags
> reagent filter backend

- code/modules/mob/living/simple_mob/subtypes/animal/farm animals/lythios.dm
This will stop Glacicorns from randomly dying from heatstroke.
Apparently when Lythios is at its warmest temperature stabilization warms up Glacicorns just enough to die of heatstroke. As simple mob temp stabilization will eventually be removed according to Silicons I am simply upping Glacicorn heat tolerance slightly.
:cl:
fix: Glacicorns should no longer die when Lythios gets a bit warm.
/:cl:
> Stop Dying Glacicorns

- maps/endeavour/levels/deck1.dmm
- maps/endeavour/levels/deck2.dmm
- maps/endeavour/levels/deck3.dmm
- maps/endeavour/levels/deck4.dmm
Reworks a lot of the wiring on Endeavor. A lot of the work is just making it look nice and ensuring all wire junctions are oriented the right way (following any wire from an APC and going in the natural seeming direction will take you to the power source).  Some areas like starboard dorms didn't have power, I wired them up. A few breakers were moved/removed as needed for the ship to function right. The Main SMES was changed from something better than you can build to being a normal Main SMES but with half the starting charge since this ship is designed to use the Secondary Supply SMES for its starting power rather than Main. There was also some shifting of things from one grid to another, e.g. security was moved from the D3 midship grid to the D3 aft grid since it's in the aft of the …
> Power and Atmos Fixes

- code/game/objects/items/storage/medical/hypokit.dm
- code/modules/reagents/chemistry/chemical_reaction-legacy.dm
Two things.
Firstly, normal hypovials no longer spawn with a bunch of empty vials in them. Advanced kits still spawn with large vials.
Secondly, the myelamine recipe now uses calcium instead of iron, that makes slightly more sense given it's all about coagulation.
The infamous "Salt PR" but will hopefully save medmains further untold hours of throwing empty vials into disposals every shift.
Wiki update for the myelamine recipe to follow.
:cl:
del: Hypokits no longer spawn with empty vials
tweak: Myelamine now created with Calcium instead of Iron
/:cl:
> Hyper-Specific Medical Nitpicks

- code/modules/paperwork/paper/paper.dm
admin datum usr can be client
:cl:
fix: admins can see faxed paper again
/:cl:
> fix admin fax viewing

- code/__DEFINES/mobs/life.dm
- code/game/dna/dna_modifier.dm
- code/game/gamemodes/cult/soulstone.dm
- code/game/machinery/computer/Operating.dm
- code/game/machinery/cryo.dm
- code/game/objects/items/defib/shockpaddles.dm
- code/game/rendering/atom_huds/atom_hud_provider.dm
- code/modules/admin/verbs/debug.dm
- code/modules/mob/living/carbon/brain/life.dm
- code/modules/mob/living/carbon/breathe.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/carbon_defines.dm
- code/modules/mob/living/carbon/health.dm
- code/modules/mob/living/carbon/human/human-damage-legacy.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/simple_mob/subtypes/animal/pets/cat_vr.dm
- code/modules/mob/mob.dm
- code/modules/organs/external/wound.dm
- code/modules/resleeving/machines.dm
- code/modules/species/species.dm
- code/modules/species/station/alraune.dm
adds support for controlling the ~~speed~~ point at which ~~crabs~~ carbons die
required for holospheres because their hologram form has very low health which isn't possible if they die at -100
this is set in mob/living because that's where maxHealth is currently handled but right now only carbons care about minHealth because everything else ignores the old config option and dies at 0
changes are replicated to also store crit and softcrit thresholds
better control over the point at which things die
:cl:
add: add minHealth which controls when carbons die so we can set it in species
/:cl:
> add minHealth which controls when carbons die so we can set it in species

- citadel.dme
- maps/endeavour/endeavour-papers.dm
- maps/endeavour/levels/deck1.dmm
- maps/endeavour/levels/deck2.dmm
- maps/endeavour/levels/deck3.dmm
- maps/endeavour/levels/deck4.dmm
- maps/sectors/nebula_tradeport/levels/nebula_tradeport.dmm
Gets docking working on Deck 4 for all traveler shuttles. This system will bypass docking code requirements, however, a member of security, engineering or command is required to open the blast doors on Deck 4 to admit entrance to a security checkpoint area.
Also, a bunch of small bug fixes to things like decals, lighting, extra switches and things out in space, and a bunch of wiring and airless tile issues on the other decks. 
Enables docking for traveler shuttles on Endeavour, updates a bunch of landmarks so that shuttles can land around the Endeavour.
:cl:
add: Docking bay and docking points around the Endeavour
fix:  A bunch of bugs and mistakes on several decks got fixed.
fix: fixed bad wiring and shuttle seating in EMT shuttle.
fix: bad wire in the dorms on deck 2
fix: bad stairs …
> Docking update and bug fixes (i got rid of the funny name)

- code/modules/admin/admin.dm
As title. Does not work because it should be checking that decomped convo is mul of 3+1 but it's just checking for mul of 3
it's fun
:cl:
fix: Fix Intercom Convo verb for admins/event managers
/:cl:
> Fixes Intercom Convo

- code/modules/loadout/loadout_xeno.dm
Just removes the lines that make only specific species be able to spawn with certain loadout items. Doesn't touch Phoronoids and Vox equipment, as it's more specialized.
Allows everyone to pick specific clothing, as it's just that. I don't think there could be a way you couldn't get your hands on any of them. It was already removed for other species (and called legacy_species_lock, so while working, maybe not quite up to date?)
:cl:
tweak: Allows everyone to pick some more xenowear options
/:cl:
> Removed Tajaran, Unathi, and Promethean centric xenowear lock

- code/datums/components/horror_aura.dm
Title.
Do you have any idea how THICK the admin logs get when there's horror mobs around?
:cl:
code: A spooky mob's horror aura will only be active if a player mob is present on the same z-level they are.
/:cl:
> Makes horror aura only active when players are present in z-level

- code/game/objects/effects/map_effects/radiation_emitter.dm
Title.
Reduces admin log bloating. Admins/EMs spawning new radiation emitters are logged, if that's any concern at all. But generally these map effects exist only through mappers just putting them in otherwise.
:cl:
code: Map effect radiation emitters will no longer be logged to admins by default.
/:cl:
> Stops logging radiation emitter map effects

- code/modules/mob/living/carbon/human/death.dm
- code/modules/organs/organ.dm
gib removes your organs
removing your brain kills you
you are then killed by being gibbed
thus, you have died twice
(this is bad because we want to know if the source of someone's death was being gibbed or not for species handle_death proc!!!)
you shouldn't kill someone who is already dead
:cl:
fix: stops gibbing people killing them twice
/:cl:
> stops gibbing people killing them twice

- code/modules/organs/internal/species/xenochimera.dm
- code/modules/species/station/xenochimera.dm
Gives Xenochimeras everything the weaving trait would give a custom species. Given spider silk is protein fibers, it would also fit right in, while allowing to explain the organ as a sort of fat reserve, leaving it up to the player whether their chimera did adopt such an ability.
Gives Xenochimeras another tool to be the spooky ambush predators in the dark tunnels. It follows the comment that they get all the special verbs, as they can't pick them. The only counter point may be that they won't be affected by weaversilk traps due to having the organ, even if in character, they never have adapted such an ability.
:cl:
add: Gave Xenochimeras the weaving abilities.
/:cl:
> Effectivly gives xenochimera the weaving trait

- code/modules/species/station/standard/tajaran.dm
Tajarans sit in a weird spot where they have the same speed as the fastest species (Teshari) but with only extremely meager counterbalance, taking only 5% more brute/burn damage but having a full healthbar.
Removed Tajaran speed, returned down to human levels. Reduced Tajaran brute/burn damage down to teshari levels - that being standard 10% more damage taken. They keep their snow speed and lack of any encumbering weight maluses 
balanced species is good for the balance of the game
:cl:
tweak: Tajara speed nerf and slight stat rebalance
/:cl:
> Tajaran Speed Nerf

- code/modules/integrated_electronics/subtypes/filters.dm
- code/modules/integrated_electronics/subtypes/input.dm
- code/modules/integrated_electronics/subtypes/reagents.dm
Fixes the IC reagent filter by updating it to the latest circuitry code from Baystation.
Also add 3 new circuits components
Produce filter, filters grown plant produce like apples and wheat.
Ore filter, filters ores.
Reagent purger, a simple device to delete reagents.
edit1:
View filter now has a range setting
edit2:
Added a plant analyzer component
edit3:
Projectile simulator that either outputs a refrence when aiming for a relative x and y or aim for a refrence, either outputting a positive or negative pulse.
edit4:
Slime scanner also outputs Rabid, obedience and disciplined
> IC filter fix plus additions

- code/game/objects/items/id_cards/contractor_ids.dm
This fixes that contractor IDs (The faction not being NT ones, not the Traveler title) do show which other company they are employed by. At the same time, it allows them to use alternative titles for the jobs.
Showing which company someone belongs to on the ID was intended, and did just break. Alternative titles were explicitly disabled, due to confusing titles coming with some factions, but as there no longer are any, we can allow the full range of known station alternatives. A Vey-Med nurse probably should stay a nurse, and not become a full doctor when working at an NT station, at least title wise, as example.
:cl:
tweak: Allows contractors to have alt-titles
fix: Contractor IDs show the employing company
/:cl:
> Show contractors Employing Company+Allow alt titles

- code/game/area/station/shuttle_area.dm
- maps/rift/levels/rift-04-surface1.dmm
- maps/rift/levels/rift-06-surface3.dmm
- maps/rift/shuttles.dm
- maps/sectors/nebula_tradeport/levels/nebula_tradeport.dmm
- maps/sectors/nebula_tradeport/nebula_tradeport-areas.dm
- maps/sectors/nebula_tradeport/nebula_tradeport-shuttles.dm
Some simple fixes : 
- The Old Century should have its APC, exterior airlock sensor, and lighting work correctly.
- The library got its scanner back ! Before that, the scanner near the library computer was actually a photocopier  (the sprite of the Photocopier and Scanner are the same.). Books can be publised again
- The scoophead should work again. I removed the mention of a area that, I expect, was the issue with the shuttle.
Fixes are always good ! :D
> Fixes for : The Old Century Shuttle (Powerwise/Light wise) / Library scanner on Atlas / Scoophead

- code/modules/events/event_container.dm
- code/modules/events/event_container_vr.dm
Those pesky pirates taught they could attack a base on Lythios 43c with those fighters. NSB Atlas sensor detected them, was set on blue alert... 
... But the fighter never came down. Turns out, Dukes and Baron repaired with hopes and ducktape aren't totaly made for re-entry. 
For now, the event will be removed, until we can code map based event, so the event that trigger when on a NT vessel, and not a base.
_"Lieutenant Gaeta, set the fleet to Condition Three."_
No more people scared on Atlas about non-existing Fighters.
The event will be back **event**ualy. :D
> Removal of the fighter event

- code/datums/datacore.dm
Fixes what was overlooked in #6980, which only made IDs display their alternative title, this also makes the manifest show it.
Manifest, arrivals message, and IDs agree again on what someone is.
:cl:
fix: Non-NT crew get announced and listed as their chosen job title.
/:cl:
> Non-Nt workers now get their chosen title in the manifest

- code/modules/jobs/job_types/station/civillian/librarian.dm
Fixes the reporter alt title to also get their reporter outfit, which is a camera with film, a press badge, and a tape recorder
Gives press a thing to show, besides providing them with the gear they may need. The outfit was already made like it, and works, only was assigned to a `librarian/librarian/reporter` alt title, rather than just the librarian/reporter one that's in use.
:cl:
tweak: Reporter librarians start with press gear.
/:cl:
> Gives station reporters a press badge and tape recorder

- code/game/objects/items/weapons/cigs_lighters.dm
As title. On harm intent, it drops it to the ground, instead (both for the funny and because this is actually required to get the "put it out by stomping it" thing to work)
Y'all know I'm a hater and I still unironically think that making every smoker a litterer by default too is a bit goofy
:cl:
tweak: Cigarette butts go to a free hand if available, instead of dropping to the ground
/:cl:
> Makes cigarette butts go to hand instead of drop by default

- code/modules/organs/external/external.dm
- code/modules/species/holosphere/appearance.dm
- code/modules/species/holosphere/holosphere_shell.dm
if you switch to a loadout using the change loadout verb/ability then unused slots get replaced with a blank icon / 'nothing'
when embedding an object into a bodypart, don't try covering the object in blood if the species has no blood
the holosphere's shell understands whatever the hologram understands, thereby fixing things like the AI's name becoming "synthesized voice"
fixes to intended behaviour
:cl:
fix: if you switch to a loadout using the change loadout verb/ability then unused slots get replaced with a blank icon / 'nothing'
fix: when embedding an object into a bodypart, don't try covering the object in blood if the species has no blood
fix: the holosphere's shell understands whatever the hologram understands
/:cl:
> holosphere fixes

- code/game/objects/mob_spawner.dm
Ashlanders should no longer be attacked by animals they are suppose to herd. The issue was that mob spawners which is how Surt generates most of its mobs continue to use the depreciated "lavaland" faction even though Scori now use the "bind-surt" faction from the new factions system.
:cl:
fix: spawned Surt mobs now use the BIND_TO_MAP faction like the Scori
/:cl:
> Fixes Surt Mob Factions

- code/modules/mob/living/carbon/give.dm
why do i have to do this
i think literally anyone who has ever tried to use it can tell you why it's good
:cl:
qol: the "Give" verb is no longer completely without feedback if you're giving to one person
/:cl:
> Makes "Give" verb show a message if you clicked it and it's showing a prompt

- code/game/objects/items/devices/flashlight.dm
fix flares not turning off properly
fix
:cl:
fix: fix flares not turning off properly
/:cl:
> fix flares not turning off properly

- code/game/turfs/simulated/floor_types/water.dm
Adds the check that someone's actually touching the water for the breathing check
You don't end up being drowned when being fireman carried by someone flying over the water
:cl:
fix: You no longer can breath water while flying over it.
/:cl:
> Don't drown while flying over the water

- code/modules/species/station/xenochimera.dm
Hopefully makes the code a bit clearer to see, being a bit explicit with what the respiratory biomorph changes.
Biothermic biomorph was changed, to both make it actually change the temperature the body will reach naturally (so hot blooded actually is warmer, and cold blooded only takes the enviroments temperature). Hot blooded is resistant to warmer temperatures now, as the heat level checks your body temperature, not the enviroments one, and as the default is 37°C, you were always going to burn yourself switching to it, unless you were in a cold enviroment. But there, you may be breathing in too cold air, and hurt yourself there, which is what hot blooded would be stopping. There are also checks to not add the normal temperature handling, if the species is already doing it in a special …
> Touches up xenochimera adaptations

- code/game/turfs/simulated/floor_types/snow.dm
- code/game/turfs/unsimulated/beach.dm
- code/modules/mining/mine_turfs.dm
As title. Grave digging is supposed to take 6 seconds; instead, it takes as little time as you want, because interrupting it has it go through anyway. do_after needs to be checked, you can't just put it in on its own. There should probably be a "must use result" lint for functions.
bugfix
:cl:
fix: Gravedigging no longer goes through even if interrupted
/:cl:
> Fixes grave digging not checking do_after

- code/modules/mob/living/carbon/human/human-defense-legacy.dm
people with no blood cannot bleed
people with no blood should not bleed
:cl:
fix: you cannot bleed if you have no blood
/:cl:
> you no longer visually bleed if you have no blood

- code/modules/jobs/job_types/station/civillian/chaplain.dm
- code/modules/jobs/job_types/station/medical/psychiatrist.dm
removes counsoler from psych
adds therapist to chaplain
removes 'religious' title from chaplain alt titles
removes RAA title from chaplain
- psych is a medical title; medical staff have medical titles. this is not what your character calls themselves this is official NT titles on manifests and paperwork.
- therapist should be its own role but i can't be bothered to add a new role before i rework jobs and roles again so here you go for now
- RAA was redundant. okay, it was funny, but we don't need "#AA" titles for everything; IAA is a very specific and important role and i'm not interested in diluting it
congratulations i am fed up over alt titles and so i'm actively going to touch them now
> reworks chaplain/psych alt titles

- citadel.dme
- code/modules/mob/living/carbon/human/human_defines.dm
- code/modules/species/protean/protean.dm
- code/modules/species/protean/protean_blob.dm
- code/modules/species/protean/protean_powers.dm
- code/modules/species/species_shapeshift.dm
- code/modules/species/station/xenochimera.dm
gives a verb to proteans and xenochimera that let them mimic another person within range.
this copies:
gender and identity
skin colour, skin tone and eye colour
hair and gradients
ears, horns, tail and wings
markings
target's icon base (for xenochimera ONLY. this, again, cannot work with proteans due to how limbs work. protean limbs are always robotic)
robot limbs (for proteans ONLY. this, again, cannot work with xenochimera due to how limbs work)
gives a verb to proteans and xenochimera that let them reset appearance to the currently-selected character slot.
:cl:
add: mimic-appearance verb, which lets you mimic the appearance of someone in range. for xenochimera and proteans only, because they're the only real shapeshifting races we have)
/:cl:
> shapeshifter copy and reset verb

- code/modules/mob/living/carbon/human/movement.dm
- code/modules/species/holosphere/holosphere.dm
- code/modules/species/species.dm
they can't eat normally and require recharging
they take nutrition when healing/reviving and upon hitting 0 cannot revive from their sphere (leaving them slow and defenceless)
ultimately the hunger slowdown is just too punishing for how they're currently setup, but i'm wary of completely disabling it for them, so halving it should be a pretty good measure
balance!
:cl:
balance: half the slowdown from holospheres getting hungry
/:cl:
> half the slowdown from holospheres getting hungry

- code/game/click/rig.dm
- code/modules/hardsuits/_rig.dm
Allows Holospheres to actually use modules, and stops seals from breaking it an intelligence does it from inside the suit, telling the game to do it on the wearer, not user.
Code should work as intended, and especially the second part softlocks one.
:cl:
fix: Holosphere can make use of installed modules, not just toggle and select them.
fix: Hardsuits seal around the wearer, not user, can be different with IIS module
/:cl:
> Two fixes for hardsuits IIS

- code/modules/species/station/xenochimera.dm
Tell the thermal sight to only toggle when the eyes aren't already glowing. That way, it remains ensured that they have the glow while the sight is active, but it lets them have a passive glow afterwards, too, if they spawned with it.
Lets xenochimeras decide to be always visible in the dark, instead of only when they use the thermal sight
:cl:
tweak: Eyeglow sticks to Xenochimeras as they selected it
/:cl:
> Don't disable chimera eyeglow if they use thermal sight

- code/game/rendering/plane_masters/plane_render.dm
Just sets the default for plane_renderers to ``BOTTOMLEFT``, currently only used in darksight, and as every piece (short of the one that's explicitly set to ``FULLSCREEN``) needs it to work correctly. The ``darkvision_blackness`` ~~may even not be necessary, as even with it not being where it should be, the darksight didn't see past walls~~ is required to hide wall mounted things, which are on a tile you may see, but not the wall it is from the darkness.
Fixes darksight fully
:cl:
fix: blackness in darksight where it shouldn't be
/:cl:
> Fixes the pitch black darkness of darksight being offset

- code/modules/reagents/chemistry/reagents/blood/blood_holder.dm
Implements silicons fix in 2 lines
Not crashing on build is healthy for future development
Checks if the divisor amount for draw() and erase() are equal to or less than zero and returns immediately the appropriate value instead of diving by zero.
:cl:
fix: fixed a divide-by-zero exception caused by blood erase() and draw()
/:cl:
> Fast lazy fix for drawing or erasing blood

- code/modules/reagents/chemistry/reagents/blood/blood_holder.dm
A quick check if the total is zero, before trying to divide through it.
No runtimes while a body grills on Lythios 43a, all blood already evaporated, and more tries to do so.
:cl:
fix: No runtime if a bloodless corpse gets more blood erased
/:cl:
> No runtime if the blood_holder is empty

- code/modules/vore/lick_wounds.dm
Just changes the living_mobs(1) to view(1), which in turn includes the mob it gets checked from
"Licking your wounds" is something a person does on themselves, not on others, so the ability should probably allow it to be used on the person itself. Right-clicking on your own mob also lists it already, but can't be called, putting the verb and the argument in the command bar, without working.
:cl:
tweak: people are able to lick their own wounds
/:cl:
> Allows the lick wounds ability to target oneself

- code/game/objects/items/devices/translator.dm
As title. It's a little weird that it checks if they can _understand_ what's being said but not if they can _hear_ it.
I'm pretty sure it's supposed to work this way??
:cl:
qol: Made universal translators display text if the user can't hear what's being said, not just if they can't understand it
/:cl:
> Lets handheld translator work if owner can't hear, even if they understand the language

- code/modules/mob/living/carbon/human/human-damage-legacy.dm
- code/modules/species/station/xenochimera.dm
Makes the chimera regenerate only replace missing organ/limbs, and fully heal them all, rather than deleting and respawning everything. This makes them not lose implants from it. It's done by making restore_all_organs actually restore ALL organs, and not just bodyparts. It's only used for aheals otherwise, and that already replaces every organ before, so there aren't any changes. The other part is copying the create_organs part where they are actually made, after checking the chimera would be missing a limb they should have. Should they somehow have another limb grafted to them, they'll heal it, but not regenerate if it gets amputated again. They will still heal robotic limbs, but that's not avoidable without more checks.
An ability that needs 10 seconds of their concentration currently …
> Less invasive chimera regenerate

- code/modules/projectiles/guns/gun/launcher.dm
- code/modules/projectiles/guns/gun/launcher/crossbow.dm
- code/modules/projectiles/guns/gun/projectile/ballistic.dm
- code/modules/projectiles/guns/gun/projectile/ballistic/shotgun.dm
Potentially dirty fixes, although there is only one new var to stop the revolver spinning to use the full magazine equals chamber logic of that, which does seem like it has the intended effect for double-barrel shotguns.
The crossbow attack_self returns early as it attempts to switch firemodes, which is why it can't be drawn, object to be thrown was just moved into the shooter.
Double barrel shotguns should actually load two shells, and crossbows are currently spawned in, but don't work.
:cl:
fix: crossbows can be drawn
fix: double-barrel is actually two barrels
/:cl:
> Small gun fixes

- code/datums/ability_handler.dm
looks like reticles were moved a folder deeper, fixes this.
Found a dmi file path that was targeting nothing. I'm assuming the next folder deeper is what was wanted.
Bug fixes 💯 
-Fix filepath in ability_handler proc
:cl:
fix: fixes cursor reticle bug in ability_handler
/:cl:
> Fix cursor icon bug in datum/ability_handler/proc/process_ability()

- code/modules/vehicles/sealed/mecha/subtypes/micro.dm
i play a character that has scale 50% and is thereby the size of one tile
they can't fit in the micro mech and being below 50% can just obliterate you appearance-wise
let the small creatures drive the small robots
:cl:
tweak: change micro mech size requirement to <= 50% instead of <50%
/:cl:
> change micro mech size requirement to <= 50% instead of <50%

- code/modules/vehicles/sealed/mecha/mecha.dm
Updates the default melee damage type for all combat mechs to be brute, since it's a big metal fist punching you. This is placed on the abstract combat mech datum so it can be overridden. This seems to fix the issue where mech melee attacks would play the sound but then not do any damage.
I'm not well-versed enough in the mech code to know why this is marked as legacy, but it fixes the bug so that's good enough for me for now.
Fixes a pretty big bug regarding combat mechs.
:cl:
fix: Combat mechs can now melee again.
/:cl:
> Fixes combat mech melee

- code/game/objects/items.dm
As a programmer your code is like your children, hit them to make them work harder.
Fixes /obj/item/proc/set_body_cover_flags() to actually set body cover flags.
This should fix:
-Being unable to eat with your mask down
-Masks working for breathing when down
-Raised glasses like welding helmets giving you protection when up
-Rolled down uniforms still protect your torso
-Rolled up sleeves still protect your arms
-Chameleon gear not cloning body protection flags
:cl:
fix: Fix unable to eat when mask is down
/:cl:
> Fix set_body_cover_flags()

- code/modules/species/holosphere/holosphere.dm
- code/modules/species/species_shapeshift.dm
title
shapeshifter_reset_to_slot is now shapeshifter_reset_to_slot_generic which has parameters for the duration, cooldown and text
someone asked for it and it feels like something they should be able to do
:cl:
add: gives holospheres the reset to slot and set size verbs
/:cl:
> gives holospheres the reset to slot and set size verbs

- maps/rift/levels/rift-02-underground2.dmm
- maps/rift/levels/rift-03-underground1.dmm
- maps/rift/levels/rift-04-surface1.dmm
- maps/rift/levels/rift-05-surface2.dmm
- maps/rift/levels/rift-06-surface3.dmm
- maps/rift/levels/rift-09-west_caves.dmm
- maps/rift/levels/rift-10-west_plains.dmm
Renames most of the NSB Atlas substations and breaker boxes to label which floor they're on and generally be more consistent. This should help managing RCON be a lot smoother. See screenshots of the new layout:
The old RCON labels were inconsistent and somewhat confusing. This helps engineering players, especially new ones, learn the RCON system quicker. To compare, this is what the breakers were like before:
:cl:
tweak: Adjusted the RCON labels of the substations and breaker boxes on the NSB Atlas.
/:cl:
> Renamed Atlas substations/breakers to be consistent

- maps/rift/levels/rift-06-surface3.dmm
Trying my hand at fixing a relatively simple problem. What could possibly go wrong?
Made the partition all-access in the DART so it could actually be used. All edits were done in StrongDMM
Makes all of the doors in the DART all-access. The cockpit is already all-access so I don't see why there are two partitions with list(1) access separating the front foyer and rear foyer. It's basically useless until this gets fixed.
:cl:
fix: req_access set to "null" on both sliding secure doors. Otherwise, I literally have 0 idea what the other changes are in code or why they're occurring.
:cl:
> Dart Door Fix

- code/modules/mob/living/carbon/human/emote.dm
- code/modules/surgery/implant.dm
- code/modules/surgery/organs_internal.dm
When you set your character's pose with the non-stealth verbs, the emote now shows what your new pose is. 
Also changes surgery requirements so synths can implant things in their limbs.
**Bootleg Tarot** adjusts their posture.
Central Command Officer looks at Bootleg Tarot.
John Humanson looks at Bootleg Tarot.
Nuclear Operative looks at Bootleg Tarot.
Enigma Trooper looks at Bootleg Tarot.
Bradley looks at Bootleg Tarot.
the mouse (298) looks at Bootleg Tarot.
John Nut looks at Bootleg Tarot.
:cl:
tweak: Set-Pose and Set-Pose (Temporary) will now display your covered-under-warranty definitely-non-canon definitely-not-submissive positions. Silicons be glad that I didn't use the pillow biting pose instead. 
fix: Synth arm implanting now works.
/:cl:
> adds engine repair posing

- code/modules/mob/living/silicon/robot/drone/matrix_hive.dm
Just a slight change to how the drone upgrades are applied. Mostly ensures they get only applied once, and don't delete and re-add the upgraded item. The potential for infinite growth remains, although it would need admin intervention to remove the already applied upgrades from the list. It still will allow it to be upgrades even if the drone got edited before, why I removed the initial() call for it.
As fun as exponentially growing power storage is, and with enough time, an extremely tanky drone, upgrades should only apply once. The speed upgrade actually is an upgrade again, as it's no delay anymore, but tiles per seconds, so the sign had to switch.
:cl:
fix: Actuator enhancement is actually an enhancement again.
tweak: drone upgrades only get applied once
/:cl:
> Drone matrix upgrades touchup

- code/modules/species/shadekin/shadekin.dm
- code/modules/species/shadekin/shadekin_traits.dm
Biggest change is that Space turf counts as dark for Shadekin, and those Shadekin who would lose energy in the light (Yellow, Purple, Orange) now instead have minimal regeneration in the light. This will be important for the future change to Shadekin with them travelling through space, since space is always bright.
Siemens Coeff is also returned to the previous value, as it was before needless drama happened.
HUD values were updated since sometimes regeneration would put the value to one which wasn't checked by the switch, causing the HUD to mess up for a short time. (i.e. value goes to 24.1 which wasn't covered.)
Current plan for the future of Shadekin will have them move through space, and during such discussion I was told to go ahead and make Space tiles count as dark to ensure those …
> Shadekin-Spacekin-Futureproofing

- code/modules/overmap/legacy/overmap_shuttle.dm
- code/modules/overmap/legacy/ships/computers/shuttle.dm
Look on the title
we dont need two sector names on landingspot selection
:cl:
tweak: shuttle landing spot selection is now tgui
tweak: shuttles no longer prepend sector name to a landing spot
/:cl:
> shuttles no longer add sector name infront of the Landingpoint name, landingpoints should do that themselves

- code/modules/projectiles/projectile/projectile.dm
Just a single line change to make inflict_agony actually do it
Less or non-lethal projectiles that use that var should actually be less lethal, instead of applying the damage with the type of the base projectile (i.E. 80 brute beanbags)
:cl:
fix: certain type of less-lethal projectiles now are less-lethal again
/:cl:
> inflict agony actually inflicts agony/hallos

- code/modules/species/protean/protean_blob.dm
The "be spontaneous prey" vore setting was working the precise opposite of intended for proteans re-blobbing from flat.
Prefs Like This Should Definitely Work Exactly As Described And Not The Exact Opposite Lest Upsetting Things Happen
:cl:
fix: made protean dropvore(?) not check the exact opposite pref it should
/:cl:
> Protean "drop prey" pref fixed not to do the exact opposite of the pref

- code/game/objects/structures/door_assembly.dm
Some glass door assemblies are pointing to a typepath that does not exist. Because the typepaths are built via a string, for some ungodly reason, this is not caught in compile.
Doors: buildable. Good.
:cl:
fix: Various glass airlocks are now actually buildable
/:cl:
> Fixes various door assemblies to be constructible

- code/game/objects/items/weapons/handcuffs.dm
- code/modules/clothing/glasses/_glasses.dm
Makes blindfolds actually blind the wearer, and disruptor cuffs to stop disrupting the protean when removed. I just found them while searching how it could be done for the blindfolds, and then noticed they never get cleared.
Less hassle when admins want to temporarily detain a protean, having to manually remove the trait when the cuffs get removed. There already are fake blindfolds for the ones we have, which effectively is just a duplicate while the real ones don't do anything.
:cl:
fix: disruptor cuffs stop disrupting if removed
fix: real blindfolds actually blind
/:cl:
> Blindfold and disruptor cuffs fix

- code/_globals/regexes.dm
- code/modules/mob/emote.dm
- code/modules/mob/living/carbon/human/human_organs.dm
- If you start a `me` message with a comma or an apostrophe, there will no longer be a space between your name and the message. I.e. "**John Trasen** , being hungry, eats." -> "**John Trasen**, being hungry, eats."
- Fixes reversed logic with dropping things with a broken hand. Your character will now correctly cry in pain when trying to do this.
- Also potentially fixes reversed logic with collapsing with a broken leg and screaming in pain.
- In both of the above cases, it will deal halloss (pain) damage, since using a broken bone tends to hurt a lot.
Small fix and improvement.
:cl:
fix: Fixed erroneous space when starting a me message with a comma or apostrophe.
fix: Your character will now cry in pain when trying to hold something with a broken hand.
/:cl:
> A couple minor fixes

- code/modules/clothing/spacesuits/void/station/science.dm
Changes the encumbrance of the Bypass Voidsuits down from 55 to 40.
Just makes it more viable to use the suit, as multiple complains were noted of the suit being too slow to be all that useful. Hopefully this makes it light enough for most people to have it be worthwhile. (Took me long enough to not be lazy about changing it.)
:cl: Kade
tweak: Changes the Hazard Bypass Voidsuit to be lighter.
/:cl:
> Hazard Bypass Update

- code/modules/reagents/chemistry/reagents/blood/blood_holder.dm
- code/modules/reagents/machinery/coffeemaker.dm
- code/modules/vore/fluffstuff/life_crystals.dm
- You can now deactive a life crystal by using it in your hand. This is permanent (it breaks it), since not being able to reuse them seems to be intentional according to a code comment.
- Ghosts can no longer interact with the coffeemaker.
- Blood splatters from bleeding now correctly use a species' blood color (or custom blood color for custom species).
The life crystal one is arguably very QOL for people who use them but want to take off their uniforms for whatever reason. Blood color is also a nice touch for people who use custom blood colors for their species (or really, for any species that doesn't use the usual blood color). The other is a simple bugfix.
:cl:
add: You can now deactivate a life crystal by using it in your hand.
fix: Ghosts can no longer brew coffee.
fix: Bleeding now …
> A couple more fixes

- code/game/area/Space Station 13 areas.dm
- code/game/area/Tether_areas.dm
- code/game/area/rift_areas.dm
- code/game/area/station/security_areas.dm
- maps/rift/levels/rift-04-surface1.dmm
Adds some missing nightshift areas to the Atlas map. This should help the nightshift look more consistent.
Also removes a lot of duplicate/unused areas from the Atlas areas file.
I also added a missing APC to the hallway leading to IAA/janitorial/library, and added missing lights to the virology dorms.
Nightshift looks good c:
:cl:
tweak: More areas will now respect the nightshift on the Atlas.
fix: Added a missing APC to the secondary civilian hallway on the Atlas.
fix: Added missing lights to the virology dorms on the Atlas.
/:cl:
> Add more nightshift areas to the Atlas

- code/game/click/click.dm
- code/game/click/item_attack.dm
- code/game/click/items.dm
- code/game/click/melee/melee_attack/unarmed.dm
- code/game/click/melee/melee_attack/weapon.dm
- code/game/objects/items-interaction.dm
- code/game/objects/obj.dm
- code/modules/projectiles/targeting/targeting_overlay.dm
Alters the aim mode so that not every single click will trigger it if you have the "can use items" set to disallowed. Now, it checks to see if you are actually doing something. Specifically, it will trigger when:
- You attack something in melee, either unarmed or with a weapon. Some edge cases are not accounted for because of \~snowflake code\~.
- You click on yourself (e.g. to administer an injector or examine yourself for injuries).
- You fire a weapon or otherwise use a ranged attack/interaction.
- You pick something up (including from your inventory).
- You use something in your hand (which includes stuff like PDAs, signalers, grenades, or even flashing your ID card; the idea is that if you have using items disallowed, your character becomes VERY jumpy at anything your victim does!). …
> Fixes unintuitive aim mode code

- code/__DEFINES/time.dm
- code/__HELPERS/time.dm
- code/_globals/time_vars.dm
- code/game/world.dm
This PR removes the `GLOB.timezoneOffset` variable, as it appears Byond 514 added timezone support for the `time2text` proc. So, that variable was made redundant, and in fact caused more headaches, as the nightshift was working with a different time entirely than what the actual station time said.
Based on more intensive local testing, this seems to have actually fixed the problem, and the nightshift will now properly engage and disengage at the stated times. There do not appear to be any side effects to removing the variable that I am aware of.
This has a side effect tha,t because station times were distorted for a while, **station time is effectively rolled back 2 hours.** E.g. whereas station time would start at 19:00, it now starts at 17:00 as the code dictates.
The nightshift still …
> Fix nightshift again
